### ISSUE TITLE
ErrorCode:AuthorizationPermissionMismatch get_storage_info_for_blob SAS token missing (t) URI symbol for Index tags permission

### ISSUE THREAD

**Issue by DavidGrob-MS** [Azure/azure-iot-sdk-python#1026]
# Context

- **OS and version used:** Ubuntu 18.04
- **Python version:** 3.7.13
- **pip version:** 22.0.4

## Description of the issue

IoT hub file upload doesn't allow setting blob index tags. azure.iot.device.IoTHubDeviceClient.get_storage_info_for_blob(blob_name) returns a SAS URL with read (r) and write (w)  URI symbol permissions which allows uploading blob data and setting metadata tags, but not (t) URI symbol which allows reading and writing index tags

 https://docs.microsoft.com/en-us/azure/storage/blobs/storage-manage-find-blobs?tabs=azure-portal#sas-permissions
The blob read (r) and write (w) permissions alone aren't enough to allow reading or writing its index tags (t) is needed.
 
Permission | URI symbol | Allowed operations
Index tags | t | Get and set index tags for a blob

## Code sample exhibiting the issue
        # Upload the specified file
        with BlobClient.from_blob_url(sas_url) as blob_client:
            with open(file_name, "rb") as f:
                result = blob_client.upload_blob(f, overwrite=True)
            try:
                blob_client.set_blob_tags(tags=indexTagData)
            except HttpResponseError as ex:

Please remove any connection string information!

## Console log of the issue

azure.core.exceptions.HttpResponseError: This request is not authorized to perform this operation using this permission.
RequestId:bb4991e0-801e-0010-493d-9e5ee1000000
Time:2022-07-23T02:39:13.9960162Z
ErrorCode:AuthorizationPermissionMismatch
Content: <?xml version="1.0" encoding="utf-8"?>
<Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.
RequestId:bb4991e0-801e-0010-493d-9e5ee1000000
Time:2022-07-23T02:39:13.9960162Z</Message></Error>

**Comment by cartertinney** [comment]
@DavidGrob-MS Apologies for the delay in response - I'm going to look into why this is happening and will report back

**Comment by cartertinney** [comment]
@DavidGrob-MS 

I have confirmed that this is a known issue with the IoTHub service, not on the device SDK.

**Comment by DavidGrob-MS** [comment]
@cartertinney 

Thanks so much, feel free to close the bug.
