### ISSUE TITLE
TLS transition support [Technical Question]

### ISSUE THREAD

**Issue by stanleyoz** [Azure/azure-iot-sdk-python#1027]
Please advise if the current azure-iot-device install covers the upcoming DigiCert Global G2 root certificate transition? When was the support updated to the depository (so we can advise our device users accordingly). Thanks.

**Comment by stanleyoz** [comment]
Can someone from the IoT SDK team advise? main concern is how far back the package that will not support the new CA Root certificate?

**Comment by anthonyvercolano** [comment]
Working on it.  Getting a security PM to address.  (I think it mostly depends on if your trusted cert database is relatively up to date.)

**Comment by RamIoTMalhotra** [comment]
Hi @stanleyoz the SDK depends on the underlying operating system to retrieve trusted roots. I'd check the certificate store for the G2 root to confirm if the root is indeed present. (This is quite a popular root in many common trust bundles so you should have it if you've updated in the last year, but I'd still validate with a few devices to make sure). Also check out https://aka.ms/iot-ca-updates on how to validate against a test endpoint we have set up.

**Comment by stanleyoz** [comment]
> Working on it. Getting a security PM to address. (I think it mostly depends on if your trusted cert database is relatively up to date.)

Thanks for the push mate

**Comment by stanleyoz** [comment]
> Hi @stanleyoz the SDK depends on the underlying operating system to retrieve trusted roots. I'd check the certificate store for the G2 root to confirm if the root is indeed present. (This is quite a popular root in many common trust bundles so you should have it if you've updated in the last year, but I'd still validate with a few devices to make sure). Also check out https://aka.ms/iot-ca-updates on how to validate against a test endpoint we have set up.

Hi Ramio. Fantastic! That support page is well documented and will do the job ... we will get on it. Thank you.
