### ISSUE TITLE
Do we have python code sample for device provision using enrollment group?

### ISSUE THREAD

**Issue by yogaavanade** [Azure/azure-iot-sdk-python#1034]
Can you help me with the python code snippets for devision provision using enrollment group ?

**Comment by cartertinney** [comment]
There shouldn't be a difference between provisioning a device that was enrolled via an Individual Enrollment or an Enrollment Group.

Either way, you're going to provision the same

```
provisioning_host = "<Your Provisioning Host>"
id_scope = "<Your ID Scope>"
registration_id = "<Your Registration ID>"
symmetric_key = "<Your Symmetric Key>"

provisioning_device_client = ProvisioningDeviceClient.create_from_symmetric_key(
    provisioning_host=provisioning_host,
    registration_id=registration_id,
    id_scope=id_scope,
    symmetric_key=symmetric_key,
)
provisioning_device_client.register()
```

**Comment by yogaavanade** [comment]
@cartertinney 
**I tried with the same. By it fails with the below error** 
FYKI - I have given enrollment group in place of the registration_id and symmetric key taken from the enrollment group.

====
Traceback (most recent call last):
  File "\Miniconda3\envs\myenv\lib\site-packages\azure\iot\device\provisioning\aio\async_provisioning_device_client.py", line 29, in handle_result
    return await callback.completion()
  File "\Miniconda3\envs\myenv\lib\site-packages\azure\iot\device\common\async_adapter.py", line 91, in completion
    return await self.future
azure.iot.device.exceptions.ServiceError: register request returned a service error status code 401

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dps_using_enrollmentgroup.py", line 69, in <module>
    asyncio.run(main())
  File "\Miniconda3\envs\myenv\lib\asyncio\runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "\Miniconda3\envs\myenv\lib\asyncio\base_events.py", line 587, in run_until_complete
    return future.result()
  File "dps_using_enrollmentgroup.py", line 35, in main
    registration_result = await provisioning_device_client.register()
  File "\Miniconda3\envs\myenv\lib\site-packages\azure\iot\device\provisioning\aio\async_provisioning_device_client.py", line 83, in register
    result = await handle_result(register_complete)
  File "\Miniconda3\envs\myenv\lib\site-packages\azure\iot\device\provisioning\aio\async_provisioning_device_client.py", line 43, in handle_result
    raise exceptions.ClientError("Unexpected failure") from e
azure.iot.device.exceptions.ClientError: Unexpected failure

**Comment by cartertinney** [comment]
@yogaavanade

The issue is likely that you are giving enrollment group in place of registration id. You should be providing the device IDs.

See this sample for an example:
https://github.com/Azure/azure-iot-sdk-python/blob/main/samples/sync-samples/provision_symmetric_key_group.py

**Comment by olivakar** [comment]
@yogaavanade 
The enrollment group id is never required for the group sample anywhere. If you have 1 or multiple devices in 1 enrollment group, it should always be the registration id of the individual devices which is often similar to device id. 

As for the symmetric key, the symmetric key of the group (or master key) is also never needed. You need to compute the device symmetric key and use those for the individual devices.

Please take a look at these lines from our sample which illustrates how to compute a device symmetric key.
https://github.com/Azure/azure-iot-sdk-python/blob/main/samples/sync-samples/provision_symmetric_key_group.py#L37-L69

**Comment by yogaavanade** [comment]
@olivakar 
Thanks, that is really helpful. It worked at last. I computed the key for the device using the helper function provided and then tried running the same script. 

Much appreciated.
