### ISSUE TITLE
Segmentation fault when importing iothub_client

### ISSUE THREAD

**Issue by beyondhong** [Azure/azure-iot-sdk-python#104]
- **OS and version used:** <VERSION> 
Host: ubuntu16 x86_64
embedded os: openwrt

- **Python runtime used:** <VERSION> 
Python-2.7.12
- **SDK version used:** <VERSION> 
release_2017_08_25
gcc: 4.6.3
libboost_python.so.1.65.1

# Description of the issue:

After cross-compiling the sdk, I copy iothub_client.so and iothub_client_sample.py to my device.
It print Segmentation fault when running ptyhon iothub_client_sample.py
It happened when importing iothub_client

c samples(like iothub_client_sample_amqp and iothub_client_sample_mqtt)  run properly!

# Code sample exhibiting the issue:

import random
import time
import sys
print 'before import iot_client'
import iothub_client
print 'after import iot_client'

# Console log of the issue:

before import iot_client
Segmentation fault

**Comment by beyondhong** [comment]
can anyone tell me how I should  trace this kind of exception?

**Comment by beyondhong** [comment]
I solved it!

**Comment by plus500s** [comment]
How did you solve it?

**Comment by beyondhong** [comment]
> How did you solve it?

wow, it's been a long time! 
It might be caused by libboost_python.
The first time I compiled it , it did not work on my device. 
After few days of researching, I found a different way of compiling on the internet. And it worked for me. I cannot remember the website...
