### ISSUE TITLE
Unable to add blob tags via iot blob upload

### ISSUE THREAD

**Issue by petoor** [Azure/azure-iot-sdk-python#1065]
Hi.

As the title states, I am unable to add blob tags to blobs uploaded via the iot hub.

Following your guide : https://github.com/MicrosoftDocs/azure-docs/blob/main/articles/iot-hub/iot-hub-python-python-file-upload.md
it should be as simple as 
```
# Upload the specified file
with BlobClient.from_blob_url(sas_url) as blob_client:
    with open(file_name, "rb") as f:
        result = blob_client.upload_blob(f, overwrite=True)
        blob_client.set_blob_tags({"test":"tag"})
        return (True, result)
```

However this yields a 
`<Error><Code>AuthorizationPermissionMismatch</Code><Message>This request is not authorized to perform this operation using this permission.`

On the other hand i am able to add metadata
```
# Upload the specified file
with BlobClient.from_blob_url(sas_url) as blob_client:
    with open(file_name, "rb") as f:
        result = blob_client.upload_blob(f, overwrite=True)
        blob_client.set_blob_metadata({"test":"tag"})
        return (True, result)
```

Is there any workaround around this? Adding the correct permissions to the iothub for instance.
I know this does not fit in the python sdk per se, but if you can point me to the correct repository to post this then ill gladly reupload.

**Comment by timtay-microsoft** [comment]
This is likely tied to [this issue](https://github.com/Azure/azure-iot-sdk-csharp/issues/2359), FYI @cartertinney

**Comment by petoor** [comment]
@lev-i Thanks, we do indeed need this feature so just knowing that Microsoft has it prioritized in a sprint would be very helpful.

**Comment by lev-i** [comment]
@petoor
Other customers running into the same issue had a workaround. They aren't using metadata, so they put the tags in the metadata and then copied the tags across in a Blob OnChange function.

Would that workaround be feasible for you, at least for the time being?

**Comment by lev-i** [comment]
@petoor
I'm closing this out for now. Please feel free to re-open it if you'd like.

There is the above workaround, as long as you aren't using metadata. If you are, do be aware that the Gateway team is currently working on a fix, however I wouldn't expect that to be released until after the current planning period.

**Comment by petoor** [comment]
Hi @lev-i .

Im glad they are working on a fix.

For anyone else browsing this issue : Our fix is to have an azure function with a blob trigger, that takes the metadata and adds that as tags. It works, it is not very complex, but of course it would be a better solution if it was not there at all.

**Comment by stefan-hudelmaier** [comment]
It's been half a year... Any update on this?

**Comment by lev-i** [comment]
@timtay-microsoft 

Is this still being worked on by your team?

**Comment by timtay-microsoft** [comment]
This issue is a service issue, not an SDK issue, so my team (Java + C# SDK) isn't driving this. I'm not aware of anyone on the service team working on this issue in particular, but they are undertaking a large refactoring of the service and this may get fixed inadvertently because of that. This service-side refactor may take a long time though. 

If the workaround discussed above isn't sufficient, then I'd suggest opening a support ticket through the Azure portal to get some traction.
