### ISSUE TITLE
Problem with building IoT SDK

### ISSUE THREAD

**Issue by suleymanov** [Azure/azure-iot-sdk-python#108]
- **OS and version used:** Ubuntu 16.04.3 

- **Python runtime used:** 2.7.12 

- **SDK version used:** 2017-12-01 

# Description of the issue:
I try to follow [instruction](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#linux) to install SDK on Linux machine. Build step takes very long time and eventually fails with error.

# Code sample exhibiting the issue:
    git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git
    sudo apt-get update
    sudo apt-get install -y git cmake build-essential curl libcurl4-openssl-dev libssl-dev uuid-dev
    cd azure-iot-sdk-python/build_all/linux
    ./setup.sh
    ./build.sh

# Console log of the issue:
    [ 97%] Building CXX object provisioning_device_client_python/src/CMakeFiles/provisioning_device_client_python.dir/provisioning_device_client_python.cpp.o
    c++: internal compiler error: Killed (program cc1plus)
    Please submit a full bug report, with preprocessed source if appropriate.
    See <file:///usr/share/doc/gcc-5/README.Bugs> for instructions. provisioning_device_client_python/src/CMakeFiles/provisioning_device_client_python.dir/build.make:62: recipe for target 'provisioning_device_client_python/src/CMakeFiles/provisioning_device_client_python.dir/provisioning_device_client_python.cpp.o' failed
    make[2]: *** [provisioning_device_client_python/src/CMakeFiles/provisioning_device_client_python.dir/provisioning_device_client_python.cpp.o] Error 4
    CMakeFiles/Makefile2:5629: recipe for target 'provisioning_device_client_python/src/CMakeFiles/provisioning_device_client_python.dir/all' failed
    make[1]: *** [provisioning_device_client_python/src/CMakeFiles/provisioning_device_client_python.dir/all] Error 2
    Makefile:138: recipe for target 'all' failed
    make: *** [all] Error 2

**Comment by zolvarga** [comment]
@suleymanov 

This looks like the compiler is out of mempory.
How much RAM you have?

Best Regards,
Zoltan

**Comment by suleymanov** [comment]
@zolvarga 
I'm not sure at the moment, but it's likely **Basic_A0** instance.
