### ISSUE TITLE
[Technical Question] Any support for OpenWrt

### ISSUE THREAD

**Issue by anhtu91** [Azure/azure-iot-sdk-python#1087]
Hi, 
I am trying to use azure iot python sdk for my small router, which uses OpenWrt OS. My question is, is there anyway to run python sdk for OpenWrt? And the router has only 6MB storage. I have tried with 
1. pyinstaller to create a binary -> Too big binary 
2. installed only necessary python package -> Also too big and too many python package muss go with.
3. tried to use azure iot c sdk with cross compiler -> Until now, it doesn't work for me because of my missing knowledge about cross compiler
I really would like to hear your advices.
Thanks

**Comment by anthonyvercolano** [comment]
@anhtu91 Getting the Python SDK down in a small environment like that ins't a current goal for the SDK.  It's likely that you can have better luck with the C SDK.  I would suggest you raise this issue in the issues of github.com/azure/azure-iot-sdk-c.

I note that have issues in their with folks asking about openwrt.
