### ISSUE TITLE
Can't send messages from multiple (virtual) devices

### ISSUE THREAD

**Issue by suleymanov** [Azure/azure-iot-sdk-python#109]
- **OS and version used:** Ubuntu 16.04.3 LTS

- **Python runtime used:** 2.7.12

- **SDK version used:**  2017_12_01

# Description of the issue:

Introduction:

We're planning to implement monitoring solution with Azure IoT platform which is going to have a lot of devices running. As I understand, each device ("hardware") needs a name/key pair to be successfully recognized by IoT Hub and be able to send/receive messages. To that point, I see no problem to specify same pair for all devices, which could be as many as thousands (otherwise it would be quite hard to register each device individually, i.e. providing unique name/key pair).

Issue description:

Of course, before deploying solution on real devices, I want to experiment with virtual ones. I tried to create two virtual clients sharing same name/key pair and sending data to Hub asynchronously. What I see is only one of them actually sending data while another shows up with errors for each message. I didn't proceed with experimenting on "thousands" of devices as I'm sure I would face the same issue. For now, I'm not sure if that's problem of that specific SDK, but I could successfully emulate desired behaviour with 2 Node.js virtual devices (I can provide sample code if needed). Now, questions that do worry me:
-- is it possible to fix this issue and be able to emulate multiple virtual devices sharing same name/key pair?
-- won't we face the same problem when we start to deploy implemented solution with real devices?

# Code sample exhibiting the issue:

    from time import sleep
    from iothub_client import IoTHubClient, IoTHubMessage, IoTHubTransportProvider

    def callback(msg, res, context):
        pass

    conn_string = ''  # my device connection string
    protocol = IoTHubTransportProvider.MQTT
    client = IoTHubClient(conn_string, protocol)
    client2 = IoTHubClient(conn_string, protocol)
    msg = IoTHubMessage(bytearray('hello'))  # one that doesn't come to Hub
    msg2 = IoTHubMessage(bytearray('goodbye'))  # one that comes to Hub
    while True:
        client.send_event_async(msg, callback, 0)
        # sleep(5)  # uncommenting that line won't help
        client2.send_event_async(msg2, callback, 0)
        sleep(5)

# Console log of the issue:

    Error: Time:Tue Dec 12 15:16:27 2017 File:/home/railsuleymanov/azure-iot-sdk-python/c/c-utility/adapters/socketio_berkeley.c Func:socketio_send Line:814 Failure: sending socket failed. errno=32 (Broken pipe).
    Error: Time:Tue Dec 12 15:16:27 2017 File:/home/railsuleymanov/azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:write_outgoing_bytes Line:628 Error in xio_send.
    Error: Time:Tue Dec 12 15:16:27 2017 File:/home/railsuleymanov/azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1357 Error in write_outgoing_bytes.
    Error: Time:Tue Dec 12 15:16:27 2017 File:/home/railsuleymanov/azure-iot-sdk-python/c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:332 1358: Failure sending control packet data
    Error: Time:Tue Dec 12 15:16:27 2017 File:/home/railsuleymanov/azure-iot-sdk-python/c/umqtt/src/mqtt_client.c Func:mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
    Error: Time:Tue Dec 12 15:16:27 2017 File:/home/railsuleymanov/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:publish_mqtt_telemetry_msg Line:777 Failed attempting to publish mqtt message

**Comment by zolvarga** [comment]
@suleymanov 

Multiple devices cannot share the same name/key. Each device has to be a unique device registered on IoTHub. When you created all those devices on IoTHub you can run multiple software client (even on the same machine) and send message from each client to IoTHub.

Best Regards,
Zoltan
