### ISSUE TITLE
[Technical Question]

### ISSUE THREAD

**Issue by yateenbbaluja** [Azure/azure-iot-sdk-python#1090]
Hi All, 

I am using azure iot stack to test the device provisioning service but I am getting the error as I run the sample code with all the variables values inserted.

raise ValueError("Registration Id can not be none, empty or blank.")
ValueError: Registration Id can not be none, empty or blank. I am also attaching the screenshot.

On the Azure portal I have created individual enrollment with the device-ID, Keys and ID_scope but still getting this error.

Regards,
Yateen 
![Screenshot 2023-01-09 203621](https://user-images.githubusercontent.com/20497835/211393233-1dd20871-f5fc-489e-b2d8-87210e6b071a.png)

**Comment by ryanwinter** [comment]
Hi Yateen,

So registration_id is empty, are you setting REGISTRATION_ID as an environment variable in the session?

**Comment by yateenbbaluja** [comment]
Yes but

> Hi Yateen,
> 
> So registration_id is empty, are you setting REGISTRATION_ID as an environment variable in the session?

Yes. But it got solved as the env file wasn't correctly formatted.

**Comment by ryanwinter** [comment]
I'm glad this is solved, please feel free to reopen, or create a new issue if you run into further issues.
