### ISSUE TITLE
Running iothub_client_sample_class with h flag causes error

### ISSUE THREAD

**Issue by briglx** [Azure/azure-iot-sdk-python#11]
I'm running the following on a raspberry pi and get an invalid syntax

```bash
pi@raspberrypi:~/azure-iot-sdk-python/device/samples $ python iothub_client_sample_class.py -h
  File "iothub_client_sample_class.py", line 158
    self._send_reported_state_callback, user_context)
       ^
SyntaxError: invalid syntax
```

**Comment by zolvarga** [comment]
The issue has been fixed by pull request:
https://github.com/Azure/azure-iot-sdk-python/pull/10

It will be included in the next release of Python SDK

Best Regards,
Zoltan
