### ISSUE TITLE
target_include_directories with lists of includes cause build to fail

### ISSUE THREAD

**Issue by rk-bp** [Azure/azure-iot-sdk-python#110]
- **OS and version used:** <VERSION> 
Yocto Krogoth

- **Python runtime used:** <VERSION> 
3.3

- **SDK version used:** <VERSION> 
1.1.29

# Description of the issue:

See an issue building just like this:
https://stackoverflow.com/questions/44425257/how-to-properly-use-target-include-directories-with-lists-of-includes

# Code sample exhibiting the issue:

# Console log of the issue:

Patch that fixed the build issue...

[0001-Fix-CMakeLists.txt.patch.txt](https://github.com/Azure/azure-iot-sdk-python/files/1580489/0001-Fix-CMakeLists.txt.patch.txt)

**Comment by tameraw** [comment]
@rk-bp - Thanks for filing this issue. We'll investigate and update you.

**Comment by zolvarga** [comment]
@rk-bp 

You are building on Yocto. We will investigate if applying the BUILD_INTERFACE into cmake will work with our main target platforms.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Closed as there is a workaround and work item created

**Comment by tameraw** [comment]
@rk-bp thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute customer satisfaction survey.
