### ISSUE TITLE
Device Provisioning: How to pass X.509 certificate?

### ISSUE THREAD

**Issue by vortec** [Azure/azure-iot-sdk-python#112]
I'm experimenting with `provisioning_device_client_sample.py`, but can't find a way to pass a certificate. Could someone tell me how that is done? Thanks in advance!

**Comment by zolvarga** [comment]
@vortec 

The idea of provisioning is to get the certificate from a hardware store on the device which is secure and hidden from the user code. Therefore the provisioning client will not get the certificate from the user code.
If you want to use X509 certificate for client authentication you should use the regular Device Client.
For that see the sample here:
https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample_x509.py

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Closing as answered.

**Comment by vortec** [comment]
I'm sorry I'm so late with my answer, but my understanding is that while using a TPM is the preferred way to go (as you said, it hides the private key) you can also use the X.509 attestation mechanism and I also saw options for individual X.509 enrollments.

For example, in this Java example: https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-java#simulate-the-device you can pass the public and private certificate and let the SDK identify against the DPS.

I see the same setup steps in the Python example: https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-python#create-a-device-enrollment-entry but the code itself doesn't seem to use any certificates. Where does it get the certificate information from?

My position is that I have devices running Linux which come with individual client certificates (where the public keys are known and which I want to bulk upload to DPS). I want to use them to authenticate against the DPS and let the DPS create IoT Hub devices. In the future we want to use TPMs, but right now we must use these files.

My understanding was that this should be possible using DPS, am I on the wrong track somewhere?

**Comment by vortec** [comment]
I can't re-open this ticket to get visibility, so I try a mention one last time: @zolvarga :-)

**Comment by zolvarga** [comment]
@vortec 

Hi Fabian,

We don't have a sample code yet for the authentication flow you are describing. 
We are working on it to provide that. The first sample will be implemented in C SDK.
As soon as that is checked into C, I will create a Python sample based on it.
I will let you know if the Python sample is checked in.

Best Regards,
Zoltan

**Comment by robbinvandamme** [comment]
@zolvarga 

Do you have a timeline on that example? 
Where can we start to create one our self?

thx,

Robbin

**Comment by abhatikar** [comment]
@zolvarga I am trying to run this [sample](https://github.com/Azure/azure-iot-sdk-c/tree/master/provisioning_client/samples/prov_dev_client_sample).
I want to use the x509 hsm type. I cannot see how to pass on the generated certificate and key for running this sample.
Am I missing something ?

**Comment by zolvarga** [comment]
@vortec 

Sorry for the late answer.
What you would like to accomplish is currently available only in C (and other SDKs).
To create a custom HSM sample in Python is more work than exposing the C SDK through a wrapper.
We created a work item for ourselves for this, it is in the queue, but cannot provide a deadline for it now.

Best Regards,
Zoltan

**Comment by aurashn** [comment]
@vortec  were you able to find a workaround for that issue?

**Comment by Bnjmn83** [comment]
@vortec 

We are now at the same place you were in. Did you make any progress?

I also asked my self why this example https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-python#create-a-device-enrollment-entry did connect to DPS differently as this guy here https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample_x509.py.

I am also still facing issues in getting the last example to run.
Any help is appreciated.

Greetings from Frankfurt,
Ben

**Comment by Bnjmn83** [comment]
btw I found the part in the docs that explains the need of having the private key and the certificate on the device:
(https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-x509ca-overview#authenticating-devices-signed-with-x509-ca-certificates)

> Authenticating devices signed with X.509 CA certificates
With X.509 CA certificate registered and devices signed into a certificate chain of trust, what remains is device authentication when the device connects, even for the first time. When an X.509 CA signed device connects, it uploads its certificate chain for validation. The chain includes all intermediate CA and device certificates. With this information, IoT Hub authenticates the device in a two-step process. IoT Hub cryptographically validates the certificate chain for internal consistency, and then issues a proof-of-possession challenge to the device. IoT Hub declares the device authentic on a successful proof-of-possession response from the device. This declaration assumes that the device's private key is protected and that only the device can successfully respond to this challenge. We recommend use of secure chips like Hardware Secure Modules (HSM) in devices to protect private keys.

>

**Comment by Bnjmn83** [comment]
> @vortec
> 
> Hi Fabian,
> 
> We don't have a sample code yet for the authentication flow you are describing.
> We are working on it to provide that. The first sample will be implemented in C SDK.
> As soon as that is checked into C, I will create a Python sample based on it.
> I will let you know if the Python sample is checked in.
> 
> Best Regards,
> Zoltan

@zolvarga Any update on this? It seems there is still no example code, neither in C nor in python.

**Comment by ulel** [comment]
@Bnjmn83, what I did was that I created a simple "custom HSM", custom as in no HSM and instead reading from file: https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/devdoc/using_custom_hsm.md

You have to build a library of it and linked it when building the C SDK for the Python SDK.

**Comment by AshithPolepalli** [comment]
@zolvarga 
Has the support for x509 added for python with an example? i cannot find as of now. 
Is there any estimated date for it? 
If there is support added but not example, can i get api reference to build code for my requirement?

@vortec 
I am having exact same requirement as you. Were you able to find any working solution for this using Python SDK?

Thanks in Advance.

**Comment by pierreca** [comment]
@AshithPolepalli see my comment on a related issue:
https://github.com/Azure/azure-iot-sdk-python/issues/226#issuecomment-485932275
I'm hoping to have something to show some time in May.

**Comment by pierreca** [comment]
addressed in #272. this is fixed in v2

**Comment by az-iot-builder-01** [comment]
@zolvarga, @vortec, @robbinvandamme, @abhatikar, @aurashn, @Bnjmn83, @ulel, @AshithPolepalli, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
