### ISSUE TITLE
[Technical Question] How can I stop the iot edge device from sending MQTT messages up stream ?

### ISSUE THREAD

**Issue by gauss345** [Azure/azure-iot-sdk-python#1130]
How can we stop forwarding our MQTT messages to the IoT Hub ?

We have a scenario that our devices are on a production line, and due to network traffic restrictions and cost implications, we would like to have only local MQTT message routing, and not have it send upstream. 

What we found was that when we create a automatic deployment in the IoT Hub portal, the `common_route` is added by default, but for our local E2E test environment, one can safely just omit this message route.

Is there a possibility to stop this ? I hope my question is understandable, and i'm open to explain in more detail.

**Comment by cartertinney** [comment]
@gauss345 

Apologies for the late reply - I think this is something you'd have to ask IoT Edge team about, as this repository is just about the Python SDK, but your problem appears to be more about the IoT Edge solution configuration.

I spoke with someone from Edge on your behalf, and they told me that you should do the same thing in your production environment as you have done in your local E2E test environment - omit the route.

They also provided me this document to help explain how it works: https://learn.microsoft.com/en-us/azure/iot-edge/module-composition?view=iotedge-1.4#declare-routes

I am going to close this issue now as it has nothing to do with this Python SDK. If anything else comes up, please direct your query towards the Edge product.
