### ISSUE TITLE
Stale package on arm64?

### ISSUE THREAD

**Issue by mathaou** [Azure/azure-iot-sdk-python#1141]
Based on the following information:

https://learn.microsoft.com/en-us/azure/iot-hub/device-management-python
https://github.com/Azure/azure-iot-sdk-python/blob/main/samples/iothub_simple_c2d_with_reconnect.py

cannot import name 'IoTHubDeviceClient' from 'azure.iot.device'
cannot import name 'MQTTConnectionDroppedError' from 'azure.iot.device'

This is on arm64 python3. Is this package stale or has this functionality been removed from the SDK? There appears to be conflicting information from both Microsoft itself and the wider community wherever I go regarding the state of this python SDK.

If I *really* have to I will just use the Node.js/Java SDK since those appear to be the most widely supported, but I'm just confused as to what is even going on with this developer ecosystem.

**Comment by lev-i** [comment]
@mathaou

What version of the SDK are you using?

There are a few things that come to mind here. Have you checked that you ran `pip install azure-iot-device==3.0.0b2` on whichever python version you're running? And that the python version is 3.7 or newer? Also, I'm assuming you got those error messages when running the linked simple_c2d_with_reconnect sample? If so, it might help if you post the logs, but most important would be the SDK version.

**Comment by cartertinney** [comment]
@mathaou

Right now, version 3.x of our SDK is not yet fully featured - it is still just in a preview. 3.0.0b2 that you have installed does not yet have `ProvisioningSession` included in it. Do note that until we exit preview, APIs, object models, and design approaches are completely subject to change as they are all a work in progress. We do not have a date for a finished 3.x release right now.

All of this means that we suggest you stick with 2.x for most purposes, as it is fully featured, and will provide the full functionality you are looking for, using the `IoTHubDeviceClient`, `IoTHubModuleClient` and `ProvisioningDeviceClient`. The latest version of 2.x is 2.12.0, and is very stable.

You can find samples for version 2.x in the https://github.com/Azure/azure-iot-sdk-python/tree/v2

**Comment by mathaou** [comment]
This solved the issue.
