### ISSUE TITLE
Request to update quickstart guide

### ISSUE THREAD

**Issue by mb-codialist** [Azure/azure-iot-sdk-python#1148]
Hey folks,
please consider updating the quickstart docs for the \samples. Currently https://learn.microsoft.com/en-us/azure/iot-develop/quickstart-send-telemetry-central?pivots=programming-language-python refers to V2 of the SDK, which can be confusing to the reader. 
Specifically, the "iothub_simple_telemetry.py" requires IOTHUB_DEVICE_CONNECTION_STRING, which is not mentioned in the "Quickstart: Send telemetry from a device to Azure IoT Central" guide.

**Comment by cartertinney** [comment]
The V2 SDK is still the main release - V3 is in preview, and not yet GA, so we are not yet updating documentation to refer to it.
