### ISSUE TITLE
[feature request] Allow shorter topics to save data

### ISSUE THREAD

**Issue by claria** [Azure/azure-iot-sdk-python#1149]
My feature request does not directly apply to the azure-iot-sdk-python repository, more
generally to the azure iothub backend. But i did not know, where i should place this feature request.

**Is your feature request related to a problem? Please describe.**

We send many small mqtt messages to the iothub. Currently, the length of the topic is a significant 
amount of the mqtt message which contains unneccessary data:

devices/device-foobar/messages/events/$.ct=application%2Fjson%3Bcharset%3Dutf-8

**Describe the solution you'd like**

Allow a shorter topic:

/d/device-foobar/m/e/$json

**Comment by cartertinney** [comment]
We cannot shorten the topic as that is part of the IoT Hub specification.
