### ISSUE TITLE
How to handle exceptions in the send_message() method?

### ISSUE THREAD

**Issue by AndreManzi** [Azure/azure-iot-sdk-python#1151]
Hello,
I am experiencing the following behavior:
During the send_message() call the message is put in a queue, that  queue does not have a timeout or anything and if the connection to internet is severed, the exceptions that happens in the thread in which the method is running are uncatchable.
What could be done to catch the exceptions inside of the send_message() method?
Thanks

**Comment by AndreManzi** [comment]
I am using regular client.

What I did was just before the send_message() method to close the internet connection.

The thing that I would like to accomplish is to handle exceptions that are happening in the backgroud thread where the send_message() is executed.

here are the logs:
`DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting run_op in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Creating pipeline executor
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_http:Gateway Hostname not present. Setting Hostname to: elstmvisiluxiotd01.azure-devices.net   
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_http:HTTPTransportStage(InitializePipelineOperation): got connection args
DEBUG:azure.iot.device.common.http_transport:creating a SSL context
DEBUG:azure.iot.device.common.http_transport:configuring SSL context with client-side certificate and key
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:InitializePipelineOperation: completing without error
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting <azure.iot.device.common.evented_callback.EventedCallback object at 0x000001989EEBCD00> in callback thread
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Creating callback executor
DEBUG:azure.iot.device.common.evented_callback:Callback completed with result None
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting run_op in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:Gateway Hostname not present. Setting Hostname to: elstmvisiluxiotd01.azure-devices.net
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(InitializePipelineOperation): got connection args
DEBUG:azure.iot.device.common.mqtt_transport:creating mqtt client
INFO:azure.iot.device.common.mqtt_transport:Creating client for connecting using MQTT over TCP
DEBUG:azure.iot.device.common.mqtt_transport:creating a SSL context
DEBUG:azure.iot.device.common.mqtt_transport:configuring SSL context with default certs
DEBUG:azure.iot.device.common.mqtt_transport:configuring SSL context with client-side certificate and key
DEBUG:azure.iot.device.common.mqtt_transport:Created MQTT protocol client, assigned callbacks
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:InitializePipelineOperation: completing without error
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting <azure.iot.device.common.evented_callback.EventedCallback object at 0x000001989EEBD780> in callback thread
DEBUG:azure.iot.device.common.evented_callback:Callback completed with result None
INFO:azure.iot.device.iothub.sync_clients:Connecting to Hub...
DEBUG:azure.iot.device.iothub.pipeline.mqtt_pipeline:Starting ConnectOperation on the pipeline
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting run_op in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionStateStage(ConnectOperation): State changes DISCONNECTED -> CONNECTING. Sending 
op down
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): connecting
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): Starting watchdog
DEBUG:azure.iot.device.common.mqtt_transport:connecting to mqtt broker
INFO:azure.iot.device.common.mqtt_transport:Connect using port 8883 (TCP)
DEBUG:paho:Sending CONNECT (u1, p0, wr0, wq0, wf0, c0, k60) client_id=b'cert'
DEBUG:azure.iot.device.common.mqtt_transport:_mqtt_client.connect returned rc=0
DEBUG:paho:Received CONNACK (1, 0)
INFO:azure.iot.device.common.mqtt_transport:connected with result code: 0
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_connected in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_connected in callback thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: completing connect op       ges CONNECTING -> CONNECTED. Connection es
INFO:azure.iot.device.iothub.abstract_clients:Connection State - Connected
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(ConnectOperation): cancellinging on_connected_handler watchdog
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:ConnectOperation: completing without error
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting on_complete in callback thread
DEBUG:azure.iot.device.common.evented_callback:Callback completed with result None                           watchdog
INFO:azure.iot.device.iothub.sync_clients:Successfully connected to Hub
INFO:root:sending message
INFO:azure.iot.device.iothub.sync_clients:Sending message to Hub...
DEBUG:azure.iot.device.iothub.pipeline.mqtt_pipeline:Starting SendD2CMessageOperation on the pipeline       
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting run_op in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:SendD2CMessageOperation: creating worker op of type MQTTPublishOperation
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage(MQTTPublishOperation): publishing on devices/cert/messages/events/%24.ct=application%2Fjson&%24.ce=UTF-8                                MQTTPublishOperation
INFO:azure.iot.device.common.mqtt_transport:publishing on devices/cert/messages/events/%24.ct=application%hing on devices/cert/messages/events/%242Fjson&%24.ce=UTF-8
DEBUG:paho:Sending PUBLISH (d0, q1, r0, m1), 'b'devices/cert/messages/events/%24.ct=application%2Fjson&%242Fjson&%24.ce=UTF-8.ce=UTF-8'', ... (25 bytes)                                                                                 .ce=UTF-8'', ... (25 bytes)
DEBUG:azure.iot.device.common.mqtt_transport:_mqtt_client.publish returned rc=0
DEBUG:azure.iot.device.common.mqtt_transport:Waiting for response on MID: 1
INFO:azure.iot.device.common.mqtt_transport:disconnected with result code: 7
DEBUG:azure.iot.device.common.mqtt_transport:  File "c:\Users\amanzi\.vscode\extensions\ms-python.python-2023.12.0\pythonFiles\lib\python\debugpy\_vendored\pydevd\_pydev_bundle\pydev_monkey.py", line 1118, in __call__
    ret = self.original_func(*self.args, **self.kwargs)
  File "C:\Users\amanzi\AppData\Local\Programs\Python\Python310\lib\threading.py", line 966, in _bootstrap  
    self._bootstrap_inner()
  File "C:\Users\amanzi\AppData\Local\Programs\Python\Python310\lib\threading.py", line 1009, in _bootstrap_inner
    self.run()
  File "C:\Users\amanzi\AppData\Local\Programs\Python\Python310\lib\threading.py", line 946, in run
    self._target(*self._args, **self._kwargs)
  File "c:\repos\sendtocloud\venv\lib\site-packages\paho\mqtt\client.py", line 3591, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "c:\repos\sendtocloud\venv\lib\site-packages\paho\mqtt\client.py", line 1756, in loop_forever
    rc = self._loop(timeout)
  File "c:\repos\sendtocloud\venv\lib\site-packages\paho\mqtt\client.py", line 1164, in _loop
    rc = self.loop_read()
  File "c:\repos\sendtocloud\venv\lib\site-packages\paho\mqtt\client.py", line 1558, in loop_read
    return self._loop_rc_handle(rc)
  File "c:\repos\sendtocloud\venv\lib\site-packages\paho\mqtt\client.py", line 2350, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "c:\repos\sendtocloud\venv\lib\site-packages\paho\mqtt\client.py", line 3475, in _do_on_disconnect
    on_disconnect(self, self._userdata, rc)
  File "c:\repos\sendtocloud\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 208, in on_disconnect
    logger.debug("".join(traceback.format_stack()))

INFO:azure.iot.device.common.mqtt_transport:Forcing paho disconnect to prevent it from automatically reconnecting
DEBUG:azure.iot.device.common.mqtt_transport:in paho thread.  nulling _thread
DEBUG:azure.iot.device.common.mqtt_transport:Done forcing paho disconnect
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_disconnected in pipeline thread    
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_disconnect called: The connection was lost.
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:ConnectionStateStage(DisconnectedEvent): State changes CONNECTED -> DISCONNECTED. Not attempting to reconnect (Connection retry disabled)
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_disconnected in callback thread
INFO:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: Unexpected disconnect (no pending connection op)
INFO:azure.iot.device.iothub.abstract_clients:Connection State - Disconnected
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: Connection Retry disabled - 
cancelling in-flight operations
INFO:azure.iot.device.iothub.abstract_clients:Cleared all pending method requests due to disconnect
DEBUG:azure.iot.device.common.mqtt_transport:Cancelling all pending operations
DEBUG:azure.iot.device.common.mqtt_transport:Cancelling 1 - Triggering callback
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Already in pipeline thread for on_complete
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:MQTTPublishOperation: completing with error Operation cancelled before PUBACK received
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:SendD2CMessageOperation: Worker op (MQTTPublishOperation) has been completed
DEBUG:azure.iot.device.common.pipeline.pipeline_ops_base:SendD2CMessageOperation: completing with error Operation cancelled before PUBACK received
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting on_complete in callback thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:PipelineRootStage: BackgroundExceptionEvent received. Calling on_background_exception_handler
INFO:azure.iot.device.common.evented_callback:Callback completed with error Operation cancelled before PUBACK received
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_background_exception in callback thread 
INFO:azure.iot.device.common.evented_callback:NoneType: None

WARNING:azure.iot.device.common.handle_exceptions:Exception caught in background thread.  Unable to handle. 
WARNING:azure.iot.device.common.handle_exceptions:['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: Unexpected disconnection\n']`


Here is the code:
`client = IoTHubDeviceClient.create_from_x509_certificate(
    x509, iot_hub_name, device_id, connection_retry=False)

# Connect to the IoT Hub
client.connect()


fake_data = '{"data1": 27, "data2":30}'

# Define the message to be sent
message = Message(fake_data, content_type="application/json",
                  content_encoding="UTF-8")

logging.info('sending message')
time.sleep(4)
try:
    
# Send the message to the IoT Hub
    client.send_message(message)
except Exception as e:
    logging.info(e)

# Disconnect from the IoT Hub
client.disconnect()
`

**Comment by cartertinney** [comment]
@AndreManzi You can use the `.on_background_exception` handler to receive exceptions that occur in the background thread. Same as with a receive data handler, just set the attribute to a function that takes a single argument, and when a background exception occurs, the exception will be passed to that function.

**Comment by AndreManzi** [comment]
@cartertinney thanks for the assistance, it is working

**Comment by positron96** [comment]
Hi guys, I am having exact same problem. 
While it is good to be able to attach an exception handler with `on_background_exception`, I see that a call to `send_message` will hang forever when the connection is broken. Is there a way to interrupt execution of `send_message`, so that my thread can continue to do something, like store the messages on disk?

**Comment by positron96** [comment]
ok, never mind, I found that I can put "connection_retry=False" when creating the object
