### ISSUE TITLE
I see no matter you install or download the git files. You need run additional comment.

### ISSUE THREAD

**Issue by VickiFu** [Azure/azure-iot-sdk-python#117]
git submodule update --init --recursive 
Code is need no matter how you get the github files.

- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by zolvarga** [comment]
@VickiFu 

It is very unclear what you are trying to do. Could you please write down what you did step-by-step?

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@VickiFu 

Closing as problem solved with a Skype conversation. The first clone was not successful and the repo was not complete.

Zoltan

**Comment by tameraw** [comment]
@VickiFu thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
