### ISSUE TITLE
Are there any plans to support MQTT-WS?

### ISSUE THREAD

**Issue by wmmihaa** [Azure/azure-iot-sdk-python#1172]
Our customers have gateways sitting behind firewalls which are out of their control, in which case the gateway cannot communicate withthe IoT Hub using the MQTT protocol.

According to the documentation (/README.md) the python client only support MQTT. Are there any plans to support MQTT over websockets? If not, are there any workarounds for implementing this?

**Comment by cartertinney** [comment]
We do support WebSockets. You pass in the `websockets=True` keyword argument to your preferred client factory method, such as in [this example](https://github.com/Azure/azure-iot-sdk-python/blob/main/samples/async-hub-scenarios/send_message_over_websockets.py)
