### ISSUE TITLE
azure-iot-device v2.13.0 does not support paho-mqtt v2.0.0

### ISSUE THREAD

**Issue by smijatovic** [Azure/azure-iot-sdk-python#1175]
Installing python paho-mqtt version 2.0.0 caused a conflict with the latest (current date: 05032024) azure-iot-device version 2.13.0.

```shell
ERROR: Cannot install azure-iot-device==2.13.0, testenv because these package versions have conflicting dependencies.

The conflict is caused by:
    testenv 0.0.1 depends on paho-mqtt==2.0.0
    azure-iot-device 2.13.0 depends on paho-mqtt<2.0.0 and >=1.6.1
    testenv 0.0.1 depends on paho-mqtt==2.0.0
    azure-iot-device 2.12.0 depends on paho-mqtt<2.0.0 and >=1.6.1
``` 

paho-mqtt version 2.0.0 was released on the 10th february 2024 and is currently (current date: 05032024) the latest supported version.

**Comment by cartertinney** [comment]
We'll get on fixing this right away.

**Comment by cartertinney** [comment]
Currently we don't support version 2.0 of Paho. We might be able to at some point, but for now this is a backlog item. Is it possible for you to use 1.x instead?
