### ISSUE TITLE
hi i have a problem when i install azure-iot-hub in my rasberry pi 5 command  sudo pip install azure-iot-hub

### ISSUE THREAD

**Issue by riadhhasnaoui** [Azure/azure-iot-sdk-python#1177]
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Collecting azure-iot-hub
  Using cached https://www.piwheels.org/simple/azure-iot-hub/azure_iot_hub-2.6.1-py2.py3-none-any.whl (2.7 kB)
Collecting msrest<1.0.0,>=0.6.21
  Using cached https://www.piwheels.org/simple/msrest/msrest-0.7.1-py3-none-any.whl (84 kB)
Collecting uamqp<2.0.0,>=1.2.14
  Using cached uamqp-1.6.8.tar.gz (4.5 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
Collecting azure-core<2.0.0,>=1.10.0
  WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/azure-core/azure_core-1.30.1-py3-none-any.whl
  Using cached https://www.piwheels.org/simple/azure-core/azure_core-1.30.1-py3-none-any.whl (193 kB)
Requirement already satisfied: requests>=2.21.0 in /usr/lib/python3/dist-packages (from azure-core<2.0.0,>=1.10.0->azure-iot-hub) (2.28.1)
Requirement already satisfied: six>=1.11.0 in /usr/lib/python3/dist-packages (from azure-core<2.0.0,>=1.10.0->azure-iot-hub) (1.16.0)
Collecting typing-extensions>=4.6.0
  Using cached https://www.piwheels.org/simple/typing-extensions/typing_extensions-4.10.0-py3-none-any.whl (33 kB)
Requirement already satisfied: requests-oauthlib>=0.5.0 in /usr/lib/python3/dist-packages (from msrest<1.0.0,>=0.6.21->azure-iot-hub) (1.3.0)
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProtocolError('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))': /simple/isodate/
Collecting isodate>=0.6.0
  Using cached https://www.piwheels.org/simple/isodate/isodate-0.6.1-py2.py3-none-any.whl (45 kB)
Requirement already satisfied: certifi>=2017.4.17 in /usr/lib/python3/dist-packages (from msrest<1.0.0,>=0.6.21->azure-iot-hub) (2022.9.24)
Building wheels for collected packages: uamqp
  Building wheel for uamqp (pyproject.toml) ... error
  error: subprocess-exited-with-error
  
  × Building wheel for uamqp (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [157 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-cpython-311
      creating build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/__init__.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/utils.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/sender.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/mgmt_operation.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/address.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/compat.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/connection.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/errors.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/types.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/client.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/constants.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/session.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/receiver.py -> build/lib.linux-aarch64-cpython-311/uamqp
      copying uamqp/message.py -> build/lib.linux-aarch64-cpython-311/uamqp
      creating build/lib.linux-aarch64-cpython-311/uamqp/authentication
      copying uamqp/authentication/__init__.py -> build/lib.linux-aarch64-cpython-311/uamqp/authentication
      copying uamqp/authentication/cbs_auth_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/authentication
      copying uamqp/authentication/common.py -> build/lib.linux-aarch64-cpython-311/uamqp/authentication
      copying uamqp/authentication/cbs_auth.py -> build/lib.linux-aarch64-cpython-311/uamqp/authentication
      creating build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/__init__.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/mgmt_operation_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/utils.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/sender_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/client_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/connection_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/session_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      copying uamqp/async_ops/receiver_async.py -> build/lib.linux-aarch64-cpython-311/uamqp/async_ops
      running egg_info
      writing uamqp.egg-info/PKG-INFO
      writing dependency_links to uamqp.egg-info/dependency_links.txt
      writing requirements to uamqp.egg-info/requires.txt
      writing top-level names to uamqp.egg-info/top_level.txt
      reading manifest file 'uamqp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      adding license file 'LICENSE'
      writing manifest file 'uamqp.egg-info/SOURCES.txt'
      copying uamqp/c_uamqp.c -> build/lib.linux-aarch64-cpython-311/uamqp
      running build_ext
      will build uamqp in build/temp.linux-aarch64-cpython-311/cmake
      Building with generator flags: -G "Unix Makefiles"
      calling cmake /tmp/pip-install-lucf48ke/uamqp_d7a66006460a49c8894d6cdc10d5aba5/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release
      -- The C compiler identification is GNU 12.2.0
      -- The CXX compiler identification is GNU 12.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at deps/azure-macro-utils-c/CMakeLists.txt:4 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Warning (dev) at deps/azure-macro-utils-c/CMakeLists.txt:14 (option):
        Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
        --help-policy CMP0077" for policy details.  Use the cmake_policy command to
        set the policy and suppress this warning.
      
        For compatibility with older versions of CMake, option is clearing the
        normal variable 'run_int_tests'.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Deprecation Warning at deps/umock-c/CMakeLists.txt:4 (cmake_minimum_required):
        Compatibility with CMake < 3.5 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Looking for include file stdint.h
      -- Looking for include file stdint.h - found
      -- Looking for include file stdbool.h
      -- Looking for include file stdbool.h - found
      -- target architecture: GENERIC
      -- Performing Test CXX_FLAG_CXX11
      -- Performing Test CXX_FLAG_CXX11 - Success
      CMake Error at /tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/cmake/data/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
        Could NOT find OpenSSL, try to set the path to OpenSSL root folder in the
        system variable OPENSSL_ROOT_DIR (missing: OPENSSL_CRYPTO_LIBRARY
        OPENSSL_INCLUDE_DIR)
      Call Stack (most recent call first):
        /tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/cmake/data/share/cmake-3.28/Modules/FindPackageHandleStandardArgs.cmake:600 (_FPHSA_FAILURE_MESSAGE)
        /tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/cmake/data/share/cmake-3.28/Modules/FindOpenSSL.cmake:668 (find_package_handle_standard_args)
        deps/azure-c-shared-utility/CMakeLists.txt:116 (find_package)
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 353, in <module>
          main()
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/usr/lib/python3/dist-packages/pip/_vendor/pyproject_hooks/_in_process/_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 410, in build_wheel
          return self._build_with_temp_dir(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 395, in _build_with_temp_dir
          self.run_setup()
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 487, in run_setup
          super().run_setup(setup_script=setup_script)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/build_meta.py", line 311, in run_setup
          exec(code, locals())
        File "<string>", line 260, in <module>
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/__init__.py", line 103, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/core.py", line 201, in run_commands
          dist.run_commands()
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/wheel/bdist_wheel.py", line 368, in run
          self.run_command("build")
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/command/build.py", line 131, in run
          self.run_command(cmd_name)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/dist.py", line 963, in run_command
          super().run_command(command)
        File "/tmp/pip-build-env-p784d1dl/overlay/local/lib/python3.11/dist-packages/setuptools/_distutils/dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 134, in run
        File "<string>", line 183, in build_cmake
        File "/usr/lib/python3.11/subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cmake /tmp/pip-install-lucf48ke/uamqp_d7a66006460a49c8894d6cdc10d5aba5/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for uamqp
Failed to build uamqp
ERROR: Could not build wheels for uamqp, which is required to install pyproject.toml-based projects

**Comment by cartertinney** [comment]
azure-iot-hub is no longer maintained here by us.

You can find it here:
https://github.com/Azure/azure-iot-hub-python/

**Comment by riadhhasnaoui** [comment]
> azure-iot-hub is no longer maintained here by us.
> 
> You can find it here: https://github.com/Azure/azure-iot-hub-python/

Tell me the instructions to install azure iot hub from that link : https://github.com/Azure/azure-iot-hub-python/

**Comment by cartertinney** [comment]
You will need to ask the maintainers of that repository that I linked, we do not maintain that SDK here. I have notified them on my end that you are experiencing the issue, but please open a GitHub issue on their repository, not this one.
