### ISSUE TITLE
hi i follow this instruction : https://docs.microsoft.com/en-us/azure/iot-edge/how-to-install-iot-edge-linux-arm to install iot edge on my rasberry pi 5 but i got an error 

### ISSUE THREAD

**Issue by riadhhasnaoui** [Azure/azure-iot-sdk-python#1178]
riadhhasnaoui@raspberrypi:~ $ curl https://packages.microsoft.com/config/debian/11/packages-microsoft-prod.deb > ./packages-microsoft-prod.deb
sudo apt install ./packages-microsoft-prod.deb
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  3134  100  3134    0     0   4485      0 --:--:-- --:--:-- --:--:--  4483
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Note, selecting 'packages-microsoft-prod' instead of './packages-microsoft-prod.deb'
packages-microsoft-prod is already the newest version (1.0-debian11.1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
riadhhasnaoui@raspberrypi:~ $ sudo apt-get update; \
  sudo apt-get install moby-engine
Hit:1 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease   
Hit:3 http://deb.debian.org/debian bookworm InRelease            
Hit:4 http://deb.debian.org/debian-security bookworm-security InRelease
Hit:5 http://deb.debian.org/debian bookworm-updates InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
moby-engine is already the newest version (24.0.9-debian11u1).
0 upgraded, 0 newly installed, 0 to remove and 3 not upgraded.
riadhhasnaoui@raspberrypi:~ $ sudo apt-get update; \
  sudo apt-get install aziot-edge defender-iot-micro-agent-edge
Hit:1 http://deb.debian.org/debian bookworm InRelease
Hit:2 http://archive.raspberrypi.com/debian bookworm InRelease                
Hit:3 http://deb.debian.org/debian-security bookworm-security InRelease       
Hit:4 http://deb.debian.org/debian bookworm-updates InRelease                 
Hit:5 https://packages.microsoft.com/debian/stretch/multiarch/prod stretch InRelease
Reading package lists... Done
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
Some packages could not be installed. This may mean that you have
requested an impossible situation or if you are using the unstable
distribution that some required packages have not yet been created
or been moved out of Incoming.
The following information may help to resolve the situation:

The following packages have unmet dependencies:
 defender-iot-micro-agent-edge:armhf : Depends: libcurl3:armhf but it is not installable
                                       Depends: libssl1.0.2:armhf but it is not installable
                                       Depends: sudo:armhf
 hostname : Conflicts: hostname:armhf but 3.23+nmu1 is to be installed
 hostname:armhf : Conflicts: hostname but 3.23+nmu1 is to be installed
E: Error, pkgProblemResolver::Resolve generated breaks, this may be caused by held packages.
riadhhasnaoui@raspberrypi:~ $

**Comment by cartertinney** [comment]
This is not related to the `azure-iot-device` SDK
