### ISSUE TITLE
How to connect to IoT Hub using protected private key in TPM

### ISSUE THREAD

**Issue by wudiqiang2024** [Azure/azure-iot-sdk-python#1179]
I generate key pair in TPM (Infineon SLB9670) and then generate certificate.

X509 is used in the SDK to connect to Azure IoT Hub. The key_file parameter requires a private key file, but my private key is stored in the TPM and cannot be taken out.

Can the key_file parameter support pkcs#11 or tpm2-tss-engine? Or is there any other way to solve it?

**Comment by cartertinney** [comment]
This scenario is not currently supported.
