### ISSUE TITLE
Allow higher version of urllib3

### ISSUE THREAD

**Issue by mdczaplicki** [Azure/azure-iot-sdk-python#1180]
Please allow higher version of `urllib3`. The one required in this package is quite old.

**Comment by cartertinney** [comment]
I'll take a look next time I get a chance to see what options are viable for us. We had heavily restricted the versioning for urllib3 due to a compatibility issue - perhaps with time having passed we can loosen the restriction.

**Comment by Eramismus** [comment]
Are there any updates on relaxing the urllib3 version? Is there still a compatibility issue?

**Comment by cartertinney** [comment]
@Eramismus

Unfortunately, right now it looks like we will not be lifting this version restriction.

**Comment by cartertinney** [comment]
`azure-iot-device` version 2.14.0 has been released containing this fix.
