### ISSUE TITLE
Authentication to IoTHub using DefaultAzureCredentials to be able to run Direct Methods

### ISSUE THREAD

**Issue by jsnchzjmnz** [Azure/azure-iot-sdk-python#1183]
Hi,
I have some Azure IoTHub direct methods working, and I want to call them through Python. I can instantiate the clients using create_from_connection_string, but I want to use DefaultAzureCredential instead Connection Strings. My idea by now is to try to extract a token from DefaultAzureCredential, to be able to use it in other function such as create_from_sastoken or similar.
Does this make sense?
Is there a way to do it that I'm not seeing?

**Comment by cartertinney** [comment]
We do not support direct instantiation from this auth method, no.
