### ISSUE TITLE
[feature request] support requests >2.32 via maintained requests-unixsocket fork?

### ISSUE THREAD

**Issue by robin-wayve** [Azure/azure-iot-sdk-python#1187]
**Is your feature request related to a problem? Please describe.**
We would like to upgrade `requests` for https://github.com/advisories/GHSA-9wx4-h78v-vm56

**Describe the solution you'd like**
requests-unixsocket has been forked to address the previous blocker: https://github.com/msabramo/requests-unixsocket/issues/73#issuecomment-2125848213

**Comment by robin-wayve** [comment]
previously discussed @ #1182

**Comment by cartertinney** [comment]
I'll try and get this updated in the next week or so. We have to make sure that the fork of `requests-unixsocket` is safe.

**Comment by cartertinney** [comment]
Version 2.14.0 has been released containing this fix
