### ISSUE TITLE
[feature request] Pass certificate and key file contents instead of file path

### ISSUE THREAD

**Issue by Siecje** [Azure/azure-iot-sdk-python#1188]
**Is your feature request related to a problem? Please describe.**

I'm loading the certificate to get the common name. I'd like to pass the contents of the certificate and key file when provisioning.

**Describe the solution you'd like**

For `azure.iot.device.X509` to accept the file contents instead of the file paths.

**Describe alternatives you've considered**

My current work around is to create temp files.

**Comment by cartertinney** [comment]
I'll bring this up with the team, but I would not expect us to implement support for this feature in the near future.

**Comment by ryanwinter** [comment]
Hi @Siecje,

We are only working on security and stability issues at this point, however I will add this to our backlog for future consideration.
