### ISSUE TITLE
Improve ProvisioningDeviceClient.register() exception

### ISSUE THREAD

**Issue by Siecje** [Azure/azure-iot-sdk-python#1195]
If the device client certificate has expired `ProvisioningDeviceClient.register()` will raise `ClientError("Unexpected failure")`.

https://github.com/Azure/azure-iot-sdk-python/blob/62690bd999c918caccaf900d3d9c78f3a707cdef/azure-iot-device/azure/iot/device/provisioning/aio/async_provisioning_device_client.py#L46C20-L46C59

The original exception is more useful. `ServiceError("register request returned a service error status code 401")`

**Comment by ryanwinter** [comment]
Thanks for the feedback @Siecje, at this time we only focused on stability and security related fixes, but we will add this to our internal backlog for consideration in the future.
