### ISSUE TITLE
MacOS python 3.* build

### ISSUE THREAD

**Issue by AmarShaked** [Azure/azure-iot-sdk-python#121]
After I follow all the instructions I get an error:

Traceback (most recent call last):
  File "app.py", line 4, in <module>
    from hub_client import send
  File "/Users/shakedamar/Projects/axonize-python-sdk/hub_client.py", line 3, in <module>
    import iothub_client
ImportError: dynamic module does not define module export function (PyInit_iothub_client)

I tried with all the above versions: 3.5, 3.6, 3.7

**Comment by zolvarga** [comment]
@AmarShaked 

Could you please send us the code you run?

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@AmarShaked 

Please also send us the platform and SDK info. (OS and SDK version)

Best Regards,
Zoltan

**Comment by jspaith** [comment]
Closing this out as it's been open for a bit.  @AmarShaked, if you can get us the code please re-activate this or else open a new issue.  Thanks.

**Comment by tameraw** [comment]
@AmarShaked thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
