### ISSUE TITLE
ImportError: DLL load failed: The specified procedure could not be found.

### ISSUE THREAD

**Issue by sbijou** [Azure/azure-iot-sdk-python#122]
- **OS and version used:** Windows 7 SP1 [6.1.7601]

- **Python runtime used:** Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32

- **SDK version used:** Branch: master

# Description of the issue:
cannot import iothub_client

i have MSVC++ [2010, 2012, 2013, 2015, 2017] redistributable (x64) installed

# Code sample exhibiting the issue:
import iothub_client

# Console log of the issue:
C:\Windows\System32>pip install azure-iothub-device-client
Collecting azure-iothub-device-client
  Downloading azure_iothub_device_client-1.2.3-py3-none-win_amd64.whl (426kB)
    100% |████████████████████████████████| 430kB 602kB/s
Installing collected packages: azure-iothub-device-client
Successfully installed azure-iothub-device-client-1.2.3

C:\Windows\System32>python
Python 3.6.4 (v3.6.4:d48eceb, Dec 19 2017, 06:54:40) [MSC v.1900 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import iothub_client
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python36\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified procedure could not be found.

**Comment by zolvarga** [comment]
@sbijou 

You need to have c++ runtime installed to load the DLL.
The easiest way to get it working to install Visual Studio (Community edition is enough).

Please let me know if that fixed the problem.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@sbijou 

Sorry, I missed your comment about the runtime installation, but could you pls make sure those installations are correct?

Best Regards,
Zoltan

**Comment by sbijou** [comment]
@zolvarga 

I finally got it to work... Long story short. On a new Win7 SP1 install, I just needed to do ALL Windows updates. A few hours later, it worked.

Thanks for the help!

(Now if i could just get pip install to work on MacOS...)

**Comment by tameraw** [comment]
@sbijou thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).

**Comment by kartheekakkur** [comment]
File "C:\ProgramData\Anaconda3\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.
