### ISSUE TITLE
mqtt_client_publish send failed

### ISSUE THREAD

**Issue by ohmyheartbeat** [Azure/azure-iot-sdk-python#123]
- **OS and version used: Windows 10

- **Python runtime used: 2.7.14 

- **SDK version used: 1.1.27

# Description of the  issue:

i run the sample , the console output `mqtt_client_publish send failed`

# Code sample exhibiting the issue:

# Console log of the issue:
iotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:_socketio_dowork Line:529 Socketio_Failure: Receiving data from endpoint: 10053.
Error: Time:Wed Mar  7 09:44:08 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:_socketio_dowork Line:529 Socketio_Failure: Receiving data from endpoint: 10053.
Error: Time:Wed Mar  7 09:44:08 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:_socketio_dowork Line:529 Socketio_Failure: Receiving data from endpoint: 10053.
Error: Time:Wed Mar  7 09:44:38 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:_socketio_dowork Line:529 Socketio_Failure: Receiving data from endpoint: 10053.
Error: Time:Wed Mar  7 09:44:39 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:_socketio_dowork Line:529 Socketio_Failure: Receiving data from endpoint: 10053.
Error: Time:Wed Mar  7 09:44:40 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:_socketio_dowork Line:529 Socketio_Failure: Receiving data from endpoint: 10053.
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_sendPacketItem Line:332 141: Failure sending control packet data
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\iothub_client\src\iothubtransport_mqtt_common.c Func:_publish_mqtt_telemetry_msg Line:777 Failed attempting to publish mqtt message
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_sendPacketItem Line:332 141: Failure sending control packet data
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\iothub_client\src\iothubtransport_mqtt_common.c Func:_publish_mqtt_telemetry_msg Line:777 Failed attempting to publish mqtt message
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_sendPacketItem Line:332 141: Failure sending control packet data
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\iothub_client\src\iothubtransport_mqtt_common.c Func:_publish_mqtt_telemetry_msg Line:777 Failed attempting to publish mqtt message
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_sendPacketItem Line:332 141: Failure sending control packet data
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:_mqtt_client_publish Line:1030 Error: mqtt_client_publish send failed
Error: Time:Wed Mar  7 09:45:41 2018 File:C:\Users\Administrator\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\iothub_client\src\iothubtransport_mqtt_common.Confirmation[0] received for message with result = MESSAGE_TIMEOUT
    message_id: message_0
output that will help debugging -->

**Comment by zolvarga** [comment]
@ohmyheartbeat 

Please update tot the latest SDK and try again.  1.1.27 is very old version

Best Regards,
Zoltan

**Comment by jspaith** [comment]
Closing out as this has been open for a bit.  @ohmyheartbeat, if you still hit issues on a new SDK please re-activate this issue or open a new one.  Thanks.

**Comment by tameraw** [comment]
@ohmyheartbeat thank you for your contribution to our open-sourced project!  Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).
