### ISSUE TITLE
iothub_messaging_sample.py fails with SASL handshake failed with code 02

### ISSUE THREAD

**Issue by DmitryBychkou** [Azure/azure-iot-sdk-python#124]
- **OS and version used:** Debian 9.3 (stretch), Raspbian 9.3 (stretch)
- **Python runtime used:** Python 2.7.13
- **SDK version used:** Branch: master

# Description of the issue:
iothub_messaging_sample.py fails with SASL handshake failed with code 02

Steps to reproduce:
1. Build the Azure IoT Hub SDKs for Python on Linux
2. Insert connection string and device_id into iothub_messaging_sample.py.
3. Run iothub_messaging_sample.py

# Console log of the issue:
python iothub_messaging_sample.py

Python 2.7.13 (default, Nov 24 2017, 17:33:09)
[GCC 6.3.0 20170516]
IoT Hub Service Client for Python

Starting the IoT Hub Service Client Messaging Python sample...
    Connection string = <connection_string>
    Device ID         = <device_id>
Sending message: 0
Sending message: 1
Sending message: 2
Sending message: 3
Sending message: 4
Sending message: 5
Sending message: 6
Sending message: 7
Sending message: 8
Sending message: 9
Press Enter to continue...
Error: Time:Wed Mar  7 16:39:10 2018 File:/root/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:on_sasl_frame_received_callback Line:901 SASL handshake failed with code 02
Error: Time:Wed Mar  7 16:39:10 2018 File:/root/azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:decode_ssl_received_bytes Line:788 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Wed Mar  7 16:39:10 2018 File:/root/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:on_underlying_io_error Line:237 Error callback received in unexpected state
Error: Time:Wed Mar  7 16:39:10 2018 File:/root/azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:837 Error in decode_ssl_received_bytes.

send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
Error: Time:Wed Mar  7 16:39:11 2018 File:/root/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:saslclientio_send_async Line:1173 send called while not open
Error: Time:Wed Mar  7 16:39:11 2018 File:/root/azure-iot-sdk-python/c/uamqp/src/connection.c Func:on_bytes_encoded Line:253 Cannot send encoded bytes
Error: Time:Wed Mar  7 16:39:11 2018 File:/root/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1122 saslclientio_close called while not open
Error: Time:Wed Mar  7 16:39:11 2018 File:/root/azure-iot-sdk-python/c/uamqp/src/connection.c Func:on_bytes_encoded Line:257 xio_close failed

**Comment by zolvarga** [comment]
@DmitryBychkou 

Thanks for reporting this, we will take a look at it.

Best Regards,
Zoltan

**Comment by arjankroontolsma** [comment]
I have the same problem, 
Is there any progress in the sollution?


`python iothub_messaging_sample.py

Python 2.7.15rc1 (default, Apr 15 2018, 21:51:34)
[GCC 7.3.0]
IoT Hub Service Client for Python

Starting the IoT Hub Service Client Messaging Python sample...
    Connection string = HostName=tolsmademoa31a5.azure-devices.net;SharedAccessKeyName=service;SharedAccessKey=KYf91rrvwAh3nLqyR3K5ROfoEDED1WZXSTHDkh9xerE=
    Device ID         = 68a3f8c2-0344-4a29-9a14-dcbf8ab4e4b9
Sending message: 0
{"service client sent a message": 15.48}
Sending message: 1
{"service client sent a message": 15.50}
Sending message: 2
{"service client sent a message": 14.49}
Sending message: 3
{"service client sent a message": 12.25}
Sending message: 4
{"service client sent a message": 14.75}
Sending message: 5
{"service client sent a message": 14.01}
Sending message: 6
{"service client sent a message": 12.90}
Sending message: 7
{"service client sent a message": 13.74}
Sending message: 8
{"service client sent a message": 14.54}
Sending message: 9
{"service client sent a message": 12.29}
Press Enter to continue...
Error: Time:Fri Apr 20 09:00:09 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:on_sasl_frame_received_callback Line:901 SASL handshake failed with code 02
Error: Time:Fri Apr 20 09:00:09 2018 File:/home/azure/azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:decode_ssl_received_bytes Line:762 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Fri Apr 20 09:00:09 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:on_underlying_io_error Line:237 Error callback received in unexpected state
Error: Time:Fri Apr 20 09:00:09 2018 File:/home/azure/azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:811 Error in decode_ssl_received_bytes.

send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
send_complete_callback called with context : 0
messagingResult : OK
Error: Time:Fri Apr 20 09:01:58 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:saslclientio_send_async Line:1173 send called while not open
Error: Time:Fri Apr 20 09:01:58 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/connection.c Func:on_bytes_encoded Line:255 Cannot send encoded bytes
Error: Time:Fri Apr 20 09:01:58 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1122 saslclientio_close called while not open
Error: Time:Fri Apr 20 09:01:58 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/connection.c Func:on_bytes_encoded Line:259 xio_close failed
Error: Time:Fri Apr 20 09:01:58 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1122 saslclientio_close called while not open
Error: Time:Fri Apr 20 09:01:58 2018 File:/home/azure/azure-iot-sdk-python/c/uamqp/src/connection.c Func:connection_close Line:1381 xio_close failed
`

**Comment by pierreca** [comment]
This happens because the underlying C SDK does not support using the `service` shared access policy, because of this: 

https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_service_client/src/iothub_messaging_ll.c#L457

This will be followed up on https://github.com/Azure/azure-iot-sdk-c/issues/529 on the C SDK side.

**Comment by mboujonnier** [comment]
Instead of using `SharedAccessKeyName=service`, is there another way to do which would work ?

**Comment by pierreca** [comment]
@mboujonnier using the `iothubowner` policy should work. it's the only one supported by the C SDK for now and therefore the only one that the Python SDK can offer.

**Comment by mboujonnier** [comment]
Ah.... thanks for checking, I was using the wrong SAK.... it works, All my apologies.

**Comment by az-iot-builder-01** [comment]
@DmitryBychkou, @zolvarga, @arjankroontolsma, @mboujonnier, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by MichaelDenczek** [comment]
Testing with C code, the issue also occurs with the iothub_devicemethod_sample and possibly others.  The iothubowner work-around does allow the applications to run successfully. 

The SDK should be updated to support service shared access keys or the samples should have their documentation updated to indicate the iothubowner requirement.
