### ISSUE TITLE
ImportError: /usr/lib/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/lib/python2.7/site-packages/iothub_client/iothub_client.so)

### ISSUE THREAD

**Issue by TedZhaoC** [Azure/azure-iot-sdk-python#127]
Sorry for the long string in the title, but it will be much helpful for later search. 

I try to use the iot-sdk-python on an embedded platform. After running "**python iothub_client_sample.py**", it gives me the following error, 

_ImportError: /usr/lib/libcrypto.so.1.0.0: version `OPENSSL_1.0.0' not found (required by /usr/lib/python2.7/site-packages/iothub_client/iothub_client.so)_

Thanks for the answers.

**Comment by zolvarga** [comment]
@TedZhaoC 

Please check if you have opensl installed:
/sbin/ldconfig -p | grep openssl

If not:
sudo apt-get install openssl

Best Regards,
Zoltan

**Comment by TedZhaoC** [comment]
Yes, the openssl is already installed. 

Update:
We figure it out a way to get around the block. The real reason is that the running platform already has newer libraries than the building system. The easier solution is to copy all necessary ones and specify via preloading. The trick is never attempt to overwrite the existing ones otherwise one would end up with not be able to run any commands, e.g. cd, ls etc. 
The final solution should be either MicroSoft or OEM vendor makes all libraries consistent. 

Best regards,
Ted

**Comment by yzhong94** [comment]
@TedZhaoC , thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V)
