### ISSUE TITLE
Forcing https to use TLS1.2 or higher

### ISSUE THREAD

**Issue by adw555** [Azure/azure-iot-sdk-python#133]
- **OS and version used:** Ubuntu 16.04 

- **Python runtime used:** 3 

- **SDK version used:** Lts 01-2018 

# Description of the issue:

Is there a way when using the file upload functionality to the IOT Hub, to use TLS 1.2 only (disable 1.1/1.0)?

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by zolvarga** [comment]
@adw555 

Yes, you have to use the set_option API with "tls_version" option name and "2" as a value.

Use:
0 -> TLS VERSION_1_0
1 -> TLS VERSION_1_1
2 -> TLS VERSION_1_2

Best Regards,
Zoltan

**Comment by andrewwylie** [comment]
Many thanks Zoltan.

On 17 Apr 2018, at 21:25, Zoltan Varga <notifications@github.com<mailto:notifications@github.com>> wrote:


@adw555<https://github.com/adw555>

Yes, you have to use the set_option API with "tls_version" option name and "2" as a value.

Use:
0 -> TLS VERSION_1_0
1 -> TLS VERSION_1_1
2 -> TLS VERSION_1_2

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Closing as answered

**Comment by BertKleewein** [comment]
The SDK version that this question refers to is very old and no longer supported, but according to my reading of the code, the correct values to pass are `10` for TLS 1.0, `11` for TLS 1.1, and `12` for TLS 1.2. The default, at least for the Linux version of this library, is TLS 1.2.
