### ISSUE TITLE
Wheels built for Mac can't be installed: not a supported wheel on this platform

### ISSUE THREAD

**Issue by alanjcastonguay** [Azure/azure-iot-sdk-python#135]
- **OS and version used:** OSX 10.13.4 (17E199)

- **Python runtime used:** Python 3.6.5

- **SDK version used:** commit a8176c87b04382e7db96551b62ba0af2ae841ed4 (2018-04-12)

# Description of the issue:

Wheels built for MacOSX can't be installed on MacOSX. This is similar to issue #36 -- the `PLAT_ARCH` is embedded as a tag in the wheel filename. But `macos64` is not a supported platform (on my machine). As far as I can tell, it's not a supported platform on _any_ machine.

```
$ azure-iot-sdk-python/build_all/mac/release.sh --build-python 3.6

$ python3 -m pip install azure-iot-sdk-python/build_all/mac/release_device_client/dist/azure_iothub_device_client-1.3.2-py3-none-macos64.whl

azure_iothub_device_client-1.3.2-py3-none-macos64.whl is not a supported wheel on this platform.
```

The filename component `macos64` comes directly from the following in `release.sh`, and `PLAT_ARCH` is not used for anything else.

```bash
# identify processor architecture
if [[ "$(uname -m)" = "x86_64" ]] ; then
    PLAT_ARCH="macos64"
else
    PLAT_ARCH="macos32"
fi
```

The logic in pip determining the above supported-ness is parsing the wheel's filename for tags:

```python
>>> from pip._internal.wheel import Wheel
>>> w = Wheel("azure_iothub_device_client-1.3.2-py3-none-macos64.whl")
>>> w.file_tags
{('py3', 'none', 'macos64')}
>>> w.supported()
False
```

... and comparing against the list of supported tags:

```python
>>> from pip._internal import pep425tags
>>> pep425tags.get_supported()
```

# Suggested PLAT_ARCH:
* macosx_10_6_x86_64
* macosx_10_6_i386

**Comment by zolvarga** [comment]
@alanjcastonguay 

Thanks for the detailed report. This is a known issue and we are working on it.
I will get back to you as soon as we have the packages.

Best Regards,
Zoltan
