### ISSUE TITLE
ImportError: /usr/src/app/iothub_client.so: invalid ELF header

### ISSUE THREAD

**Issue by CarlosLabrado** [Azure/azure-iot-sdk-python#139]
Hello after a few problems building with python 3 on the mac I was able to get it to work, but when I try to import it gives me this error:

ImportError: /usr/src/app/iothub_client.so: invalid ELF header

Here are some of the logs from when it was built

[100%] Built target iothub_client_python
Test project /Users/username/Desktop/azure/azure-iot-sdk-python/c/cmake/iotsdk_mac
No tests were found!!!
~/Desktop/azure/azure-iot-sdk-python
copy iothub_client library to samples folder
copy iothub_client_mock library to tests folder
copy iothub_service_client library to samples folder
copy iothub_service_client_mock library to tests folder
copy provisioning_device_client library to samples folder
cp: /Users/username/Desktop/azure/azure-iot-sdk-python/c/cmake/iotsdk_mac/provisioning_device_client_python/src/provisioning_device_client.dylib: No such file or directory
copy provisioning_device_client_mock library to tests folder
cp: /Users/username/Desktop/azure/azure-iot-sdk-python/c/cmake/iotsdk_mac/provisioning_device_client_python/tests/provisioning_device_client_mock.dylib: No such file or directory
cp: /Users/username/Desktop/azure/azure-iot-sdk-python/c/cmake/iotsdk_mac/provisioning_device_client_python/src/provisioning_device_client.dylib: No such file or directory
python3.6 iothub_service_client_ut.py
test_IoTHubDeviceMethod (__main__.TestClassDefinitions) ... ok
test_IoTHubDeviceTwin (__main__.TestClassDefinitions) ... ok
test_IoTHubMap (__main__.TestClassDefinitions) ... ok
test_IoTHubMessage (__main__.TestClassDefinitions) ... ok
test_IoTHubMessaging (__main__.TestClassDefinitions) ... ok
test_IoTHubRegistryManager (__main__.TestClassDefinitions) ... ok
test_IoTHubServiceClientAuth (__main__.TestClassDefinitions) ... ok
test_IoTHubDeviceConnectionState (__main__.TestEnumDefinitions) ... ok
test_IoTHubDeviceMethodResult (__main__.TestEnumDefinitions) ... ok
test_IoTHubDeviceStatus (__main__.TestEnumDefinitions) ... ok
test_IoTHubDeviceTwinResult (__main__.TestEnumDefinitions) ... ok
test_IoTHubFeedbackStatusCode (__main__.TestEnumDefinitions) ... ok
test_IoTHubMapResult (__main__.TestEnumDefinitions) ... ok
test_IoTHubMessageResult (__main__.TestEnumDefinitions) ... ok
test_IoTHubMessagingResult (__main__.TestEnumDefinitions) ... ok
test_IoTHubRegistryManagerResult (__main__.TestEnumDefinitions) ... ok
test_IoTHubDeviceMethodError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubDeviceMethodErrorArg (__main__.TestExceptionDefinitions) ... ok
test_IoTHubDeviceTwinError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubDeviceTwinErrorArg (__main__.TestExceptionDefinitions) ... ok
test_IoTHubError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubMapError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubMapErrorArg (__main__.TestExceptionDefinitions) ... ok
test_IoTHubMessageError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubMessageErrorArg (__main__.TestExceptionDefinitions) ... ok
test_IoTHubMessagingError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubMessagingErrorArg (__main__.TestExceptionDefinitions) ... ok
test_IoTHubRegistryManagerError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubRegistryManagerErrorArg (__main__.TestExceptionDefinitions) ... ok
test_IoTHubServiceClientAuthError (__main__.TestExceptionDefinitions) ... ok
test_IoTHubServiceClientAuthErrorArg (__main__.TestExceptionDefinitions) ... ok

----------------------------------------------------------------------
Ran 31 tests in 0.008s

OK
python3.6 iothub_service_client_map_test.py
test_IoTHubMap (__main__.TestIotHubMap) ... ok
test_IoTHubMapAddDelete (__main__.TestIotHubMap) ... ok

----------------------------------------------------------------------
Ran 2 tests in 0.009s

OK

**Comment by pierreca** [comment]
@CarlosLabrado I fixed a couple of issues with the mac build - can you try to checkout the latest version from master and let me know if you still see the issue?

**Comment by pierreca** [comment]
closing after some inactivity. we believe the Mac build is fixed, provided that boost-python is installed and updated to the latest version using brew. feel free to reopen/open a new issue if the problem persists.

**Comment by az-iot-builder-01** [comment]
@CarlosLabrado, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
