### ISSUE TITLE
File missing

### ISSUE THREAD

**Issue by guidoffm** [Azure/azure-iot-sdk-python#14]
The file https://github.com/Azure/azure-iot-sdk-python/blob/doc/get_started/python-run-sample.md referenced in the device/readme.md is missing

**Comment by olivierbloch** [comment]
Hi @guidoffm 
It seems you are referencing files that are in the develop branch. We are now working out of the master branch and the develop branch is out of date.
I am closing this issue. Please feel free to reopen if you still see something off in the docs
Thanks
