### ISSUE TITLE
IOTHUB_CLIENT_INDEFINITE_TIME

### ISSUE THREAD

**Issue by IanLeatherbury** [Azure/azure-iot-sdk-python#140]
Hardware: Running Raspberry Pi 3 Model B Motherboard.
OS: Debian 9.3
Python 2.7.13

Hey guys, just had a new error message pop up. Am curious what it means. The time displayed is the correct time, so not sure what might be causing it.

Error: *IOTHUB_CLIENT_INDEFINITE_TIME*

```
Error: Time:Wed May  9 21:11:45 2018 
File:/home/pi/iot-hub-python-raspberrypi-client-app/azure-iot-sdk-python/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_GetLastMessageReceiveTime Line:1672 
result = IOTHUB_CLIENT_INDEFINITE_TIME
No message received
```

Some additional context would be helpful.

Happy to post to StackOverflow as well.

**Comment by IanLeatherbury** [comment]
Details on SO: https://stackoverflow.com/questions/50282504/iothub-client-indefinite-time

To be clear, my project is still working. I am trying to make sure it does not break in the future though :-)

**Comment by zolvarga** [comment]
@IanLeatherbury 

It returns with  IOTHUB_CLIENT_INDEFINITE_TIME when getting the time from the OS is failed. It is a C API what calls to the system.
It is could be a problem with the specific device or OS.

Best Regards,
Zoltan

**Comment by pierreca** [comment]
Closed with @zolvarga's answer. thanks!
