### ISSUE TITLE
Sdk is not building in Raspian/Python3.6

### ISSUE THREAD

**Issue by renato04** [Azure/azure-iot-sdk-python#143]
- **OS and version used:** <VERSION> 
Raspbian GNU/Linux 9 

- **Python runtime used:** <VERSION> 
python 3.6

- **SDK version used:** <VERSION> 
latest stable (i think)

# Description of the issue:

I'm trying to build the sdk in raspian and i'm getting this error at very end of the build process. I don`t know what i have to do now.

# Code sample exhibiting the issue:

./setup.sh --python-version 3
./build.sh --build-python 3
# Console log of the issue:

~/azure-iot-sdk-python
copy iothub_client library to samples folder
copy iothub_client_mock library to tests folder
copy iothub_service_client library to samples folder
copy iothub_service_client_mock library to tests folder
copy provisioning_device_client library to samples folder
copy provisioning_device_client_mock library to tests folder
python3 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: /home/pi/azure-iot-sdk-python/device/tests/iothub_client_mock.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv

**Comment by LinuxChristian** [comment]
I get the same error with the exact same setup.

**Comment by LinuxChristian** [comment]
Correction, I get the error when using build-python 3.4.

I tried compiling it with build-python=3.5 and that works for the repo head.

However I get the error,

```
Error: Time:Fri Jun  1 13:57:22 2018 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:584 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Fri Jun  1 13:57:22 2018 File:/home/pi/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Fri Jun  1 13:57:22 2018 File:/home/pi/azure-iot-sdk-python/c/iothub_service_client/src/iothub_devicetwin.c Func:sendHttpRequestTwin Line:264 HTTPAPIEX_SAS_ExecuteRequest failed
Error: Time:Fri Jun  1 13:57:22 2018 File:/home/pi/azure-iot-sdk-python/c/iothub_service_client/src/iothub_devicetwin.c Func:IoTHubDeviceTwin_GetTwin Line:450 Failure sending HTTP request for create device
Error: Time:Fri Jun  1 13:57:22 2018 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:582 curl_easy_perform() failed: Out of memory
```

Perhaps related to something else.

**Comment by ewertons** [comment]
Hi @LinuxChristian ,
to fix the issue you are seeing please refer to this [comment](https://github.com/Azure/azure-iot-sdk-c/issues/308#issuecomment-348848995).
Otherwise you need to upgrade curl in your machine.
The Azure IoT Python client SDK is a wrapper around our C SDK, and the recommendation for upgrading curl is posted [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/devbox_setup.md#set-up-a-linux-development-environment).

**Comment by pierreca** [comment]
@ewertons thanks for stepping up!
@LinuxChristian Can you please confirm if this suggestion solved your issue? Closing the issue since it's inactive but feel free to reopen if that doesn't work. Thanks!

**Comment by LinuxChristian** [comment]
Thanks for the reply and sorry about the delay. I will try the fix within a day and report back.

**Comment by LinuxChristian** [comment]
Sorry for the late reply. Took a while to test a couple of different combinations. I still get the error,

```
Scanning dependencies of target iothub_service_client_python
[100%] Building CXX object python_service_client/src/CMakeFiles/iothub_service_client_python.dir/iothub_service_client_python.cpp.o
[100%] Linking CXX shared library iothub_service_client.so
[100%] Built target iothub_service_client_python
Scanning dependencies of target iothub_service_client_mock
[100%] Building CXX object python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/iothub_service_client_mock.cpp.o
[100%] Building CXX object python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/__/src/iothub_service_client_python.cpp.o
[100%] Linking CXX shared library iothub_service_client_mock.so
[100%] Built target iothub_service_client_mock
completed run...
Tue 24 Jul 15:21:11 CEST 2018
Test project /home/pi/azure-iot-sdk-python/c/cmake/iotsdk_linux
No tests were found!!!
~/azure-iot-sdk-python
copy iothub_client library to samples folder
copy iothub_client_mock library to tests folder
copy iothub_service_client library to samples folder
copy iothub_service_client_mock library to tests folder
copy provisioning_device_client library to samples folder
copy provisioning_device_client_mock library to tests folder
python3.4 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: /home/pi/azure-iot-sdk-python/device/tests/iothub_client_mock.so: undefined symbol: _ZNK5boost6python7objects21py_function_impl_base9max_arityEv

```

It does not matter if gnutls and openssl installed. I have however installed the SDK using the latest pip package and that works better.

So I am happy to keep this issue closed. It may just be some strange packages on my system.

**Comment by pierreca** [comment]
@LinuxChristian thanks for the report - can you confirm which version of the boost library you have installed on your system?

**Comment by LinuxChristian** [comment]
@pierreca I am using Libboost 1.62
