### ISSUE TITLE
SDk not building on mac with python 3.6.2

### ISSUE THREAD

**Issue by niksacdev** [Azure/azure-iot-sdk-python#144]
- **OS and version used:** <VERSION> macOS HS 10.13.4

- **Python runtime used:** <VERSION> Python 3.6.2

- **SDK version used:** <VERSION> git clone
Homebrew 1.6.6
Also, ran the ./setup.sh --python-version 3.6 - Worked without any errors
BUILDING BOOST for PYTHON 3.6
Warning: boost 1.67.0_1 is already installed and up-to-date
To reinstall 1.67.0_1, run `brew reinstall boost`
Warning: openssl 1.0.2o_1 is already installed and up-to-date
To reinstall 1.0.2o_1, run `brew reinstall openssl`
Warning: cmake 3.11.2 is already installed and up-to-date
To reinstall 3.11.2, run `brew reinstall cmake`
Warning: boost-python3 1.67.0 is already installed and up-to-date
To reinstall 1.67.0, run `brew reinstall boost-python3`

# Description of the issue:
Ran the steps as described, Setup runs without errors but Build fails. I get the following output as an error and no so file created in samples. Specifically, I need the Device Provisioning Client.
I can see the error below relates to test. I am not worried much if the tests are not run, but I don't see the compiled output (the iothub_client.so file) to use with my python samples folders. 

Ran ./build.sh --python-version 3.6           

# Console log of the issue:
Full Log Attached
[log.txt](https://github.com/Azure/azure-iot-sdk-python/files/2049990/log.txt)

clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [python_service_client/tests/iothub_service_client_mock.dylib] Error 1
make[1]: *** [python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/all] Error 2
make: *** [all] Error 2
No tests were found!!!
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/test/iothub_client_mock.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/tests/iothub_service_client_mock.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: /Users/niksacmac/OneDrive/projects-mac/github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: No module named iothub_client_mock

**Comment by vjrantal** [comment]
@niksacdev I had the same issue and I believe it is due to the way latest Boost gets installed by brew and how latest cmake tries to find Boost. In you log output, the problem is visible in line that says:

```
Could NOT find Boost
```

I fixed by first setting some environment variables:

```
export BOOST_ROOT=/usr/local/Cellar/boost/1.67.0_1
export BOOST_INCLUDEDIR=/usr/local/Cellar/boost/1.67.0_1/include
export BOOST_LIBRARYDIR=/usr/local/Cellar/boost-python3/1.67.0/lib
```

And then fixing another issue with a symlink:

```
ln -s /usr/local/Cellar/boost-python3/1.67.0/lib/libboost_python36-mt.dylib /usr/local/Cellar/boost-python3/1.67.0/lib/libboost_python-mt.dylib
```

**Comment by niksacdev** [comment]
@vjrantal  - you are a rock star!! .. thanks so much, that did it, able to compile everything and the test run fine as well. 

Cheers!
