### ISSUE TITLE
Twin modification

### ISSUE THREAD

**Issue by yoyonstantine** [Azure/azure-iot-sdk-python#147]
Hi, I'm using the iothub_client_simple.py. All run ok but I trying to modify the twin adding tags and other info but i don´t know how y can do. Anyone can help me with this?

**Comment by yzhong94** [comment]
Hi @yoyonstantine , have you seen this [guide ](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-twin-getstarted)on how to get started with device twin on Python?

**Comment by zolvarga** [comment]
@yoyonstantine 

You have to use the "send_reported_state" Python API and send the twin json string to update the twin structure:
Please take a look at the "iothub_client_sample.py" line 194

Best Regards,
Zoltan

**Comment by pierreca** [comment]
closing since the question has been answered
