### ISSUE TITLE
Setting content type causes d2c failures

### ISSUE THREAD

**Issue by taylormoran** [Azure/azure-iot-sdk-python#153]
- **OS and version used:** Windows 10 

- **Python runtime used:**  3.6.4

- **SDK version used:** azure-iothub-device-client 1.3.5 

# Description of the issue:
I'm currently using the simulated device to test routing d2c messages. Attempting to set content type to "application/json" causes the following response:

"IoT Hub responded to message with status: BECAUSE_DESTROY". 

Strange thing is I can remove the forward slash and the system property will not cause any issues when sending the message but of course will not route. I don't know if this an issue with the text (it shouldn't have to be escaped) or something in the SDK.

I'm able to successfully return "application/json" with get_content_type_system_property() so it's not a problem with setting it as much as when sending it with send_event_async().

# Code sample exhibiting the issue:
message.set_content_type_system_property("application/json")
print(message.get_content_type_system_property())            
client.send_event_async(message, send_confirmation_callback, None)

# Console log of the issue:

**Comment by pierreca** [comment]
it sounds like it might be related to how the property is serialized - are you using the MQTT protocol by any chance?

**Comment by taylormoran** [comment]
Thanks for the response.

Yes, I'm using the MQTT protocol. I don't know if it makes a difference but I tried creating an IoTHubMessage as a string and a bytearray.

**Comment by pierreca** [comment]
properties in MQTT are serialized as part of the topic, so I don't think the payload type does not make a difference. One interesting test would be to try and use AMQP instead and see if that works. Would you mind trying this?

In the meantime I'm going to talk with the C SDK folks and see if they are aware of any limitation on their side.

**Comment by taylormoran** [comment]
I'm able to set Content Type successfully when using AMQP. Checked my test blob storage and it was in the system properties dictionary. 

While using AMQP, I'm getting an InternalServerError from the IoT Hub when trying to route off a value in the body but that's a different issue.

**Comment by pierreca** [comment]
I think it might be related to this: https://github.com/Azure/azure-iot-sdk-c/issues/331

**Comment by cartertinney** [comment]
Yes, this is certainly related to [#331](https://github.com/Azure/azure-iot-sdk-c/issues/331). The solution is also the same. Please use the set option method of the IoTHubClient instance as follows:

client.set_option("auto_url_encode_decode", true)

It is always recommended to enable this option unless you are handling URL Encoding/Decoding with your own logic. We will update the documentation to reflect this in the future.

For now, as the issue already has a fix, I am closing this thread. Please reopen the issue if this solution does not solve your problem @taylormoran .

**Comment by pierreca** [comment]
@cartertinney thanks for the help!

*@taylormoran thank you for your question/contribution to our open-sourced project! Please help us improve by filling out [this 2-minute customer satisfaction survey](https://www.surveymonkey.com/r/Q5PLZ3V).*
