### ISSUE TITLE
Problem accessing an IoT Hub device with multiple DeviceClient instances

### ISSUE THREAD

**Issue by martinabbott** [Azure/azure-iot-sdk-python#156]
- **OS and version used:** <VERSION> Ubuntu 16.04 LTS
- **Python runtime used:** <VERSION> Python 2.7
- **SDK version used:** <VERSION> Built from source on 10/07/2018

# Description of the issue:
I am building gateways that maintain device client connections to IoT Hub devices and since these gateways can act as a mesh this means that it is possible for a device to move from one gateway to another.

Since the devices are only occasionally connected, the only way to know it has moved is via a twin update to say what the gateway mac address is.

I'm still working out the mechanics of that, but I've noticed that when two gateways connect a device to IoT Hub at the same time I get hundreds of executions of the Device Twin callback and lots of errors.

I am using a modified sample from the samples folder distributed in the GitHub repo to test(iothub_client_sample.py) that just sends messages and has the device twin callback implemented.

When using MQTT it keeps executing the twin callback and I get hundreds (or thousands) of error messages like:
`Socketio_Failure: Receiving data from endpoint: errno=104`

When changing to AMQP we get among others:
`Func:on_amqp_messenger_subscription_changed_callback Line:1646 Unexpected AMQP messenger state`

Using MQTT_WS we don't get the same device twin and error event storm but it does execute the twin callback each time it creates messages even when there is no twin change, and AMQP_WS gets the same problem as regular AMQP.

There is no Close option in the Python SDK so the only way to close the connection to IoT Hub is to destroy the object (currently using del) but that seems to be inconsistent.

I've tried this using the .NET Core SDK and it does not exhibit this behaviour. With that I should be able to detect a change, update the relevant gateway twin and tell it to close the connection for that device.

But I have other reasons for wanting to use Python for the solution so am keen to understand the behaviour.

**Comment by pierreca** [comment]
@martinabbott 
A couple of clarifying questions:
- when you say "when two gateways connect a device" do you mean that the same deviceId is used to connect with 2 different gateways, therefore generating 2 connections with the same device id?
- those gateways, what are they? Azure IoT Edge gateways? which version?

**Comment by martinabbott** [comment]
- Yeah, two gateways using the same connection string to the same device id.
- Not IoT Edge, just using the basic IoT Device Client sample in .\device\samples\iothub_client_sample.py with some modifications to remove extraneous code.


Could be completely the wrong thing to do, we're still developing, but it is an artifact of what we're trying to achieve with the mesh.

Short version of the story...a gateway maintains a list of device clients in a dictionary for sensors that are attached to it. That connection is unicast, if it's connected it stays connected via that gateway until there is a problem. At that point it broadcasts and connects to another gateway. At that point it's unicast again.

We need to control disconnection on the initial gateway. We currently do this using a twin property on the sensor...when the initial gateway tries sees the update to the sensor it knows to disconnect, although there are still problems with that. 

However, even before that, when the second gateway establishes a connection to the same device id we get the behaviour described.

This large volume of events and errors does not occur with .NET Core, although we do have the issue of ensuring the right gateway receives an update and disconnection occurs, that's a work in progress!

However, .NET Core is not something we can use in this case, because reasons!

**Comment by pierreca** [comment]
@martinabbott  Azure IoT Hub only allows one connection per device. I'm suspecting that what is happening is that the retry logic kicks in and leads to this race between those 2 devices. if you edit the twin for each reconnection with a unique field value, the etag gets updated, so you end up with a lot of notifications. this is just a theory though.

I'd be interested in knowing if it still happens if you introduce a reasonable delay between the first gateway disconnecting and the second one connecting, to make sure you have only one active connection at a time?

**Comment by martinabbott** [comment]
Yeah the problem is we have no way of introducing the delay directly because the gateway never knows that the disconnection has happened, although I wonder if we can do that through a gateway twin update.

NOTE: This behaviour happens without any twin updates happening I think, it just hits a race condition immediately after starting 2 connections.

Interestingly, .NET Core doesn't show this behaviour.

**Comment by pierreca** [comment]
@martinabbott I believe .NET Core has a less aggressive retry policy - might be why. have you tried it with both protocols though? or just AMQP? might be that the multiplexing feature helps in this case?

Finetuning (or disabling) the retry policy might help, but it's not going to solve the problem. you may always run into a race condition at some point or in some circumstances. it feels like a distributed systems issue almost (I'm no specialist...)

would there be a way, while the sensor is in the "broadcast" phase, to disconnect its existing client? would there be a way for gateways to advertise who "owns" the sensor?

I also wonder if this is something Azure IoT Edge could help with.

**Comment by martinabbott** [comment]
Tried MQTT and AMQP, both exhibit similar behaviour, with MQTT definitely being worse!

IoT Edge is sadly out as there is a dependency on the sensors so we're probably too far down the line to pivot to a new architecture.

The sensors have configuration via a device twin that is maintained by the gateway and pushed to the sensor when it occasionally connects. The gateway also maintains a queue for sensors it believes it's associated with for store and forward situations as the gateway is not guaranteed to be permanently online.

I'll have a think and revert back about the disconnection process, might be that we can use a status on the gateway device twin and a backend service to update the twin of the old gateway to get it to drop the connection before accepting a new connection.

**Comment by pierreca** [comment]
if you can detect connections/disconnections from the sensor to the gateway, could you sync it with connecting/disconnecting the device client?

**Comment by martinabbott** [comment]
Happy for the issue to be closed, it's an unsupported scenario as you say so I will find an alternative solution. 

If I think it's interesting to the community when we solve it I'll come back here or blog.

Thanks for the help and direction.

**Comment by az-iot-builder-01** [comment]
@martinabbott, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
