### ISSUE TITLE
Get "iotHubName is not found" error when using Pip packages

### ISSUE THREAD

**Issue by luyaok** [Azure/azure-iot-sdk-python#158]
- **OS and version used:** <VERSION> Windows 10

- **Python runtime used:** <VERSION> Python 3.6.5

- **SDK version used:** <VERSION> azure-iothub-device-client-1.4.0

# Description of the issue:
When sending message to Azure IoT Hub using packages installed by Pip then get "iotHubName is not found" error.

# Code sample exhibiting the issue:
I run the official sample:[ iothub_client_sample.py](https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample.py)

# Console log of the issue:
```
D:\Sample\azure-iot-sdk-python\device\samples>python iothub_client_sample.py -c "HostName=xxxxxx.azure-devices.net;DeviceId=device1;SharedAccessKey=xxxxxx" -p mqtt

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
IoT Hub Client for Python
Starting the IoT Hub Python sample...
    Protocol MQTT
    Connection string=HostName=ritaiothub.azure-devices.net;DeviceId=device1;SharedAccessKey=***
Error: Time:Mon Jul 16 17:07:45 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Mon Jul 16 17:07:45 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating iothub handle
set_option TrustedCerts successful
SetRetryPolicy to: retryPolicy = 2
SetRetryPolicy to: retryTimeoutLimitInSeconds = 100
GetRetryPolicy returned: retryPolicy = 2
GetRetryPolicy returned: retryTimeoutLimitInSeconds = 100
IoTHubClient is reporting state
IoTHubClient sending 5 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [3] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [4] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: BUSY
Confirmation[0] for reported state received with:
    status_code: 204
    Total calls confirmed: 1
Confirmation[0] received for message with result = OK
    message_id: message_0
    correlation_id: correlation_0
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 1
Confirmation[1] received for message with result = OK
    message_id: message_1
    correlation_id: correlation_1
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 2
Confirmation[2] received for message with result = OK
    message_id: message_2
    correlation_id: correlation_2
    Properties: {'temperatureAlert': 'true'}
    Total calls confirmed: 3
Confirmation[3] received for message with result = OK
    message_id: message_3
    correlation_id: correlation_3
    Properties: {'temperatureAlert': 'true'}
    Total calls confirmed: 4
Confirmation[4] received for message with result = OK
    message_id: message_4
    correlation_id: correlation_4
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 5
```

**Comment by pierreca** [comment]
@luyaok are you setting the content-type property by any chance? 
can you see if what is suggested in this issue works for you? 
https://github.com/Azure/azure-iot-sdk-python/issues/138

**Comment by luyaok** [comment]
@pierreca Thanks for the reply. I don't set content-type. As suggested in #138 I add `client.set_option("auto_url_encode_decode", True)` but get the same error. I tried all protocols, mqtt, amqp and http, all of them reproduce the same error for me.
But C SDK don't reproduce this error for me.

AMQP:

```
D:\Sample\azure-iot-sdk-python\device\samples>python iothub_client_sample.py -c "HostName=xxxx.azure-devices.net;DeviceId=device1;SharedAccessKey=xxxx" -p amqp

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
IoT Hub Client for Python
Starting the IoT Hub Python sample...
    Protocol AMQP
    Connection string=HostName=xxxx.azure-devices.net;DeviceId=device1;SharedAccessKey=xxxx
Error: Time:Tue Jul 17 15:38:54 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Tue Jul 17 15:38:54 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating iothub handle
set_option TrustedCerts successful
```

HTTP:

```
D:\Sample\azure-iot-sdk-python\device\samples>python iothub_client_sample.py -c "HostName=xxxx.azure-devices.net;DeviceId=device1;SharedAccessKey=xxxx" -p http

Python 3.6.5 (v3.6.5:f59c0932b4, Mar 28 2018, 17:00:18) [MSC v.1900 64 bit (AMD64)]
IoT Hub Client for Python
Starting the IoT Hub Python sample...
    Protocol HTTP
    Connection string=HostName=xxxx.azure-devices.net;DeviceId=device1;SharedAccessKey=xxxx
Error: Time:Tue Jul 17 15:41:33 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:892 iotHubName is not found
Error: Time:Tue Jul 17 15:41:33 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:928 Failure creating iothub handle
set_option TrustedCerts successful
```

**Comment by pierreca** [comment]
@luyaok thanks for the additional information!
I just released a new version of the packages last night that snapped to the latest C SDK, would you mind updating to 1.4.1 and letting me know if you still see the problem?

**Comment by pierreca** [comment]
@luyaok actually no need to test with the latest packages, it looks like it still happens. We're looking into it with the C SDK folks - it looks like it's related to a lower-level C SDK thing and as far as I can tell the messages still get sent so it is not blocking, it's just ugly, correct?

**Comment by luyaok** [comment]
@pierreca Yes, messages get sent successfully. Just the error message seems unexpected.

**Comment by rowlandg** [comment]
I see exactly this too (iotHubName is not found, but messages get thru.)
I didn't when I started playing with the azure iothub sdk python last week.
(I'm using WSL Debian with Python 2.7)

**Comment by evxipol** [comment]
Hello,
I have the same errors:
Error: Time:Wed Jul 18 09:39:12 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1077 iotHubName is not found
Error: Time:Wed Jul 18 09:39:12 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:924 Failure creating iothub handle

**Comment by pierreca** [comment]
@rowlandg @evxipol thanks for the feedback - it seems like a generalized issue and @ewertons will be looking at it from the C SDK perspective. Once this is fixed, we'll release new packages.

**Comment by zolvarga** [comment]
@luyaok @rowlandg @evxipol 

It was an issue in the C++ wrapper. I checked in the fix.
See the change here:
https://github.com/Azure/azure-iot-sdk-python/commit/e49a1fa23c1624e645bd630f40b0b2fdb4e0993d

Best Regards,
Zoltan

**Comment by pierreca** [comment]
@zolvarga thanks a lot for the fix!

@luyaok @rowlandg @evxipol @ToadTWP666 if you're building the SDK from source by cloning our repository, would you mind giving the fix a try and see how that works for you?

We will be releasing a new version of the packages with the fix in the coming days.

**Comment by rowlandg** [comment]
Thx. Will do when I get back from hols in a couple of weeks :)

**Comment by ivandojr** [comment]
I'm having the same problem.
I believe I have the latest version, because apparently the fix from @zolvarga is already there.

**Comment by pierreca** [comment]
@ivandojr the fix is checked in, but the pip packages haven't been released - are you using pip packages or compiling from source?

**Comment by dustinsummers** [comment]
Do we know when the pip packages will be released?

**Comment by pierreca** [comment]
@dustinsummers within the next couple of days. We’re running into some issues with the generation of pip packages for MacOS which has been delaying us but worst case we’ll publish which platform separately to get you the fix. I will update the issue, tag everybody and close it when the packages are out.

**Comment by KundhanSoothsayer** [comment]
Hello Guys,

We are facing the same issue with pip installed iothub-client saying
Error: Time:Tue Aug  7 18:31:50 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1077 iotHubName is not found
Error: Time:Tue Aug  7 18:31:50 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:924 Failure creating iothub handle
generic error.

We are not able to send CSV files using http protocol by IoT hub client to IoT Hub because if this Issue.

I understand that the compatible packages for pip are not yet released. If that is the reason i am getting following error. Please let us know when the packages are available. If it is not related to the Packages then please let us know cause of the Issue. 

Thank you
Kundhan

**Comment by pierreca** [comment]
@KundhanSoothsayer that might be a different issue. the error that other folks are seeing is a spurious error that doesn't influence the successful connection to IoT Hub (which does not seem to be your case). Can you send messages successfully independently of the error? is the device communicating at all and only file upload is failing, or is it failing to connect?

regarding packages: I've been hitting issues with our release process and I'm taking the time to debug it to not release something that might be half broken - it's coming, I apologize about the delay. Really appreciate everybody's patience with this!!

**Comment by KundhanSoothsayer** [comment]
Hi Pierre,

File upload functionality is failing and we are not able to send the messages to IoT hub. I used same client to connect through MQTT it works fine.

Thank you
Kundhan

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by KundhanSoothsayer** [comment]
Thanks for the response,

I am using Python 3.6 on Windows 10 Machine.
Please find the code and logs.

-------------------------------------------------------------------------------------------------------
Code:

import time
import sys
import iothub_client
import os
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult, IoTHubError

CONNECTION_STRING = "CONNECTION_STRING OF DEVICE FROM IOT HUB"
PROTOCOL = IoTHubTransportProvider.HTTP

PATHTOFILE = "FOLDER PATH"
FILENAME = "CustomerSite1_d20180618.csv"

def blob_upload_conf_callback(result, user_context):
    if str(result) == 'OK':
        print ( "...file uploaded successfully." )
    else:
        print ( "...file upload callback returned: " + str(result) )
		
def iothub_file_upload_sample_run():
    try:
        print ( "IoT Hub file upload sample, press Ctrl-C to exit" )

        client = IoTHubClient(CONNECTION_STRING, PROTOCOL)

        f = open(PATHTOFILE, "r")
        content = f.read()

        client.upload_blob_async(FILENAME, content, len(content), blob_upload_conf_callback, 0)

        print ( "" )
        print ( "File upload initiated..." )

        while True:
            time.sleep(30)

    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )
    except:
        print ( "generic error" )

if __name__ == '__main__':
    print ( "Simulating a file upload using the Azure IoT Hub Device SDK for Python" )
    print ( "    Protocol %s" % PROTOCOL )
    #print ( "    Connection string=%s" % CONNECTION_STRING )

    iothub_file_upload_sample_run()		
-------------------------------------------------------------------------------------------------------------

Logs:

(geaddzpy36) C:\GEA\OptiPartner\Code>python Optipartner_Batch_Edge.py
Simulating a file upload using the Azure IoT Hub Device SDK for Python
    Protocol HTTP
IoT Hub file upload sample, press Ctrl-C to exit
Error: Time:Mon Aug 13 02:25:47 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1077 iotHubName is not found
Error: Time:Mon Aug 13 02:25:47 2018 File:C:\release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:924 Failure creating iothub handle
generic error

**Comment by pierreca** [comment]
@KundhanSoothsayer  if you look closely you'll see that it's a different error. As i asked in my previous comment please open a *different* issue. posting here 1/ distracts from resolving the other issue 2/ does not help with issue triage. 
thanks.

**Comment by KundhanSoothsayer** [comment]
I have created  a new issue. Please find it.
https://github.com/Azure/azure-iot-sdk-python/issues/170

Thanks
Kundhan

**Comment by 1-Peter** [comment]
@pierreca Are there any news on the release of the pip packages? I am really looking forward to getting them.

Thanks,
Peter

**Comment by pierreca** [comment]
@1-Peter I just released the packages v1.4.2. Apologies for the wait time!

**Comment by az-iot-builder-01** [comment]
@luyaok, @rowlandg, @evxipol, @ivandojr, @KundhanSoothsayer, @1-Peter, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by itslasya** [comment]
Error: Time:Wed Mar 20 15:04:47 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1412 x509 option has wrong value, the only acceptable one is "true"
Error: Time:Wed Mar 20 15:04:47 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core_ll.c Func:IoTHubClientCore_LL_CreateFromConnectionString Line:1463 iotHubName is not found
Error: Time:Wed Mar 20 15:04:47 2019 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothub_client_core.c Func:create_iothub_instance Line:941 Failure creating iothub handle
Unexpected error IoTHubClient.IoTHubClient, IoTHubClientResult.ERROR from IoTHub

kindly help me in understanding this issue

**Comment by rowlandg** [comment]
At a glance...
Have you addressed this?
IoTHubClientCore_LL_CreateFromConnectionString Line:1412 x509 **option has wrong value, the only acceptable one is "true"**

**Comment by KundhanSoothsayer** [comment]
Yes,

We have fixed this, our blob storage to IoT Hub is not connected, there was a bug in IOT Hub UI that made it looked like is properly connected but it is not connected.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

________________________________
