### ISSUE TITLE
Problem importing iothub_client in Windows

### ISSUE THREAD

**Issue by pelocruz** [Azure/azure-iot-sdk-python#16]
Hi,

I have just installed Python 3.6.0 in a Windows 10 machine.
I have then installed the iothub-client package using the command: pip install iothub-client
The installation completed successfully. However, when I try importing the package I get the following error:

> import iothub_client
> Traceback (most recent call last):
>   File "<stdin>", line 1, in <module>
>   File "C:\Python36-32\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
>     from .iothub_client import *
> ImportError: DLL load failed: The specified module could not be found.

Any help is much appreciated. 
Thanks,
Pedro

**Comment by zolvarga** [comment]
Hi Pedro,

The documentation was misleading, iothub-client packages are obsolete
Please use the latest packages from here:
https://pypi.python.org/pypi?:action=display&name=azure-iothub-device-client&version=1.1.7.0

Notice: the name changed to “azure-iothub-device-client” for device client and "azure-iothub-service-client" for service client.

I am updating the documents now.

Thanks,
Zoltan

**Comment by kincki** [comment]
any solutions people?

**Comment by pierreca** [comment]
@kincki would this help? https://github.com/Azure/azure-iot-sdk-python#important-installation-notes---dealing-with-importerror-issues

**Comment by misd92** [comment]
> Hi Pedro,
> 
> The documentation was misleading, iothub-client packages are obsolete
> Please use the latest packages from here:
> https://pypi.python.org/pypi?:action=display&name=azure-iothub-device-client&version=1.1.7.0
> https://pypi.python.org/pypi?:action=display&name=azure-iothub-service-client&version=1.1.0.1
> 
> Notice: the name changed to “azure-iothub-device-client” for device client and "azure-iothub-service-client" for service client.
> 
> I am updating the documents now.
> 
> Thanks,
> Zoltan

Hi @zolvarga ,

I am trying to use "iothub_client" for my Azure IoT Edge module. Are these new libraries an alternate for the previous iothub_client? I am assuming that the modules specified here are to communicate with Azure IoT Hub directly instead of Edge runtime. If so how can I avoid the issue of Import error in Edge modules?
