### ISSUE TITLE
upload_blob_async causes file upload requests exceeded limit error

### ISSUE THREAD

**Issue by shazz** [Azure/azure-iot-sdk-python#161]
- **OS and version used:** <VERSION> 
Ubuntu 16.04

- **Python runtime used:** <VERSION> 
3.5.2

- **SDK version used:** <VERSION> 
1.4.0

# Description of the issue:
When browsing a file system and calling upload_blob_async() to upload a lot of very small files, it generates errors:
"Number of active file upload requests exceeded limit
then
"The request has been throttled. Wait 10 seconds and try again"

I guess this is due to the fact this is a async call. Is there a way to use a sync one or a pool or... Or I need to look for the callback before calling the method again (kind of lock).
Thanks !

# Code sample exhibiting the issue:

```
    def upload_to_blob(self, destinationfilename, source, size, usercontext, blob_upload_conf_callback):
        self.client.upload_blob_async(
            destinationfilename, source, size,
            blob_upload_conf_callback, usercontext)
            
                    if '*' in log['filename']:
                        os.chdir(log['path'])
                        for f in glob.glob(log['filename']):
                            with open(f, 'rb') as logfile:
                                data = logfile.read()
                                path = current_time + "/" + log['name'] + "/" + str(os.path.getmtime(f)) + "_" + os.path.basename(f)   
                                self.hub_manager.upload_to_blob(path, data, len(data), 1001, self.blob_upload_conf_callback)     

    def upload_to_blob(self, destinationfilename, source, size, usercontext, blob_upload_conf_callback):
        self.client.upload_blob_async(
            destinationfilename, source, size,
            blob_upload_conf_callback, usercontext)
```

# Console log of the issue:

`2018-07-20 02:09:32,127 - [IoTHub] Blob upload confirmation[1001] received for message with result = ERROR`

**Comment by pierreca** [comment]
That's correct - you'll need to use the async callback to know when to trigger the next upload. You don't need an active lock though, simply making it asynchronously iterate over your list of files should do it.

Not knowing what your use-case is I don't know if this suggestion is relevant, but if it's a lot of very small files though, would they fit into messages (256kb?) have you thought about using this and the message routing feature of IoT Hub instead of file upload? (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-read-custom)

**Comment by pierreca** [comment]
closing as we're considering this answered - please do let us know if it's not the case and we'll reopen it.

**Comment by az-iot-builder-01** [comment]
@shazz, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
