### ISSUE TITLE
cannot run the setup file

### ISSUE THREAD

**Issue by RitikaKamtam** [Azure/azure-iot-sdk-python#162]
- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by pierreca** [comment]
Closing for lack of usable information - please edit your issue description and we'll reopen it.

**Comment by az-iot-builder-01** [comment]
@RitikaKamtam, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/DesignPage.aspx#FormId=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu&Token=af48ed4ed02842bea21e0d3933b78fac)
