### ISSUE TITLE
install azure-iothub-device-client failed on Mac 10.13.5

### ISSUE THREAD

**Issue by czgtest** [Azure/azure-iot-sdk-python#164]
OS and version used: Mac
Python runtime used: Python 2.7.14
SDK version used: azure-iothub-device-client
Description of the issue:
        install azure-iothub-device-client failed 

Console log of the issue:

VSCs-Mac-mini:ShakeShake_19 vsc$ pip install azure-iothub-device-client
Collecting azure-iothub-device-client
  Could not find a version that satisfies the requirement azure-iothub-device-client (from versions: )
No matching distribution found for azure-iothub-device-client

**Comment by pierreca** [comment]
That is because we have never released pip packages for MacOS. We are working on it though so expect this to start working in the next few days.

**Comment by pierreca** [comment]
@czgtest I just released pip packages for MacOS, would you mind giving it a try?
```
pip install azure_iothub_device_client
```

it will still need to have boost installed, which you can deal with by doing:
```
brew install boost-python
```
or in the case of python3:
```
brew install boost-python3
```

Please do report if you're running into any sort of issue!

**Comment by pierreca** [comment]
@sanhardik that does not tell us much unfortunately: I'd like to try and reproduce the problem. I would need to know:
- how you installed Python
- how you installed Boost
- how you downloaded our SDK

Right now we're suggesting everyone to use brew to install python and its dependencies.

Considering it's a different error from the original poster and so as not to spam his notification I'd request that you open a new issue, with those details. thanks!

@czgtest if you try to download our package again, can you let us know if it works? we close inactive issues after a few days so I'm closing this in hopes that it resolved your error but if it didn't I'll reopen it.

**Comment by az-iot-builder-01** [comment]
@czgtest, @sanhardik, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by czgtest** [comment]
I  run bellow commands on Mac.  then get crash when run python script.
pip install azure_iothub_device_client
brew install boost-python
![image](https://user-images.githubusercontent.com/35018765/56570682-f85cda00-65ed-11e9-84fc-c6991b657df0.png)

**Comment by czgtest** [comment]
#270
