### ISSUE TITLE
DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by WaleedSehgal** [Azure/azure-iot-sdk-python#169]
- **OS and version used:** <VERSION> Windows 10

- **Python runtime used:** <VERSION> 3.5.5 (Anaconda)

- **SDK version used:** <VERSION> 1.4.1

# Description of the issue:
I am trying to run the sample SimulatedDevice.py to send telemetry data to my IoThub but I am getting **DLL load Failed error** 

# Code sample exhibiting the issue:

```python
import random
import time
import sys

import iothub_client
from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult
from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue

MyNodeDevice --output table
CONNECTION_STRING = "REMOVED"

PROTOCOL = IoTHubTransportProvider.MQTT
MESSAGE_TIMEOUT = 10000

TEMPERATURE = 20.0
HUMIDITY = 60
MSG_TXT = "{\"temperature\": %.2f,\"humidity\": %.2f}"

def send_confirmation_callback(message, result, user_context):
    print ( "IoT Hub responded to message with status: %s" % (result) )

def iothub_client_init():
   
    client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
    return client

def iothub_client_telemetry_sample_run():

    try:
        client = iothub_client_init()
        print ( "IoT Hub device sending periodic messages, press Ctrl-C to exit" )

        while True:
           
            temperature = TEMPERATURE + (random.random() * 15)
            humidity = HUMIDITY + (random.random() * 20)
            msg_txt_formatted = MSG_TXT % (temperature, humidity)
            message = IoTHubMessage(msg_txt_formatted)

            prop_map = message.properties()
            if temperature > 30:
              prop_map.add("temperatureAlert", "true")
            else:
              prop_map.add("temperatureAlert", "false")

            print( "Sending message: %s" % message.get_string() )
            client.send_event_async(message, send_confirmation_callback, None)
            time.sleep(1)

    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )

if __name__ == '__main__':
    print ( "IoT Hub Quickstart #1 - Simulated device" )
    print ( "Press Ctrl-C to exit" )
    iothub_client_telemetry_sample_run()
```

# Console log of the issue:
```shell
 Traceback (most recent call last):
  File "SimulatedDevice.py", line 11, in <module>
    import iothub_client
  File "C:\Users\Waleed\AppData\Local\Programs\Python\Python35\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found. 
```

*[edit:pierreca:2018-8-12] formatting*

**Comment by pierreca** [comment]
@WaleedSehgal this can happen if the x86 version of python is installed on an x64 machine (pip will download our x64 package all the time because it goes by the CPU architecture). Can you confirm if you're running python x64?

**Comment by WaleedSehgal** [comment]
Yes, I am running python x64.

**Comment by pierreca** [comment]
@WaleedSehgal I've setup an anaconda test environment (with the latest 5.2.0 version that includes python 3.6.5) and ran the sample successfully. I'm going to ask you to double-check because this is typically the situation we encounter with this error. 

1. can you go into your control panel -> uninstall a program and make sure that the anaconda installation explicitly states "64 bit"? (this is what I see:)
![image](https://user-images.githubusercontent.com/4979572/44007302-d1894e72-9e47-11e8-892e-541f9a50688e.png)

2. can you verify when you are running `pip install azure-iothub-device-client` that it downloads the package called `azure_iothub_device_client-1.4.1-py3-none-win_amd64.whl` ?

3. can you verify that the python interpret you're running your script on recognizes the platform as x64 by running this in the python interpreter:
```python
import platform
platform.architecture()
```

If you believe it might be related to the difference between python 3.5 and python 3.6, can you install the latest anaconda version and try again?

**Comment by tpenland** [comment]
I'm having the same issue. I'm using Python 3.7 x64. Using Anaconda as you suggested @pierreca worked.

**Comment by WaleedSehgal** [comment]
@pierreca Yes seems like there is an issue with python versions other than 3.6. Between I was able to run the sample successfully upon setting my environment to python 3.6

**Comment by az-iot-builder-01** [comment]
@WaleedSehgal, @tpenland, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by kartheekakkur** [comment]
File "C:\ProgramData\Anaconda3\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by kincki** [comment]
@pierreca thanks for this solution.. I removed 3.7.x, and installed 3.6.8, and it worked..
