### ISSUE TITLE
AMQP transport failed to establish connection with service.

### ISSUE THREAD

**Issue by ksaye** [Azure/azure-iot-sdk-python#17]
I have written a simple Python script with the following logic, summary it initiated the iothub_client once and loops forever.  After some time, it seems to stop working, presumably when the authentication (using "iotHubClient = IoTHubClient(connection_string, protocol)" and the AMQP protocol) needs regenerate a SAS token.

Other than running "iotHubClient = iothub_client_init()", which seems inefficient, I suggest that the Python code not have to worry about it and the C code try to re-authenticate.

```
def main():
    global iotHubClient, UDP_IP, UDP_PORT

   
    try:
        sock = socket.socket(socket.AF_INET, socket.SOCK_DGRAM)
        sock.bind((UDP_IP, UDP_PORT))

        iotHubClient = iothub_client_init()

        while True:
            data, addr = sock.recvfrom(1024) # buffer size is 1024 bytes
            data = data.replace('\r\n', '')
            try:
              UDPMessage = data.split(':')
              if UDPMessage[0] == "TempUpdate":
                message = '{ "event": "%s", "sensor": "%s", "temperature": %3.2f}' % (UDPMessage[0], UDPMessage[1], float(UDPMessage[2]))
                print message
                IoTmessage = IoTHubMessage(bytearray(str(message), 'utf8'))
                iotHubClient.send_event_async(IoTmessage, send_confirmation_callback, message)
            except:
              print data
            
    except IoTHubError as e:
        print("Unexpected error %s from IoTHub" % e)
        return
    except KeyboardInterrupt:
        print("IoTHubClient sample stopped")``


**Error I am seeing:**

Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:364 Failure: select failure.
Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:establishConnection Line:643 Failed to open the connection with CBS.
Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:IoTHubTransportAMQP_DoWork Line:1351 AMQP transport failed to establish connection with service.
Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp_auth.c Func:authentication_reset Line:637 Failed to reset the authentication state (authentication status is invalid: 2)
Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:prepareDeviceForConnectionRetry Line:1080 Failed resetting the authenticatication state of device
Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp_methods.c Func:iothubtransportamqp_methods_unsubscribe Line:719 unsubscribe called while not subscribed
Error: Time:Tue Feb 21 06:40:02 2017 File:/root/iot/azure-iot-sdks/c/iothub_client/src/iothubtransportamqp.c Func:destroyMessageReceiver Line:883 Failed closing the AMQP message receiver.

**Comment by zolvarga** [comment]
Hello @ksaye,

Thanks for using our SDK. I am looking at the issue you reported and will get back to you as soon as possible.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Hi @ksaye,

It looks like you have a socket failure. It is not related to the token renewal because the code could not even connect to CBS. Please try it on a different machine. I run the code for hours without issues.
If you still having issues please enable extra logging and paste here the log with the entire code.

Best Regards,
Zoltan

**Comment by ksaye** [comment]
Thanks.

I have noticed the error after a day or so, so it does take hours.

I moved to MQTT and do not see the issue.  I will move back to AMQP to see if it comes back.

Kevin

**Comment by ewertons** [comment]
Hi @ksaye ,
we just completed a longhaul run using the python AMQP sample in the repo (latest from master, modified to send telemetry once a second for 48 hours), and it didn't present any failure.

Further, we restarted the test and simulated a brief connectivity error and upon plugging the cable again the client reconnected and sent all the events in the queue.

At this point I would ask you to verify the issue you are seeing using one of the samples we have and also monitor the network to make sure you have connectivity at all times.

**Comment by tameraw** [comment]
@ksaye - Please let us know if still having issues.

**Comment by gatornation11** [comment]
I had to create a new IoT Hub to test out device streaming. I linked the device to the new hub but the device will not connect. I removed the registration for the device in DPS and recreated it. Still will not register. Nothing has changed on my device. Getting this error in debug mode for the client.
nfo failure 11001.10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\c-utility\adapters\tlsio_schannel.c Func:tlsio_schannel_close Line:1195 invalid tls_io_instance->tlsio_state = TLSIO_STATE_NOT_OPEN10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\c-utility\adapters\tlsio_schannel.c Func:tlsio_schannel_open Line:1165 xio_open failed10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\uamqp\src\saslclientio.c Func:saslclientio_open_async Line:1097 xio_open failed10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\uamqp\src\connection.c Func:connection_open Line:1344 Opening the underlying IO failed10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\uamqp\src\link.c Func:link_attach Line:1154 Begin session failed10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\uamqp\src\message_receiver.c Func:messagereceiver_open Line:362 Link attach failed10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\uamqp\src\amqp_management.c Func:amqp_management_close Line:1020 AMQP management instance not open10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_connection.c Func:on_cbs_open_complete Line:153 CBS open failed10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\uamqp\src\amqp_management.c Func:amqp_management_open_async Line:981 Failed opening message receiver10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_connection.c Func:create_cbs_handle Line:278 Failed to open the connection with CBS.10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_connection.c Func:amqp_connection_create Line:421 amqp_connection_create failed (failed creating the CBS handle)10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:establish_amqp_connection Line:839 Failed establishing connection (failed to create the amqp_connection instance).10-59-24 AM [00003144] [00008900] Error: File:d:\projs\act.0301.m\deps\azure-iot-sdk-c\iothub_client\src\iothubtransport_amqp_common.c Func:IoTHubTransport_AMQP_Common_DoWork Line:1584 AMQP transport failed to establish connection with service.

**Comment by pierreca** [comment]
@gatornation11 unfortunately there's not enough information here for us to know what's going wrong with your device: it just says the connection cannot be established, but we have no idea what your device connectivity, configuration on your hub, and anything else related to your connection is.

Additionally in any case the python SDK does not support device streaming yet. I'd suggest switching to the C or C# SDKs if you want to test this feature.

**Comment by gatornation11** [comment]
What else do you need? I’m stuck. This is before streaming (which I’m using C btw).
The device isn’t enrolling DPS
[cid:image001.png@01D4D8D9.08B21B60]
The only log file that is created.
01-39-46 PM [00007516] [00007444] Logging has been configured!
01-39-46 PM [00007516] [00007444] Running service...
01-39-46 PM [00007516] [00007444] Microsoft::Azure::DeviceManagement::Client::DMService::DMService
01-39-46 PM [00007516] [00007444] Microsoft::Azure::DeviceManagement::Client::DMService::RunService
01-39-46 PM [00007516] [00007440] Microsoft::Azure::DeviceManagement::Client::DMService::ServiceMain
01-39-46 PM [00007516] [00007440] Microsoft::Azure::DeviceManagement::Client::DMService::Start
01-39-46 PM [00007516] [00007440] Microsoft::Azure::DeviceManagement::Client::DMService::EnsureReported
01-39-46 PM [00007516] [00007440] Microsoft::Azure::DeviceManagement::Client::DMService::OnStart
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::DMService::ServiceWorkerThread
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::DMService::EnsureReported
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::AzureDMClient::AzureDMClient
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::AzureDMClient::Run
01-39-46 PM [00007516] [00007080] Registering: clearReportedCmd
01-39-46 PM [00007516] [00007080] Registering: __deviceSchemas
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::AzureDMClient::EnumeratePlugins
01-39-46 PM [00007516] [00007080] Enumerating plugin manifests from: C:\azureclient\bin\..\manifests
01-39-46 PM [00007516] [00007080] Found Manifest: C:\azureclient\bin\..\manifests\CertificateManagementManifest.json
01-39-46 PM [00007516] [00007080] Parsing json file: C:\azureclient\bin\..\manifests\CertificateManagementManifest.json
01-39-46 PM [00007516] [00007080] Loading: CertificateManagementPlugin.dll
01-39-46 PM [00007516] [00007080] Is Out of proc: 1
01-39-46 PM [00007516] [00007080] Keep alive time: 50000
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::PluginProxy::Load
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Client::OutOfProcPluginBinaryProxy::Load
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Common::PluginNamedPipeTransport::SendAndGetResponse
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Common::PluginNamedPipeTransport::Initialize
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Common::PluginNamedPipeTransport::ClientInitialization
01-39-46 PM [00007516] [00007080] Microsoft::Azure::DeviceManagement::Common::PluginNamedPipeTransport::LaunchPluginHost
01-39-46 PM [00007516] [00007080] Pluginhost has been launched.
01-39-46 PM [00007516] [00006644] Microsoft::Azure::DeviceManagement::Common::PluginNamedPipeTransport::PluginHostMonitor
01-39-46 PM [00007516] [00007080] Monitoring thread created.
01-39-46 PM [00007516] [00006644] Plugin host exited.
01-39-46 PM [00007516] [00006644] Microsoft::Azure::DeviceManagement::Common::PluginNamedPipeTransport::ClientUninitializePlugin

Service is running
[cid:image002.png@01D4D8D9.532BF6C0]

I put in the endorsement key and the reg id.

**Comment by pierreca** [comment]
@gatornation11 trying to help here, but since you're responding to a closed issue instead of creating a new one, you're not seeing the template we provide that usually helps structure the bug hunt.

- Which SDK are you using? which version of it? this doesn't look like Python SDK logs so I'm not sure why you're posting in that issue and on that repository
- can you post a code snippet of what you're doing with the associated console logs?
- if using the python SDK, are you using pip packages or building it yourself? how are you doing this?
