### ISSUE TITLE
SDK does not work behind a corp proxy

### ISSUE THREAD

**Issue by haimiko** [Azure/azure-iot-sdk-python#174]
Hello,
I'm currently running Ubuntu 16.0.4 x86_64, python3.5 and SDK version 1.4.2 and experiencing segmentation faults when running with a proxy configuration.    If I remove the proxy configuration, the script executes but is unable to get to the IoT hub.

I configured proxy as such:

`PROXY = "http://myproxy.com:123"

def iothub_client_init():
    # Create an IoT Hub client
    client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
    client.set_option("proxy_data",PROXY)
    return client`

When I run the script i get the following error:

` python3 simulatedDevice.py

IoT Hub Quickstart #1 - Simulated device

Press Ctrl-C to exit

Segmentation fault (core dumped)`

**Comment by pierreca** [comment]
@jspaith from the C SDK looked at it and it seems we have an issue with our boost wrapper. this is a bug and the feature is broken (it actually never worked). Flagging this as such and adding it to our backlog to be solved ASAP.
thanks for reporting this!

**Comment by haimiko** [comment]
Excellent.  Any ETA on when there may be a fix? 
Thank you

**Comment by pierreca** [comment]
@cartertinney is working on it so we should have a fix in the next few days.

**Comment by cartertinney** [comment]
@haimiko We have completed a fix. Our apologies for the delay. In order to set a proxy please use the HttpProxyOptions object as follows:

```
from iothub_client import IoTHubClient, HttpProxyOptions

client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
proxy = HttpProxyOptions("http://myproxy.com", 8888)
client.set_option("proxy_data", proxy)
```

You may optionally also add a username and password to the proxy options object.
We will be adding official documentation in the coming days, but this should get you started.

**Comment by az-iot-builder-01** [comment]
@haimiko, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by haimiko** [comment]
I upgraded iothub_client to 1.4.2 and got he following error:

ImportError: cannot import name 'HttpProxyOptions'

**Comment by pierreca** [comment]
@haimiko the fix is checked in but packages haven't been released yet. we'll update this issue when this is the case. expect the fix to be in version 1.4.3. of the packages. sorry for the confusion!

**Comment by pierreca** [comment]
Fixed with release 1.4.3

**Comment by haimiko** [comment]
Thank you! When will this get published to the PIP repo?

**Comment by pierreca** [comment]
@haimiko it is published now.

**Comment by haimiko** [comment]
Thank  you.  I see that it successfully upgraded :) .  I'm seeing a new
error:

Error: Time:Tue Sep 18 21:04:26 2018
File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c
Func:SendMqttConnectMsg Line:2122 failure connecting to address
XXX.azure-devices.net where XXX is my IoT Edge name.

**Comment by pierreca** [comment]
@haimiko different error, different issue please. working on closed issues is difficult and confuses folks looking at the issue history
