### ISSUE TITLE
AMQP Support Document

### ISSUE THREAD

**Issue by sanket-kulkarni-vmware** [Azure/azure-iot-sdk-python#18]
Hi,

I didn't find any official document which demonstrates Azure IoT Hub AMQP support similar to [MQTT Support Doc](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support). 

Can you please share the details of it.

**Comment by olivierbloch** [comment]
Hi @sanket-kulkarni-vmware 
I confirm that we don't have a single document for AMQP as we have for MQTT and we should definitively consider it.
In the meantime, you can find information (scattered across our documentation and SDKs code):
- [Authentication](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security)
- [our C SDK implementation for AMQP
](https://github.com/Azure/azure-uamqp-c), including [detailed requirement docs](https://github.com/Azure/azure-uamqp-c/tree/master/devdoc)
- [our node.js SDK implementation for AMQP](https://github.com/Azure/azure-iot-sdk-node/tree/master/device/transport/amqp), including [detailed requirement docs
](https://github.com/Azure/azure-iot-sdk-node/tree/master/device/transport/amqp/devdoc)

Using our SDKs should make your life way easier and I am wondering what's the reason for deciding not to use them (that'd help us make our SDKs and docs even better and more useful for you).
Hope this helps.

**Comment by zolvarga** [comment]
Documentation is there - closing as resolved
