### ISSUE TITLE
Error when building Python SDK on RPi 2 (Raspbian)

### ISSUE THREAD

**Issue by oscbex** [Azure/azure-iot-sdk-python#19]
Hi,
I'm trying to connect my Raspberry Pi 2 (running Raspbian Wheezy) to my MS IoT hub. Process:

1. I first fetched the Python SDK to the Pie with:

`git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git `

The installed Python version is 2.7.3.

2. Then I ran through the setup of the Python SDK successfully (including a cmake-3.2.2 update).

3. Moved on to compiling the Python SDK by following this guide: [https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#linux](url)

Problem: The build gets stuck at 97% (see error printout below). The guide I linked to above actually describes that the build could get stuck at 98% (when building Python client library iothub_client.so) due to lack of memory. I checked this and yes, I had memory issues, so I increased the swapfile size to 1 GB as suggested in the guide. This increase of memory gives me some 100MB memory margin, but I still get the exact same error message at 97% (see the printout below).

Any tips or suggestions on how to get this resolved?

Error printout:
`pi@raspberrypi ~/azure-iot-sdk-python/build_all/linux $ sudo ./build.sh
...
...
[ 97%] Building CXX object python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o
/home/pi/azure-iot-sdk-python/device/iothub_client_python/src/iothub_client_python.cpp:143:7: error: looser throw specifier for ‘virtual IoTHubError::~IoTHubError()’
/usr/include/c++/4.6/exception:65:13: error:   overriding ‘virtual std::exception::~exception() throw ()’
python/src/CMakeFiles/iothub_client_python.dir/build.make:54: recipe for target 'python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o' failed
make[2]: *** [python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o] Error 1
CMakeFiles/Makefile2:2418: recipe for target 'python/src/CMakeFiles/iothub_client_python.dir/all' failed
make[1]: *** [python/src/CMakeFiles/iothub_client_python.dir/all] Error 2
Makefile:126: recipe for target 'all' failed
make: *** [all] Error 2
pi@raspberrypi ~/azure-iot-sdk-python/build_all/linux $`

Cheers!
Oscar

**Comment by zolvarga** [comment]
Hi Oscar,

I have a question (The link you pasted here for the guide is dead): 
- What are you building? Are you including in the build the unit and e2e tests and websocket support? I would suggest to try to run the "build.sh" without any switch.

Please make sure you are building the minimum configuration you need. If the build is running out of the memory anyway, try to cross compile the SDK for Raspberry Pi. Here is a cross compilation example for C-SDK:
[https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/SDK_cross_compile_example.md](url)

Best Regards,
Zoltan

**Comment by oscbex** [comment]
Thanks Zoltan. Weird with the link, I can see it's dead but if you copy/paste it into a browser it works. Anyway, I you look at the procedure described, for Python 2.7 there is no switch (I just used the ./build.sh command). And when monitoring the memory during the build process it never went below 90MB. Will check the cross-compilation.

BR
Oscar

**Comment by costasgrath** [comment]
Hello,

I would like to report that I am having the exact same problem as Oscar. 

I just need the iothub_client library to start playing in Python so I have followed the instructions 100% as they are described and I get this error.

By the way Zoltan, this error has to do with overriding the template without providing a destructor class, so I don't believe this has to do with memory size. Most probable has to do with some cmake or gcc switch concerning function overloading. 

Also, I would also like to add that I have already compiled azure-iot-sdk-c successfully but didn't make a differenc.e

Thanks,
Costas.

**Comment by zolvarga** [comment]
Hi Costas,

We just compiled the Python SDK on Raspberry Pi using the latest Ubuntu release:
Description:    Raspbian GNU/Linux 8.0 (jessie) 

Make sure to try this:
- Install the necessary tools:
sudo apt-get install build-essential g++ python-dev autotools-dev libicu-dev build-essential libbz2-dev libboost-all-dev

- Run "./build.sh" from azure-iot-sdk-python/build_all/linux folder

This worked for us, please let me know...

Best Regards,
Zoltan

**Comment by tameraw** [comment]
@oscbex - Please let us know if still having issues.
