### ISSUE TITLE
pip package installs on Python 3.6 but depends on Python 3.5

### ISSUE THREAD

**Issue by celaus** [Azure/azure-iot-sdk-python#191]
Hi! I am simply trying to send telemetry data into IoT Hub for a blog post :smile: 

This time I installed the Python SDK via pip and fixed the initial boost dependency issue (#145) by renaming the library accordingly, but the iothub_client.so expects a dynamic library python3.5m.so ...

- **OS and version used:** Fedora 28

- **Python runtime used:** 3.6.6

- **SDK version used:** device client sdk 1.4.2 (installed via pip)

# Description of the issue:
Installing via pip into a Python 3.6 environment works and the [site](https://pypi.org/project/azure-iothub-device-client/) also says 3.6 is supported. However, when running the "simple sample" of the device client sdk, import fails (see below).

In order to get around issue #145 both a ubuntu built libboost-python3.so and the native libboost-python3.so was used with the same result.

# Code sample exhibiting the issue:
The simple sample client 

# Console log of the issue:

~~~bash
$ ls
client.py  libboost_python-py35.so.1.58.0* 
$ python client.py 
Traceback (most recent call last):
  File "client.py", line 6, in <module>
    from iothub_client import IoTHubClient, IoTHubTransportProvider, IoTHubMessage
  File "/home/cm/.local/lib/python3.6/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libpython3.5m.so.1.0: cannot open shared object file: No such file or directory
$  python --version
Python 3.6.6
~~~

Digging deeper: the iothub_client.so seems to have been dynamically linked to libpython3.5m.so.1.0 - even though it was distributed for Python 3.6? Nevermind the other lib dependencies that are not found.

~~~
$ ldd iothub_client.so 
./iothub_client.so: /lib64/libcurl.so.4: no version information available (required by ./iothub_client.so)
	linux-vdso.so.1 (0x00007ffcb2b89000)
	libboost_python-py35.so.1.58.0 => not found
	libpython3.5m.so.1.0 => not found
	libcurl.so.4 => /lib64/libcurl.so.4 (0x00007f7c81264000)
	libssl.so.1.0.0 => not found
	libcrypto.so.1.0.0 => not found
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f7c81045000)
	librt.so.1 => /lib64/librt.so.1 (0x00007f7c80e3d000)
	libuuid.so.1 => /lib64/libuuid.so.1 (0x00007f7c80c36000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f7c808a4000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f7c80510000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f7c802f8000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f7c7ff39000)
	libnghttp2.so.14 => /lib64/libnghttp2.so.14 (0x00007f7c7fd13000)
	libidn2.so.0 => /lib64/libidn2.so.0 (0x00007f7c7faf6000)
	libssh.so.4 => /lib64/libssh.so.4 (0x00007f7c7f87d000)
	libpsl.so.5 => /lib64/libpsl.so.5 (0x00007f7c7f66c000)
	libssl.so.1.1 => /lib64/libssl.so.1.1 (0x00007f7c7f3ff000)
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f7c7ef73000)
	libgssapi_krb5.so.2 => /lib64/libgssapi_krb5.so.2 (0x00007f7c7ed24000)
	libkrb5.so.3 => /lib64/libkrb5.so.3 (0x00007f7c7ea37000)
	libk5crypto.so.3 => /lib64/libk5crypto.so.3 (0x00007f7c7e81b000)
	libcom_err.so.2 => /lib64/libcom_err.so.2 (0x00007f7c7e617000)
	libldap-2.4.so.2 => /lib64/libldap-2.4.so.2 (0x00007f7c7e3c3000)
	liblber-2.4.so.2 => /lib64/liblber-2.4.so.2 (0x00007f7c7e1b4000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f7c7df9d000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f7c81a39000)
	libunistring.so.2 => /lib64/libunistring.so.2 (0x00007f7c7dc1c000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f7c7da18000)
	libkrb5support.so.0 => /lib64/libkrb5support.so.0 (0x00007f7c7d809000)
	libkeyutils.so.1 => /lib64/libkeyutils.so.1 (0x00007f7c7d605000)
	libresolv.so.2 => /lib64/libresolv.so.2 (0x00007f7c7d3ee000)
	libsasl2.so.3 => /lib64/libsasl2.so.3 (0x00007f7c7d1d1000)
	libssl3.so => /lib64/libssl3.so (0x00007f7c7cf7e000)
	libsmime3.so => /lib64/libsmime3.so (0x00007f7c7cd56000)
	libnss3.so => /lib64/libnss3.so (0x00007f7c7ca2b000)
	libnssutil3.so => /lib64/libnssutil3.so (0x00007f7c7c7fb000)
	libplds4.so => /lib64/libplds4.so (0x00007f7c7c5f7000)
	libplc4.so => /lib64/libplc4.so (0x00007f7c7c3f2000)
	libnspr4.so => /lib64/libnspr4.so (0x00007f7c7c1b2000)
	libselinux.so.1 => /lib64/libselinux.so.1 (0x00007f7c7bf89000)
	libcrypt.so.1 => /lib64/libcrypt.so.1 (0x00007f7c7bd60000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007f7c7bae0000)

~~~

**Comment by pierreca** [comment]
@celaus sorry you're running into all these issues. the boost dependency is something we're looking at removing because it's the source of so many issues. Because of it, the version of python installed on the system has to match the version that boost & the SDK was compiled with, which creates a crazy compatibility matrix where only a few combinations are supported.

I'm curious to see exactly which version of the package you're downloading - would you mind pasting the log of the pip install command to see exactly which wheel file was downloaded?

**Comment by celaus** [comment]
Hehe, yeah the boost dependency seems to be the cause quite a few issues. In this case I could provide the boost dependency by simply copying the binary into the directory - but it's really not wise to do the same for a Python3.5 memory lib when it should be using Python3.6 :sweat_smile: , and this looks to come from the `iothub_client.so`. 

I attached the
[log.txt](https://github.com/Azure/azure-iot-sdk-python/files/2364122/log.txt), I hope it helps


~~~
$ pip3 show azure-iothub-device-client
Name: azure-iothub-device-client
Version: 1.4.2
Summary: IoT Hub Device Client Library
Home-page: https://github.com/Azure/azure-iot-sdk-python/tree/master/device
Author: aziotclb
Author-email: aziotclb@microsoft.com
License: Apache Software License
Location: /home/cm/.local/lib/python3.6/site-packages
Requires: 
~~~

**Comment by pierreca** [comment]
@celaus what is extra confusing is that Python 3.6 is the version supported on Windows and Python 3.5 is the version supported on Linux. 
we're working on a new version of the SDK that should be free of those issues but it's going to be a few weeks. in the meantime your best option is to use python 3.5 or rebuild the SDK for python 3.6 instead of using pip packages.

**Comment by celaus** [comment]
Oh man, talk about Python version issues. 

I am happy to help, but I ended up using the Node SDK for my blogpost ([https://blog.x5ff.xyz/blog/cratedb-iothub-timeseries-prediction/](https://blog.x5ff.xyz/blog/cratedb-iothub-timeseries-prediction/)), happy to help out fixing the Python SDK though, so if you need more information on the issues, let me know. 

Thank you for taking care of this, btw!

**Comment by pierreca** [comment]
got it, thanks for the update! yeah the python version situation is bad. we're working on it. I'll close the issue then.

**Comment by az-iot-builder-01** [comment]
@celaus, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by ondrejspilka** [comment]
The issue  still persists. Why @pierreca closed the issue?
Windows 3.6
Linux 3.5
Mac 3.7

Brutal...

**Comment by geekinutah** [comment]
This is still an issue with Ubuntu 20.04. We've now moved on to python 3.7 but still have the deps on python3.5.
