### ISSUE TITLE
Release of pypi package azure-iothub-provisioningserviceclient

### ISSUE THREAD

**Issue by Bnjmn83** [Azure/azure-iot-sdk-python#194]
I had to build it on my own since this is still 1.0.0.
Any reason you guys did not release it yet?
Old version is lacking a few important features...

**Comment by pierreca** [comment]
@Bnjmn83 @cartertinney is working on a new version that includes all new features announced this week at ignite. we'll release it in the next couple of weeks.

**Comment by pierreca** [comment]
The new version of the SDK with all latest features was released on Dec 14 (v1.2.0). Sorry for the late update/closing on this issue.
