### ISSUE TITLE
Blob upload using x509 certs

### ISSUE THREAD

**Issue by Vijay-Karthick** [Azure/azure-iot-sdk-python#200]
Hi,

I have a device communicating to my IoT Hub using CA signed certificates (proof of possession has been done) communicating using MQTT protocol.

I'm able to successfully communicate to the Hub. But I'm not able to upload files to blob.

However, I'm able to upload files successfully from a device authenticated using SAS token using the procedure in [https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload](url) to the same IoT Hub.

Can you please tell me why upload to blob works from a device authenticated via SAS token (on MQTT and HTTP) but not from a device authenticated via TLS certificate (on MQTT)?

Kind regards,
Vijay.

**Comment by pierreca** [comment]
I believe this is a limitation of the service, not much the SDK can do about that. Closing since we cannot act on it here.

for reference, from another SDK:
https://github.com/Azure/azure-iot-sdk-node/issues/302

**Comment by az-iot-builder-01** [comment]
@Vijay-Karthick, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
