### ISSUE TITLE
Unable to include boost files in cmake

### ISSUE THREAD

**Issue by naveen3p** [Azure/azure-iot-sdk-python#201]
- **OS and version used:** <VERSION> Ubuntu 14.04

- **Python runtime used:** <VERSION> python2.7

- **SDK version used:** <VERSION> 1.2.8

# Description of the issue:
Hi,

I am having issue w.r.t boost file inclusion when toolchain make file is generation the Make file.

I found that there are three files where SDK is looking to for Boost libraries namely, provisioning_device_client , iot_hub_client_python and  service CmakeLists.txt.

I captured the console log. And i included debug message in Cmake file to check whether it is able to find the compiled Boost libraries or not. I have also tried with Boost ver 1.64.0 and the same error repeated.

# Code sample exhibiting the issue:

# Console log of the issue:

-- Boost version: 1.68.0
-- Boost version: 1.68.0
-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/bin/armv7l-timesys-linux-gnueabihf-gcc
-- Check for working C compiler: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/bin/armv7l-timesys-linux-gnueabihf-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/bin/armv7l-timesys-linux-gnueabihf-g++
-- Check for working CXX compiler: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/bin/armv7l-timesys-linux-gnueabihf-g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- IoT Client SDK Version = 1.2.8
-- Provisioning client ON
-- Provisioning SDK Version = 1.2.8
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- Looking for __x86_64__
-- Looking for __x86_64__ - not found
-- Looking for __i386__
-- Looking for __i386__ - not found
-- Looking for __arm__
-- Looking for __arm__ - found
-- target architecture: ARM
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- Found OpenSSL: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/lib/libssl.so;/home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/lib/libcrypto.so (found version "1.0.1k") 
-- Cross compiling not using pkg-config
-- Found CURL: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/lib/libcurl.so (found version "7.37.0") 
-- Found CURL: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/lib/libcurl.so  
-- target architecture: ARM
-- target architecture: ARM
-- target architecture: ARM
-- target architecture: ARM
-- iothub architecture: ARM
prov_device_client Boost files checkup
-- Could NOT find Boost
-- Found PythonLibs: /home/sumish/test1/Linux_Source/bg349_dtvplus_linux/distr/build_armv7l-timesys-linux-gnueabihf/toolchain/usr/lib/libpython2.7.so (found suitable version "2.7.3", minimum required is "2.7") 
IOT hub client Boost files checkup
-- Could NOT find Boost
IOT hub client Boost files checkup
-- Could NOT find Boost
-- Configuring done
-- Generating done
-- Build files have been written to: /home/sumish/Azure_Python_SDk/CrossCompiled_Azure_Python_Sdk/azure-iot-sdk-python/cmake

Thank you.

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@naveen3p, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
