### ISSUE TITLE
[Documentation/Example] Creating a Device with X509 Chain

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#206]
Is there an example or documentation on creating a device with an X509 cert?

Something similar to https://github.com/Azure/azure-iot-sdk-python/blob/master/service/samples/iothub_registrymanager_sample.py#L45

**Comment by pierreca** [comment]
@bearrito sorry for the super-late response.
it's basically the same API:
```python
new_device = iothub_registry_manager.create_device(DEVICE_ID, primary_thumbprint, secondary_thumbprint, IoTHubRegistryManagerAuthMethod.X509_THUMBPRINT)
new_device = iothub_registry_manager.create_device(DEVICE_ID, None, None, IoTHubRegistryManagerAuthMethod.X509_CERTIFICATE_AUTHORITY)
```

I'll add this to the samples.

**Comment by bearrito** [comment]
Thank you!  We ended up discovering this on our own and it works well.

**Comment by az-iot-builder-01** [comment]
@bearrito, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
