### ISSUE TITLE
azure-sdk-c iothub_client  sample run error 

### ISSUE THREAD

**Issue by chinnaece** [Azure/azure-iot-sdk-python#208]
when i cross  compiled iothub_client application for my AM-5728 EVM , 
i got below error . Below is my output log . please help me . My connection string is correct.

root@am57xx-evm:~# ./iothub_ll_telemetry_sample 

Creating IoTHub handle
Sending message 1 to IoTHub
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:725 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1209 Failed opening the underlying I/O.
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:981 Error: io_open failed
Error: Time:Tue Oct  9 13:16:15 2018 File:/home/kdasari/azure-iot-sdk-c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:1893 failure connecting to address IH-Embedded-COE.azure-devices.net.
Sending message 2 to IoTHub
Sending message 3 to IoTHub
Sending message 4 to IoTHub
Sending message 5 to IoTHub
Error: Time:Tue Oct  9 13:16:16 2018 File:/home/kdasari/azure-iot-sdk-c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:632 Failure: getaddrinfo failure -5.

**Comment by pierreca** [comment]
`getaddrinfo`means the hostname that you are connecting to is not resolving correctly on your device/module.

**Comment by chinnaece** [comment]
After setting up a network connection through ethernet ensure it's working good , **i got a new error as shown below please look into this** 


root@am57xx-evm:~# .**/iothub_ll_telemetry_sample** 
./iothub_ll_telemetry_sample: error while loading shared libraries: libssl.so.1.0.0: cannot open shared object file: No such file or directory

**Comment by az-iot-builder-01** [comment]
@chinnaece, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
