### ISSUE TITLE
Getting "No module named iothub_client" error

### ISSUE THREAD

**Issue by terrymandin** [Azure/azure-iot-sdk-python#21]
- Linux raspberrypi 4.4.50+ #970 Mon Feb 20 19:12:50 GMT 2017 armv6l GNU/Linux
- Python 2.7.9
- I don't see the SDK version anywhere.  It is the current git code as of March 22, 2017

# Description of the issue:
I followed these unix instructions (defaulted to python 2.7) to compile the SDK on my Pi: https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md.  When complete, I tried the sample:

 python iothub_client_sample.py -c HostName=myhub.azure-devices.net;DeviceId=RaspberryPiZero;SharedAccessKey=MyKey -p amqp

I got an "ImportError: No module named iothub_client" error

I recompiled and see that I am getting an error with the compilation.  I have attached the build log.
[putty.log.txt](https://github.com/Azure/azure-iot-sdk-python/files/866220/putty.log.txt)

# Code sample exhibiting the issue:

I used the iothub_client_sample.py file. I did not alter it.

# Console log of the issue:
pi@raspberrypi:~/azure-iot-sdk-python/device/samples $ python iothub_client_sample.py -c HostName=myhub.azure-devices.net;DeviceId=RaspberryPiZero;SharedAccessKey=MyKey -p amqp
Traceback (most recent call last):
  File "iothub_client_sample.py", line 10, in <module>
    import iothub_client
ImportError: No module named iothub_client
-bash: -p: command not found

**Comment by tdevendra** [comment]
I am also facing same issue. Apparently I can't find iothub_client.so anywhere after running build.sh.

**Comment by terrymandin** [comment]
My build wasn't working as my swap space was too small.  I upped it to 500 MB and it compiles now.  See this link to increase your swap space: http://raspberrypi.stackexchange.com/questions/70/how-to-set-up-swap-space

**Comment by tdevendra** [comment]
I am not sure that that's the issue in my case. I am not seeing iothub_client.so.
Are you able to see this library file built?

I have build azure-iot-sdk-c but after that I need to build azure-iot-sdk-python where it fails.

If I directly run python samples after C code build is done, I get "no module named iothub_client" error.

Can you provide me steps how you built it for python?

**Comment by tdevendra** [comment]
I have solved my issue. Its working for me now.

**Comment by editter** [comment]
@tdevendra What ended up being the problem and wow did you fix it?

**Comment by tameraw** [comment]
Great. Thanks for the update.

**Comment by llealgt** [comment]
@tdevendra  can you help me explaining what you did , you mention "python sdk needs c code for building" but what that means? do i need to install gcc ?

**Comment by brusMX** [comment]
I fixed it. In my case after following this documentation:

https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#installs-needed-to-compile-the-sdks-for-python-from-souce-code

I found that you need to copy the `iothub_client.so` file into your working directory that was generated in `/azure-iot-sdk-python/c/cmake/iotsdk_linux/python/src/iothub_client.so` while you were compiling it. Probably there is more elegant way to add this to python global modules, but this works.
