### ISSUE TITLE
Support for software update in azure iot python sdk

### ISSUE THREAD

**Issue by cgoma** [Azure/azure-iot-sdk-python#218]
- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

Hi Team,

I am working on software update using azure iot. I have found few links which talking about implementing this using azure iot node js  sdk and  azure iot c sdk as mentioned in below links
"https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device"
"https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-firmware-update"

I havenot used much of C and node js. So I am actually looking for software update using python.
I havent find any link or tutorial which talks about implementing the software update using azure iot python sdk. Please let me know if there is any support/tutorial for software update using azure iot python sdk.

**Comment by az-iot-builder-01** [comment]
@cgoma, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
