### ISSUE TITLE
Support for software update in azure iot python sdk

### ISSUE THREAD

**Issue by cgoma** [Azure/azure-iot-sdk-python#219]
- **OS and version used:** Ubuntu 16.04 

- **Python runtime used:** Python 3.8.7 

- **SDK version used:** <VERSION> 

# Description of the issue:

Support for software update in azure iot python sdk

# Code sample exhibiting the issue:

# Console log of the issue:

Hi Team,

I am working on software update using azure iot. I have found few links which talking about implementing this using azure iot node js sdk and azure iot c sdk as mentioned in below links
"https://github.com/Azure/azure-iot-sdk-c/tree/master/iothub_client/samples/iothub_client_sample_mqtt_dm/pi_device"
"https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-firmware-update"

I havenot used much of C and node js. So I am actually looking for software update using python.
I havent find any link or tutorial which talks about implementing the software update using azure iot python sdk. Please let me know if there is any support/tutorial for software update using azure iot python sdk.

**Comment by pierreca** [comment]
@cgoma there's nothing specially written on that topic using the Python SDK this being said the pattern (using the device twin) remains valid - it's only APIs that change.
[The main sample file ](https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample.py) shows how to use the device twin APIs.

**Comment by pierreca** [comment]
closing after some inactivity - feel free to reopen if there are any more questions.

**Comment by az-iot-builder-01** [comment]
@cgoma, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
