### ISSUE TITLE
IotHubMessage is truncated by byte array containing a zero

### ISSUE THREAD

**Issue by DumDumin** [Azure/azure-iot-sdk-python#220]
- **OS and version used:** Windows 10

- **Python runtime used:** 3.6

- **SDK version used:** <VERSION> 

# Description of the issue:

I try to send a byte array to the iot hub, which contains zeros. All bytes after and including an zero are not received in the iot hub, which I receive in a java application listing to a consumer group.

# Code sample exhibiting the issue:

    from iothub_client import IoTHubClient, IoTHubTransportProvider, IoTHubMessage

    CONNECTION_STRING = "..."
    PROTOCOL = IoTHubTransportProvider.HTTP

    def send_confirmation_callback(message, result, user_context):
        print("Confirmation received for message with result = %s" % (result))

    if __name__ == '__main__':
        client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
        client.set_option("MinimumPollingTime", 2)

    while True:

        serialized_segment = b'\x86\x05\x08\x9a\x89\x00\xf7\xe7'
        message = IoTHubMessage(serialized_segment)

        client.send_event_async(message, send_confirmation_callback, None)
        print("Message transmitted to IoT Hub")

        time.sleep(10)

Output of the received data converted to a hex string:
8605089a89

This behavior does not depend on the bytes I send, from an zero on nothing is received by the iot hub.

Sending the same bytes with the C SDK is working fine.
Thank you

**Comment by pierreca** [comment]
@DumDumin I was able to repro and confirm my hunch, it has to do with how our boost wrapper works over the C SDK - the Python3 byte sequence is interpreted as a string and `\x00` character is interpreted as the end of it.

The simplest fix to this is to cast to a byte array:

```python
serialized_segment = bytearray(b'\x86\x05\x08\x9a\x89\x00\xf7\xe7')
message = IoTHubMessage(serialized_segment)
```

This will invoke the proper constructor of `IoTHubMessage` and send all the bytes.

**Comment by az-iot-builder-01** [comment]
@DumDumin, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
