### ISSUE TITLE
TLS handshake failed : System.IO.IOException

### ISSUE THREAD

**Issue by tanieee28** [Azure/azure-iot-sdk-python#221]
I have created a iot edge solution using python sdk and trying to run build and run the solution in a simulator provided by Azure Extension in VS Code.
When it gets build and tries to run it get an errror as follows:

Error: Time:Wed Oct 17 06:27:35 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
edgeHubDev       | 2018-10-17 06:27:35.989 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 3897dd7a
DataGenerator    | Error: Time:Wed Oct 17 06:27:36 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
edgeHubDev       | 2018-10-17 06:27:36.057 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 58113c0b
DataGenerator    | Error: Time:Wed Oct 17 06:27:38 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
edgeHubDev       | 2018-10-17 06:27:38.055 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 2ca42293
DataGenerator    | Error: Time:Wed Oct 17 06:27:42 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
edgeHubDev       | 2018-10-17 06:27:42.082 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 51bdd64c
DataGenerator    | Error: Time:Wed Oct 17 06:27:50 2018 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:send_handshake_bytes Line:673 error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
edgeHubDev       | 2018-10-17 06:27:50.039 +00:00 [WRN] - TLS handshake failed., System.IO.IOException: Channel is closed, 110b6724

I am new to this and trying to understand why am i getting this error. 
By the way, i am having a windows machine.

**Comment by pierreca** [comment]
Our SDK uses TLS certificate verification and does not recognize your IoT Edge certificate as properly signed, so it's closing the connection.

cc @LazarusX @formulahendry is there something the VS code extension does to manage CA certs for the python samples?

**Comment by tanieee28** [comment]
@pierreca Thanks for u reply.

I havent changed the certificates.. From, ur point what i can understand is the certificates are not right, but i think that certificates are being downloaded by iotedge itself and i didnt changed that.
pardon me, but i am not expertise in iotedge.

For now, i am ignoring that as my modules are running perfectly fine.

**Comment by pierreca** [comment]
According to @formulahendry what you're hitting is related to this: https://github.com/Azure/iotedgehubdev/issues/67 which is in turn related to this: https://github.com/Azure/azure-iot-sdk-python/issues/150

basically the C SDK needs to get that feature in so that we can add it in Python so that @formulahendry and his team can enable this scenario in VS Code. For now, we're blocked.

Given there are other issues (#150) to track this problem i'm closing this as duplicate.

**Comment by az-iot-builder-01** [comment]
@tanieee28, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
