### ISSUE TITLE
Even though the HttpProxyOptions function is used, the Proxy server is NOT being called

### ISSUE THREAD

**Issue by designncode7** [Azure/azure-iot-sdk-python#222]
- ****OS** and version used: Windows 10 version 1703 OS Build: 15063.786
- **Python runtime used: Python 3.6.5 in an Anaconda environment
- **SDK version used: azure-iothub-client-1.4.3

**# Description of the issue**: even though we have updated to the latest libraries and we are calling the HttpProxyOptions function (per fix for Issue #174 ), the connection to Azure IoT Hub fails as the MQTT async connection tries to go through the Internet and is  blocked by the corporate firewall.  It is like the Proxy options are not being used or as if the proxy options are ignored.

**# Code sample exhibiting the issue:**
```
from iothub_client import IoTHubClient, HttpProxyOptions
client = IoTHubClient(CONNECTION_STRING, PROTOCOL)
proxy = HttpProxyOptions("http://myproxy.com", 8888)
client.set_option("proxy_data", proxy)
Note: Proxy URL and port have been modified from original
```

**# Console log of the issue:**

> Error: Time:Mon Oct 22 13:01:10 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:socketio_open Line:308 Failure: connect failure 10060.
> Error: Time:Mon Oct 22 13:01:10 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\c-utility\adapters\tlsio_schannel.c Func:tlsio_schannel_open Line:1165 xio_open failed
> Error: Time:Mon Oct 22 13:01:10 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:mqtt_client_connect Line:1000 Error: io_open failed
> Error: Time:Mon Oct 22 13:01:10 2018 File:C:\Release\iot-sdks-internals\release\python\automation\aziotsdk_pytools\src\c\iothub_client\src\iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2122 failure connecting to address SmartManufacturingIoTLabDemo.azure-devices.net.
> IoT Hub responded to message with status: BECAUSE_DESTROY

**Comment by pierreca** [comment]
@designncode7 sorry for the long response time, I wanted to set up a proxy and re-test this. It does work, the problem is that the suggestion in #174 is wrong: the proxy address should not include "http://". I'll edit it to fix it.

This will work:
```python
proxy = HttpProxyOptions("myproxy.com", 8888)
client.set_option("proxy_data", proxy)
```

**Comment by designncode7** [comment]
@pierreca: ok that explains why the proxy settings were ignored.  The code was using MQTT protocol.  We are using MQTT_WS now.  Thanks.

**Comment by az-iot-builder-01** [comment]
@designncode7, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
