### ISSUE TITLE
client doesn't reconnect after network connectivity restoration

### ISSUE THREAD

**Issue by hmansu444** [Azure/azure-iot-sdk-python#224]
- **OS and version used:** Debian 9

- **Python runtime used:** Python 2.7.13

- **SDK version used:** tags/release_2018_09_17

# Description of the issue:
Initially I have network connectivity When I initiate a client connection from device, In between The network connectivity is lost, It also doesn't indicates the lost of connection on device and client script keeps on running and when the network connectivity is restored, client keeps on running but doesn't reconnects with hub

# Code sample exhibiting the issue:
Client Init function
```
def iothub_client_init():
    # prepare iothub client
    client = IoTHubClient(CONNECTION_STRING, PROTOCOL)

    # set the time until a message times out
    client.set_option("messageTimeout", MESSAGE_TIMEOUT)
    # some embedded platforms need certificate information
    set_certificates(client)
    # this brings in x509 privateKey and certificate
    client.set_option("x509certificate", X509_CERTIFICATE)
    client.set_option("x509privatekey", X509_PRIVATEKEY)
    if client.protocol == IoTHubTransportProvider.MQTT or client.protocol == IoTHubTransportProvider.MQTT_WS:
        client.set_device_twin_callback(
            device_twin_callback, TWIN_CONTEXT)
        client.set_connection_status_callback(
            connection_status_callback, CONNECTION_STATUS_CONTEXT)
    # to enable MQTT logging set to 1
    if client.protocol == IoTHubTransportProvider.MQTT:
        client.set_option("logtrace", 0)
    retryPolicy = IoTHubClientRetryPolicy.RETRY_INTERVAL
    retryInterval = 100
    client.set_retry_policy(retryPolicy, retryInterval)
    print ( "SetRetryPolicy to: retryPolicy = %d" %  retryPolicy)
    print ( "SetRetryPolicy to: retryTimeoutLimitInSeconds = %d" %  retryInterval)
    retryPolicyReturn = client.get_retry_policy()
    print ( "GetRetryPolicy returned: retryPolicy = %d" %  retryPolicyReturn.retryPolicy)
    print ( "GetRetryPolicy returned: retryTimeoutLimitInSeconds = %d" %  retryPolicyReturn.retryTimeoutLimitInSeconds)
    return client
```
Connection Callback Function
```
def connection_status_callback(result, reason, user_context):
    global CONNECTION_STATUS_CALLBACKS
    print "Connection status changed[%d] with:" % (user_context)
    print "    reason: %d" % reason
    print "    result: %s" % result
    CONNECTION_STATUS_CALLBACKS += 1
    print "    Total calls confirmed: %d" % CONNECTION_STATUS_CALLBACKS
```
Main Function
```
def iothub_client_sample_run():

    try:
        
        client = iothub_client_init()

        if client.protocol == IoTHubTransportProvider.MQTT:
            print ( "IoTHubClient is reporting state" )
            #reported_state = "{\"connectivity\":\"cellular\"}"
            #client.send_reported_state(reported_state, len(reported_state), send_reported_state_callback, SEND_REPORTED_STATE_CONTEXT)

        while True:
            print ( "IoTHubClient waiting for commands, press Ctrl-C to exit" )

            time.sleep(10)
    except IoTHubError as iothub_error:
        print ( "Unexpected error %s from IoTHub" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubClient sample stopped" )
```

# Console log of the issue:
![image](https://user-images.githubusercontent.com/10773137/47565206-5b262f00-d945-11e8-9dc3-0eb627cb3353.png)
There is no visible change in the console log once the network is disconnected and then connected again

**Comment by pierreca** [comment]
@hmansu444  a couple questions from my colleagues on the C SDK team which the python SDK wraps around:

- Does you see any log when you get connected initially?
- How long do you wait for the reconnection to happen?

The MQTT keepalive is 4 minutes so it may take as much as 8 to detect a failed connection - messages aren't lost,  the SDK is queueing them up by the way, so if we manage to reconnect they will get sent and if we don't it's a bug.

Also, what type of connection are you using? is there something that would trick the OS into thinking the socket is still alive and well when the data is buffered somewhere? how do you test for loss of connectivity?

**Comment by hmansu444** [comment]
@pierreca  I tested again and It reconnected after 5-8 minutes.

**Comment by az-iot-builder-01** [comment]
@hmansu444, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
