### ISSUE TITLE
Setting message content type to application/json causes edgehub to error on message

### ISSUE THREAD

**Issue by sputnik13** [Azure/azure-iot-sdk-python#227]
- **OS and version used:** Ubuntu 16.04
- **Python runtime used:** CPython 3.5.2
- **SDK version used:** 1.4.3

# Description of the issue:
When content type is set to "application/json" on an outbound message, edgeHub fails to forward the message with the following warning
```
2018-10-29 23:54:29.190 +00:00 [WRN] - Message address devices/mpae-xenial/modules/PythonModuleTwinClient/messages/events/device_type=module_twin_client&%24.ct=application/json&%24.ce=utf-8&%24.on=output1/ does not match any topic.
```

It appears this is due to "application/json" being passed literally rather than being url-encoded.  Attempting a similar operation in the C# client works fine.  Looking through the C SDK, we found reference to tests that set the content type to "application%2fjson", which does seem to work from the python interface.  However, this is different from the way the C# API works, in that there is no need to url-encode content-types from the application code using the C# SDK.

There also appears to be no documentation referencing the need to url-encode content type values in the python API.

It would be preferable to have an SDK/API experience consistent with other language SDKs and not require url-encoding from the user.

# Code sample exhibiting the issue:
message.set_content_type_system_property('application/json')

# Console log of the issue:

**Comment by pierreca** [comment]
@sputnik13 the C SDK used to not do the URI encoding itself, and we inherited this behavior - because it would've become a breaking change they chose to not fix the default behavior and instead introduce an option that you can set using the following call to `set_options`:
```python
client.set_options('auto_url_encode_decode', true)
```

more context here: https://github.com/Azure/azure-iot-sdk-python/issues/153

**Comment by az-iot-builder-01** [comment]
@sputnik13, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
