### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found.

### ISSUE THREAD

**Issue by lopitals** [Azure/azure-iot-sdk-python#229]
- **OS and version used:** Windows 10 Pro - ver 1803 build 17134.345 x64

- **Python runtime used:** 3.7.1 x64

- **SDK version used:** azure-iot-provisioning-device-client==1.4.3

# Description of the issue:

Hi team,

I was going through:

[Create and provision a simulated X.509 device using Python device SDK for IoT Hub Device Provisioning Service](https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-x509-python)

But in _Simulate Device_ point 6, I couldn't provision device client via sample, and got the error.

**Path:**

D:\IoT\Git\azure-iot-sdk-python\provisioning_device_client\samples

**Files on dir:**

provisioning_device_client_args.py
provisioning_device_client_sample.py
provisioning_device_client_sample_class.py

**%PATH% env**

`echo %PATH%
D:\IoT\Git\cmd;C:\Program Files (x86)\Common Files\NetSarang;C:\Program Files (x86)\Common Files\Oracle\Java\javapath;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\Intel\WiFi\bin\;C:\Program Files\Common Files\Intel\WirelessCommon\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;D:\IoT\Git\cmd;D:\IoT\Git\mingw64\bin;D:\IoT\Git\usr\bin;D:\IoT\Python\Python37\Scripts\;D:\IoT\Python\Python37\;C:\Users\lopital\AppData\Local\Programs\Python\Launcher\;C:\Users\lopital\AppData\Local\Microsoft\WindowsApps;D:\IoT\CMake\bin`

Please your advice, thanks in advance.

Patricio Campos

# Code sample exhibiting the issue:

`python provisioning_device_client_sample.py`

# Console log of the issue:
`D:\IoT\Git\azure-iot-sdk-python\provisioning_device_client\samples>python provisioning_device_client_sample.py
Traceback (most recent call last):
  File "provisioning_device_client_sample.py", line 10, in <module>
    from provisioning_device_client import ProvisioningDeviceClient, ProvisioningTransportProvider, ProvisioningSecurityDeviceType, ProvisioningError, ProvisioningHttpProxyOptions
  File "D:\IoT\Python\Python37\lib\site-packages\provisioning_device_client\__init__.py", line 1, in <module>
    from .provisioning_device_client import *
ImportError: DLL load failed: The specified module could not be found.`

**Comment by pierreca** [comment]
The SDK does not support Python 3.7. On Windows, we only have support for Python 3.6. this is because of a dependency on boost. Also: please make sure to download python 3.6 for x64, given you're running on an x64 system.

**Comment by az-iot-builder-01** [comment]
@lopitals, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
