### ISSUE TITLE
Do you have plan to support on MacOS?

### ISSUE THREAD

**Issue by awong1900** [Azure/azure-iot-sdk-python#23]
Do you have plan to support on MacOS?

**Comment by zolvarga** [comment]
@awong1900 

Please take a look at our latest release :) We just added the support for OSX build.
https://github.com/Azure/azure-iot-sdk-python/releases
You can find the instructions here:
https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#mac

Best Regards,
Zoltan

**Comment by awong1900** [comment]
Yes it is work. Great job.
