### ISSUE TITLE
No to_python (by-value) converter found for C++ type: void*

### ISSUE THREAD

**Issue by k2nsloos** [Azure/azure-iot-sdk-python#230]
Hi,

I noticed that the azure-iot-python-sdk knocks it self out whenever I receive an incoming device method. The callback is set by set_device_method_callback_ex(), instead of the regular version.

 I intended to register a callback, which allowed to respond to the incoming call asynchronously. That is not returning the response in  the same call, but using device_method_response() member function, to set the actual response at some point in the future.

However boost tosses a TypeError: No to_python (by-value) converter found for C++ type: void*
I'm not sure how to fix this.

Kind regards,
Jaap

**Comment by k2nsloos** [comment]
The issue arises on line 1228 of  in device/iothub_client_python/src/iothub_client_python.cpp

Where you pass the void pointer to the python routine.

boost::python::object user_response_obj = deviceMethodCallback(method_name_std_string, payload_std_string, method_id, userContext);

**Comment by pierreca** [comment]
I will - please provide a sample code in python that shows the issue as well as the console log, and versions of the OS and Python interpreter used. thanks!

**Comment by k2nsloos** [comment]
The hw is a raspberry pi 1b+ (armhf / armv6l), running rasbian and python 2.7.
I'll try to create an python example script today.

**Comment by k2nsloos** [comment]
[example.zip](https://github.com/Azure/azure-iot-sdk-python/files/2571513/example.zip)

If I run the attached python file, and invoke a direct method using the HTTPS Api, then I get the following log output. The example requires twisted to run. (That's in fact what I want: integrate the client with existing code written for the twisted framework.)

`
2018-11-12T10:19:16+0000 [__main__#info] Using connection string HostName=testjaap.azure-devices.net;DeviceId=iot_test_device;SharedAccessKey=MF72+cjhmOo2orIgRcC/yOgwJRe+ZVrw/C233Vl6i18=
-> 10:19:16 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 192 | USERNAME: testjaap.azure-devices.net/iot_test_device/?api-version=2017-11-08-preview&DeviceClientType=iothubclient%2f1.2.9%20(native%3b%20Linux%3b%20armv7l) | PWD: XXXX | CLEAN: 0
<- 10:19:16 CONNACK | SESSION_PRESENT: true | RETURN_CODE: 0x0
-> 10:19:16 SUBSCRIBE | PACKET_ID: 2 | TOPIC_NAME: $iothub/methods/POST/# | QOS: 0
<- 10:19:16 SUBACK | PACKET_ID: 2 | RETURN_CODE: 0
<- 10:19:21 PUBLISH | IS_DUP: false | RETAIN: 0 | QOS: DELIVER_AT_MOST_ONCE = 0x00 | TOPIC_NAME: $iothub/methods/POST/reboot/?$rid=1 | PAYLOAD_LEN: 46
2018-11-12T10:19:21+0000 [stderr#error] TypeError: No to_python (by-value) converter found for C++ type: void*
`

Curl call:
`curl -X POST \
  https://testjaap.azure-devices.net/twins/iot_test_device/methods?api-version=2018-06-30 \
  -H 'Authorization: SharedAccessSignature XXX' \
  -H 'Content-Type: application/json' \
  -d '{
    "methodName": "reboot",
    "responseTimeoutInSeconds": 200,
    "payload": {
        "input1": "someInput",
        "input2": "anotherInput"
    }
}'
`

**Comment by pierreca** [comment]
@k2nsloos the fix has been checked in - we'll be releasing another version within the next couple of weeks.

**Comment by k2nsloos** [comment]
Hi @pierreca, many thanks for your time and effort. 
I'll checkout master and try it right away ;)

**Comment by pierreca** [comment]
Fixed in version 1.4.5 of the packages! thanks for your patience!
