### ISSUE TITLE
Is there the way to get the query list with some condition use IoTHub Python SDKs  

### ISSUE THREAD

**Issue by Demonlijianmin** [Azure/azure-iot-sdk-python#233]
hi，now i have a device id list，i want to get the status of them in once query，i do not know how to achieve it。

**Comment by pierreca** [comment]
@Demonlijianmin Some good docs about queries here: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-query-language

if you have a piece of code that doesn't work and you suspect a bug, please open an issue about that and add code and console logs.

**Comment by az-iot-builder-01** [comment]
@Demonlijianmin, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
