### ISSUE TITLE
Ubuntu 16.04 Dockerfile build failure

### ISSUE THREAD

**Issue by brycepg** [Azure/azure-iot-sdk-python#235]
- **OS and version used:** <VERSION> 
Ubuntu 16.04

- **Python runtime used:** <VERSION> 
CPython 2.7 and 3.5

- **SDK version used:** <VERSION> 
659647f1d6a19ec0e43014e87174595fe96ccf9b (latest commit as of this post)

# Description of the issue:

Building the [Dockerfile_Linux.build.x86_64](https://github.com/Azure/azure-iot-sdk-python/blob/master/dockerfiles/Dockerfile_Linux.build.x86_64) Dockerfile fails.

`docker --version`: `Docker version 18.09.0, build 4d60db4`

# Reproduction:

Create a new directory to contain your docker context
I ran these steps to start the build:
```
wget https://raw.githubusercontent.com/Azure/azure-iot-sdk-python/master/dockerfiles/Dockerfile_Linux.build.x86_64 -O Dockerfile
git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git src
docker build .
```

# Console log of the issue:

I added `set -x` to `src/c/build_all/linux/setup.sh` to diagnose this issue:

```
+ repo_exists
+ push_dir /usr/sdk/src/c/build_all/linux
+ pushd /usr/sdk/src/c/build_all/linux
++ git rev-parse --is-inside-work-tree
fatal: Not a git repository: /home/bryce/tmp/src/.git/modules/c
+ '[' '' == true ']'
+ return 1
+ clone_source
+ git clone https://github.com/Azure/azure-iot-sdk-c.git
fatal: destination path 'azure-iot-sdk-c' already exists and is not an empty directory.
+ exit 1
```

**Comment by brycepg** [comment]
If I delete all the python3 specific stuff, leaving only the python2 required lines, I do not run into this failure.

**Comment by pierreca** [comment]
@brycepg sorry for the delayed response

Looks like the failure happens within the C SDK build script itself around [here](https://github.com/Azure/azure-iot-sdk-c/blob/master/build_all/linux/setup.sh#L21)

I just ran it again on my machine (we run this on every release) and got to the appropriate line [(repo already cloned)](https://github.com/Azure/azure-iot-sdk-c/blob/master/build_all/linux/setup.sh#L44)

so I'm not sure what's going on here...

would you like to try and dig into this further or was this issue informational? are you blocked in any capacity?

**Comment by brycepg** [comment]
Yeah I will look into it. I'm not blocked at all by this.

**Comment by brycepg** [comment]
Did you run the exact commands I listed above to try to reproduce? I can still reproduce it with those exact commands.

I suspect it's a combination of the setup being called twice -- once for each python, version and the recursive traversal script looking in the `.git` directory and finding a directory with the same name as an actual submodule and trying to call `clone_source`.

**Comment by pierreca** [comment]
I did. and did it again just to make sure, literally copy/pasting from this issue. and it worked.
The only difference I can see (but shouldn't matter) is that I'm running ubuntu 18.04 as my host os.

can you paste your full logs (after removing any information you deem sensitive)?

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@brycepg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
