### ISSUE TITLE
Ubuntu 14.04 Build Failure (regression)

### ISSUE THREAD

**Issue by brycepg** [Azure/azure-iot-sdk-python#236]
- **OS and version used:** <VERSION> 
Parent OS: 16.04
Docker distro: Ubuntu 14.04

- **Python runtime used:** <VERSION> 
CPython 2.7

- **SDK version used:** <VERSION> 
`release_2018_10_31`

# Description of the issue:

Recursively cloning the tag `release_2018_10_31` fails to build on ubuntu 14.04
`release_2018_09_17` works fine.

# Code sample exhibiting the issue:

Run the following lines in a shell to reproduce the issue. Installing docker is required.

```
git clone --recursive --branch release_2018_10_31 https://github.com/Azure/azure-iot-sdk-python.git
cat <<EOF > azure-iot-sdk-python/Dockerfile
FROM ubuntu:14.04

# Update image
SHELL ["/bin/bash", "-c"]

RUN apt-get update && apt-get install -y sudo cmake build-essential curl libcurl4-openssl-dev \
    libssl-dev uuid-dev python-pip apt-utils

WORKDIR /usr/sdk

COPY ./ ./

RUN pip install --upgrade pip==10.0.1 && python -m pip install -U setuptools wheel
RUN ./build_all/linux/setup.sh
RUN ./build_all/linux/release.sh
EOF
cd azure-iot-sdk-python
docker build .
```

Run the lines above with branch `release_2018_09_17` to verify the regression.

# Console log of the issue:

The relevant error is during the build:
```
[ 24%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/ws_url.c.o
Linking C static library libaziotsharedutil.a
[ 24%] Built target aziotsharedutil
Linking CXX shared library provisioning_device_client_mock.so
[ 24%] Built target provisioning_device_client_mock
Linking CXX shared library iothub_client_mock.so
[ 24%] Built target iothub_client_mock
Linking CXX shared library iothub_service_client_mock.so
[ 24%] Built target iothub_service_client_mock
make: *** [all] Error 2
The command '/bin/bash -c ./build_all/linux/release.sh' returned a non-zero code: 1
```

**Comment by pierreca** [comment]
we're not maintaining Ubuntu 14.04 as an active target. given the difficulties Boost present, we're rewriting the SDK to not use that and won't be investing time on the existing version fixing issues for unsupported targets.

**Comment by az-iot-builder-01** [comment]
@brycepg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by markrad** [comment]
This issue has been identified and will be addressed shortly. In the meantime one can circumvent this issue by editing the file ```provisioning_client\samples\custom_hsm_example\CMakeLists.txt``` and adding ```compileAsC99()``` immediately after the line ```cmake_minimum_required(VERSION 2.8.11)``` close to the top of the file.

_Mark Radbourne MSFT_

**Comment by markrad** [comment]
This issue has been addressed.
