### ISSUE TITLE
Buffer messages across a device restart

### ISSUE THREAD

**Issue by LTsLlama** [Azure/azure-iot-sdk-python#238]
We are running devices on sometimes unstable Wi-Fi and internet connection. The SDK and IoT Hub is really good at buffering messages if the connection fail and sending them once a connection is available again - see screenshot. The issue is our devices get manually switched off over night. What is the best method for persisting messages across a manual device restart? Do you have code examples showing how to do this?

![image](https://user-images.githubusercontent.com/26236547/48925033-8cc5f200-ef13-11e8-8973-7dc78273b169.png)

**Comment by pierreca** [comment]
I'm sorry, unfortunately we don't have a recommendation for this given customer requirements and hardware capabilities vary widely (I have no idea what processes are allowed on your device, what your storage space looks like, etc). I'm glad to hear that the recovery logic is working well though.

**Comment by az-iot-builder-01** [comment]
@LTsLlama, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
