### ISSUE TITLE
Module object has no attribute __version__

### ISSUE THREAD

**Issue by BrianSidebotham** [Azure/azure-iot-sdk-python#24]
- Windows 7 Pro 64-bit

- Python 2.7.13 and 3.6.1

- Unknown

Hi Guys,

After using both 2.7.13 and 3.6.1 and installing by `python -m pip install azure-iothub-device-client` and trying to run the sample, I get the following error message:

```
...Desktop\azure-iot-sdk-python\device\samples>python iothub_client_sample.py

Python 2.7.13 (v2.7.13:a06454b1afa1, Dec 17 2016, 20:42:59) [MSC v.1500 32 bit (Intel)]
Traceback (most recent call last):
  File "iothub_client_sample.py", line 221, in <module>
    print ( "IoT Hub for Python SDK Version: %s" % iothub_client.__version__ )
AttributeError: 'module' object has no attribute '__version__'
```

It's the same message for both versions of Python.
Am I doing something fundamentally wrong?

**Comment by zolvarga** [comment]
@BrianSidebotham 

No, you are doing OK. This is a known issue, we are working on the fix.

Here is how you can unblock yourself:
Got to the **iothub_client_sample.py** and comment out line 226 like:
**#print ( "IoT Hub for Python SDK Version: %s" % iothub_client.__version__ )**

This line just an additional info, and not needed to run the sample.

Best Regards,
Zoltan

**Comment by BrianSidebotham** [comment]
Thanks @zolvarga 

It's just not my day for simple things holding me up. Thanks for letting me know, at least that unblocks me and I can move forward.

Sorry - I should have tried commenting out the offending line, but I just thought if it couldn't even do that then it's all fundamentally broken. Looking forward to giving things a try now. Thanks.

**Comment by BrianSidebotham** [comment]
Oh, a self compiled version on Linux with Python 2.7.12 works fine though. :+1:

**Comment by zolvarga** [comment]
Awesome! Thanks for letting me know! :)

**Comment by tameraw** [comment]
An update to the sample has been made and released.
