### ISSUE TITLE
File upload confirmation callback does not include reference to file

### ISSUE THREAD

**Issue by LTsLlama** [Azure/azure-iot-sdk-python#241]
- **OS and version used:** Windows 10 / Raspbian
- **Python runtime used:** 3.6
- **SDK version used:** 1.4.3

# Description of the issue:
We are using the upload_blob_async method to upload files to blob storage and want to delete the files once they have been confirmed as being uploaded successfully.
The issue is the confirmation callback does not include detail on the file uploaded and we potentially uploading multiple files, so how do we know what has been completed successfully?

**Comment by az-iot-builder-01** [comment]
@LTsLlama, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
