### ISSUE TITLE
Firmware update example

### ISSUE THREAD

**Issue by LTsLlama** [Azure/azure-iot-sdk-python#243]
- **OS and version used:** Rasbian
- **Python runtime used:** 3.6
- **SDK version used:** 1.4.3

# Description of the issue:
A Python example of the firmware update process as explained [here](https://docs.microsoft.com/en-us/azure/iot-hub/tutorial-firmware-update) would be really helpful.

**Comment by JesseJ12345** [comment]
@LTsLlama , Do you get any idea about **Firmware update** with python ?  We can deal with it together

**Comment by LTsLlama** [comment]
@JesseJ12345, I ended up writing a custom script independent of IoT hub. It checks Blob storage on startup and downloads the new version if available.

**Comment by JesseJ12345** [comment]
@LTsLlama ， Thanks.

**Comment by pierreca** [comment]
cc @dominicbetts FYI - request for more python samples.
I think this issue would be more appropriate in the samples repository associated with the docs so I'm opening it there and closing it here: https://github.com/Azure-Samples/azure-iot-samples-python/issues/9

Additional note: @LTsLlama @JesseJ12345 given we're rewriting the Python SDK, I'd much rather focus the effort on samples for the future (much better) version than for the current one. I will gladly merge a pull request if someone submits it though.

**Comment by az-iot-builder-01** [comment]
@JesseJ12345, @LTsLlama, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
