### ISSUE TITLE
segfault using MQTT and the azure-iothub-device-client

### ISSUE THREAD

**Issue by andrewwylie** [Azure/azure-iot-sdk-python#245]
- **OS and version used:** Ubuntu 16.04.3 
- **Python runtime used:**  3.5.2 
- **SDK version used:** 1.4.4 

# Description of the issue:
At 2:55am this morning (18/12/18) all five of my IoT devices using the azure-iothub-device-client reported the error
```
Error: Time:Tue Dec 18 02:55:23 2018 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_dowork Line:1006 Socketio_Failure: Receiving data from endpoint: errno=104.
```

This was then followed by the python program crashing with the following entry in the syslog

```
Dec 18 02:55:27 test1 kernel: [22947505.313713] python3[6172]: segfault at 109750ce0 ip 00007fae10614aa2 sp 00007fae09750cc0 error 4 in iothub_client.so[7fae10398000+35f000]
```
# Code sample exhibiting the issue:

```python
import time
import iothub_client

from iothub_client import IoTHubClient, IoTHubTransportProvider, DeviceMethodReturnValue

client = IoTHubClient(<connection_string>,IoTHubTransportProvider.MQTT)

def method_callback(method_name, payload, user_context):
    print('received method call:')
    print('\tmethod name:', method_name)
    print('\tpayload:', str(payload))
    retval = DeviceMethodReturnValue()
    retval.status = 200
    retval.response = "{\"key\":\"value\"}"
    return retval

print('subscribing to method calls')
client.set_device_method_callback(method_callback, 0)

while True:
    time.sleep(1)
```

[edit: pierreca: 2019-1-18] formatting

**Comment by pierreca** [comment]
@andrewwylie did you end up opening an SR or posting more information somewhere?

like I said, not much for us to go on here. I'd like to solve this issue but I won't be able to with just that.
If that's all you have, I'd be curious to know if at least it's reproed more recently or if it was a one-time thing that hasn't happened again?

**Comment by andrewwylie** [comment]
The issue hasn't reoccurred since, so I can close this ticket and keep monitoring it.

**Comment by pierreca** [comment]
OK. I'll close it for now but feel free to come back and comment and I'll reopen it. thanks!

**Comment by az-iot-builder-01** [comment]
@andrewwylie, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
