### ISSUE TITLE
Build Issue on Raspberry Pi +3 

### ISSUE THREAD

**Issue by georgimos** [Azure/azure-iot-sdk-python#246]
Hi 

I currently have an issue building this SDK on my raspberry Pi +3

- **Raspbian GNU/Linux:** <VERSION> 9

- **Python 3:** <VERSION> python 3.5 

- **SDK version used:** <VERSION> 

# Description of the issue:
when i try to build the sdk it stops at 22% and i get error of
 "Makefile:138: recipe for target 'all' failed make: *** [all] Error 2"
the build stops after that

# Console log of the issue:
/home/pi/workspace/azure-iot-sdk-python/c/cmake/iotsdk_linux /home/pi/workspace/azure-iot-sdk-python
-- The C compiler identification is GNU 6.3.0
-- The CXX compiler identification is GNU 6.3.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.9
-- Provisioning client ON
-- Provisioning SDK Version = 1.2.9
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: ARM
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- Found OpenSSL: /usr/lib/arm-linux-gnueabihf/libssl.so;/usr/lib/arm-linux-gnueabihf/libcrypto.so (found version "1.1.0j") 
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.29") 
-- Checking for module 'libcurl'
--   Found libcurl, version 7.52.1
-- Found CURL: curl  
-- target architecture: ARM
-- target architecture: ARM
-- target architecture: ARM
-- target architecture: ARM
-- iothub architecture: ARM
-- target architecture: ARM
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1534 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  /home/pi/workspace/azure-iot-sdk-python/provisioning_device_client/CMakeLists.txt:53 (find_package)

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   python-py35
-- Found PythonLibs: /usr/lib/arm-linux-gnueabihf/libpython3.5m.so (found suitable version "3.5.3", minimum required is "3.5") 
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1534 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  /home/pi/workspace/azure-iot-sdk-python/device/iothub_client_python/CMakeLists.txt:53 (find_package)

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   python-py35
CMake Warning at /usr/share/cmake-3.7/Modules/FindBoost.cmake:1534 (message):
  No header defined for python-py35; skipping header check
Call Stack (most recent call first):
  /home/pi/workspace/azure-iot-sdk-python/service/CMakeLists.txt:53 (find_package)

-- Boost version: 1.62.0
-- Found the following Boost libraries:
--   python-py35
-- Configuring done
-- Generating done
CMake Warning:
  Manually-specified variables were not used by the project:

    run_valgrind

-- Build files have been written to: /home/pi/workspace/azure-iot-sdk-python/c/cmake/iotsdk_linux
Initial MAKE_CORES=4
VSPACE=1864040
MAKE_CORES=4
Starting run...
Tue Dec 18 09:41:27 GMT 2018
Scanning dependencies of target custom_hsm_example
Scanning dependencies of target parson
Scanning dependencies of target msr_riot
Scanning dependencies of target aziotsharedutil
[  1%] Building C object provisioning_client/samples/custom_hsm_example/CMakeFiles/custom_hsm_example.dir/custom_hsm_example.c.o
[  2%] Building C object CMakeFiles/parson.dir/deps/parson/parson.c.o
[  2%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/DICE/DiceSha256.c.o
[  2%] Linking C static library libcustom_hsm_example.a
[  2%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotAes128.c.o
[  2%] Built target custom_hsm_example
[  3%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotAesTables.c.o
[  3%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotCrypt.c.o
Scanning dependencies of target provisioning_device_client_mock
[  3%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotDerEnc.c.o
[  3%] Linking C static library libparson.a
[  3%] Built target parson
[  4%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotEcc.c.o
[  4%] Building CXX object provisioning_device_client_python/tests/CMakeFiles/provisioning_device_client_mock.dir/provisioning_device_client_mock.cpp.o
[  4%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotHmac.c.o
Scanning dependencies of target iothub_client_mock
[  4%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/base32.c.o
[  4%] Building CXX object python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o
[  4%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotKdf.c.o
[  4%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/base64.c.o
[  5%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotSha256.c.o
[  5%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotX509Bldr.c.o
[  5%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/buffer.c.o
[  6%] Building C object provisioning_client/deps/CMakeFiles/msr_riot.dir/RIoT/Emulator/RIoT/RIoTCrypt/RiotBase64.c.o
[  6%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/connection_string_parser.c.o
[  6%] Linking C static library libmsr_riot.a
[  6%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer.c.o
[  6%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/consolelogger.c.o
[  6%] Built target msr_riot
Scanning dependencies of target iothub_service_client_mock
[  7%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/crt_abstractions.c.o
[  8%] Building CXX object python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/iothub_service_client_mock.cpp.o
[  8%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/constmap.c.o
[  8%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/doublylinkedlist.c.o
[  9%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/gballoc.c.o
[  9%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/gbnetwork.c.o
[  9%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/gb_stdio.c.o
[  9%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/gb_time.c.o
[ 10%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/gb_rand.c.o
[ 10%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/hmac.c.o
[ 10%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/hmacsha256.c.o
[ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/http_proxy_io.c.o
virtual memory exhausted: Cannot allocate memory
python/test/CMakeFiles/iothub_client_mock.dir/build.make:62: recipe for target 'python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o' failed
make[2]: *** [python/test/CMakeFiles/iothub_client_mock.dir/iothub_client_mock.cpp.o] Error 1
CMakeFiles/Makefile2:4590: recipe for target 'python/test/CMakeFiles/iothub_client_mock.dir/all' failed
make[1]: *** [python/test/CMakeFiles/iothub_client_mock.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 11%] Building CXX object python_service_client/tests/CMakeFiles/iothub_service_client_mock.dir/__/src/iothub_service_client_python.cpp.o
[ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/xio.c.o
[ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/singlylinkedlist.c.o
[ 12%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/map.c.o
[ 12%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/sastoken.c.o
[ 12%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/sha1.c.o
[ 13%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/sha224.c.o
[ 13%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/sha384-512.c.o
[ 13%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/strings.c.o
[ 13%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/string_token.c.o
[ 14%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/string_tokenizer.c.o
[ 14%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/uuid.c.o
[ 14%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/urlencode.c.o
[ 15%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/usha.c.o
[ 15%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/vector.c.o
[ 15%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/xlogging.c.o
[ 16%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/optionhandler.c.o
[ 16%] Building CXX object provisioning_device_client_python/tests/CMakeFiles/provisioning_device_client_mock.dir/__/src/provisioning_device_client_python.cpp.o
[ 16%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/agenttime.c.o
[ 16%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o
[ 16%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/lock_pthreads.c.o
[ 17%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/platform_linux.c.o
[ 17%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/socketio_berkeley.c.o
[ 17%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tickcounter_linux.c.o
[ 18%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/threadapi_pthreads.c.o
[ 18%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/uniqueid_linux.c.o
[ 18%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/envvariable.c.o
[ 19%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/linux_time.c.o
[ 19%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/httpapiex.c.o
[ 19%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/httpapiexsas.c.o
[ 20%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/httpheaders.c.o
[ 20%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/httpapi_curl.c.o
[ 20%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o
[ 20%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/adapters/x509_openssl.c.o
[ 21%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/wsio.c.o
[ 21%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/uws_client.c.o
[ 21%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/uws_frame_encoder.c.o
[ 21%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/ws_url.c.o
[ 22%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/utf8_checker.c.o
[ 22%] Linking C static library libaziotsharedutil.a
[ 22%] Built target aziotsharedutil
[ 22%] Linking CXX shared library provisioning_device_client_mock.so
[ 22%] Built target provisioning_device_client_mock
[ 22%] Linking CXX shared library iothub_service_client_mock.so
[ 22%] Built target iothub_service_client_mock
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by MaWa19** [comment]
Why do you even try to build the sdk on a Raspberry Pi when this is one of the few devices which the PyPI package is available for?
Consider following these instructions: [Install the Python modules using PyPI wheels from PyPI](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#install-the-python-modules-using-pypi-wheels-from-pypi)

**Comment by pierreca** [comment]
@georgimos it looks like the compiler is running out of memory. Not sure that this is a problem with the sdk itself. from your logs:
> [ 11%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/http_proxy_io.c.o
virtual memory exhausted: Cannot allocate memory

**Comment by georgimos** [comment]
@pierreca ya looks like that was the issue i cleaned that up and i got it working

**Comment by pierreca** [comment]
@georgimos thanks for confirming! closing as resolved.

**Comment by az-iot-builder-01** [comment]
@MaWa19, @georgimos, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
