### ISSUE TITLE
AMQP SASL Documentation

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#25]
Hello, I've seen the other issue related to documentation. This is a similar request.

Following https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security

Is it required to encode the SAS token when using SASL-Plain?

I'll note I have looked at https://github.com/Azure/azure-iot-sdk-python/tree/master/device/samples  but did not see any usage of sas tokens only the policy keys.

**Comment by tameraw** [comment]
As per the documentation:
"In both cases, the password field contains the token, as described in [IoT Hub security tokens](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-security#security-tokens)."

As per the sample comment:
The SDK will use the Key to form a SAS Token.
