### ISSUE TITLE
Intercept log messages from C sdk and print with logging module

### ISSUE THREAD

**Issue by alevincenzi** [Azure/azure-iot-sdk-python#252]
- **OS and version used:** <VERSION> 
ubuntu:xenail
- **Python runtime used:** <VERSION> 
Python 3.5.2
- **SDK version used:** <VERSION> 
azure-iothub-device-client 1.4.6

# Description of the issue:

Hello,
we are developing an iot edge module in python and we use the logging module to print out messages to stdout and text file.

We cannot find a way to intercept the messages that are printed by the underlying C sdk. For example, messages reporting that the connection is lost. Yes, they are visible in the stdout but we would like to handle them via the python logging handlers to be able to, for example, have them in a log file all formatted in the same way (for further parsing and filtering).

The text below reports the first lines printed when the module starts. The module cannot connect immediately and the error is displayed at the beginning of the line (no formatting with our format).

Thanks

# Console log of the issue:

> 2019-01-15 15:13:38,991 [INF] - Edge Module
> 2019-01-15 15:13:38,991 [INF] -     3.5.2 (default, Nov 12 2018, 13:43:14) 
> 2019-01-15 15:13:38,991 [INF] -     [GCC 5.4.0 20160609]
> 2019-01-15 15:13:38,991 [INF] -     Protocol MQTT
> 2019-01-15 15:13:38,992 [INF] - Setting input channel variables
> Error: Time:Tue Jan 15 15:13:38 2019 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:380 Failure: connect failure 111.
> Error: Time:Tue Jan 15 15:13:38 2019 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:764 wait_for_connection failed
> Error: Time:Tue Jan 15 15:13:38 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
> Error: Time:Tue Jan 15 15:13:38 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
> Error: Time:Tue Jan 15 15:13:38 2019 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
> Error: Time:Tue Jan 15 15:13:38 2019 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2151 failure connecting to address virtualhumswe.
> Error: Time:Tue Jan 15 15:13:39 2019 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:wait_for_connection Line:380 Failure: connect failure 111.
> Error: Time:Tue Jan 15 15:13:39 2019 File:/usr/sdk/src/c/c-utility/adapters/socketio_berkeley.c Func:socketio_open Line:764 wait_for_connection failed
> Error: Time:Tue Jan 15 15:13:39 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_open_complete Line:760 Invalid tlsio_state. Expected state is TLSIO_STATE_OPENING_UNDERLYING_IO.
> Error: Time:Tue Jan 15 15:13:39 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_open Line:1258 Failed opening the underlying I/O.
> Error: Time:Tue Jan 15 15:13:39 2019 File:/usr/sdk/src/c/umqtt/src/mqtt_client.c Func:mqtt_client_connect Line:1001 Error: io_open failed
> Error: Time:Tue Jan 15 15:13:39 2019 File:/usr/sdk/src/c/iothub_client/src/iothubtransport_mqtt_common.c Func:SendMqttConnectMsg Line:2151 failure connecting to address virtualhumswe.
> 2019-01-15 15:13:41,528 [INF] - Twin callback called with:
> 2019-01-15 15:13:41,528 [INF] -   updateStatus = COMPLETE
> 2019-01-15 15:13:41,528 [INF] -   payload = {"desired":{"$version":4},"reported":{"$version":1}}
> 2019-01-15 15:13:41,529 [INF] -   context = <__main__.HubManager object at 0x7fa531a4b358>
> 2019-01-15 15:13:43,259 [INF] - [variables] Received message { "timestamp" : "2019-01-15T15:13:37.110118Z", "machineid" :...
> 2019-01-15 15:13:52,113 [INF] - [variables] Received message { "timestamp" : "2019-01-15T15:13:52.109329Z", "machineid" :...
>

**Comment by pierreca** [comment]
@alevincenzi I don't know if there will be a way to do that with this version of the SDK (based on the C SDK)

The next version of the SDK (written fully in Python) uses the standard logging module and we will have a preview soon (not full featured, but hopefully enough to get started). Over the next couple of months, we should be full-featured and with any luck it'll match your timeline?

**Comment by alevincenzi** [comment]
@pierreca thank you for your fast reply and thank you for the info!
Yes, we will keep an eye on the releases to test it out as soon as it will be available. 

I have seen that the code in `c/c-utility/inc/azure_c_shared_utility/xlogging.h` defines a set of functions with 3 log levels (Info, Error, Binary).  I was hoping that while wrapping the skd you planned to define the `xlogging_get_log_function` to control the prints from pyhton.

Question closed : )

**Comment by az-iot-builder-01** [comment]
@alevincenzi, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
