### ISSUE TITLE
Unable to run HSM sample on Raspberry Pi

### ISSUE THREAD

**Issue by eXXL** [Azure/azure-iot-sdk-python#256]
- **OS and version used:** Raspberry Pi 3b+ with Raspian OS -->

- **Python runtime used:** 3.5.3

- **SDK version used:** current

# Description of the issue:
I cannot send data using HSM/TPM to Azure IoT hub using the sample from SDK.

I used this sample to provision the TPM device:
https://github.com/Azure/azure-iot-sdk-python/blob/master/provisioning_device_client/samples/provisioning_device_client_sample.py

I use a Raspberry Pi + LetsTrust TPM Chip.

It worked fine using the Node SDK but I want to send data using Python because I can read data from sensors better that using Node.JS.

The log file writes that there is not enough memory but am not sure if this is right. The node sample works good.

Can you give my any hints what might go wrong here or how I can send data using TPM and python?

# Code sample exhibiting the issue:
https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_prov_hsm_sample.py

# Console log of the issue:
```
Python 3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
IoT Hub Client for Python
Starting the IoT Hub Python sample...
    IoTHub Uri=eXXL01.azure-devices.net
    Device ID=sjfhjnj7a4fe63hesm3bamcxgl2wtyip72wayzlvtngdctwxy3aa
    Security Type=SAS
    Protocol HTTP
IoTHubClient sending 5 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Out of memory

Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
Confirmation[0] received for message with result = ERROR
    message_id: message_0
    correlation_id: correlation_0
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 1
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [3] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [4] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: BUSY
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Out of memory

Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
Confirmation[1] received for message with result = ERROR
    message_id: message_1
    correlation_id: correlation_1
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 2
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Out of memory

Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
Confirmation[2] received for message with result = ERROR
    message_id: message_2
    correlation_id: correlation_2
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 3
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Out of memory

Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
Confirmation[3] received for message with result = ERROR
    message_id: message_3
    correlation_id: correlation_3
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 4
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Out of memory

Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Mon Feb  4 16:32:34 2019 File:/home/pi/azure-iot-sdk-python/c/iothub_client/src/iothubtransporthttp.c Func:DoEvent Line:1685 unable to HTTPAPIEX_SAS_ExecuteRequest
Confirmation[4] received for message with result = ERROR
    message_id: message_4
    correlation_id: correlation_4
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 5
^X^CTraceback (most recent call last):
  File "iothub_client_prov_hsm_sample.py", line 120, in <module>
    iothub_client_prov_hsm_sample_run()
  File "iothub_client_prov_hsm_sample.py", line 99, in iothub_client_prov_hsm_sample_run
    time.sleep(10)

```

**Comment by eXXL** [comment]
Hi Pierre,
switching to MQTT did it! Now it works!

Thank you very much,
Alex

**Comment by pierreca** [comment]
@eXXL glad it works :) I believe we had similar issues on MacOS where a bug in the curl library had that impact. out of curiosity can you let me know which version of curl is installed on your system?

**Comment by eXXL** [comment]
Hi Pierre,
I'm sorry for the late reply. I was busy for a couple of days.

The curl version I use is this one:

curl 7.52.1 (arm-unknown-linux-gnueabihf) libcurl/7.52.1 OpenSSL/1.0.2l zlib/1.2.8 libidn2/0.16 libpsl/0.17.0 (+libidn2/0.16) libssh2/1.7.0 nghttp2/1.18.1 librtmp/2.3

Cheers,
Alex

**Comment by joy03265** [comment]
Hi member,
I meet the following issue. Anyone know how to fix it. Thanks
Error: Time:Tue Feb 19 22:21:39 2019 File:/Users/joy/Downloads/azure-iot-samples-python-master/iot-hub/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Tue Feb 19 22:21:39 2019 File:/Users/joy/Downloads/azure-iot-samples-python-master/iot-hub/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Tue Feb 19 22:21:39 2019 File:/Users/joy/Downloads/azure-iot-samples-python-master/iot-hub/azure-iot-sdk-python/c/iothub_service_client/src/iothub_devicemethod.c Func:sendHttpRequestDeviceMethod Line:332 HTTPAPIEX_SAS_ExecuteRequest failed
Error: Time:Tue Feb 19 22:21:39 2019 File:/Users/joy/Downloads/azure-iot-samples-python-master/iot-hub/azure-iot-sdk-python/c/iothub_service_client/src/iothub_devicemethod.c Func:IoTHubDeviceMethod_DeviceOrModuleInvoke Line:500 Failure sending HTTP request for device method invoke

 curl --version
curl 7.64.0 (x86_64-apple-darwin18.2.0) libcurl/7.64.0 SecureTransport zlib/1.2.11
Release-Date: 2019-02-06
Protocols: dict file ftp ftps gopher http https imap imaps ldap ldaps pop3 pop3s rtsp smb smbs smtp smtps telnet tftp
Features: AsynchDNS IPv6 Largefile NTLM NTLM_WB SSL libz UnixSockets

**Comment by pierreca** [comment]
@joy03265 that seems like a different error/issue. can you please open a new issue and give us some details about how to reproduce the problematic behavior?

**Comment by az-iot-builder-01** [comment]
@eXXL, @joy03265, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
