### ISSUE TITLE
cannot import lib iothub_client

### ISSUE THREAD

**Issue by TPponmat** [Azure/azure-iot-sdk-python#258]
- **OS and version used:** <ARMBIAN 5.59 > 

- **Python runtime used:** <2.7.15rc> 

- **SDK version used:** <azure-iothub-device-client==1.4.6> 

# Description of the issue:
I install sdk sample file in part azure-iot-sdk-python/device/samples ==> then I got this error massage

# Code sample exhibiting the issue:
Azure sample file in part
azure-iot-sdk-python/device/samples

# Console log of the issue:
  File "/home/pea/workspace/hive_os/volttron/env/local/lib/python2.7/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: libssl.so.1.0.2: cannot open shared object file: No such file or directory

**Comment by pierreca** [comment]
That's typically related to not having libssl installed. i'm not familiar with armbian so i'm not sure what to suggest, but it basically boils down to either a missing package, or the existing system version being incompatible with the one that is linked to by the SDK.
This is typically why we suggest that only specific linux distributions are supported and we have a few dockerfiles [here](https://github.com/Azure/azure-iot-sdk-python/tree/master/dockerfiles) that list what dependencies to install.

**Comment by pierreca** [comment]
closed as we believe this has been answered and the issue is inactive.

**Comment by az-iot-builder-01** [comment]
@TPponmat, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
