### ISSUE TITLE
Approximate Update Timeline?

### ISSUE THREAD

**Issue by jackt-moran** [Azure/azure-iot-sdk-python#259]
My organization is developing a longer term plan for our project and need to decide on a language. We would like to use Python, but we've experienced some stability issues that are unacceptable. We suspect that the pure Python version of this library will resolve our stability issues, but the timing of the release affects our decision - do you have an approximate timeline for the release date of this new version?

**Comment by pierreca** [comment]
we're hard at work on releasing a preview version this month which will include telemetry and cloud-to-device support, but not twins and methods yet. We will work on these features in the following weeks, then move on to add provisioning service support. I'm fairly reluctant to communicate aggressive timelines though but I sure hope that we'll be done by the end of spring.
Might be earlier depending on which protocol and features you want to use.

you can follow the work happening on https://github.com/azure/azure-iot-sdk-python-preview

**Comment by jackt-moran** [comment]
Thanks!

**Comment by pierreca** [comment]
closing as we believed it's been answered and no other follow up.

**Comment by az-iot-builder-01** [comment]
@jackt-moran, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
