### ISSUE TITLE
Unable to build without AMQP and service client

### ISSUE THREAD

**Issue by vjrantal** [Azure/azure-iot-sdk-python#26]
- **OS and version used:** Any 

- **Python runtime used:** 2.7 

- **SDK version used:** IoT Hub SDK for C, version 1.1.12 

# Description of the issue:

Build error when disabling AMQP and service client support. An example scenario where disabling those might be wanted is when building on a Raspberry Pi and just wanting to use the device client with MQTT.

# Code sample exhibiting the issue:

Example cmake flags that trigger the issue:

```
cmake -Drun_valgrind:BOOL=OFF -DcompileOption_CXX:STRING="-Wno-unused-value" -DcompileOption_C:STRING="-Wno-unused-value" -Drun_e2e_tests:BOOL=OFF -Drun_longhaul_tests=OFF -Duse_amqp:BOOL=OFF -Duse_http:BOOL=ON -Duse_mqtt:BOOL=ON -Ddont_use_uploadtoblob:BOOL=OFF -Duse_wsio:BOOL=ON -Drun_unittests:BOOL=OFF -Dbuild_python:STRING=2.7 -Dbuild_javawrapper:BOOL=OFF -Dno_logging:BOOL=OFF -Dskip_samples=ON -DPYTHON_INCLUDE_DIR=$(python-config --prefix)/include/python2.7 -DPYTHON_LIBRARY=$(python-config --prefix)/lib/libpython2.7.dylib ../..
```

# Console log of the issue:

The issue is two-fold.

The first error is:

```
Scanning dependencies of target iothub_client_python
[ 96%] Building CXX object python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o
/home/pi/azure-iot-sdk-python/device/iothub_client_python/src/iothub_client_python.cpp: In static member function ‘static const TRANSPORT_PROVIDER* (* IoTHubClient::GetProtocol(IOTHUB_TRANSPORT_PROVIDER))()’:
/home/pi/azure-iot-sdk-python/device/iothub_client_python/src/iothub_client_python.cpp:1090:14: error: ‘AMQP_WS’ was not declared in this scope
         case AMQP_WS:
              ^
/home/pi/azure-iot-sdk-python/device/iothub_client_python/src/iothub_client_python.cpp:1091:24: error: ‘AMQP_Protocol_over_WebSocketsTls’ was not declared in this scope
             protocol = AMQP_Protocol_over_WebSocketsTls;
                        ^
python/src/CMakeFiles/iothub_client_python.dir/build.make:62: recipe for target 'python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o' failed
make[2]: *** [python/src/CMakeFiles/iothub_client_python.dir/iothub_client_python.cpp.o] Error 1
CMakeFiles/Makefile2:1366: recipe for target 'python/src/CMakeFiles/iothub_client_python.dir/all' failed
make[1]: *** [python/src/CMakeFiles/iothub_client_python.dir/all] Error 2
Makefile:94: recipe for target 'all' failed
make: *** [all] Error 2
```

And after above fixed, the second is:

```
[ 96%] Built target iothub_client_mock
Scanning dependencies of target iothub_service_client_python
[ 97%] Building CXX object python_service_client/src/CMakeFiles/iothub_service_client_python.dir/iothub_service_client_python.cpp.o
azure-iot-sdk-python/service/src/iothub_service_client_python.cpp:23:10: fatal error: 'iothub_sc_version.h' file not found
#include "iothub_sc_version.h"
         ^
1 error generated.
```

**Comment by vjrantal** [comment]
Fixing the issue overall required two separate PRs. First part is addressed with https://github.com/Azure/azure-iot-sdk-python/issues/27 and second with https://github.com/Azure/azure-iot-sdk-c/issues/120.

**Comment by tameraw** [comment]
@vjrantal - Thanks for providing those PRs. The C one is merged and we're looking at the one here in Python.

**Comment by vjrantal** [comment]
@tameraw Thanks.

Wanted to mention that this issue relates also to the `Known build issues` mentioned at https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#compile-the-python-modules . I was first unable to build on Raspberry Pi due to memory running out, but when I patched the code to be able to build without service client and AMQP, the build process takes a bit less memory and build succeeds (with default swap settings on the latest Raspbian Jessie release).

**Comment by zolvarga** [comment]
@vjrantal 

Thanks for the fixes, they are merged. I am closing this issue.

Best Regards,
Zoltan
