### ISSUE TITLE
After some time send_confirmation_callback returns MESSAGE_TIMEOUT

### ISSUE THREAD

**Issue by erdemontas** [Azure/azure-iot-sdk-python#263]
- **OS and version used:** <"Raspbian GNU/Linux 9 (stretch)> 

- **Python runtime used:** <3.5.3> 

- **SDK version used:** <azure-iothub-device-client==1.4.6> 

# Description of the issue: 
I sent bunch of data to the iothub for while without any problem. After some time(I really dont know when exactly and why) send_cofirmation_callback returns MESSAGE_TIMEOUT. When I restart the program it sends successfully. I use a queue in python program to send coming data with 5 seconds interval. I use iothub_client_sample.py as example while I wrote my code. 
So questions appear; 
Why after some time iothub stops receiving messages?
 

# Code sample exhibiting the issue:

```
def send_confirmation_callback(message, result, user_context):

    print("Confirmation received for message with result = %s" % (result))
    
    if not "OK" in str(result): 
        eventLogger(errorFile,"Error: Message can not sent to Azure. Result: %s " % str(result) )
       
        
    
    return result

def iothub_client_init():
    # prepare iothub client
    client = IoTHubClient(globalConfigs["connectionString"], PROTOCOL)
    
    if client.protocol == IoTHubTransportProvider.HTTP:
        client.set_option("timeout", TIMEOUT)
        client.set_option("MinimumPollingTime", MINIMUM_POLLING_TIME)
    # set the time until a message times out
    client.set_option("messageTimeout", MESSAGE_TIMEOUT)
    # some embedded platforms need certificate information
    set_certificates(client)
    
    # to enable MQTT logging set to 1
    if client.protocol == IoTHubTransportProvider.MQTT:
        client.set_option("logtrace", 0)
   
    retryPolicy = IoTHubClientRetryPolicy.RETRY_INTERVAL
    retryInterval = 100
    client.set_retry_policy(retryPolicy, retryInterval)
    
    print ( "SetRetryPolicy to: retryPolicy = %d" %  retryPolicy)
    print ( "SetRetryPolicy to: retryTimeoutLimitInSeconds = %d" %  retryInterval)
    retryPolicyReturn = client.get_retry_policy()
    print ( "GetRetryPolicy returned: retryPolicy = %d" %  retryPolicyReturn.retryPolicy)
    print ( "GetRetryPolicy returned: retryTimeoutLimitInSeconds = %d" %  retryPolicyReturn.retryTimeoutLimitInSeconds)

    return client

def sendDataToAzure(iotHubString):    
    q.put(iotHubString, False)
    
def workerFunc(q):
    
    while True:      #here check if we have internet connection
          
        currentTime = time.time()
        while not q.empty(): 
            
            while(time.time()-currentTime > 5): 
                                 
                try:        
                    if __name__ == '__main__':
                        print("q.size() : {0}" . format(q.qsize()))
                        temp=q.get()
                        print("Sent at {0} \t: {1}" .format(getTimeStamp(),temp))
                        dataText = IoTHubMessage(temp)
                        messageResult = client.send_event_async(dataText, send_confirmation_callback, None)
                        
                except TypeError:
                    print("Expected byte array")
                    eventLogger(errorFile, "Expected byte array, ")
                
                except IoTHubError as iothub_error:
                    print ( "Unexpected error %s from IoTHub" % iothub_error )
                    eventLogger(errorFile, "Unexpected error %s from IoTHub" % iothub_error)
                
                except KeyboardInterrupt:
                    print ( "IoTHubClient sample stopped" )
                    
                currentTime = time.time()

client = iothub_client_init()

while True:
    
    dataFromNrf = getDataFromNrf()   
    if(dataFromNrf != -1):
        try:
            preparedAzureString = prepareStringForAzure(dataFromNrf)
            sendDataToAzure(preparedAzureString)        
        except TypeError:
            print("Wrong data")
        finally:
            None
```

# Console log of the issue:

2019-02-28 22:40:10	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:15	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:17	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:22	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:31	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:33	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:41	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:40:51	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:41:01	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:41:11	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:41:23	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:42:02	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:42:07	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT 
2019-02-28 22:42:07	Error: Message can not sent to Azure. Result: MESSAGE_TIMEOUT

**Comment by pierreca** [comment]
this would happen when the client is failing to reconnect to the hub before the message timeout is reached. highly likely a networking issue.

**Comment by erdemontas** [comment]
> 
> 
> this would happen when the client is failing to reconnect to the hub before the message timeout is reached. highly likely a networking issue.


In the same conditions, after MESSAGE_TIMEOUT appears, when I restart the program(via CTRL+C and retyping 'python program.py' in terminal ), messages successfully received by iothub. Does library has any function to restart the client? or any other method ? What would your suggestion?

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@erdemontas, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
