### ISSUE TITLE
Setting keepalive option causes segfault

### ISSUE THREAD

**Issue by sam-findler** [Azure/azure-iot-sdk-python#264]
- **OS and version used:** <Ubuntu 14.04> 

- **Python runtime used:** <2.7.6> 

- **SDK version used:** <fork of 1.4.6> 

# Description of the issue:

With MQTT, the "keepalive" option is supposed to set the frequency at which ping/pingresp happens to the iothub, per the c sdk (https://github.com/Azure/azure-iot-sdk-c/blob/master/doc/Iothub_sdk_options.md).  However, adding that option at initialization of a process causes an immediate segfault.  Specifically:
```
Process finished with exit code 139 (interrupted by signal 11: SIGSEGV)
```

# Code sample exhibiting the issue:

Works:
```
client = IoTHubModuleClient(connection_string, IoTHubTransportProvider.MQTT)
      client.set_retry_policy(IoTHubClientRetryPolicy.RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER, 5)
client.set_option("x509certificate", cert)
client.set_option("x509privatekey", key)
```

Doesn't:
```
client = IoTHubModuleClient(connection_string, IoTHubTransportProvider.MQTT)
      client.set_retry_policy(IoTHubClientRetryPolicy.RETRY_EXPONENTIAL_BACKOFF_WITH_JITTER, 5)
client.set_option("x509certificate", cert)
client.set_option("x509privatekey", key)
client.set_option("keepalive", 100)
```

**Comment by sam-findler** [comment]
Closing, as I realized the c sdk being out of date caused it.

**Comment by az-iot-builder-01** [comment]
@sam-findler, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
