### ISSUE TITLE
No way to close IoTHubClient connections and destroy() not present for IoTHubClient

### ISSUE THREAD

**Issue by mindentropy** [Azure/azure-iot-sdk-python#265]
- **OS and version used:**  <Ubuntu 4.18> 

- **Python runtime used:** <2.7.15> 

- **SDK version used:**  <master> 

# Description of the issue:
The documentation for Python does not mention anyway to destroy the IoTHubClient or connections to the cloud from device. I have a scenario where I would like to disconnect all
connections to Azure Cloud from the device and reconnect. I searched the code and I found destroy() function for IoTHubClient but I get the following error

 AttributeError: 'IoTHubClient' object has no attribute 'destroy'

# Code sample exhibiting the issue:

```python
#!/usr/bin/env python

import iothub_client

from iothub_client import IoTHubClient
from iothub_client import IoTHubTransportProvider

if __name__ == '__main__':
	
	connstr = '<MY CONNSTR'
	protocol = IoTHubTransportProvider.MQTT

	client = IoTHubClient(
		connstr,
		protocol
		)

	client.destroy()
```

# Console log of the issue:

```
Traceback (most recent call last):
  File "test_iothub.py", line 18, in <module>
    client.destroy()
AttributeError: 'IoTHubClient' object has no attribute 'destroy'
```

**Comment by pierreca** [comment]
There is no method in this version of the SDK that allows you to manually change the connection status. This version of the SDK is based off the C SDK and this wrapper approach has not worked well so we're deprecating it and won't be adding this feature. 

On the bright side, we are building a new, more pythonic SDK and it already includes the possibility to connect/disconnect manually, so we should be able to honor your request very soon: Check out https://github.com/azure/azure-iot-sdk-python-preview for our current progress!

**Comment by az-iot-builder-01** [comment]
@mindentropy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
