### ISSUE TITLE
Setup script for building python sdk on macOS installs boost for python 3.7, although python 3.6 was specified

### ISSUE THREAD

**Issue by mibarg** [Azure/azure-iot-sdk-python#266]
- **OS and version used:** macOS 10.14

- **Python runtime used:** python 3.6

- **SDK version used:** release_2019_01_03

# Description of the issue:

Setup script for building python sdk on macOS installs boost for python 3.7, although python 3.6 was specified.

Following [this](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#build-the-azure-iot-hub-sdks-for-python-on-mac-os) guide, I ran the _setup.sh_ script with `./setup.sh --python-version 3.6` and then the _build.sh_ script with `./build.sh --build-python 3.6`. Setup script was successful, but the build script failed to find boost (see error below).
After investigation, it seems like the setup script has install boost for python 3.7, not 3.6. Switching to a virtualenv with python 3.7 solved the issue - the build script terminated successfully.

# Console log of the issue:
~~~
(venv) $ ./build.sh --build-python 3.6
<path>/azure-iot-sdk-python/c/cmake/iotsdk_mac <path>/azure-iot-sdk-python
-- The C compiler identification is AppleClang 10.0.1.10010046
-- The CXX compiler identification is AppleClang 10.0.1.10010046
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc
-- Check for working C compiler: /Library/Developer/CommandLineTools/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++
-- Check for working CXX compiler: /Library/Developer/CommandLineTools/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- IoT Client SDK Version = 1.2.12
-- Provisioning SDK Version = 1.2.12
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file stdbool.h
-- Looking for include file stdbool.h - found
-- target architecture: x86_64
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Success
-- Found PkgConfig: /usr/local/bin/pkg-config (found version "0.29.2") 
-- Checking for module 'libcurl'
--   Found libcurl, version 7.54.0
-- Found CURL: curl  
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- target architecture: x86_64
-- iothub architecture: x86_64
-- Could NOT find Boost
CMake Error at <path>/azure-iot-sdk-python/device/iothub_client_python/CMakeLists.txt:44 (string):
  string sub-command REPLACE requires at least four arguments.


-- Found PythonLibs: /usr/local/opt/python/Frameworks/Python.framework/Versions/3.7/lib/libpython3.6m.dylib (Required is at least version "3.6") 
-- Could NOT find Boost
CMake Error at <path>/azure-iot-sdk-python/service/CMakeLists.txt:44 (string):
  string sub-command REPLACE requires at least four arguments.


-- Configuring incomplete, errors occurred!
See also "<path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
Test project <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac
No tests were found!!!
<path>/azure-iot-sdk-python
copy iothub_client library to samples folder
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
copy iothub_client_mock library to tests folder
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/test/iothub_client_mock.dylib: No such file or directory
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client library to samples folder
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client_mock library to tests folder
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/tests/iothub_service_client_mock.dylib: No such file or directory
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: <path>/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
python3.6 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ModuleNotFoundError: No module named 'iothub_client_mock'
~~~

**Comment by pierreca** [comment]
Thanks for pointing this out. that's because this is the latest version installable using brew. 
Given we can only release one package per architecture with a specific version of boost and we have been supporting Python 3.7, we're not going to make changes to the script to allow for 3.6. 

If you want to submit a PR to support others version of python we'll gladly review it though.

**Comment by az-iot-builder-01** [comment]
@mibarg, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mibarg** [comment]
Sounds reasonable. However, I suggest changing [this](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#build-the-azure-iot-hub-sdks-for-python-on-mac-os) README to point out the issue since it has python 3.6 as an option.

**Comment by saeed2402** [comment]
The workaround for version 3.7 works for me. However, ./build.sh still fails, here are the error messages:

[ 20%] Building C object c-utility/CMakeFiles/aziotsharedutil.dir/src/uuid.c.o
In file included from /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/device/iothub_client_python/test/iothub_client_mock.cpp:10:
In file included from /usr/local/include/boost/python.hpp:11:
In file included from /usr/local/include/boost/python/args.hpp:8:
In file included from /usr/local/include/boost/python/detail/prefix.hpp:13:
In file included from /usr/local/include/boost/python/detail/wrap_python.hpp:151:
In file included from /System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/Python.h:85:
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:534:5: error: 'register' storage class specifier is deprecated and incompatible with
      C++17 [-Werror,-Wdeprecated-register]
    register PyObject *obj,     /* Object */
    ^~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:553:5: error: 'register' storage class specifier is deprecated and incompatible with
      C++17 [-Werror,-Wdeprecated-register]
    register PyObject *obj      /* Object */
    ^~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:575:5: error: 'register' storage class specifier is deprecated and incompatible with
      C++17 [-Werror,-Wdeprecated-register]
    register const wchar_t *w,  /* wchar_t buffer */
    ^~~~~~~~~
/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7/unicodeobject.h:593:5: error: 'register' storage class specifier is deprecated and incompatible with
      C++17 [-Werror,-Wdeprecated-register]
    register wchar_t *w,        /* wchar_t buffer */
    ^~~~~~~~~

[......]

Test project /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac
No tests were found!!!
~/Desktop/IoT/take-01/Github/azure-iot-sdk-python
copy iothub_client library to samples folder
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
copy iothub_client_mock library to tests folder
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/test/iothub_client_mock.dylib: No such file or directory
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client library to samples folder
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client_mock library to tests folder
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/tests/iothub_service_client_mock.dylib: No such file or directory
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: /Users/saeed/Desktop/IoT/take-01/Github/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
python2.7 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: dynamic module does not define init function (initiothub_client_mock)

Any help is highly appreciated,
Thanks.
