### ISSUE TITLE
Support for provisioning device with group enrollment and symmetric key

### ISSUE THREAD

**Issue by taak77** [Azure/azure-iot-sdk-python#267]
- **OS and version used:** Raspbian stretch

- **Python runtime used:** 3.5

- **SDK version used:** provisioning device client 1.4.6

# Description of the issue:
I can't find the example of Python SDK for device provisioning with group enrollment and symmetric key same as the ones below

NodeJS:
https://github.com/Azure/azure-iot-sdk-node/blob/master/provisioning/device/samples/register_symkeygroup.js

Java:
https://github.com/Azure/azure-iot-sdk-java/blob/master/provisioning/provisioning-samples/provisioning-symmetrickey-sample/src/main/java/samples/com/microsoft/azure/sdk/iot/ProvisioningSymmetricKeySample.java

Python SDK has provisioning example here but they doesn't have symmetric key example with group enrollment.
https://github.com/Azure/azure-iot-sdk-python/tree/master/provisioning_device_client/samples

Also i don't see `SYMMETRIC_KEY` enum defined in the SDK but instead `UNKNOWN` is defined.
https://github.com/Azure/azure-iot-sdk-python/blob/master/provisioning_device_client/provisioning_device_client.py#L20

It _seems_ C SDK supports provisioning device with symmetric key
https://github.com/Azure/azure-iot-sdk-c/blob/499744e6a75fcf7cf3be1eaf2946760bab410e28/provisioning_client/devdoc/using_provisioning_client.md#provisioning-samples

Can someone confirm whether the latest Python SDK supports provisioning device with group enrollment and symmetric key or not and whether the example exists if it's supported?

**Comment by taak77** [comment]
Anyone has any information on this? @pierreca?

**Comment by cartertinney** [comment]
This feature was not implemented for the Python SDK V1. We are no longer adding additional features to this SDK.

However, the Python SDK V2 (https://github.com/Azure/azure-iot-sdk-python-preview), which is currently in preview does have an implementation of this feature, and it will be included in our next pip release, around the end of the month.

Note that since V2 is a preview SDK, the APIs are subject to change until we do a General Availability (GA) release.

**Comment by taak77** [comment]
@cartertinney thanks for pointing me to V2 SDK, I tested it and confirmed the functionality I've asked works with V2. I'll close the issue.

**Comment by az-iot-builder-01** [comment]
@taak77, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
