### ISSUE TITLE
Unexpected error IoTHubRegistryManager.create_device, IoTHubRegistryManagerResult.HTTPAPI_ERROR

### ISSUE THREAD

**Issue by mibarg** [Azure/azure-iot-sdk-python#268]
- **OS and version used:** macOS 10.15

- **Python runtime used:** python 3.7

- **SDK version used:** release_2019_01_03

# Description of the issue:
I'm trying to follow the guide [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#build-the-azure-iot-hub-sdks-for-python-on-mac-os) to compile the sdk for macOS. I managed to build the SDK successfully, but now I'm getting the error below. After searching through your issues, I found a proposed solution to update curl but I'm already using the latest version. Appreciate your help.

# Code sample exhibiting the issue:
I'm running the service example _iothub_registrymanager_sample.py_.

# Console log of the issue:
(venv) $ python iothub_registrymanager_sample.py 

Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]
IoT Hub Service Client for Python

Starting the IoT Hub Service Client Registry Manager Python sample...
    Connection string = <CONNECTION_STRING>
    Device ID         = <DEVICE_ID>
Error: Time:Thu Apr  4 16:38:14 2019 File:<path>/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: SSL connect error

Error: Time:Thu Apr  4 16:38:14 2019 File:<path>/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Thu Apr  4 16:38:14 2019 File:<path>/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Thu Apr  4 16:38:14 2019 File:<path>/azure-iot-sdk-python/c/iothub_service_client/src/iothub_registrymanager.c Func:sendHttpRequestCRUD Line:1346 HTTPAPIEX_SAS_ExecuteRequest failed
Unexpected error IoTHubRegistryManager.create_device, IoTHubRegistryManagerResult.HTTPAPI_ERROR

**Comment by pierreca** [comment]
The curl issue usually manifests itself with an out of memory error. which version of curl are you using?
Also, out of curiosity, why not use the precompiled packages for mac?

**Comment by mibarg** [comment]
I'm using curl 7.64.1.
I wasn't aware that you had a precompiled version. I've tried now (using pip in a new virtualenv) and I'm getting the same error.

**Comment by mibarg** [comment]
I've noticed by running `which curl` that I was using the default macOS version of curl (version 7.54.0), not the home-brew installed version (7.64.1). However, changing my path and rerunning the sample resulted in the same error.

**Comment by pierreca** [comment]
@mibarg changing the `PATH` value only change which executable gets picked up by the terminal not necessarily which library gets picked up by a process trying to load it. 

can you try setting your `DYLD_LIBRARY_PATH` value to wherever libcurl is installed (it's `/usr/local/lib` on my machine)? I managed to repro the error you're seeing and get rid of it by doing this so hopefully it'll work for you too.

**Comment by mibarg** [comment]
Thank you for your help. I'm getting a different error now:

~~~
(venv) $ python iothub_registrymanager_sample.py
Traceback (most recent call last):
  File "sample.py", line 6, in <module>
    import iothub_service_client
  File "<path>/venv/lib/python3.7/site-packages/iothub_service_client/__init__.py", line 1, in <module>
    from .iothub_service_client import *
ImportError: dlopen(<path>/venv/lib/python3.7/site-packages/iothub_service_client/iothub_service_client.so, 2): Symbol not found: __cg_jpeg_resync_to_restart
  Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
  Expected in: /usr/local/lib/libJPEG.dylib
 in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO
~~~

**Comment by pierreca** [comment]
I gotta say I'm stumped then. I just tried this exact setup on my Mac, with exactly this version of curl, and it worked...

I'm not sure if this could interfere and how to fix it:
> curl is keg-only, which means it was not symlinked into /usr/local,
because macOS already provides this software and installing another version in
parallel can cause all kinds of trouble.

I'm also wondering if this problem could happen because of something else than curl. can you paste the latest error you're seeing as well as the output of `brew list`?

I really don't want to leave you hanging but I'm running out of ideas...

**Comment by mibarg** [comment]
Thanks again for your help.
I could try completely removing everything I have installed through brew, and then reinstall. Let me know if you think that might help.

My brew list
~~~
(venv) $ brew list
azure-cli	cmake		ghostscript	icu4c		libevent	libogg		nghttp2		pcre2		sdl2		webp
boost		curl		giflib		jansson		libffi		libpng		openldap	pkg-config	sdl2_image	xz
boost-python3	freetype	git		jemalloc	libidn		libssh2		openssl		python		sdl2_mixer
brotli		gdbm		glib		jpeg		libmetalink	libtiff		ossp-uuid	readline	sdl2_ttf
c-ares		gettext		gstreamer	libev		libmodplug	libvorbis	pcre		rtmpdump	sqlite
~~~

Latest error:
~~~
(venv) $ python iothub_registrymanager_sample.py 

Python 3.7.3 (default, Mar 27 2019, 09:23:15) 
[Clang 10.0.1 (clang-1001.0.46.3)]
IoT Hub Service Client for Python

Starting the IoT Hub Service Client Registry Manager Python sample...
Connection string = <CONNECTION_STRING>
Device ID = <DEVICE_ID>
Error: Time:Wed Apr 10 09:05:41 2019 File:/Users/trashcan/release/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Couldn't resolve host name

Error: Time:Wed Apr 10 09:05:41 2019 File:/Users/trashcan/release/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:603 (result = HTTPAPI_OPEN_REQUEST_FAILED)
Error: Time:Wed Apr 10 09:05:41 2019 File:/Users/trashcan/release/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
Error: Time:Wed Apr 10 09:05:41 2019 File:/Users/trashcan/release/azure-iot-sdk-python/c/iothub_service_client/src/iothub_registrymanager.c Func:sendHttpRequestCRUD Line:1346 HTTPAPIEX_SAS_ExecuteRequest failed
Unexpected error IoTHubRegistryManager.create_device, IoTHubRegistryManagerResult.HTTPAPI_ERROR
~~~

**Comment by pierreca** [comment]
@mibarg "trashcan" is the affectionate name we give our Mac build machine (one of those cylindrical mac pros). nothing to see here :) 

What I do see however is that the error has changed: it now says
```
Func:HTTPAPI_ExecuteRequest Line:601 curl_easy_perform() failed: Couldn't resolve host name
```

this means that for some reason, the DNS resolver of the machine this code is running on cannot find the IoT Hub instance you're trying to connect to. 

can you try to ping your hub to see if it resolves correctly? (it won't respond to pings but it should resolve)? At that point it's more likely to be a configuration issue than an actual bug.

**Comment by mibarg** [comment]
Hi, I was using an old connection string. After fixing it, I'm getting the original error again.
I'll try to reinstall everything and see if that helps.

**Comment by capfish** [comment]
I was having this same issue also with 10.15, 3.7, and 2019_01_03 and these are the steps that I took to get it working, many of it was inspired from this link https://stackoverflow.com/questions/49625315/httpapi-error-when-creating-device-identity-with-local-python-on-azure-iot-hub

- If you don't already install [brew](https://brew.sh/).
- Install boost and curl

        brew install boost-python3
        brew install curl
        echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile
        echo 'export PATH="/usr/local/opt/curl/bin:$PATH"' >> ~/.bash_profile

- Set up linker and C++ libraries to point to the brew installed ones.  From inside your pipenv/virtualenv

        export LDFLAGS="-L/usr/local/opt/curl/lib -L/usr/local/opt/openssl/lib"
        export CPPFLAGS="-I/usr/local/opt/curl/include -I/usr/local/opt/openssl/include"

- Then outside of your project clone the [azure-iothub-python-sdk](https://github.com/Azure/azure-sdk-for-python)

         git clone --recurse-submodules https://github.com/Azure/azure-sdk-for-python.git
         git checkout remotes/origin/update-146
  You'll be in a detached head state, but that's ok we aren't going to commit anything to this repo
  
- Edit `azure-iothub-sdk-python/build_all/mac/build.sh` line 10 should be changed to `PYTHON_VERSION=3.7` line 50 should be `python_prefix=$(python-config --prefix)` (remove the 3)
- Then build the library

        cd azure-iothub-sdk-python/build_all/mac/build.sh
        ./build.sh
  This should put `iothub_service_client.so` in `azure-iothub-sdk-python/service/samples`
- Replace your pip installed `iothub_service_client.so` with the built one

        cp azure-iothub-sdk-python/service/samples/iothub_service_client.so /path/to/virtualenv/lib/python3.7/site-packages/iothub_service_client/iothub_service_client.so
  If you don't know the path to your virtualenv you can find it via (be sure you're in your virtualenv)

        pip show azure-iothub-service-client

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@mibarg, @capfish, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
