### ISSUE TITLE
Unauthorised issue with X.509 certificates and MQTT protocol with python client

### ISSUE THREAD

**Issue by ganeshbio** [Azure/azure-iot-sdk-python#271]
- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

I am trying to use python client for connecting to IOTHUB using x.509 authentication.  I am getting unauthorized error. I tried with Java SDK and it works fine for both MQTT and AMQP. I also validated certificates by writing simple MQTT client and this also works fine.  How to pass certificated in iothub_client_sample_x509.py? Is there any specfic format?
# Code sample exhibiting the issue:

# Console log of the issue:

Python 2.7.10 (default, Feb 22 2019, 21:17:52) 
[GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
IoT Hub for Python SDK Version: 1.4.6
Starting the IoT Hub Python sample...
    Protocol MQTT
    Connection string=HostName=terraform.azure-devices.net;DeviceId=megadevice1;x509=true
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/c-utility/pal/tlsio_options.c Func:set_and_validate_x509_type Line:34 Unsupported x509 type: 2
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/c-utility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_setoption Line:633 Failed tlsio_options_set
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2271 unable to IoTHubTransport_SetOption
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SetOption Line:1620 IoTHubClientCore_LL_SetOption failed
IoTHub Client SetOption failed with result: 1Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/c-utility/pal/tlsio_options.c Func:set_and_validate_x509_type Line:34 Unsupported x509 type: 2
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/c-utility/pal/ios-osx/tlsio_appleios.c Func:tlsio_appleios_setoption Line:633 Failed tlsio_options_set
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_SetOption Line:2271 unable to IoTHubTransport_SetOption
Error: Time:Wed May  8 22:34:30 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core.c Func:IoTHubClientCore_SetOption Line:1620 IoTHubClientCore_LL_SetOption failed
IoTHub Client SetOption failed with result: 1IoTHubClient sending 5 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [3] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [4] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: BUSY
-> 22:34:30 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: terraform.azure-devices.net/megadevice1/?api-version=2017-11-08-preview&DeviceClientType=python%2f1.4.6%20iothubclient%2f1.2.12%20(Darwin%3b%20x86_64) | CLEAN: 0
<- 22:34:32 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Wed May  8 22:34:32 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1617 Connection Not Accepted: 0x5: Not Authorized
-> 22:34:32 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: terraform.azure-devices.net/megadevice1/?api-version=2017-11-08-preview&DeviceClientType=python%2f1.4.6%20iothubclient%2f1.2.12%20(Darwin%3b%20x86_64) | CLEAN: 0
<- 22:34:33 CONNACK | SESSION_PRESENT: false | RETURN_CODE: 0x5
Error: Time:Wed May  8 22:34:33 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothubtransport_mqtt_common.c Func:mqtt_operation_complete_callback Line:1617 Connection Not Accepted: 0x5: Not Authorized
-> 22:34:34 CONNECT | VER: 4 | KEEPALIVE: 240 | FLAGS: 128 | USERNAME: terraform.azure-devices.net/megadevice1/?api-version=2017-11-08-preview&DeviceClientType=python%2f1.4.6%20iothubclient%2f1.2.12%20(Darwin%3b%20x86_64) | CLEAN: 0
^CIoTHubClient sample stopped
Error: Time:Wed May  8 22:34:34 2019 File:/Users/ganesh/projects/iot/azure-iot-sdk-python/c/iothub_client/src/iothub_client_core_ll.c Func:IoTHubClientCore_LL_GetLastMessageReceiveTime Line:2166 result = IOTHUB_CLIENT_INDEFINITE_TIME
No message received

**Comment by pierreca** [comment]
@ganeshbio thanks for filing this issue.
the problem is that by default, our packages are built with the built-in TLS implementation of MacOS and the C SDK (which the Python SDK uses) does not support x509 with this specific TLS stack.

The way to get around this problem is to recompile the SDK to use openssl.
The instructions to rebuild the SDK from scratch are here:
https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md

In order to rebuild the SDK with openssl, you'd need to modify the [build.sh script](https://github.com/Azure/azure-iot-sdk-python/blob/master/build_all/mac/build.sh) to add `-Duse_openssl=ON` on the [cmake command line 59](https://github.com/Azure/azure-iot-sdk-python/blob/master/build_all/mac/build.sh#L59)

**Comment by ganeshbio** [comment]
Thanks for your quick reply!
It worked for me!

**Comment by az-iot-builder-01** [comment]
@ganeshbio, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by cbauer10** [comment]
@pierreca Any update on how to do this with the current version of the SDK?  The workaround of building it with OpenSSL does not work with Xcode 13 and OpenSSL 3.0.1.
