### ISSUE TITLE
Python register client device X509 authentication

### ISSUE THREAD

**Issue by protatremy** [Azure/azure-iot-sdk-python#272]
- Ubuntu 16.04
- Python 3.6
- SDK version used:
azure-iot-provisioning-device-client==1.4.6

# Description of the issue:
Hello, I'm using SDK to register devices with a generated certificate issued from a intermediate certificate.
When I try to register the device, using the sample "provisioning_device_sample.py", I cannot setup the new certificate used.
I'm trying using:  
```
provisioning_client = ProvisioningDeviceClient(GLOBAL_PROV_URI, ID_SCOPE, SECURITY_DEVICE_TYPE, PROTOCOL)
provisioning_client.set_option("x509certificate", X509_CERTIFICATE)
provisioning_client.set_option("x509privatekey", X509_PRIVATEKEY)
```
But the code execution returns:
unable to set x509 options more than once:

```
Error: Time:Fri May 10 09:40:24 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:tlsio_openssl_setoption Line:1505 unable to set x509 options more than once
Error: Time:Fri May 10 09:40:24 2019 File:/usr/sdk/src/c/deps/uhttp/src/uhttp.c Func:uhttp_client_open Line:1035 Failed setting x509 certificate
Error: Time:Fri May 10 09:40:24 2019 File:/usr/sdk/src/c/provisioning_client/src/prov_transport_http_client.c Func:create_connection Line:619 failed to open http client
Error: Time:Fri May 10 09:40:24 2019 File:/usr/sdk/src/c/provisioning_client/src/prov_transport_http_client.c Func:prov_transport_http_open Line:764 Failure creating http connection
Error: Time:Fri May 10 09:40:24 2019 File:/usr/sdk/src/c/provisioning_client/src/prov_device_ll_client.c Func:Prov_Device_LL_Register_Device Line:860 Failure establishing  connection
Unexpected error ProvisioningDeviceClient.register__device, ProvisioningDeviceClientResult.ERROR
```

Looking through the SDK C code it seems that the interface class allowing to set X509 details is not implemented, and the options are hardcoded?

Can you provide a solution?

**It seems that it is not possible to set X509 options with python SDK**.

**Comment by protatremy** [comment]
linked to:
https://github.com/Azure/azure-iot-sdk-python/issues/112

**Comment by pierreca** [comment]
@protatremy we've greatly simplified our client library and ported it to a full python implementation that supports what you're asking for.
please see https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/register_x509.py and let us know if that helps?

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@protatremy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by protatremy** [comment]
The V2 fix the issue thanks
