### ISSUE TITLE
send message reports OK in spite of random SharedAccessKeyName and device id

### ISSUE THREAD

**Issue by esidebo** [Azure/azure-iot-sdk-python#273]
Running the following on Mac using Docker:
- **OS and version used:** <VERSION> Ubuntu 16.04

- **Python runtime used:** <VERSION> 3.5.2

- **SDK version used:** <VERSION> 1.4.4

# Description of the issue:
I have a problem in my application, messages from the cloud does not seem to reach my device. I ran iothub_messaging_sample.py as a base test. However, I don't understand what this script is supposed to test exactly. I send messages with IoTHubMessaging::send_async() and the send_complete_callback is called ("messagingResult : OK") for all messages, regardless of

- value of `SharedAccessKeyName` inside the `CONNECTION_STRING` 
- value of the `DEVICE_ID`

i.e. I can put anything for these values. I'm surprised to get OK when putting a device id that doesn't exist. Is this expected?

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@esidebo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
