### ISSUE TITLE
azure-iot-sdk-python dockerfiles reference deprecated resin repos on Dockerhub

### ISSUE THREAD

**Issue by toolboc** [Azure/azure-iot-sdk-python#274]
# Description of the issue:
azure-iot-sdk-python dockerfiles for armv7l platforms are using deprecated base images provided by [resin](https://hub.docker.com/u/resin/) on Dockerhub.  These should be updated to support newer images provided by [balenalib](https://hub.docker.com/u/balenalib/).

# Code sample exhibiting the issue:
1. [Dockerfile_Rasp.build.armv7l_jessie](https://github.com/Azure/azure-iot-sdk-python/blob/master/dockerfiles/Dockerfile_Rasp.build.armv7l_jessie#L1)

> FROM resin/raspberrypi3-python:2.7.13

![image](https://user-images.githubusercontent.com/2018336/59621011-eed68680-90f3-11e9-9751-cb4448f97228.png)

This image reference should be updated to:
`balenalib/raspberrypi3-python:2.7.13`

2.[Dockerfile_Rasp.build.armv7l_stretch](https://github.com/Azure/azure-iot-sdk-python/blob/master/dockerfiles/Dockerfile_Rasp.build.armv7l_stretch#L1)

> FROM resin/raspberrypi3-debian:stretch

![image](https://user-images.githubusercontent.com/2018336/59620937-b6cf4380-90f3-11e9-9e5f-28b0fb1b0a83.png)

This image reference should be updated to:
`balenalib/raspberrypi3-debian:stretch`

**Comment by pierreca** [comment]
@toolboc thanks !! turns out we may be pushing even more changes given we're going more public with the new version of the SDK that doesn't require to be rebuilt or specific versions of boost. we may be able to greatly simplify which versions of docker containers we use.

I'm not sure why the PR #275 was closed (probably because of what I did to branches) but we'll see if we can pull this manually.

**Comment by pierreca** [comment]
fix was merged to the v1-deprecated branch. thanks!

**Comment by az-iot-builder-01** [comment]
@toolboc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
