### ISSUE TITLE
How to notify IoT Hub of a completed file upload?

### ISSUE THREAD

**Issue by openedhardware** [Azure/azure-iot-sdk-python#277]
I am uploading a file blob using the sample code - https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_file_upload.py

But how can I notify IoT Hub of a completed file upload like this? 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-file-upload#notify-iot-hub-of-a-completed-file-upload

**Comment by openedhardware** [comment]
![image](https://user-images.githubusercontent.com/16890683/61331644-d40f4300-a854-11e9-95a3-4f7fa26919d5.png)

Closing now... :)

**Comment by az-iot-builder-01** [comment]
@openedhardware, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
