### ISSUE TITLE
Q: Python-based device provisioning with Custom HSM

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python#278]
I tried to set up device group enrollment using IoT Python SDK, but I can't provision more than one device in such way. 
The reason seems to be that the current Python-based provisioning uses the library provisioning_device_client.so, which, in turn, is set to use _hsm_client_riot.c_ for device provisioning.
In IoT C SDK there is an option to use Custom HSM (with some steps to rebuild the libraries to use custom HSM). Is there a way to integrate it into Python option?

**Comment by bukarev** [comment]
Apparently it's a known problem without no good answer in the existing SDK. I should rather switch to the new version preview.

**Comment by az-iot-builder-01** [comment]
@bukarev, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
