### ISSUE TITLE
Problems running tutorial on raspberry pi

### ISSUE THREAD

**Issue by wennemer** [Azure/azure-iot-sdk-python#279]
hanks for IoT Hub tutorial as well as mattjhayes/ Issue #11406

But i still have a problem running the sample.

First errror:
ImportError: libboost_python-py27.so.1.62.0: cannot open shared object file: No such file or directory

Linked it:
ln -s libboost_python-py27.so.1.67.0 libboost_python-py27.so.1.62.0

Next error:
ImportError: /usr/lib/x86_64-linux-gnu/libcurl.so.4: version `CURL_OPENSSL_3' not found

Workaround:
sudo apt install libcurl3 python-pip

not working: libcurl4 (7.64.-0-4) is installed

I am a newbie.
Would be nice, if someone could help me!

**Comment by wennemer** [comment]
Problem solved!
Recompiling and manual copying to destination folder.

**Comment by az-iot-builder-01** [comment]
@wennemer, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
