### ISSUE TITLE
Error when using .so: “wrong ELF class: ELFCLASS64” on 32-bit machine

### ISSUE THREAD

**Issue by mjohngreene** [Azure/azure-iot-sdk-python#280]
Using Python 2.7.15 Ubuntu 18.04.2 on a 64-bit machine to build per instructions at https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#build-the-azure-iot-hub-sdks-for-python-on-linux, we get this error when running the resultant .so on a 32-bit Yocto machine running Python 2.7.12.

Per this post: 
https://stackoverflow.com/questions/216000/gcc-error-wrong-elf-class-elfclass64?rq=1, I imagine the build can be done with a GCC flag. Simply using "-m32" when running ./build.sh, however, did not work.

I suspect I could also use/change some sort of configuration parameter. However, I can not find anything obvious to change in the SDK.

More specifically, the error is: 'ImportError: /home/root/build_folder/iothub_client.so: wrong ELF class: ELFCLASS64'

**Comment by pierreca** [comment]
@mjohngreene Maybe a bit of good news here, but we've realized some time ago already that rebuilding the SDK is a pain, so we've rewritten most of it in pure python - hopefully, if what you're after is the device SDK, what we just pushed to the master branch and the corresponding pip package should be a much smoother experience for you.

if what you're after is the service sdk, we still have work ahead of us and will be posting more info during the months of september and october.

**Comment by mjohngreene** [comment]
Thanks, @pierreca.  Great news that the improved Python SDK will not require cross-compiling.  Should save a lot of headaches.  And, yes, the device SDK is what we are looking for.  We will proceed with the latest pushed version and provide feedback, open issues, etc. accordignly.  Thanks again for the feedback/guidance.

**Comment by pierreca** [comment]
seems like this will be addressed with v2 - closing.

**Comment by az-iot-builder-01** [comment]
@mjohngreene, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
