### ISSUE TITLE
Q: any way to send c2d message via REST?

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python#281]
I've got a requirement to be able to send a c2d message, and my sender can only support REST API.

Apparently [IoT Hub REST](https://docs.microsoft.com/en-us/rest/api/iothub/) doesn't support this functionality, so I'm trying to package it into an Azure serverless function using this Python SDK and available via REST.

I've picked the sending part of my code from the samples provided with this SDK, and added them to the HttpTrigger function template, here's what I have:
```
def open_complete_callback(context):
    logging.info( 'open_complete_callback called with context: {0}'.format(context) )

def send_complete_callback(context, messaging_result):
    context = 0
    logging.info( 'send_complete_callback called with context : {0}'.format(context) )
    logging.info( 'messagingResult : {0}'.format(messaging_result) )

def main(req: func.HttpRequest) -> func.HttpResponse:
    logging.info('Python HTTP trigger function processed a request.')
    [extract deviceid and payload parameters from the request]
    connStr = "my IoT Hub connection string"
    iothub_messaging = IoTHubMessaging(connStr)
    iothub_messaging.open(open_complete_callback,0)

    message = IoTHubMessage(bytearray(payload, 'utf8'))
    iothub_messaging.send_async(deviceid, message, send_complete_callback, 0)
    return func.HttpResponse("done")
```

When I try to run it locally I see a lot of errors like these:
```
[8/1/19 11:19:06 PM] Error: Time:Thu Aug  1 19:19:05 2019 File:/home/osboxes/v0/azure-iot-sdk-python/c/c-utility/adapters/lock_pthreads.c Func:Lock Line:50 pthread_mutex_lock failed.
[8/1/19 11:19:06 PM] Error: Time:Thu Aug  1 19:19:05 2019 File:/home/osboxes/v0/azure-iot-sdk-python/c/iothub_service_client/src/iothub_messaging.c Func:ScheduleWork_Thread Line:63 Lock failed, shall retry
```

My guess is that the callback function gets called after the program has actually completed. Is there any way to avoid that? Like, running send_async without callback function, or making the main() function to wait for callback to complete -- so far I couldn't make either of these workarounds work, though.

**Comment by az-iot-builder-01** [comment]
@bukarev, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
