### ISSUE TITLE
ERROR: "python SimulatedDevice.py" 

### ISSUE THREAD

**Issue by hanyun2019** [Azure/azure-iot-sdk-python#283]
Python 3.7.3 error:

$ python SimulatedDevice.py
Traceback (most recent call last):
  File "SimulatedDevice.py", line 11, in <module>
    import iothub_client
  File "/Users/user/anaconda3/lib/python3.7/site-packages/iothub_client/__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: dlopen(/Users/user/anaconda3/lib/python3.7/site-packages/iothub_client/iothub_client.so, 2): Library not loaded: /usr/local/opt/boost-python3/lib/libboost_python37-mt.dylib
  Referenced from: /Users/user/anaconda3/lib/python3.7/site-packages/iothub_client/iothub_client.so
  Reason: image not found

**Comment by pierreca** [comment]
@hanyun2019 please see this section of the readme:
https://github.com/azure/azure-iot-sdk-python#important-installation-notes---dealing-with-importerror-issues

Also: we're coming up with a new version of the SDK that will make things a lot easier. if at all possible, i would strongly encourage you to look at https://github.com/azure/azure-iot-sdk-python-preview which will be merged in this repository within the next few days.

**Comment by hanyun2019** [comment]
Thanks a lot!

Pierre Cauchois <notifications@github.com> 于2019年8月21日周三 上午7:44写道：

**Comment by pierreca** [comment]
closing as probably answered

**Comment by az-iot-builder-01** [comment]
@hanyun2019, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
