### ISSUE TITLE
Assigning child devices programmatically

### ISSUE THREAD

**Issue by taak77** [Azure/azure-iot-sdk-python#286]
Is [assigning child devices](https://docs.microsoft.com/en-us/azure/iot-edge/offline-capabilities#assign-child-devices) available in this SDK or [V1](https://github.com/Azure/azure-iot-sdk-python) SDK?

It looks like Java SDK has implemented the functionality [here](https://github.com/Azure/azure-iot-sdk-java/issues/494)

cc @pierreca @olivakar

**Comment by pierreca** [comment]
Given it's already september, this issue is overdue for an update.
The work has started and @zolvarga and @olivakar will be building the v2 of the service sdk which will support that. expect to see more code by the end of the month.

**Comment by jebrando** [comment]
@taak77 the latest service SDK now supports assigning a child property through the device_scope property when you create a device.  We are creating a sample for this, but in the mean time you can give it a try.  If you have any issue with this please feel free to open a new issue.

**Comment by az-iot-builder-01** [comment]
@taak77, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by amit12cool** [comment]
When this will be available for Nodejs?
