### ISSUE TITLE
 SSL channel closed in decode_ssl_received_bytes

### ISSUE THREAD

**Issue by haimiko** [Azure/azure-iot-sdk-python#288]
I'm using the SimulatedDevice.py sample.  It was working find for awhile, then recently I cannot get more than a few data points uploaded ok before I get the following error:

```
Error: Time:Fri Aug 30 17:06:46 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Fri Aug 30 17:06:46 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Error: Time:Fri Aug 30 17:07:01 2019 File:/usr/sdk/src/c/c-utility/src/uws_client.c Func:uws_client_close_async Line:1749 close has been called when already CLOSED

```

**Comment by jebrando** [comment]
@haimiko we have deprecated the v1 python SDK, the new v2 SDK is a pure python implementation that is more stable and works better, if you can try this on the new python device SDK with the same sample [SimulatedDevice.py](https://github.com/Azure-Samples/azure-iot-samples-python/blob/master/iot-hub/Quickstarts/simulated-device/SimulatedDevice.py) we'd love to hear your feedback.

**Comment by az-iot-builder-01** [comment]
@haimiko, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
