### ISSUE TITLE
Twin string format errors

### ISSUE THREAD

**Issue by cartertinney** [Azure/azure-iot-sdk-python#289]
Received an email from a customer with the following issue:

"It seems the get_twin() method does not preserve the double quotes around the returned json.  This makes it difficult to work with json.loads(twin) as this errors out giving the expected error of “double quotes expected…etc.”"

**Comment by ryanbedford** [comment]
I don't think this is an issue.  What is returned is a dict and NOT a json string as mistakenly thought.  Using verion 1 I would get the twin and save the data straight to a file as is, valid json.  In version 2 the get_twin() returns a dict that can be used as is or a json.dumps(twin) will save valid json string data with double quotes.

**Comment by az-iot-builder-01** [comment]
@ryanbedford, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
