### ISSUE TITLE
enhancement: minimal download-zip

### ISSUE THREAD

**Issue by hassler** [Azure/azure-iot-sdk-python#29]
# Description of the issue:

Recursive download of this repo takes a long time. It would be fantastic if there was a possibility download a zip that includes all submodules, and no .git-directories.

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by tameraw** [comment]
@hassler - Thanks for raising this issue. Last I checked, GitHub does not support downloading a zip that include the submodules. You would have to download the zip for the Python repo and each submodule separately if you want to avoid cloning recursively.
