### ISSUE TITLE
facing errors while sending cloud to device messages

### ISSUE THREAD

**Issue by neha-s-deshpande** [Azure/azure-iot-sdk-python#291]
hi, 
system info-
ubuntu 16.04
azure-iothub-service-client==1.4.6

while running the code I am getting error-

> <iothub_service_client.iothub_service_client.IoTHubServiceClientAuth object at 0x7f82b264af10>
--- None
Sending message: 0
Error: Time:Tue Sep  3 15:20:52 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:on_sasl_frame_received_callback Line:909 SASL handshake failed with code 02
Error: Time:Tue Sep  3 15:20:52 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Tue Sep  3 15:20:52 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:on_underlying_io_error Line:243 Error callback received in unexpected state
Error: Time:Tue Sep  3 15:20:52 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Sending message: 1
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/iothub_service_client/src/iothub_messaging_ll.c Func:IoTHubMessaging_LL_Send Line:1483 Messaging is not opened - call IoTHubMessaging_LL_Open to open
Unexpected error : IoTHubMessaging.send_async, IoTHubMessagingResult.ERROR
send_complete_callback called with context : 0
messagingResult : OK
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:saslclientio_send_async Line:1181 send called while not open
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/uamqp/src/connection.c Func:on_bytes_encoded Line:268 Cannot send encoded bytes
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/uamqp/src/connection.c Func:on_bytes_encoded Line:272 xio_close failed
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Tue Sep  3 15:21:12 2019 File:/usr/sdk/src/c/uamqp/src/connection.c Func:connection_close Line:1437 xio_close failed
Traceback (most recent call last):
  File "send_c2d_msg1.py", line 80, in <module>
    iothub_messaging_sample_run()
  File "send_c2d_msg1.py", line 57, in iothub_messaging_sample_run
    iothub_messaging.send_async(DEVICE_ID, message, send_complete_callback, i)
iothub_service_client.iothub_service_client.IoTHubMessagingError: IoTHubMessaging.send_async, IoTHubMessagingResult.ERROR

> 

is this the error in library or on python code side?
is there any workaround?
I have tried adding **sleep** before using **iothub_messaging.close()**, but no use.

also what will be the approximate date you are releasing service-client support?

**Comment by neha-s-deshpande** [comment]
python version: 3.5.2


the code is:


> 

from time import sleep
from iothub_service_client import IoTHubMessaging, IoTHubMessage, IoTHubError

OPEN_CONTEXT = 0
FEEDBACK_CONTEXT = 1
MESSAGE_COUNT = 1
AVG_WIND_SPEED = 10.0
MSG_TXT = "{\"service client sent a message\": %.2f}"

CONNECTION_STRING = "xxxxxxxx"
DEVICE_ID = "xxxxxx"

def open_complete_callback(context):
    print ( 'open_complete_callback called with context: {0}'.format(context) )


def send_complete_callback(context, messaging_result):
    context = 0
    print ( 'send_complete_callback called with context : {0}'.format(context) )
    print ( 'messagingResult : {0}'.format(messaging_result) )


def iothub_messaging_sample_run():
    try:
        iothub_messaging = IoTHubMessaging(CONNECTION_STRING)

        iothub_messaging.open(open_complete_callback, OPEN_CONTEXT)

        for i in range(0, MESSAGE_COUNT):
            print ( 'Sending message: {0}'.format(i) )
            msg_txt_formatted = MSG_TXT % (AVG_WIND_SPEED + (10))
            message = IoTHubMessage(bytearray(msg_txt_formatted, 'utf8'))

            # optional: assign ids
            message.message_id = "message_%d" % i
            message.correlation_id = "correlation_%d" % i
            # optional: assign properties
            prop_map = message.properties()
            prop_text = "PropMsg_%d" % i
            prop_map.add("Property", prop_text)
            sleep(20)
            iothub_messaging.send_async(DEVICE_ID, message, send_complete_callback, i)

        try:
            # Try Python 2.xx first
            raw_input("Press Enter to continue...\n")
        except:
            pass
            # Use Python 3.xx in the case of exception
            input("Press Enter to continue...\n")

        iothub_messaging.close()

    except IoTHubError as iothub_error:
        print ( "Unexpected error {0}" % iothub_error )
        return
    except KeyboardInterrupt:
        print ( "IoTHubMessaging sample stopped" )

> 


if I put MESSAGE_COUNT as 1, I get above error. 
but if take it as >1 I get different error as:

> 
Sending message: 0
Sending message: 1
Error: Time:Wed Sep  4 10:53:21 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:on_sasl_frame_received_callback Line:909 SASL handshake failed with code 02
Error: Time:Wed Sep  4 10:53:21 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:decode_ssl_received_bytes Line:797 SSL channel closed in decode_ssl_received_bytes.
Error: Time:Wed Sep  4 10:53:21 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:on_underlying_io_error Line:243 Error callback received in unexpected state
Error: Time:Wed Sep  4 10:53:21 2019 File:/usr/sdk/src/c/c-utility/adapters/tlsio_openssl.c Func:on_underlying_io_bytes_received Line:846 Error in decode_ssl_received_bytes.
Error: Time:Wed Sep  4 10:53:40 2019 File:/usr/sdk/src/c/iothub_service_client/src/iothub_messaging_ll.c Func:IoTHubMessaging_LL_Send Line:1483 Messaging is not opened - call IoTHubMessaging_LL_Open to open
Traceback (most recent call last):
  File "send_c2d_msg1.py", line 42, in iothub_messaging_sample_run
    iothub_messaging.send_async(DEVICE_ID, message, send_complete_callback, i)
iothub_service_client.iothub_service_client.IoTHubMessagingError: IoTHubMessaging.send_async, IoTHubMessagingResult.ERROR

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "send_c2d_msg1.py", line 66, in <module>
    iothub_messaging_sample_run()
  File "send_c2d_msg1.py", line 55, in iothub_messaging_sample_run
    print ( "Unexpected error {0}" % iothub_error )
TypeError: not all arguments converted during string formatting
Error: Time:Wed Sep  4 10:53:40 2019 File:/usr/sdk/src/c/c-utility/adapters/lock_pthreads.c Func:Lock Line:50 pthread_mutex_lock failed.
Error: Time:Wed Sep  4 10:53:40 2019 File:/usr/sdk/src/c/iothub_service_client/src/iothub_messaging.c Func:ScheduleWork_Thread Line:63 Lock failed, shall retry
Error: Time:Wed Sep  4 10:53:40 2019 File:/usr/sdk/src/c/c-utility/adapters/lock_pthreads.c Func:Lock Line:50 pthread_mutex_lock failed.
Error: Time:Wed Sep  4 10:53:40 2019 File:/usr/sdk/src/c/iothub_service_client/src/iothub_messaging.c Func:ScheduleWork_Thread Line:63 Lock failed, shall retry

>

**Comment by neha-s-deshpande** [comment]
does anyone know how to resolve it?
I am still facing the issue.

**Comment by neha-s-deshpande** [comment]
is it on sdk side or I am missing something?
Please guide me so that I will try to resolve the issue if it is from my side.

**Comment by neha-s-deshpande** [comment]
hi, I was able to resolve the issue. 
The key name for authentication is still hardcoded in python sdk in file iothub_messaging_ll.c
I followed this link 
[(https://github.com/Azure/azure-iot-sdk-c/commit/21a13bfa722227b0a950ffcd9e6965f500879850)](url)
and made changes accordingly. Now it is working fine.


but if the code is like:
auth_hndl = IoTHubServiceClientAuth(CONNECTION_STRING)
iothub_messaging = IoTHubMessaging(auth_hndl)

instead of 
iothub_messaging = IoTHubMessaging(CONNECTION_STRING)

then it gives segmentation fault error.

**Comment by jebrando** [comment]
The Python SDK now supports Cloud-to-device messaging. You can view the sample here. If you have any question please open an issue.

**Comment by az-iot-builder-01** [comment]
@neha-s-deshpande, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
