### ISSUE TITLE
Hub message routing on $body fails

### ISSUE THREAD

**Issue by LouanDuToitS3** [Azure/azure-iot-sdk-python#294]
Using the new v2 API, I am unable to route messages using the $body tag when sending module to module messages.

In the code I send messages as following:
```python
    def _send_message(self, message, output_name):
        """Create the message object and send to the requested output."""
        try:
            message_object = Message(message, content_encoding="utf-8", content_type="application/json")
            self._module_client.send_message_to_output(message_object, output_name)
        except Exception:
            self.logging_handler.exception("Exception sending message to output")
```

The message itself will be JSON serialised and here are some samples:
```
{'time': 1565009829.844609, 's_time': '2019-08-05T12:57:09', 'routing_key': 'tic_tock'}
{'time': 1565009829.844609, 's_time': '2019-08-05T12:57:09', 'routing_key': 'tic_knock'}
{'time': 1565009829.844609, 's_time': '2019-08-05T12:57:09', 'routing_key': 'tock'}
{'time': 1565009829.844609, 's_time': '2019-08-05T12:57:09', 'routing_key': 'tock_tic'}
{'time': 1565009829.844609, 's_time': '2019-08-05T12:57:09', 'routing_key': 'knock'}
```

The filter rules in my deployment manifest is:
```json
    "$edgeHub": {
      "properties.desired": {
        "routes": {
          "send-to-tic": "FROM /messages/modules/hubtester_send/outputs/output1 WHERE CONTAINS($body.routing_key, 'tic') INTO BrokeredEndpoint(\"/modules/hubtester_receive_tic/inputs/input1\")",
          "send-to-toc": "FROM /messages/modules/hubtester_send/outputs/output1 WHERE CONTAINS($body.routing_key, 'toc') INTO BrokeredEndpoint(\"/modules/hubtester_receive_toc/inputs/input1\")"
        },
        "schemaVersion": "1.0",
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 60
        }
      }
    },
```

Using the sample strings as listed above, none of the messages are delivered.

But, as a workaround, if I now change the code to use the messages "custom_properties", like this:
```python
    def _send_message(self, message, output_name, routing_key):
        """Create the message object and send to the requested output."""
        try:
            message_object = Message(message, content_encoding="utf-8", content_type="application/json")
            if routing_key is not None:
                message_object.custom_properties["routing_key"] = routing_key

            self._module_client.send_message_to_output(message_object, output_name)
        except Exception:
            self.logging_handler.exception("Exception sending message to output")
```

And then call the `send_message` method with the reouting_key I need, and with the following routing rules in my manifest:
```json
    "$edgeHub": {
      "properties.desired": {
        "routes": {
          "send-to-tic": "FROM /messages/modules/hubtester_send/outputs/output1 WHERE CONTAINS(routing_key, 'tic') INTO BrokeredEndpoint(\"/modules/hubtester_receive_tic/inputs/input1\")",
          "send-to-toc": "FROM /messages/modules/hubtester_send/outputs/output1 WHERE CONTAINS(routing_key, 'toc') INTO BrokeredEndpoint(\"/modules/hubtester_receive_toc/inputs/input1\")"
        },
        "schemaVersion": "1.0",
        "storeAndForwardConfiguration": {
          "timeToLiveSecs": 60
        }
      }
    },
```
Then all is fine.

I tried not using the "CONTAINS" filter and just a exact "plain =" match, but that did not work either.

I would like to use message body routing.

AB#7366698

**Comment by BertKleewein** [comment]
Thanks @LouanDuToitS3 , this is very useful.  I _think_ this is happening because of an extra stringification somewhere in our code, but I will need to trace through to verify this theory.

In other words, when you try to send a Python dictionary object that looks like this:
`{'time': 1565009829.844609, 's_time': '2019-08-05T12:57:09', 'routing_key': 'knock'}`

I think that our code is converting this into a string and actually sending a string that looks like this:
`"{\"time\": 1565009829.844609, \"s_time\": \"2019-08-05T12:57:09\", \"routing_key\": \"knock\"}"`

And, of course, it might be single quoted  inside or it might be double quoted and I don't think the escapes are in the bytestream, or at least I hope they're not, but I have to make sure.

I'll dig into it and let you know.

**Comment by LouanDuToitS3** [comment]
Hi @BertKleewein, I forgot to add to the origional post that in another part of the code I serialise the  JSON as following:
```python
bytearray(json.dumps(msg), "utf-8")
```
So it is a bytearray that is sent.

**Comment by BertKleewein** [comment]
I am able to make this work with 2.2.0.

My rule is: `FROM /messages/modules/testMod/outputs/telemetry  WHERE CONTAINS($body.routing_key,  "to") INTO BrokeredEndpoint("/modules/friendMod/inputs/github")`
I'm sending with:
```
payload = {"routing_key": "tic", "blah": str(uuid.uuid4())} 
msg = Message(bytearray(json.dumps(payload),"utf-8"))                                      
msg.content_type = "application/JSON"                                                           
msg.content_encoding = "utf-8"
client.send_message_to_output(msg, "telemetry")
```
If I do that, the message gets routed.  I'm not sure why it was broken before, but I suspect the content_type and content_encoding values were not properly getting encoded in the MQTT message.

**Comment by BertKleewein** [comment]
@ LouanDuToitS3 - I know that this is an old issue and I apologize for letting it sit for so long.  It seems to be working now.  Is this still an issue for you or may I close this?

**Comment by elhorton** [comment]
Closing this issue now due to lack of response-- if this is still an issue, please open a new issue. Thanks!

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @LouanDuToitS3, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
