### ISSUE TITLE
ModuleNotFoundError: No module named 'azure'

### ISSUE THREAD

**Issue by mjohngreene** [Azure/azure-iot-sdk-python#296]
Following the example, I run into this error when attempting to run the python3 (using Python 3.7.3) script per step 3 for linux (see https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device#linux).  

The specific output is: 
'''root@a60098b4bbd7:/# python3 azure-single-msg.py
Traceback (most recent call last):
  File "azure-single-msg.py", line 3, in <module>
    from azure.iot.device.aio import IoTHubDeviceClient
ModuleNotFoundError: No module named 'azure''''

**Comment by mjohngreene** [comment]
A little further digging/researching led me to look for the specific path referred to after "from" in the third line of the linked (see previous post above) instructions (ie, /azure/iot/device/aio).  Whereas I am using python3.7 per the instructions, all of the pertinent files appear to be in a python3.6 folder:

root@a60098b4bbd7:/# find / -iname "aio"
/usr/local/lib/python3.6/dist-packages/azure/iot/device/provisioning/aio
/usr/local/lib/python3.6/dist-packages/azure/iot/device/aio
/usr/local/lib/python3.6/dist-packages/azure/iot/device/iothub/aio

Apologies, but I am not familiar enough with Python to know whether that is an issue and am, therefore, providing this as additional background.

**Comment by mjohngreene** [comment]
The 3.6/3.7 difference was the source of the problem.  I'd installed azure-io-device before switching my  python3 from 3.6 to 3.7.  So, all of the install was done to the 3.6 folder structure.

I am closing this but wanted to provide verbiage as to how I resolved it in case anyone else encounters a similar problem.

**Comment by az-iot-builder-01** [comment]
@mjohngreene, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
