### ISSUE TITLE
yocto project python sdk

### ISSUE THREAD

**Issue by asebak** [Azure/azure-iot-sdk-python#3]
Is there a yocto layer for azure iot hub sdk?

**Comment by damonbarry** [comment]
We have built/run the C SDK on Yocto before. We've also installed/run the Python SDK (which depends on the C SDK) on various Linux distros. So this should not be a problem.

Does this answer your question, or is there something more specific you're wondering about?

Thanks!

**Comment by asebak** [comment]
Well I was looking for the source files of building it on yocto, basically the recipe files if you have them?
