### ISSUE TITLE
Is `urllib3 < 1.25` requirement still needed?

### ISSUE THREAD

**Issue by oerpli** [Azure/azure-iot-sdk-python#302]
In April 2019 the new release from urllib3 (1.25) was not supported by requests. Around this time, urllib3 has been added to the dependencies of azure-iot-device (v2) due to a bug in the pip-dep-resolver ([see here](https://github.com/Azure/azure-iot-sdk-python-preview/pull/83/commits/6c4d2ba0b41ac2743885daf4459f4238bb8c20cf)).

Since then, requests has been updated to support urllib3 1.25.3 ([here](https://github.com/psf/requests/pull/5092)), so I think the dependency on urllib3 could be relaxed from 
`>1.21.1,<1.25` to `>1.21.1,<1.26,!=1.25.1,!=1.25.0`.

**Comment by cartertinney** [comment]
This is correct. Thank you for bringing this to our attention. We will make this update.

**Comment by cartertinney** [comment]
Currently tracked in #305

**Comment by az-iot-builder-01** [comment]
@oerpli, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
