### ISSUE TITLE
MQTT error when sending from Docker container

### ISSUE THREAD

**Issue by mjohngreene** [Azure/azure-iot-sdk-python#304]
I created a Docker container (see https://gist.github.com/mjohngreene/3106778faf6ba3f4c36bd8bbe0c47367) using Ubuntu 18.04 to run the new Python-only (ie, no C wrapper necessary) SDK with Python 3.7.3.  I get the following error when running the provided sample script to send a message (shown at https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device#send-a-simple-telemetry-message):

root@bb5bf61b4c90:/# python3 msg.py
Sending message...
MQTTTransportStage: _on_mqtt_connection_failure called: Connection Refused: not authorised.
MQTTTransportStage(ConnectOperation): completing with error Connection Refused: not authorised.
SerializeConnectOpsStage(ConnectOperation): completing with error Connection Refused: not authorised.
EnsureConnectionStage(MQTTPublishOperation): completing with error Connection Refused: not authorised.
IoTHubMQTTConverterStage(SendD2CMessageOperation): completing with error Connection Refused: not authorised.
Unhandled exception in background thread
This may cause the background thread to abort and may result in system instability.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 113, in thread_proc
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/iothub/pipeline/iothub_pipeline.py", line 159, in on_complete
    sys.exit(1)
SystemExit: 1
MQTTTransportStage: _on_mqtt_disconnect called: The connection was refused.
MQTTTransportStage: disconnection was unexpected
Exception caught in background thread.  Unable to handle.
azure.iot.device.common.errors.ConnectionFailedError: The connection was refused. 

When implementing the previous version of the SDK on the device we use (a Conduit from Multitech), the MQTT configuration/functionality was fairly blackbox.  So, we are by no means experts on MQTT.  And it is hardly surprising that this piece of the SDK does not work “straight out of the box” on Docker.   

Any ideas as to the source of the error and/or how to resolve it in a Docker container?

**Comment by BertKleewein** [comment]
Hi @mjohngreene, the fact that it's running inside a container shouldn't matter.  I personally do most of my testing inside Docker containers, some of them based on 18.04 like yours is.

The three most likely causes of an auth failure are:
1. The connection string that you're using is invalid or outdated.
2, If you're using MQTT to connect to an IoT Edge device, you may need to specify a CA certificate or use a different factory method to create your DeviceClient or ModuleClient object. (I'm being purposely vague here -- if this is the case, we can dig deeper)
3.  The clock inside your container is skewed by more than a few minutes or just downright wrong.

**Comment by mjohngreene** [comment]
You are a hero, @BertKleewein!  I had presumed that it should work in a container but I am just moving up the curve on Docker and, therefore, could not be entirely sure.  Thinking it was a character or three off in my connection string that was the actual source of the problem.  I lost track of my containers, though, so I'm not positive about that either.  Regardless, I built a new one and the message got through to the IoT hub like a charm.  

Thanks for your help.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @mjohngreene, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
