### ISSUE TITLE
set_device_twin_callback function call

### ISSUE THREAD

**Issue by RaymondILei** [Azure/azure-iot-sdk-python#308]
Hello,

I have a question regarding the "set_device_twin_callback" function. It is part of the Azure Iot Hub Service SDK for python(I think I am using a older version)

I found the function at the step 5 of "Create the device App" in this documentation.
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-twin-getstarted
but it doesnt have much explantion of it. 

In the documentation, it shows that he function has 3 parameter,. 
I think I have to trigger the function using the Twin Device of a client in Azure IoT Hub, but I don't know the exact place on the Azure to trigger the function with the desired field in the payload. May someone please help me?
Thanks

**Comment by az-iot-builder-01** [comment]
@RaymondILei, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by cartertinney** [comment]
Update: Quickstart documents have been made public
