### ISSUE TITLE
AttributeError: module 'asyncio' has no attribute '_get_running_loop'

### ISSUE THREAD

**Issue by mjohngreene** [Azure/azure-iot-sdk-python#310]
Attempting to send a message to IoT Hub using the ["simple send message"](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/simple_send_message.py) script on a Multitech Conduit (ARM 32-bit), I get the following error:

```
admin@mtcdt:~$ python3 azure-single-msg.pySending message...
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/azure_iot_device-2.0.0rc10-py3.5.egg/azure/iot/device/common/asyncio_compat.py", line 18, in get_running_loop
    loop = asyncio.get_running_loop()
AttributeError: module 'asyncio' has no attribute 'get_running_loop'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "azure-single-msg.py", line 26, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 387, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 274, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step
    result = coro.send(None)
  File "azure-single-msg.py", line 15, in main
    await device_client.send_message("This is a message that is being sent")
  File "<string>", line 1, in send_message
  File "/usr/lib/python3.5/site-packages/azure_iot_device-2.0.0rc10-py3.5.egg/azure/iot/device/iothub/aio/async_clients.py", line 102, in send_message
    callback = async_adapter.AwaitableCallback()
  File "/usr/lib/python3.5/site-packages/azure_iot_device-2.0.0rc10-py3.5.egg/azure/iot/device/common/async_adapter.py", line 48, in __init__
    loop = asyncio_compat.get_running_loop()
  File "/usr/lib/python3.5/site-packages/azure_iot_device-2.0.0rc10-py3.5.egg/azure/iot/device/common/asyncio_compat.py", line 20, in get_running_loop
    loop = asyncio._get_running_loop()
AttributeError: module 'asyncio' has no attribute '_get_running_loop'
```
Following is the amended script allowing it to be run on Python3.5:

```
import asyncio
import os
from azure.iot.device.aio import IoTHubDeviceClient


async def main():
    # Fetch the connection string from an enviornment variable
    conn_str = os.getenv("IOTHUB_DEVICE_CONNECTION_STRING")

    # Create instance of the device client using the connection string
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)

    # Send a single message
    print("Sending message...")
    await device_client.send_message("This is a message that is being sent")
    print("Message successfully sent!")

    # finally, disconnect
    await device_client.disconnect()


if __name__ == "__main__":
    #asyncio.run(main())
    # If using Python 3.6 or below, use the following code instead of asyncio.run(main()):
    loop = asyncio.get_event_loop()
    loop.run_until_complete(main())
    loop.close()
```

**Comment by BertKleewein** [comment]
@mjohngreene - can you tell us what exact version of 3.5 you're using?

@cartertinney - this is your area of expertise :)

**Comment by mjohngreene** [comment]
Python 3.5.2

**Comment by cartertinney** [comment]
At this time, our asynchronous library only supports Python 3.5.3+. We recommend one of the following:

* Upgrade to at least Python 3.5.3
* Use the synchronous library instead (see our [legacy samples directory](https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples/legacy-samples) for samples that use it)

**Comment by mjohngreene** [comment]
Per https://stackoverflow.com/questions/56923655/attributeerror-module-asyncio-has-no-attribute-get-running-loop: "Judging by the stack trace, asgiref is accessing the private asyncio function _get_running_loop to obtain functionality equivalent to 3.7's get_running_loop in older Python versions. But you are running 3.5.2 which lacks even the private function."

Does this mean the <3.7 solution won't actually work on 3.5.2?

**Comment by cartertinney** [comment]
Yes, our asynchronous library does not support 3.5.2, only 3.5.3+, for the exact reason you mentioned. Our synchronous library is compatible with 3.5.2 however, as it does not use asyncio.

**Comment by mjohngreene** [comment]
Understood, @cartertinney.  Thanks for the feedback.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @mjohngreene, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by mjohngreene** [comment]
Sorry, but probably should have said this before closing the issue but better late than never, I guess.  I want to confirm that I was able to successfully run the "legacy sample" @cartertinney linked to upthread.
