### ISSUE TITLE
azure.iot.device.common.errors.ProtocolClientError: Out of memory - and disconnects

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#311]
Trying out the newest iot-sdk pulled today, and testing out the code from https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/receive_direct_method.py 

I am seeing some terrible errors, and nothings work for me:
```
DEBUG:CoordinateRequestAndResponseStage(EnableFeatureOperation): running
DEBUG:CoordinateRequestAndResponseStage(EnableFeatureOperation): passing to next stage.
DEBUG:IoTHubMQTTConverterStage(EnableFeatureOperation): running
DEBUG:IoTHubMQTTConverterStage(EnableFeatureOperation): continuing with MQTTSubscribeOperation op
DEBUG:IoTHubMQTTConverterStage(MQTTSubscribeOperation): passing to next stage.
DEBUG:EnsureConnectionStage(MQTTSubscribeOperation): running
DEBUG:EnsureConnectionStage(MQTTSubscribeOperation): passing to next stage.
DEBUG:SerializeConnectOpsStage(MQTTSubscribeOperation): running
DEBUG:SerializeConnectOpsStage(MQTTSubscribeOperation): passing to next stage.
DEBUG:MQTTTransportStage(MQTTSubscribeOperation): running
INFO:MQTTTransportStage(MQTTSubscribeOperation): subscribing to $iothub/methods/POST/#
INFO:subscribing to $iothub/methods/POST/# with qos 1
DEBUG:Sending SUBSCRIBE (d0, m2) [(b'$iothub/methods/POST/#', 1)]
DEBUG:_mqtt_client.subscribe returned rc=0
INFO:Waiting for response on MID: 2
DEBUG:Received SUBACK
INFO:suback received for 1
INFO:Response received for recognized MID: 1 - triggering callback
INFO:Starting on_subscribed in pipeline thread
INFO:MQTTTransportStage(MQTTSubscribeOperation): SUBACK received. completing op.
INFO:MQTTTransportStage(MQTTSubscribeOperation): completing without error
INFO:IoTHubMQTTConverterStage(EnableFeatureOperation): completing with result from MQTTSubscribeOperation
INFO:IoTHubMQTTConverterStage(EnableFeatureOperation): completing without error
INFO:Starting on_complete in callback thread
INFO:Successfully enabled feature:methods
INFO:Waiting for method request...
DEBUG:Received SUBACK
INFO:suback received for 2
INFO:Response received for recognized MID: 2 - triggering callback
INFO:Starting on_subscribed in pipeline thread
INFO:MQTTTransportStage(MQTTSubscribeOperation): SUBACK received. completing op.
INFO:MQTTTransportStage(MQTTSubscribeOperation): completing without error
INFO:IoTHubMQTTConverterStage(EnableFeatureOperation): completing with result from MQTTSubscribeOperation
INFO:IoTHubMQTTConverterStage(EnableFeatureOperation): completing without error
INFO:Starting on_complete in callback thread
INFO:Successfully enabled feature:methods
INFO:Waiting for method request...
INFO:disconnected with result code: 1
INFO:Starting _on_mqtt_disconnected in pipeline thread
ERROR:MQTTTransportStage: _on_mqtt_disconnect called: Out of memory.
INFO:PipelineRootStage: on_disconnected.  on_disconnected_handler=<function IoTHubPipeline.__init__.<locals>._on_disconnected at 0xb178d420>
INFO:Starting _on_disconnected in callback thread
WARNING:MQTTTransportStage: disconnection was unexpected
ERROR:Exception caught in background thread.  Unable to handle.
azure.iot.device.common.errors.ProtocolClientError: Out of memory.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 250, in _on_mqtt_disconnected
    six.raise_from(errors.ConnectionDroppedError, cause)
  File "<string>", line 3, in raise_from
azure.iot.device.common.errors.ConnectionDroppedError
INFO:Connection State - Disconnected
```

**Comment by BertKleewein** [comment]
@njbuch - thanks for the report.  This is something we are working on.  The next release to pypi will make this slightly more recoverable, but a better fix is still being worked on.

**Comment by BertKleewein** [comment]
This is very much related to https://github.com/Azure/azure-iot-sdk-python/issues/301.  I suspect the root cause is exactly the same.

**Comment by njbuch** [comment]
I think you are right, and I can add that I am seeing this now, when trying the "receive messasge code problem" that I have posted: https://github.com/Azure/azure-iot-sdk-python/issues/312

The code there generates this error as well now...

**Comment by njbuch** [comment]
Btw, do you have any indicative time-horizon for these updates/fixes?

**Comment by BertKleewein** [comment]
For the record, the behavior that I'm seeing is that, inside _packet_read() inside Paho's client.py, around line 2091, _sock_recv is returning a zero-byte buffer even though it think's that there's data available.  
```
                if len(command) == 0:
                    return 1
```
Paho then tries to disconnect and reconnect the socket, but this does not remedy the situation.  It's possible that our client could manually fix the connection, but this is non-trivial and I'm not convinced it will help.

**Comment by josiahlaivins** [comment]
I'm going to also say we are having the same issue. Our package version is 2.0.0rc11.

The worst part about this is, sending messages from one Module to another is fine, but receiving produces the same error.
 
However, this error **causes both to crash** not just the one receiving. So once the receiving one goes out of memory, the sending one suddenly runs out of memory also.

**Comment by josiahlaivins** [comment]
Not sure if this is should be a separate issue, but using:
```python
IoTHubModuleClient.create_from_connection_string(os.getenv('IOTHUB_DEVICE_CONNECTION_STRING'))
```
Works for sending messages, but gets out of memory errors for receiving. _However_ if we use:
```python
IoTHubModuleClient.create_from_edge_environment()
```
everything works.

**Comment by jpagliaccio** [comment]
I am getting the same errors as of 1/6/2020 with Python 3.6 using the 2 examples in the azure-iot-device/samples/sync-samples.

**Comment by BertKleewein** [comment]
@jpagliaccio -

Can you confirm what version of azure-iot-device you're running.  The messages above imply that you're using v2.0.0-preview.12.  Can you  update to the released v2.0.0 *(or newer) library please.

If this is a problem with the v2.0.0 library, are there any problems beyond the error output?  The library is written to recover from dropped connections.  This output you pasted appears to be a dropped connection, and the library should have recovered.  The dropped connection itself is not a bug.  If the library does not recover (by reconnecting and resuming normal interaction with the hub), then this is a bug.

**Comment by BertKleewein** [comment]
azure-iot-device 2.1.1 was released yesterday, which should fix many connection problems.  If any new connection issues are discovered, please open a new issue.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @njbuch, @josiahlaivins, @jpagliaccio, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
