### ISSUE TITLE
Getting message to a module?

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#312]
I have this simple piece of code:
`async def snapmain():
    module_client = IoTHubModuleClient.create_from_edge_environment()

    # connect the client.
    await module_client.connect()

    # define behavior for receiving an input message on input1
    async def input1_listener(module_client):
        while True:
            input_message = await module_client.receive_message_on_input("input7")  # blocking call
            print("the data in the message received on input1 was ")
            print(input_message.data)
            print("custom properties are")
            print(input_message.custom_properties)

    # Schedule tasks for Method Listener
    listeners = asyncio.gather(
        input1_listener(module_client)
    )`

Started with:
```
 loop = asyncio.get_event_loop()
        loop.create_task(snapmain())
        loop.run_forever()
```

But i cannot get a message through to the modules input7, is there some routing I need, or other things specifically to enable this to work?

**Comment by BertKleewein** [comment]
Hi @njbuch , you do need routing to make this work.  If this information doesn't help you, can you tell us how you are sending the message and also provide a copy of your routing rules.

(note: these are all IoT _Edge_ routing rules and not IoT _Hub_ routing rules.)

As an example, if you wanted to have a module called `firstMod` send a message to the output named `toNextMod` and route it to the module named `nextMod` on the input named `input7`, you would add something that looks like like `myTestRoute` below into your IoT Edge deployment manifest.

```
{
  "routes": {
    "myTestRoute": "FROM /messages/modules/firstMod/outputs/toNextMod INTO BrokeredEndpoint(\"/modules/nextMod/inputs/input7\")"
  }
}
```

If routes and deployment manifests are new to you, you can learn about them here: https://docs.microsoft.com/en-us/azure/iot-edge/module-composition 

If you want to experiment with routes without the worry of creating a new deployment manifest every time you change something, you can change routes in the Azure portal.  This is what I will typically do when experimenting.  (the overhead of composing a deployment manifest is something I save for the time when I have to put things into production and need a more script-based approach to deployment):
https://docs.microsoft.com/en-us/azure/iot-edge/how-to-deploy-modules-portal

**Comment by njbuch** [comment]
@BertKleewein Thank you so much for good comments! Essentially I need to send a message from a web-app running somewhere else to this module. So its going through the IoTHub, and I want to receive in this piece of python code, not sure of I then need to route on the edge device from the edgeHub module to this module or what? Thanks again

**Comment by njbuch** [comment]
> Hi @njbuch , you do need routing to make this work. If this information doesn't help you, can you tell us how you are sending the message and also provide a copy of your routing rules.

I am simply sending them directly from Vscode for testing-purposes. "Send C2D message to device".

**Comment by BertKleewein** [comment]
@njbuch - The IoTHub feature set lets you send a C2D message to a an IoTHub _device_.  It does not let you send a C2D message to an IoTHub (or IoTEdge) _module_.  The most direct route to get information from the cloud to an IoTEdge module is to use a direct method or a module twin desired property.

**Comment by njbuch** [comment]
@BertKleewein - Thanks for clarifying this, but I dont understand why there is no replacement for that design-decision in the world of IotEdge technologies. Software components should be well structured and needs to be able to live on the device, independently of the other modules and what else might be running the device. In the device-model the module needs to have device specific configuration which is making the configuration and setup very clumsy.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @njbuch, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
