### ISSUE TITLE
Please provide advice on which version to use....

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#314]
As we have now both a deprecated/archived version of this sdk and a v2, I would like some recommendations or a roadmap, as to when I can expect things to work, and with what versions. This info would benefit a lot from being on the readme files here and on pypi.

Thanks

**Comment by cartertinney** [comment]
We recommend you use the V2 SDK. Many customers experienced significant trouble installing and using the V1, and we recommend you avoid it for this reason. Although V2 is not totally feature complete, we are working rapidly to bring things up to parity.

We do not have an explicit roadmap or timeline at this time, as we are also addressing customer feedback and issues as they come in.

Please also note that the V2 SDK is still in preview, and APIs are subject to change until the preview is completed.

**Comment by cartertinney** [comment]
As there is no associated work item, and no further response, this issue is being closed

**Comment by az-iot-builder-01** [comment]
@njbuch, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
