### ISSUE TITLE
Looking for Python sample code to get device historical messages from iothub

### ISSUE THREAD

**Issue by Laurachu** [Azure/azure-iot-sdk-python#32]
Hi,

I am working on a task to get historical D2C device messages from iothub with Python language. I wasn't able to find any helpful example code from internet. Can someone provide me some example code? 

Closed issue https://github.com/Azure/azure-sdk-for-python/issues/1131. 

Thank you very much in advance!
 Laura Chu

- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by olivierbloch** [comment]
Hi @Laurachu 
if what you are looking for is reading messages that were sent from device to IoT Hub, then you have several options.
As explained in [this document](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-endpoints), IoT Hub exposes several endpoints.
By default Device to Cloud messages are available through the "Receive device-to-cloud messages" event hub endpoint which you can access using the Event Hub python sdk (available [here](https://github.com/Azure/azure-event-hubs)).
If you prefer the data to flow into different endpoints, you can look a the "Custom endpoints" section in the same document.
