### ISSUE TITLE
Connection Refused: not authorised with send_message_x509.py sample

### ISSUE THREAD

**Issue by torntrousers** [Azure/azure-iot-sdk-python#324]
Hi, I'm trying to use the the [send_message_x509.py](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/send_message_x509.py) but it fails with 'Connection Refused: not authorised.'. 

I've registered and verified a CA certificate in the IoT Hub and the device certificate is signed by that CA certificate, and I've created a device in IoT hub configured with Authentication type as X.509 CA Signed.

Can you give me any hints on how to debug whats wrong?

```
python3 azure2.py
MQTTTransportStage: _on_mqtt_connection_failure called: Connection Refused: not authorised.
MQTTTransportStage(ConnectOperation): completing with error Connection Refused: not authorised.
SerializeConnectOpsStage(ConnectOperation): op failed.  Unblocking queue with error: Connection Refused: not authorised.
SerializeConnectOpsStage(ConnectOperation): completing with error Connection Refused: not authorised.
MQTTTransportStage: _on_mqtt_disconnect called: The connection was refused.
Callback completed with error Connection Refused: not authorised.
azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.
MQTTTransportStage: disconnection was unexpected
Exception caught in background thread.  Unable to handle.
azure.iot.device.common.transport_exceptions.ConnectionFailedError: The connection was refused.

The above exception was the direct cause of the following exception:

azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None
Traceback (most recent call last):
  File "/home/aelder/.local/lib/python3.6/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 29, in handle_result
    return await callback.completion()
  File "/home/aelder/.local/lib/python3.6/site-packages/azure/iot/device/common/async_adapter.py", line 93, in completion
    return await self.future
azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "azure2.py", line 66, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.6/asyncio/base_events.py", line 484, in run_until_complete
    return future.result()
  File "azure2.py", line 43, in main
    await device_client.connect()
  File "<string>", line 1, in connect
  File "/home/aelder/.local/lib/python3.6/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 97, in connect
    await handle_result(callback)
  File "/home/aelder/.local/lib/python3.6/site-packages/azure/iot/device/iothub/aio/async_clients.py", line 35, in handle_result
    raise exceptions.CredentialError(message="Credentials invalid, could not connect", cause=e)
azure.iot.device.exceptions.CredentialError: Credentials invalid, could not connect
```

**Comment by olivakar** [comment]
What is the device id of the device that was created on the IoTHub  ?
Please ensure that the device id is same as the common name of the device certificate.

For any pointers please check the below link :-
https://github.com/Azure/azure-iot-sdk-python/wiki/X509_Chain#iothub-telemetry-operations

**Comment by torntrousers** [comment]
Thanks so much for the quick reply. The device id was not the same as the common name in the device certificate, but I've registered a new device  with the same name as the certificate common name, but still get exactly the same error.

Is there something else I could try or some way I can debug more what is wrong?

**Comment by olivakar** [comment]
How many certificates do you have in the chain ? I mean from the leaf device up to the root ?

**Comment by torntrousers** [comment]
There is a root CA (which is not registered with Azure IoT Hub, should it be?):
-----BEGIN CERTIFICATE-----
MIIDbzCCAxWgAwIBAgIJAIE0fRSPwuUeMAoGCCqGSM49BAMCMIGUMQswCQYDVQQG
EwJHQjEPMA0GA1UECAwGTG9uZG9uMQ8wDQYDVQQHDAZMb25kb24xGDAWBgNVBAoM
D0dsb2JhbCBTZWN1cml0eTEWMBQGA1UECwwNSVQgRGVwYXJ0bWVudDEPMA0GA1UE
AwwGY3Fyb290MSAwHgYJKoZIhvcNAQkBFhFjcXJvb3RAY3J5cHRvLmNvbTAeFw0x
OTA5MDMxMTI1NDhaFw0yMTA5MDIxMTI1NDhaMIGUMQswCQYDVQQGEwJHQjEPMA0G
A1UECAwGTG9uZG9uMQ8wDQYDVQQHDAZMb25kb24xGDAWBgNVBAoMD0dsb2JhbCBT
ZWN1cml0eTEWMBQGA1UECwwNSVQgRGVwYXJ0bWVudDEPMA0GA1UEAwwGY3Fyb290
MSAwHgYJKoZIhvcNAQkBFhFjcXJvb3RAY3J5cHRvLmNvbTBZMBMGByqGSM49AgEG
CCqGSM49AwEHA0IABFsF8FONVJWNrfDdX6pMDZxIQ66lTnYdVfj52FpvLOvSCFha
1sKZO7U87wHRPtPUg6sODD6b7+bFKq8XUh7L7C2jggFMMIIBSDAPBgNVHREECDAG
hwQAAAAAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYEFOY2MS5YXWjwm0jlAmvn
ajIwJON3MIHJBgNVHSMEgcEwgb6AFOY2MS5YXWjwm0jlAmvnajIwJON3oYGapIGX
MIGUMQswCQYDVQQGEwJHQjEPMA0GA1UECAwGTG9uZG9uMQ8wDQYDVQQHDAZMb25k
b24xGDAWBgNVBAoMD0dsb2JhbCBTZWN1cml0eTEWMBQGA1UECwwNSVQgRGVwYXJ0
bWVudDEPMA0GA1UEAwwGY3Fyb290MSAwHgYJKoZIhvcNAQkBFhFjcXJvb3RAY3J5
cHRvLmNvbYIJAIE0fRSPwuUeMA4GA1UdDwEB/wQEAwICBDApBgIBBwQjDCEwMDAw
MDAwMDAwMDAwMDAwLWZmZmZmZmZmZmZmZmZmZmYwCgYIKoZIzj0EAwIDSAAwRQIg
Wr1DE4fY4k3B4EmXqM6H3LK8SHIHGO0t5Tq5Rmgev58CIQDQl8jrDZXbzds0KORP
Vx+oGw34wTjriFjY67QRimwwDg==
-----END CERTIFICATE-----

Then an intermediate certificate which is registered and verified in Azure IoT hub):
-----BEGIN CERTIFICATE-----
MIICAjCCAaigAwIBAgIBAjAKBggqhkjOPQQDAjCBlDELMAkGA1UEBhMCR0IxDzAN
BgNVBAgMBkxvbmRvbjEPMA0GA1UEBwwGTG9uZG9uMRgwFgYDVQQKDA9HbG9iYWwg
U2VjdXJpdHkxFjAUBgNVBAsMDUlUIERlcGFydG1lbnQxDzANBgNVBAMMBmNxcm9v
dDEgMB4GCSqGSIb3DQEJARYRY3Fyb290QGNyeXB0by5jb20wHhcNMTkwOTI1MTE0
ODI1WhcNMjAwMzIzMTE0ODI1WjAPMQ0wCwYDVQQKEwRpY3J0MFkwEwYHKoZIzj0C
AQYIKoZIzj0DAQcDQgAEVyxNNSStX7Qo+jAMTTk0uS23RzARgwRPDSDKH96xCnpN
2YNIH1qEmvIy5XervpPX6fVJaYUMIfBy03AzjRwqo6NvMG0wDgYDVR0PAQH/BAQD
AgIEMA8GA1UdEwEB/wQFMAMBAf8wHwYDVR0jBBgwFoAU5jYxLlhdaPCbSOUCa+dq
MjAk43cwKQYCAQcEIwwAMDAwMDAwMDAwMDAwMDAwMC1mZmZmZmZmZmZmZmZmZmZm
MAoGCCqGSM49BAMCA0gAMEUCIQDr8dpyj9/ZSoHoD0rI2HT9Km5wKT6GOpcvC+fu
gjo6MwIgWDcTuYk1JOmq1RowCxzN68VbrIWcwe1P1nF+yzK4avE=
-----END CERTIFICATE-----

and then the device certificate:
-----BEGIN CERTIFICATE-----
MIIBXzCCAQSgAwIBAgIBATAKBggqhkjOPQQDAjAPMQ0wCwYDVQQKEwRpY3J0MB4X
DTE5MDkyNTExNDkwNFoXDTIwMDMyMzExNDkwNFowKDETMBEGA1UEChMKY3EgY29t
cGFueTERMA8GA1UEAxMIZGNydENlcnQwWTATBgcqhkjOPQIBBggqhkjOPQMBBwNC
AARCFXZAUIgXuXicCk9tDK+udlv2wMF8jDg/SCTFKogLE1X6kULVvRdJMmyAtGpy
x3y0OjacdEwrO90uAfXqIf5cozgwNjAOBgNVHQ8BAf8EBAMCB4AwDAYDVR0TAQH/
BAIwADAWBgIBAgQQMDAwMDAwMDAwMDAwMDAxZTAKBggqhkjOPQQDAgNJADBGAiEA
+62FyIu3O7l0FVT/V9qLRYH6ex1E1zFCnnr0prRhveMCIQDBfsxwH+I80VPt4J1m
WnUVwjIfXcW38giNOXXP0dBX7Q==
-----END CERTIFICATE-----

**Comment by olivakar** [comment]
You have 3 certificates the root, intermediate and the leaf). 
For sending message to a device in IoTHub the certificate file used needs to have the device cert and all the other certs in the chain appended except the cert which has been certified.

So in this case it needs to be a chain of your leaf and intermediate cert.

Does this help ?

**Comment by torntrousers** [comment]
The intermediate certificate is the only one that has been added and verified to the IoT Hub. So understood that meant that it didn't need to be appended to the leaf certificate?

**Comment by olivakar** [comment]
I have tried both scenarios and both works for me :-

- Verify root certificate in IoTHub
- Send message by using a cert file chain of device + intermediate

- Verify intermediate certificate in IoTHub
- Send message via only device certificate

So I am not completely sure what is the issue. I know that the stack trace you received is similar to the one I receive if I mess up the common name.  I have to use the common name of the device certificate in the sample as well as while registering the device.

**Comment by torntrousers** [comment]
Could you send me your certificates and private keys so I could try them here, or could I send you my certificates and private keys so you could try them?

Or, is there some debugging I could switch on in the IoT hub to get more precise details about what its complaining about?

**Comment by torntrousers** [comment]
Actually, after cleaning things up and trying again it turns out it was the common name in the device certificate not matching the device  id. Correcting that and it works now. 
Thanks so much for your help.

**Comment by az-iot-builder-01** [comment]
@torntrousers, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
