### ISSUE TITLE
Out of memory Error

### ISSUE THREAD

**Issue by MiguelCHR** [Azure/azure-iot-sdk-python#328]
Hi i am getting this error:
26.09.19 16:19:10 (-0600)  core  The above exception was the direct cause of the following exception:
26.09.19 16:19:10 (-0600)  core  azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None
26.09.19 16:19:12 (-0600)  core  WARNING:azure.iot.device.common.pipeline.pipeline_stages_mqtt:Connection was unexpected
26.09.19 16:19:12 (-0600)  core  ERROR:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_disconnect called: Out of memory.
26.09.19 16:19:12 (-0600)  core  WARNING:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: disconnection was unexpected
26.09.19 16:19:12 (-0600)  core  ERROR:azure.iot.device.common.handle_exceptions:Exception caught in background thread.  Unable to handle.
26.09.19 16:19:12 (-0600)  core  azure.iot.device.common.transport_exceptions.ProtocolClientError: Out of memory.
26.09.19 16:19:12 (-0600)  core  

Before the "Out memory" i had an unauthorized  error.

I am trying to create a new connection with:
self.iotHubClient = IoTHubDeviceClient.create_from_connection_string(config.connection_string)

but the only thing that seems to work if to restart the device.

Any help with this error?

Thanks in advance!

**Comment by az-iot-builder-01** [comment]
@MiguelCHR, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by MiguelCHR** [comment]
Found out that the number of messages exceeded the number we had available

**Comment by livneros** [comment]
> Found out that the number of messages exceeded the number we had available

Can you explain how did you solve this problem?
