### ISSUE TITLE
certificates included in the samples stopped working

### ISSUE THREAD

**Issue by hassler** [Azure/azure-iot-sdk-python#33]
- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

currently connect fails due to not working certificate.

# Code sample exhibiting the issue:

any code

# Console log of the issue:

c:InitializeConnection Line:1779 mqtt_client timed out waiting for CONNACK

azure-iot-sdk-python/c/c-utility/src/tlsio_openssl.c Func:tlsio_openssl_send Line:1236 Invalid tlsio_state. Expected state is TLSIO_STATE_OPEN.

azure-iot-sdk-python/c/umqtt/src/mqtt_client.c Func:sendPacketItem Line:323 1237: Failure sending control packet data

/c/umqtt/src/mqtt_client.c Func:mqtt_client_disconnect Line:1094 Error: mqtt_client_disconnect send failed
Segmentation fault

**Comment by lulzmachine** [comment]
Also have this problem. The problem doesn't happen on my MacOS machine (which probably falls back to OS certs). But it happens on my IoT device. This is the output of the sample code:

```
/sample # python3 iothub_client_sample.py

Python 3.6.1 (default, May 18 2017, 19:55:02)
[GCC 4.8.3 20140320 (prerelease)]
IoT Hub Client for Python
Starting the IoT Hub Python sample...
    Protocol MQTT
    Connection string=HostName=<our iot hub>;DeviceId=<deviceId>;SharedAccessKey=<key>
Connecting to iot hub. Connection string: HostName=<our iot hub>.azure-devices.net;DeviceId=<deviceId>;SharedAccessKey=<key>, Protocol: MQTT
Info: IoT Hub SDK for C, version 1.1.12
set_option TrustedCerts successful
IoTHubClient is reporting state
IoTHubClient sending 5 messages
IoTHubClient.send_event_async accepted message [0] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [1] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [2] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [3] for transmission to IoT Hub.
IoTHubClient.send_event_async accepted message [4] for transmission to IoT Hub.
IoTHubClient waiting for commands, press Ctrl-C to exit
Send status: BUSY
Confirmation[0] received for message with result = MESSAGE_TIMEOUT
    message_id: message_0
    correlation_id: correlation_0
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 1
Confirmation[1] received for message with result = MESSAGE_TIMEOUT
    message_id: message_1
    correlation_id: correlation_1
    Properties: {'temperatureAlert': 'true'}
    Total calls confirmed: 2
Send status: BUSY
Confirmation[2] received for message with result = MESSAGE_TIMEOUT
    message_id: message_2
    correlation_id: correlation_2
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 3
Confirmation[3] received for message with result = MESSAGE_TIMEOUT
    message_id: message_3
    correlation_id: correlation_3
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 4
Confirmation[4] received for message with result = MESSAGE_TIMEOUT
    message_id: message_4
    correlation_id: correlation_4
    Properties: {'temperatureAlert': 'false'}
    Total calls confirmed: 5
Send status: IDLE
Send status: IDLE
Send status: IDLE
Send status: IDLE
```

I've also tried to change the sample code to only include the root cert (as mentioned on https://azure.microsoft.com/en-us/blog/azure-iot-hub-server-tls-leaf-certificate-renewal-may-2017/ ), but I had no luck getting it to work.

I'm unsure exactly how the set_option('TrustedCerts') is supposed to work, since I can't find any documentation for it either

**Comment by lulzmachine** [comment]
I also tried to load all the certs from mozillas truststore: https://curl.haxx.se/ca/cacert.pem but still I get MESSAGE_TIMEOUT on everything. Doesn't the "TrustedCerts" option affect MQTT perhaps?

**Comment by lulzmachine** [comment]
I tried to use MQTT_WS. Same error. Tried with HTTP. Got a lot of curl-related errors. Tried with AMQP. Got a lot of errors. Should I post them here? Would that help?

**Comment by lulzmachine** [comment]
We solved the problem. It was related to time being out of range of the new cert on the device.

**Comment by hassler** [comment]
Somewhat fixed and now working with the new certificates.
Debug could be improved telling us more about the certificate issue.
