### ISSUE TITLE
Error While trying connect to IoT Hub 

### ISSUE THREAD

**Issue by arnabhetc** [Azure/azure-iot-sdk-python#333]
I was trying this from readme section -->

```
import os
import asyncio
from azure.iot.device.aio import IoTHubDeviceClient
from azure.iot.device import auth


async def main():
    # Fetch the connection string from an enviornment variable
    conn_str = os.getenv("IOTHUB_DEVICE_CONNECTION_STRING")

    # Create instance of the device client using the authentication provider
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)

    # Connect the device client.
    await device_client.connect()

    # Send a single message
    print("Sending message...")
    await device_client.send_message("This is a message that is being sent")
    print("Message successfully sent!")

    # finally, disconnect
    await device_client.disconnect()


if __name__ == "__main__":
    asyncio.run(main())
```

So while I executed it  --> 

```
from azure.iot.device import authImportError: cannot import name 'auth'
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from azure.iot.device import auth
ImportError: cannot import name 'auth'
```

**Comment by SampleText2k77** [comment]
Do you really need to input `auth` from `azure.iot.device` here?
Seems that your piece of code will work without it.

**Comment by cartertinney** [comment]
This is a mistake in the sample - you don't need to import auth. We will remove it from the README.

**Comment by arnabhetc** [comment]
@cartertinney Ok got it, 
but even after removing that I am getting bellow error -->

`Traceback (most recent call last):
  File "test.py", line 27, in <module>
    asyncio.run(main())
AttributeError: module 'asyncio' has no attribute 'run'`

**Comment by cartertinney** [comment]
Which version of Python are you running? As mentioned in the README, this sample is configured for Python 3.7.

If you are using 3.5 or 3.6 please use the following code instead of `asyncio.run(main())`:

```
loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

**Comment by jebrando** [comment]
@arnabhetc If you have any more issues please feel free to re-open this issue or create a new one.

**Comment by az-iot-builder-01** [comment]
@SampleText2k77, @arnabhetc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
