### ISSUE TITLE
Is it possible "simulated TPM device using Python device SDK (azure-iot-sdk-python)" is running in linux OS? and how?

### ISSUE THREAD

**Issue by sw-tt-janvivakotar** [Azure/azure-iot-sdk-python#339]
I am refer below link.
https://docs.microsoft.com/en-us/azure/iot-dps/quick-create-simulated-device-tpm-python#prepare-the-environment
-I completed all step of **'Prepare the environment'** from 1 to 7 point(And its working fine)
-second step name is **"Create a device enrollment entry"**
   -  I didn't get any **azure_iot_sdks.sln** file in cmake folder

![Screenshot from 2019-09-30 14-24-44](https://user-images.githubusercontent.com/29775589/66037363-116a9f00-e52d-11e9-82d9-959821f7e4a5.png)

So what can i do For that.

**Comment by cartertinney** [comment]
As per the note at the top of the guide:

> This guide only applies to the now-deprecated V1 Python SDK. Simulated TPM devices are not yet been supported in V2. The team is currently hard at work bringing V2 to feature parity.

If you wish to follow this guide, please use [the deprecated V1 Python SDK](https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated). However, be aware that many customers have had problems installing V1, and we are no longer updating it

**Comment by jebrando** [comment]
@sw-tt-janvivakotar We currently don't have tpm support for the Python v2.  We are not currently planning on supporting this in the foreseeable future.  If this functionality is a blocker for you, you can reply to this and we will make a note to take this into consideration.

Sorry for any inconvenience.

**Comment by sw-tt-janvivakotar** [comment]
Its ok.

**Comment by az-iot-builder-01** [comment]
@sw-tt-janvivakotar, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
