### ISSUE TITLE
Unable to import client cert

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#35]
Ubuntu 14.04
python 2.7
Master branch

I am unable to locate the following module which is referenced in the samples. I have built using the release.sh and installed into my venv

```
  from iothub_client_cert import CERTIFICATES
```

I can import the other modules, such as  `from iothub_client import IoTHubClient`,

**Comment by lulzmachine** [comment]
"iothub_client_cert.py" is in the samples folder. You're probably looking for this: https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_cert.py
