### ISSUE TITLE
No module named 'iothub_client'

### ISSUE THREAD

**Issue by PedroCastroRequejo** [Azure/azure-iot-sdk-python#354]
Hello,
I am developing now several python modules that are going on production inmediatly.
Now, in my last module I find this message when I run it in the edge device: 
No module named 'iothub_client'
The rest of the modules go on working fine, they are alredy installed.
Is this messege generated because of the new SDK? I have asked Microsoft team and they told me that maybe i should upgrade to the new SDK, but i have a doubt if my old modules will go on working if I need to do any change.

Thanks in advance for any feedback you can give me

**Comment by az-iot-builder-01** [comment]
@PedroCastroRequejo, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
