### ISSUE TITLE
Symmetric key provisioning v2 sample does not work with enrollment groups

### ISSUE THREAD

**Issue by plpplp** [Azure/azure-iot-sdk-python#355]
We currently provision our test devices by compiling the cert/key information into the dll used within the python package of the python sdk v1. 

We would like to switch to the v2 python sdk to simplify the process but the provisioning sample of the new sdk does not seem to work, at least using symmetric keys. 

Steps to reproduce using docker (fails also doing the equivalent steps on windows):

```
FROM python:3.7

ENV PROVISIONING_SYMMETRIC_KEY my_key
ENV PROVISIONING_REGISTRATION_ID my_regid
ENV PROVISIONING_HOST my_provhost
ENV PROVISIONING_IDSCOPE my_idscope

RUN pip install azure-iot-device
COPY register_symmetric_key.py .
RUN python register_symmetric_key.py
```

fails with

```
Callback completed with error Incoming message failure
ValueError: Incoming message failure
Traceback (most recent call last):
  File "register_symmetric_key.py", line 35, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 579, in run_until_complete
    return future.result()
  File "register_symmetric_key.py", line 28, in main
    results = await asyncio.gather(register_device())
  File "register_symmetric_key.py", line 26, in register_device
    return await provisioning_device_client.register()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/provisioning/aio/async_provisioning_device_client.py", line 50, in register
    result = await callback.completion()
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/async_adapter.py", line 93, in completion
    return await self.future
ValueError: Incoming message failure
```

Am I doing something wrong here or is that a bug?

**Comment by plpplp** [comment]
It does work if we do not use enrollment groups but individual enrollments along with symmetric keys. Enrollment groups with x.509 attestation method does also work. 

The problem is that we need to use symmetric keys because the EdgeHub somehow can not authenticate x509 leave certs.

What I do not understand is, if the method `create_from_symmetric_key` would support enrollment groups, how would it infer the enrollment group name? From the SAS generated during enrollment group configuration?

**Comment by olivakar** [comment]
The provisioning sample in the name of `register_symmetric_key` is meant for symmetric key registration of an individual enrollment. 

I assume you are looking for a group enrollment.

**Comment by plpplp** [comment]
Yes I do. Is there an example on group enrollments or can you point me in a direction (documentation, a other sample)?

**Comment by olivakar** [comment]
For group enrollment the symmetric key present in the enrollment record represents the master key.
A device key needs to be derived from this master key.

You may find this link helpful.

https://docs.microsoft.com/en-us/azure/iot-dps/how-to-legacy-device-symm-key#derive-a-device-key

**Comment by olivakar** [comment]
I have also added 2 samples that may help you. Please find them here.

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/register_symmetric_key_group.py

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/legacy-samples/register_symmetric_key_group.py

Hope this helps.

**Comment by az-iot-builder-01** [comment]
@plpplp, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
