### ISSUE TITLE
Device client still drops connection

### ISSUE THREAD

**Issue by bukarev** [Azure/azure-iot-sdk-python#356]
This is a continuation of the issue #301 reported earlier.

Maybe I just don't understand how to use what has been improved in the package.
Here's what I'm getting now after I updated the package to the latest version.
`Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0x757b6b50>._execute_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 97, in run_op
    self._execute_op(op)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 142, in _execute_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 404, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: The client is not currently connected.
MQTTTransportStage(MQTTPublishOperation): completing with error The client is not currently connected.
IoTHubMQTTConverterStage(SendIotRequestOperation): completing with error The client is not currently connected.
CoordinateRequestAndResponseStage(SendIotRequestAndWaitForResponseOperation): completing with error The client is not currently connected.
HandleTwinOperationsStage(PatchTwinReportedPropertiesOperation): completing with error The client is not currently connected.
Callback completed with error The client is not currently connected.
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 97, in run_op
    self._execute_op(op)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 189, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 142, in _execute_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.7/dist-packages/azure/iot/device/common/mqtt_transport.py", line 404, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: The client is not currently connected.`

After this the client stops working.

I have something like this in my code:
`try:
    await device_client.patch_twin_reported_properties(rep_prop)
except:
    print('CLIENT DISCONNECTED, RECONNECTING')
    await device_client.patch_twin_reported_properties(rep_prop)`

Have I understood correctly the recommendation to call patch_twin_reported_properties again to force reconnect?

**Comment by jebrando** [comment]
@bukarev The SDK should reconnect automatically if there is a disruption, I have a few question so we can get a handle on the error that you received:

1. Did you start out with a sample or is this your own code

2. How long was the client connected before you received the errors?

3. During this time did the device have any network disruption or anything else that may have caused the error?

**Comment by bukarev** [comment]
@jebrando here are the answers:
1. I started with a sample while this SDK was in preview mode, and since then my code might have morphed. I'm happy to provide the code's skeleton.
2. The time to disconnection ranges from 1 to 5 minutes.
3. All other networked devices work fine, and I don't lose connection to the RaspberryPi on which this SDK is running, so I conclude there are no network interruptions.

**Comment by jebrando** [comment]
@bukarev Thanks for the information, I'm trying to get a repro here on my RaspberryPi, but I'm not successfully reproducing the same issue, I've let my run overnight.  On my pi I have python 3.7.3 and I started with the receive_twin_desired_properties_patch.py sample.

Can you start with this sample, either the [sync](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/legacy-samples/receive_twin_desired_properties_patch.py) or [async](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/receive_twin_desired_properties_patch.py) sample depending on your setup.  Also can you let us know what version of python you're using on your Pi and also before you run the sample can you add logging to the top of the file

```Python
import logging
logging.basicConfig(level=logging.DEBUG)
```

**Comment by bukarev** [comment]
After some investigation I've got a reason to believe that my program freezes because of another component, specifically, bluepy package (and the latter likely failing because my raspberryPi gets too hot over time). Closing the issue for now, sorry for the hassle.

**Comment by az-iot-builder-01** [comment]
@bukarev, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by kunalg06** [comment]
Im facing the same issue though code is on my local machine, and it disconnects after 3-7 mins. I've used the send telemetry data to iot hub from azure-iot-hub repo. simulated device.py file
