### ISSUE TITLE
Not authorized error

### ISSUE THREAD

**Issue by MiguelCHR** [Azure/azure-iot-sdk-python#363]
Hi, i have a few devices that are connected for a while then they disconnect with the following exception:

`19.10.19 09:51:32 (-0600)  core  azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None
19.10.19 09:53:34 (-0600)  core  ERROR:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_connection_failure called: Connection Refused: not authorised.
19.10.19 09:53:34 (-0600)  core  WARNING:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: Connection failure was unexpected
19.10.19 09:53:34 (-0600)  core  ERROR:azure.iot.device.common.handle_exceptions:Exception caught in background thread.  Unable to handle.
19.10.19 09:53:34 (-0600)  core  azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.
19.10.19 09:53:34 (-0600)  core  ERROR:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: _on_mqtt_disconnect called: The connection was refused.
19.10.19 09:53:34 (-0600)  core  WARNING:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: disconnection was unexpected
19.10.19 09:53:34 (-0600)  core  ERROR:azure.iot.device.common.handle_exceptions:Exception caught in background thread.  Unable to handle.
19.10.19 09:53:34 (-0600)  core  azure.iot.device.common.transport_exceptions.ConnectionFailedError: The connection was refused.
19.10.19 09:53:34 (-0600)  core  
19.10.19 09:53:34 (-0600)  core  The above exception was the direct cause of the following exception:
19.10.19 09:53:34 (-0600)  core  
19.10.19 09:53:34 (-0600)  core  azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None`

Any ideas on how to recover from here?

Thanks in advance

**Comment by cartertinney** [comment]
It appears your credentials are becoming invalid, thus leading to a dropped connection. Are you using the latest version of the Device Library (2.0.0-preview.12), or some other version?

**Comment by MiguelCHR** [comment]
Yes it seems i have the latest installed:

`
root@5999e77030cc:/usr/src/app# pip3 install azure-iot-device
Looking in indexes: https://pypi.org/simple, https://www.piwheels.org/simple
Requirement already satisfied: azure-iot-device in /usr/local/lib/python3.7/dist-packages (2.0.0rc11)
Requirement already satisfied: requests<3.0.0,>=2.20.0 in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (2.22.0)
Requirement already satisfied: paho-mqtt<2.0.0,>=1.4.0 in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (1.4.0)
Requirement already satisfied: transitions<1.0.0,>=0.6.8 in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (0.7.1)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>1.21.1; python_version != "3.4" in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (1.25.6)
Requirement already satisfied: janus<1.0.0,>=0.4.0; python_version >= "3.5" in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (0.4.0)
Requirement already satisfied: requests-unixsocket<1.0.0,>=0.1.5 in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (0.2.0)
Requirement already satisfied: six<2.0.0,>=1.12.0 in /usr/local/lib/python3.7/dist-packages (from azure-iot-device) (1.12.0)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.20.0->azure-iot-device) (3.0.4)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.20.0->azure-iot-device) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in /usr/local/lib/python3.7/dist-packages (from requests<3.0.0,>=2.20.0->azure-iot-device) (2.8)
`

**Comment by cartertinney** [comment]
While it looks like you're still on 2.0.0-preview.11 rather than .12 (you can update with `pip install azure-iot-device --upgrade`), I'm not entirely sure that the upgrade will help you.

@BertKleewein any idea what could be causing this? Is this just a need for connection retry? It seems that something else might be wrong if an connection is dropped due to authorization issues.

**Comment by MiguelCHR** [comment]
Ok in any case i am updating to 2.0.0-preview.12 for all my IoT devices.

**Comment by MiguelCHR** [comment]
UPDATE: I had the same error again with the 2.0.0-preview.12, version, anything else that i can try?

Thanks again

**Comment by BertKleewein** [comment]
This may not be related, and I see a slightly different flow through the code, but I've seen intermittent SSL handshake errors that could theoretically end up as auth errors.  If this is the problem, #389 should fix this. One thing that would help debugging is to set logging level to DEBUG and share the entire log (it will be long).  That will give additional context that should help solve the issue.

**Comment by MiguelCHR** [comment]
Hi i haven't seen this error since the 2.0.0-preview.13 release, thanks for the support

**Comment by BertKleewein** [comment]
Thanks for the feedback.  Please let me know if this comes back.

**Comment by az-iot-builder-01** [comment]
@MiguelCHR, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
