### ISSUE TITLE
DLL load failed : The specified module could not be found.

### ISSUE THREAD

**Issue by czgtest** [Azure/azure-iot-sdk-python#366]
Repro on Windows10
Python: 3.8.0 and 3.7.0

Run python code :  python -u "d:\f\Untitled-2.py"
Get the error:  DLL load failed while importing iothub_client: The specified module could not be found.

here is the step::
1. install latest python 3.8.0
![image](https://user-images.githubusercontent.com/35018765/67274545-3a120300-f4f3-11e9-99ab-f5ed8dbb5401.png)
2. install Azure IoT Hub Toolkit in VS Code
3. create one device in VS Code Toolkit
4. right-click the device and generate code
5. select python
install "pip install azure-iothub-device-client"
run code failed :
[Running] python -u "d:\f\Untitled-2.py"
Traceback (most recent call last):
File "d:\f\Untitled-2.py", line 12, in 
import iothub_client
File "C:\Users\iotedge\AppData\Local\Programs\Python\Python38-32\lib\site-packages\iothub_client_init_.py", line 1, in 
from .iothub_client import *
ImportError: DLL load failed while importing iothub_client: The specified module could not be found.
[Done] exited with code=1 in 0.383 seconds

**Comment by oerpli** [comment]
I have a similar error - not sure if it is the same though:

```
Python could not import the service's module 
Traceback (most recent call last):
  File "**\MyFile.py", line 6, in <module>
    from azure.iot.device.iothub.models.message import Message
  File "**\site-packages\azure\iot\device\__init__.py", line 7, in <module>
    from .iothub import *
  File "**\site-packages\azure\iot\device\iothub\__init__.py", line 7, in <module>
    from .sync_clients import IoTHubDeviceClient, IoTHubModuleClient
  File "**\site-packages\azure\iot\device\iothub\sync_clients.py", line 11, in <module>
    from .abstract_clients import (
  File "**\site-packages\azure\iot\device\iothub\abstract_clients.py", line 15, in <module>
    from . import pipeline
  File "**\site-packages\azure\iot\device\iothub\pipeline\__init__.py", line 8, in <module>
    from .iothub_pipeline import IoTHubPipeline
  File "**\site-packages\azure\iot\device\iothub\pipeline\iothub_pipeline.py", line 10, in <module>
    from azure.iot.device.common.pipeline import (
  File "**\site-packages\azure\iot\device\common\pipeline\pipeline_stages_mqtt.py", line 17, in <module>
    from azure.iot.device.common.mqtt_transport import MQTTTransport
  File "**\site-packages\azure\iot\device\common\mqtt_transport.py", line 9, in <module>
    import ssl
  File "**\miniconda3\current\lib\ssl.py", line 98, in <module>
    import _ssl             # if we can't import it, let the error propagate
ImportError:  DLL load failed : The specified module could not be found.
%2: %3
```

(not sure if the last line is related - I copied the whole thing from the Windows Event Log)

Here's a subset of my `conda list` that may be relevant:
```
# Name                    Version                   Build    Channel
openssl                   1.1.1c               hfa6e2cd_0    conda-forge
pyopenssl                 19.0.0                   py37_0    conda-forge
azure-iot-device          2.0.0rc12                pypi_0    pypi
python                    3.7.3                h510b542_1    conda-forge
requests                  2.22.0                   py37_1    conda-forge
requests-unixsocket       0.2.0                    pypi_0    pypi
```

**Comment by jebrando** [comment]
@czgtest Our v1 device client has been deprecated, we've replaced it with a pure python v2 which provides a lot better experience.  If you could move to the new SDK you won't see this issue.

**Comment by oerpli** [comment]
I thought I had the same problem (see StackTrace above) but it turned out that it was something unrelated.

My problem was related to how I started up my application, as my PowerShell used the conda environment correctly, whereas my Windows Service did not.

Fixing it was done with adding the necessary stuff to PATH. 

(Though I used the v2 of the SDK)

**Comment by jebrando** [comment]
With the Python v2 reaching General Availability we are recommending users move away from the v1 SDK. 
We will be closing the v1 SDK issues whose features are covered by the v2 release. 
Feel free to open an new issue if you find an issue with the v2 SDK.
 
Thank you for your patronage

**Comment by az-iot-builder-01** [comment]
@czgtest, @oerpli, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
