### ISSUE TITLE
General Question - Threading Model

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#37]
Is there any documentation concerning the threading model used by this sdk?

In particular I'm curious how the callbacks are serviced? Is there a single IO thread which is handling these callbacks? I am assuming that is what drives the use of `global` variables in the examples?

Are issues we should be aware of with the threading model and the GIL?

Thanks!

**Comment by ewertons** [comment]
Hi @bearrito ,
I'm adding @olivierbloch  here to answer about the documentation, he would have more details to share than me.

Our python SDK uses the threaded version of the C SDK, which has a single thread handling both I/O and callbacks, you are correct.
If you are using the python SDK, there should be no concerns in regards to threading.
Just to make sure, what do you mean by GIL?

**Comment by olivierbloch** [comment]
Hi @bearrito 
as Ewerton mentioned, our Python SDK is a wrapper on top of our [C SDK](https://github.com/azure/azure-iot-hub-sdk-c).
You can find documentation about the C SDK here:

- [Introduction](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-intro)
- [C SDK details](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-device-sdk-c-iothubclient) (I need to update this one as it is missing the latest APIs, but is still up to date regarding architecture)

**Comment by bearrito** [comment]
GIL = Global Interpreter Lock

Thanks much.  I'll have a look at those.

**Comment by bearrito** [comment]
Still have a question about number of threads. How many threads will attempt to enter the `send_confirmation_callback` section?

**Comment by ewertons** [comment]
How many threads will attempt to enter the send_confirmation_callback section? 
Answer: One

**Comment by bearrito** [comment]
Thanks for the help in resolving this.
