### ISSUE TITLE
Service example assumes same number of devices when it is not always the case

### ISSUE THREAD

**Issue by Alberto-Vega** [Azure/azure-iot-sdk-python#373]
Hi team moving this issue from https://github.com/MicrosoftDocs/azure-docs/issues/40863 opened by @jmonticelli

I was able to reproduce and the issue is with the method get_statistics() of the class IoTHubRegistryManager, it doesn't update the property totalDeviceCount.

After deleting a device then running this code the device count won't decrease.

In customer words:
_The Python guide suggests that we do this, but executing this sample for me returns that there are 9 total and 9 enabled devices, but only returns 7 devices to `dev_list`. Thus, the sample crashes trying to get index 7 of the device list._

```
        iothub_registry_statistics = iothub_registry_manager.get_statistics()
        print ( "Total device count                       : {0}".format(iothub_registry_statistics.totalDeviceCount) )
        print ( "Enabled device count                     : {0}".format(iothub_registry_statistics.enabledDeviceCount) )
        print ( "Disabled device count                    : {0}".format(iothub_registry_statistics.disabledDeviceCount) )
        print ( "" )
        
        //This doesn't return the correct number of devices after deleting one
        number_of_devices = iothub_registry_statistics.totalDeviceCount
        dev_list = iothub_registry_manager.get_device_list(number_of_devices)

        iothub_twin_method = IoTHubDeviceTwin(CONNECTION_STRING)

        for device in range(0, number_of_devices):
           //This line causes a IndexError: list index out of range.
            if dev_list[device].deviceId == DEVICE_ID:
                twin_info = iothub_twin_method.update_twin(dev_list[device].deviceId, UPDATE_JSON)
```

Full code is here from the tutorial: https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-twin-getstarted#register-a-new-device-in-the-iot-hub

**Comment by jebrando** [comment]
@Alberto-Vega-MSFT We've brought this up with the service team and it is being looked into.  I shall update when we hear something.

**Comment by jebrando** [comment]
@Alberto-Vega This functionality is now fixed in the service and appears to be working with the latest SDK release.  The Statistics API is reporting correctly after a delete and after an addition.  If you have any more issues please feel free to reopen this issue or open a new issue.

**Comment by az-iot-builder-01** [comment]
@Alberto-Vega, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
