### ISSUE TITLE
Using Advanced hub scenarios in SDK can not connect to IoT Edge device

### ISSUE THREAD

**Issue by secretsquirell** [Azure/azure-iot-sdk-python#374]
I'm using the register_x509.py sample in the advanced-hub-scenarios directory under the samples. I'm attempting to register a leaf device under my Edge device (running as a transparent gateway). I have had no issues using the certificates to register directly to IoT Hub.

I have set my PROVISIONING_HOST to be the hostname of my edge device. The SSL session appears to successfuly connect. However I get the following when running the command
`MQTTTransportStage: _on_mqtt_connection_failure called: Connection Refused: not authorised.
MQTTTransportStage(ConnectOperation): completing with error Connection Refused: not authorised.
SerializeConnectOpsStage(ConnectOperation): op failed.  Unblocking queue with error: Connection Refused: not authorised.
EnsureConnectionStage(MQTTSubscribeOperation): Connection failed.  Completing with failure because of connection failure: Connection Refused: not authorised.
EnsureConnectionStage(MQTTSubscribeOperation): completing with error Connection Refused: not authorised.
ProvisioningMQTTConverterStage(EnableFeatureOperation): completing with error Connection Refused: not authorised.
MQTTTransportStage: _on_mqtt_disconnect called: The connection was refused.
Unhandled exception in background thread
MQTTTransportStage: disconnection was unexpected
This may cause the background thread to abort and may result in system instability.
Exception caught in background thread.  Unable to handle.
azure.iot.device.common.transport_exceptions.ConnectionFailedError: The connection was refused.`

This is using azure-iot-sdk-python/azure-iot-device/samples/advanced-hub-scenarios/register_x509.py

**Comment by secretsquirell** [comment]
Some additional input.  looking at the docker container logs gives
`3> 2019-10-28 18:40:19.717 +00:00 [ERR] - Unable to generate identity for clientId rpi and username 0ne0008A64E/registrations/rpi/api-version=2019-03-31&ClientVersion=py-azure-iot-device%2F2.0.0-preview.12
<6> 2019-10-28 18:40:19.718 +00:00 [INF] - ClientNotAuthenticated, Client ID: rpi; Username: 0ne0008A64E/registrations/rpi/api-version=2019-03-31&ClientVersion=py-azure-iot-device%2F2.0.0-preview.12, 0c8f3d26
`

**Comment by vipeller** [comment]
Hi,

just to make sure that I understand well your scenario: what you would like to achieve is that for provisioning, instead of calling the azure hosted provisioning service directly (e.g. calling "global.azure-devices-provisioning.net"), you would like to use the SDK connecting to your edge device (that is why your specified PROVISIONING_HOST as your edge device) and register your leaf device that way?

**Comment by secretsquirell** [comment]
Yes that is correct (although I'm not certain that is supporteD)..  But I am taking a step back, and i disconnected the DPS, and am trying to use the IoTHubDeviceClient to connect to my edge device).  Basically I'd like to get my leaf device connected properly to my edge device with x509 certs.

**Comment by secretsquirell** [comment]
note if there is a better place to go ask such questions please let me know

**Comment by kkdawkins** [comment]
Hi @secretsquirell  - 

Using Edge as a proxy for which the leaf devices will use to reach out is not a supported scenario. The correct flow here is to have the leaf devices themselves talk directly to DPS to provision, and then use that certificate to talk to the Edge device.

**Comment by secretsquirell** [comment]
Ok.   lets assume that I don't want to use DPS.  I simply want to connect a device (which i created in iothub and made a child of my edge device.  The code I'm using is 
`import os
import asyncio
from azure.iot.device import X509
from azure.iot.device.aio import ProvisioningDeviceClient,IoTHubDeviceClient

provisioning_host = os.getenv("PROVISIONING_HOST")
id_scope = os.getenv("PROVISIONING_IDSCOPE")
registration_id = os.getenv("DPS_X509_REGISTRATION_ID")


async def main():
    async def register_device():
        x509 = X509(
            cert_file=os.getenv("X509_CERT_FILE"),
            key_file=os.getenv("X509_KEY_FILE"),
            pass_phrase=os.getenv("PASS_PHRASE"),
        )
        provisioning_device_client = IoTHubDeviceClient.create_from_x509_certificate(
            hostname=provisioning_host,
            device_id=registration_id,
            x509=x509
        )
        #provisioning_device_client = ProvisioningDeviceClient.create_from_x509_certificate(
        #    provisioning_host=provisioning_host,
        #    registration_id=registration_id,
        #    id_scope=id_scope,
        #    x509=x509,
        #)

        #return await provisioning_device_client.register()
        return provisioning_device_client.connect()

    results = await asyncio.gather(register_device())
    registration_result = results[0]
    print("The complete registration result is")
    print(registration_result.registration_state)


if __name__ == "__main__":
    asyncio.run(main())
`

I still get the error.  I'm on linux and used the certGen.sh command.  I still get the same error, and I'm thinking that this may be because my device certificate is not signed by the iot-edge-device-ca-iotedge.device.CA.cert.pem but is signed by my intermediate cert (which that CA cert is also signed by).  

I have in the config.yaml for the edge device the iot-edge-device-ca* certificates and key, with the trusted CA cert being the root ca cert.

**Comment by secretsquirell** [comment]
i changed the trusted CA cert in the edge config, and this code seems to work fine now
`import os
import asyncio
from azure.iot.device import X509
from azure.iot.device.aio import ProvisioningDeviceClient,IoTHubDeviceClient

provisioning_host = os.getenv("PROVISIONING_HOST")
id_scope = os.getenv("PROVISIONING_IDSCOPE")
registration_id = os.getenv("DPS_X509_REGISTRATION_ID")


async def main():
    async def register_device():
        x509 = X509(
            cert_file=os.getenv("X509_CERT_FILE"),
            key_file=os.getenv("X509_KEY_FILE"),
            pass_phrase=os.getenv("PASS_PHRASE"),
        )
        provisioning_device_client = IoTHubDeviceClient.create_from_x509_certificate(
            hostname=provisioning_host,
            device_id=registration_id,
            x509=x509
        )
        #provisioning_device_client = ProvisioningDeviceClient.create_from_x509_certificate(
        #    provisioning_host=provisioning_host,
        #    registration_id=registration_id,
        #    id_scope=id_scope,
        #    x509=x509,
        #)

        #return await provisioning_device_client.register()
        provisioning_device_client.connect()



if __name__ == "__main__":
    asyncio.run(main())`

**Comment by secretsquirell** [comment]
however when I try and run the sample send_message_x509.py I get the same error condition.

**Comment by BertKleewein** [comment]
> The correct flow here is to have the leaf devices themselves talk directly to DPS to provision, and then use that certificate to talk to the Edge device.

@kkdawkins - are you saying that it should be possible to use x509 auth to connect a leaf device to iothub using edgehub as a proxy?  I'm having a hard time wrapping my head around how this would work.  I've only used edge as a gateway for leaf devices with symmetric key and _server-side_ SSL.  If you're using x509 auth for your leaf device, that means you're using _client-side_ SSL.  Is this even possible?

**Comment by secretsquirell** [comment]
Why would I not be able to connect my leaf device to my edge using x509.  T have traced the network connection and the ssl handshake with the edge as the ssl server works fine.  What seems to be failing is the authentication at the mqtt layer.   The edgeHub container logs bear this out,  they show a failure to establish an identity for the device.   Using a shared symmetric key is imo less robust than individual x509 certificates for the devices.  Especially when the actual devices connecting to the edge device will have tpm to secure the keys.

**Comment by vipeller** [comment]
@BertKleewein the two x509 related client authentication is the thumbprint and CA-based. In the first case the hash of the certificate is assigned to the device, in the second a root ca. Edge is able to ask this configuration from IoT Hub (e.g. the cert thumbprint for the device).
When the device connects to edge, edge will request for client authentication (it sends the certificate request msg at TLS level), so the client (device) will send its certificate and authenticates itself using it. At this point edge will know that the device has a certificate and will receive a copy of that certificate (through the TLS handshake). 
If the device is set up using thumbprint, then Edge will calculate the hash of the client certificate and compares it with the information it acquired earlier from iot-hub. If it CA-based, then checks that the client certificate(chain) can be derived from the configured CA)

**Comment by vipeller** [comment]
@secretsquirell if you open the certificate you are using with the device, and check its thumbprint, can you compare it with the configuration at the azure portal for the device?

**Comment by secretsquirell** [comment]
@vipeller    I am using a CA based certificate, not the thumbprint.  I followed the MS instructions using the certGen.sh script.   
I have the following certificate chain for the certificate that i'm using on the device 
azure-iot-test-only.root.ca -> azure-iot-test-only-intermediate-cert -> iot-edge-device-identity-piiot

I have successfully connected the device using these certs using DPS (i've disconnected my DPS instance from my Hub).  I think the best thing for me to do is to go back to the beginning and generate new certs, test connectivity to the hub without the DPS and then add back in the edge device.

**Comment by secretsquirell** [comment]
I went back and recreated everything from scratch.  Followed [https://github.com/Azure/azure-iot-sdk-c/blob/master/tools/CACertificates/CACertificateOverview.md](url)
for the creation of the test CA cert, added the CA certificate to the Hub.

Created my device cert with
`certGen.sh create_device_certificate piiot`

Added the device piiot to the hub as being authenticated using a CA certificate.  Within the git clone of the python sdk, i ran send_message_x509.py    set the hostname env variable to be the hostname of my hub.  the device id env variable is set to piiot.

Connecting directly to the hub with the send_message_x509.py  I end up getting the same error in the MQTT layer.  (I previously had registered the device with DPS, but I'm taking that out of the equation).

I went back and deleted the device and re-created it in the hub, this time using thumbprint for identification,  All worked fine.  So its definately something related to the verification of my certificates.

**Comment by secretsquirell** [comment]
I re-configured back to CA, and this time I specified the full chain cert for the device an that worked fine.  So i'm at a point where I can send messages from my device directly to my hub.

**Comment by vipeller** [comment]
@secretsquirell Sorry, but I am a bit lost where we are now, can we recap:

we are talking about "edge-device" and "downstream-device", and three configuration steps:
a) configure "edge-device", so it can connect to iot-hub
b) configure "downstream-device", so iot-hub can authenticate it
c) configure "downstream-device", so it will know "edge-device"

I suppose you never had problem with a).
from your latest message, it tells me, you solved b) using x509 CA-Signed
c) basically means that "downstream-device" should know the TLS certificate chain of "edge-device". Usually it needs to install the certificate chain to "downstream-device". 

Now if c) works with symmetric keys (which means that you installed the correct certificate chain to "downstream-device", so it cant connect using TLS to "edge-device"), and you solved b), if you just re-point your "downstream-device" to "edge-device" instead of the hub, it should work (and repointing means that you add the 'GatewayHostName=xxx to your connection string, which worked in case b)

can you confirm that you passed a) and b)

When we are talking about c) can you confirm that it worked with symmetric keys (or self signed certs = thumbprint)?

If c) never worked with symmetric key/thumbprint, it was because you haven't tried, or you tried and didn't work? If you never tried, maybe it is worth it, because that gives a hint that which party isn't happy.

**Comment by secretsquirell** [comment]
Yes a) and b) worked.   For C i'm not specifying a connection string.  I'm using the IotHubDeviceClient.Create_from_x509_certificate method.  and simply setting the HOSTNAME environment variable to be the hostname of my edge device.

After mucking with the certificates on the Edge device and on the downstream device, i got it to work.  I'm not exactly sure what I did,  i ended up generating new edge_device ca certs, and once i got the CN to match (i had to set in /etc/hosts the ipaddress for my edge (which is iotedge.home, through my dns, but i set in /etc/hosts to iotedge) device, everything worked and at least the send_message_x509.py module says its sending messages.   the logs from the edgeHub container on the edge device indicate that the traffic is going through it.  So it seems to have worked.  I'll set up another downstream device and see if i can document what i did.

The certificate chain presented to the downstream device by the edge is
`Certificate chain
 0 s:CN = iotedge
   i:CN = iotedged workload ca
 1 s:CN = iotedged workload ca
   i:CN = iotedge.home.ca
 2 s:CN = iotedge.home.ca
   i:CN = Azure_IoT_Hub_Intermediate_Cert_Test_Only
 3 s:CN = Azure_IoT_Hub_Intermediate_Cert_Test_Only
   i:CN = Azure_IoT_Hub_CA_Cert_Test_Only`

which i find interesting since I ever created a cert with a CN of iotedge.  I'm thinking that the edge device creates both it and the workload ca at some point, based on the hostname.

So the net is I did get this to work as I expected.  So i'm going to close this.

**Comment by az-iot-builder-01** [comment]
@secretsquirell, @vipeller, @kkdawkins, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
