### ISSUE TITLE
AMQP Supported Anymore?

### ISSUE THREAD

**Issue by josiahlaivins** [Azure/azure-iot-sdk-python#375]
We have found that the MQTT packet size is too small for the messages we need to send. Working with the new `IoTHubModuleClient` has made things easy, however we need to change the protocol being used. 

Interestingly there seems to have been AMQP support as seen in #178 , however this was for Python 2.7 and the Transport provider does not seem to be present anymore. 

We see that there is a `MQTTTransport` object and a corresponding transport stage / pipeline. Are there plans for a AMQP implementation / Is there a way to easily switch protocols?

**Comment by YoDaMa** [comment]
Hey @josiahlaivins

We will not support AMQP in V2 of the Python SDK. In addition to that we are deprecating V1 of the Python SDK. 

If you want to use the Python SDK, make sure you are using V2, which is on pip as `azure-iot-device`. 

More information on the Device SDK is in the readme:
https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/README.md

**Comment by josiahlaivins** [comment]
Thanks for the reply @YoDaMa 

We are sending base64encoded images. Currently we can only send one image per message, which can make response times too slow if we are processing a lot of images. We would like to send batches of images, however the MQTT max size is too small (it seems) because 2 images in JSON causes out of memory errors (?). 256 mb does seem large enough though... 

Sending a single image is fine, but 2 causes out of memory so I guessed that I was reaching a max size limit. If it is possible that something else is happening, I'll create a formal issue with the out of memory errors detailed.

**Comment by YoDaMa** [comment]
@josiahlaivins Here's my suggestion, wait until we get uploadToBlob completed. We're actively working on implementing it. That'll connect to Azure Storage, and is more suitable to handling 150mb of data, and can do parallel uploads.

**Comment by josiahlaivins** [comment]
@YoDaMa We were considering blob storage also. I neglected to mention this is messaging between containers on the same device. Messages are nicer than volumes since we want to keep containers as decoupled as possible / can attach extra information.

Do you think, for "messaging between docker containers", it is possible to use a local blob storage docker container to handle this?

**Comment by YoDaMa** [comment]
That, I don't know enough about to give you a proper answer. Let me see if I can talk to someone in Azure Storage who would know more.

**Comment by jebrando** [comment]
@josiahlaivins We believe that "messaging between docker containers" is doable using local storage, but it may be a little complicated.  I'm closing this issue now, but if you have any further questions feel free to open another issue or reopen this one.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @josiahlaivins, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by deeTEEcee** [comment]
> The max message size for MQTT is 256MB... Which is fairly large.

But there's this condition `message.get_size() > device_constant.TELEMETRY_MESSAGE_SIZE_LIMIT` which limits it to 256 KB? Or were we just saying using mqtt directly with `paho.mqtt` allows a large size.

**Comment by vishnureddy17** [comment]
@deeTEEcee, the limit of 256KB is a quota on the Azure IoT Hub Service. The SDK checks the size of the message so users don't send telemetry that is not allowed by the service. 

See the doc here:
https://learn.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-quotas-throttling#other-limits
