### ISSUE TITLE
Timeout not working as expected with MQTT

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#38]
Ubuntu 14.04
Master Branch
Python 2.7.6

Protocol:  MQTT

Timeouts are taking longer than I expect, in the example below my expectation is 5 seconds for timeout. I believe I am setting the timeout setting properly.

I am testing this by allowing the code to proceed all the way to the first print statement, where I have a breakpoint. I then disconnect my eth0 and wait for the timeout.

Code Snippet
```
        self.client.set_option("messageTimeout", 5)

        .....

        print time.time()
        self.client.send_event_async(event, send_confirmation_callback, 1)
        
        while WAITING_ON_RESPONSE:
            time.sleep(.250)

        print CONFIRMATION_RESULT
        if CONFIRMATION_RESULT == IoTHubClientConfirmationResult.MESSAGE_TIMEOUT:
            print "timeout"
            print time.time()
```

The log output

```
1496425120.14
MESSAGE_TIMEOUT
timeout
1496425242.05
```

**Comment by chrit-msft** [comment]
@bearrito thanks for reporting this issue.  I will work getting a local repro and provide updates as I have them.

**Comment by bearrito** [comment]
No problem! 

Please do let me know if you need any help. I'm happy to pull a bugfix branch and try on my side.

**Comment by chrit-msft** [comment]
@bearrito in reviewing the sample, MESSAGE_TIMEOUT is declared in milliseconds, are you sure you have set your value to 5 seconds, not 5 milliseconds?
```python
# messageTimeout - the maximum time in milliseconds until a message times out.
# The timeout period starts at IoTHubClient.send_event_async.
# By default, messages do not expire.
MESSAGE_TIMEOUT = 50000
```
This declares the timeout as 50 seconds.

**Comment by bearrito** [comment]
I'll check, but that seems like it would strengthen the case for timeout having a bug?

**Comment by bearrito** [comment]
Went back and checked. Looks like a problem in the way we were building clients.

For any future readers, I can attest this is working fine with the master branch at the time of writing.
