### ISSUE TITLE
Unable to connect and receive_twin_desired_properties_patch 

### ISSUE THREAD

**Issue by livneros** [Azure/azure-iot-sdk-python#382]
Hi, I'm using a simple code based on this functionality: 
```
device_client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)
await device_client.connect()
desired = await device_client.receive_twin_desired_properties_patch()
```
While yesterday it worked perfectly, today im suddenly getting this (common) error:
```
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None
ERROR: MQTTTransportStage: _on_mqtt_disconnect called: Out of memory.
ERROR: Exception caught in background thread.  Unable to handle.
azure.iot.device.common.transport_exceptions.ProtocolClientError: Out of memory.
```
Any ideas?

**Comment by BertKleewein** [comment]
Lately I've been seeing intermittent connection failures due to SSL handshake issues.  If so, Pull #389 should address this (and, theoretically, other ConnectionDroppedError cases).  One way to know for sure is to set the logging level to DEBUG and look at the stack that gets logged right after "disconnected with result code:".

**Comment by BertKleewein** [comment]
Hi @livneros ,
Can you please try your scenario with our rc13 release and report your results?
https://pypi.org/project/azure-iot-device/2.0.0rc13/

**Comment by livneros** [comment]
@BertKleewein 
Thanks for your help!
I tried to run it as you said and those are the results (attached as a screenshot as well):
[2019-11-25 15:58:36,127] - ERROR: MQTTTransportStage: _on_mqtt_disconnect called: Paho returned rc==1 caused by None
[2019-11-25 15:58:36,130] - ERROR: Exception caught in background thread.  Unable to handle.
[2019-11-25 15:58:36,131] - ERROR: ['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None caused by Paho r                                                                                eturned rc==1 caused by None\n']
![image](https://user-images.githubusercontent.com/42512692/69556497-7b437a00-0fad-11ea-88c2-a6398856448b.png)
It works, but those errors are making it muck more difficult to detect any other issues..
Thanks,
Livne.

**Comment by BertKleewein** [comment]
That's a good point.  Those are really warnings because our SDK _should_ be recovering and reconnecting.  I'm looking for a component further on called the ReconnectStage.  This should be noticing that the connection dropped and it should reconnect.

**Comment by lokijota** [comment]
> Lately I've been seeing intermittent connection failures due to SSL handshake issues. If so, Pull #389 should address this (and, theoretically, other ConnectionDroppedError cases). One way to know for sure is to set the logging level to DEBUG and look at the stack that gets logged right after "disconnected with result code:".

How do I set the logging level to DEBUG?

**Comment by BertKleewein** [comment]
@lokijota, to set a default level (DEBUG, INFO, WARNING, or ERROR):
```
import logging
logging.basicConfig(level=logging.INFO)
```

or, for an individual component:
```
import logging
logging.getLogger("azure.iot.device").setLevel(level=logging.DEBUG)
```

**Comment by BertKleewein** [comment]
azure-iot-device 2.1.1 should resolve these issues.  Since the original issue which started this thread is very old, the information in here is no longer pertinent.  If you discover any connection issues after upgrading to 2.1.1, please open a new issue.

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @livneros, @lokijota, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
