### ISSUE TITLE
Registering without registration ID

### ISSUE THREAD

**Issue by OYTIS** [Azure/azure-iot-sdk-python#385]
In C SDK it is possible to register a device knowing only global_prov_uri and ID scope (see e.g. https://github.com/Azure/azure-iot-sdk-c/blob/master/provisioning_client/samples/prov_dev_client_ll_sample/prov_dev_client_ll_sample.c).

Now in the registration samples for python DPS registration ID is also passed (see e.g. https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/advanced-hub-scenarios/provision_x509.py). Is it possible to do the registration without knowing the registration ID? As far as I understand, it can be extracted from the X509 certificate as its CN, but still would be great to avoid parsing it in the application.

**Comment by olivakar** [comment]
As of now using the V2 SDK it is not possible to provision without knowing the registration id.

Extraction from the certificate is a possibility but this is definitely an enhancement that we have to do a feasibility analysis of.

**Comment by elhorton** [comment]
closing this issue based on inactivity. Thank you for contributing this feedback! We've added provisioning a device without registration ID to a list of features to be considered moving forward.

**Comment by az-iot-builder-01** [comment]
@OYTIS, @elhorton, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
