### ISSUE TITLE
Build IoT SDK Python Samples failed in VS 2017

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-iot-sdk-python#39]
Hi,

I was trying to [build](https://github.com/melzoghbi/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#build-the-python-device-and-service-client-modules-on-windows-using-nuget-packages-recommended) python SDK on my windows 10 dev machine. I was not able to build the Python SDK samples even after i tried to upgrade the VS solutions to use VS 2017 latest build tools. when i execute a build using build.cmd i get the following error:

![image](https://cloud.githubusercontent.com/assets/11993393/26797658/96d05d8a-49fb-11e7-95d0-18ab988f13bc.png)

**Comment by tameraw** [comment]
@melzoghbi - We captured this in our backlog and will address it.

**Comment by zolvarga** [comment]
@melzoghbi,

For building the binaries please use build_client.cmd, that should works. The build.cmd is obsolete and we will delete it.

Best Regards,
Zoltan

**Comment by melzoghbi** [comment]
Thanks @tameraw and @zolvarga will give it a shot! i switched to NodeJS SDK since i found out we are not supporting Raspbian Jessie on ARMv6 yet.
