### ISSUE TITLE
Is IoTHubDeviceClient threadsafe?

### ISSUE THREAD

**Issue by weeotch** [Azure/azure-iot-sdk-python#393]
I'm trying to use the python 2.7 compatible SDK to enable communication over all of the IoT Hub channels at once:

- Receiving cloud to device messages
- Receiving direct method invocations and sending a response
- Responding to device twin updates
- Sending device to cloud messages
- Sending device twin updates

What I'm running into is that each of these channels requires polling for messages and the calls are blocking by default.  I can use a thread per channel (IE one thread to poll for cloud to device messages, another thread to poll for direct method invocations, yet another thread to poll for device twin updates, etc.) but each of the calls has to be made on the same client object. Is this acceptable? Is the IoTHubDeviceClient class threadsafe? I can't really lock around the object because of the blocking behavior and I haven't found much in the way of documentation describing what these methods do when blocking=False.

**Comment by BertKleewein** [comment]
Hi @weeotch, the SDK should be completely threadsafe.  You shouldn't have any reason to lock around the object.  If you do need to lock, that's a bug.

Regarding your scenario, there are two different ways to do this, and both are acceptable.  The first is to spin up one thread per channel as you describe above.  The other is to poll each channel in turn using block=False and an an optional timeout.

The documentation is a work in progress and the best I can provide now is in the code at https://github.com/Azure/azure-iot-sdk-python/blob/37a44d60973b5475a7c28f895d79a83826e9e84f/azure-iot-device/azure/iot/device/iothub/sync_inbox.py#L89

In short:
* If blocking=False and timeout=0, the get() method will either return the next message immediately or immediately raise a (poorly named) `InboxEmpty` exception.   
* If blocking = False and timeout is a number, it will return the next message (if available).  If no message is immediately available, it will wait up to `timeout` seconds for a message to return, and it will raise an `InboxEmpty` exception if nothing arrives in that time.

There are tradeoffs between these two approaches, namely between the overhead of spinning up extra threads versus the overhead of polling  (if the timeout is low) or the latency you can introduce with polling (if the timeout is high).

**Comment by BertKleewein** [comment]
@weeotch - can you confirm that this answers your question?

**Comment by jebrando** [comment]
@weeotch If you have any more question please feel free to open a new issue.

**Comment by az-iot-builder-01** [comment]
@weeotch, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
