### ISSUE TITLE
Accessing Payload message in receive_method_request(method_name="XXXX")

### ISSUE THREAD

**Issue by jaypaddy** [Azure/azure-iot-sdk-python#396]
Not sure what i should do to access the message payload coming through receive_method_request.

The line print("Payload:" + method_request.data ), seems to hang and hence the direct method fails to send message from Azure Portal. When i remove the statement print("Payload:" + method_request.data ), everything works correct. However i still don;'t know how to get access to the payload  coming through Direct method

        async def method_listener(module_client):
            while True:
                method_request = await module_client.receive_method_request("ams")
                # Wait for unknown method calls
                payload = {"result": True, "data": "Received"}  # set response payload
                status = 200  # set return status code
                print("executed method: " + method_request.name)
                print("Payload:" + method_request.data )
                method_response = MethodResponse.create_from_method_request(
                    method_request, status, payload
                )
                await module_client.send_method_response(method_response)  # send response

**Comment by olivakar** [comment]
I am not exactly sure why the line will hang but the `MethodRequest` object in the azure-iot-sdk-python has no attribute called `data`. The attribute you may be looking for is payload.

**Comment by jebrando** [comment]
@jaypaddy If you are still experiencing an issue please reopen this issue

**Comment by az-iot-builder-01** [comment]
@jaypaddy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
