### ISSUE TITLE
Python IoTHub package should be under Microsoft banner

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-iot-sdk-python#4]
Hello,

The [IoTHub package](https://pypi.python.org/pypi/iothub-client/) should be also owned by the Microsoft account. We are "One microsoft", and this helps people to have confidence and allows them to find [all Microsoft packages in one page](https://pypi.org/user/microsoft/).

Account is managed by @zooba and @brettcannon , we do not claim ownership or something, it's just a way to group packages unto the Microsoft banner.

**Comment by zolvarga** [comment]
Hi Imazuel,

We are planning to release on 13th of January and we will move our packages under Microsoft baner in that release. 

Thanks,
Zoltan

**Comment by zolvarga** [comment]
New release (2017 01 17) of the packages added to the Microsoft banner.

Best Regards,
Zoltan
