### ISSUE TITLE
azure_iothub_device_client for Raspbian Jessie is not found

### ISSUE THREAD

**Issue by melzoghbi** [Azure/azure-iot-sdk-python#40]
Hi,

I was trying to run "iot_hub_client_sample.py" sample app from my Pi Zero. It seems that there is no build for Raspbian Jessie for his package. Is there any workaround for this? 

![image](https://cloud.githubusercontent.com/assets/11993393/26801406/cb311394-4a0a-11e7-8d1f-08260cf5209c.png)

I want to be able to run python apps that integrates with IoT Hub from my Pi Zero W device. Any direction is appreciate it.

Thanks.

**Comment by tameraw** [comment]
@melzoghbi - Currently we do not have a Python package for Linux as of yet. We're looking into that.
Meanwhile, please follow the instructions to clone and build.

**Comment by 5nowx** [comment]
Hey @melzoghbi 

You have to build it according to [https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#linux](url)

# Previously you need to:

- increase SWAPSIZE  inside /etc/dphys-swapfile . Also do a /etc/dphys-swapfile restart to load the settings.
- install gcc/build/curl/lib-curl-openssl-dev/libssl-dev/uuid-dev/libboost-all-dev

I've run the the samples in a rpi Zero using this methods

Good luck with that!

**Comment by tameraw** [comment]
We now provide pip packages for Linux and Raspberry Pi.

Please give it a try and let us know if you encounter any issues.
