### ISSUE TITLE
Checking if there is a connection

### ISSUE THREAD

**Issue by San42** [Azure/azure-iot-sdk-python#401]
Hi, so I am looking for a function which checks if there is a connection established to the azure iothub server? Maybe returns a boolean or 0/1.  Currently I am using client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING) and then client.connect(). Thanks!

**Comment by jebrando** [comment]
@San42 Yes, this is a gap in the current SDK.  We will be looking into this right after GA and will keep this item open for tracking.

**Comment by maheshcv** [comment]
I would be interested when this feature is ready

**Comment by BertKleewein** [comment]
Completed with commit #427

**Comment by az-iot-builder-01** [comment]
@San42, @maheshcv, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by maheshcv** [comment]
Thank you Bert. Appreciate you implementing this. This will help improve the efficiency of the solution for communicating between Azure IoT Client and Azure IoT hub. Thanks much!!
