### ISSUE TITLE
Question: Using azure-iot-sdk-python with a serial connection (UART) to a modem

### ISSUE THREAD

**Issue by jflynn129** [Azure/azure-iot-sdk-python#404]
I would like to use Python to connect to an IoT Hub for data reporting.  Looking at the Samples that are provided it looks pretty straight forward, but the examples are running on (in my case) Linux and appear to be using the standard eth interface for communication with Azure IoTHub.  For me to use with my target, I need to have it communicate using a serial port and AT commands.  I was planning on creating a shim to translate the commands into the appropriate AT commands then send/receive the response via a UART.  

Looking through the code and documents, it isn't obvious where in the Python code the communications are taking place.  Is the Python SDK simply using the Azure embedded SDK for its low level transport?  I was hoping to simply use the Python Serial library and was hoping you could provide some insight and/or documents that describe the communications transport that is being used.

Thanks.

**Comment by Alberto-Vega-MSFT** [comment]
For more info see the post on MSDN for the same question: https://social.msdn.microsoft.com/Forums/en-US/a394ac52-d37f-482e-9bdd-7d5338a7c067/connecting-to-iot-hub-using-python-and-a-uart-transport?forum=azureiothub

**Comment by az-iot-builder-01** [comment]
@jflynn129, @Alberto-Vega-MSFT, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by Alberto-Vega-MSFT** [comment]
@jflynn129 I apologize for the delay. I see that you closed this issue but I am not sure if you were able to resolve it?

**Comment by jflynn129** [comment]
No, I saw where you pointed me to the MSDN post so was expecting to hear back on that one rather than this.

**Comment by Alberto-Vega-MSFT** [comment]
@jflynn129 I reached out internally and we do not have a sample using a serial port to connect over MQTT. I was pointed to Paho but does not seem to have an easy to support this configuration. As a starting point for exploration, the code that opens the socket is here:
https://github.com/eclipse/paho.mqtt.python/blob/1eec03edf39128e461e6729694cf5d7c1959e5e4/src/paho/mqtt/client.py#L3508
