### ISSUE TITLE
Route Message from IoT Device Module

### ISSUE THREAD

**Issue by junsaw** [Azure/azure-iot-sdk-python#406]
Hey All,

I am trying to determine what is the best process for capturing and/or routing messages from an Azure IoT Device Module to the Azure IoT Hub. 

Any help will be much appreciated.

Thanks Alot 

Regards
Junior

**Comment by BertKleewein** [comment]
Hi @junsaw,

The most basic way to send messages is to use the send_message method.  I would recommend starting with this quickstart: https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-python.

If this doesn't answer your question, could you provide more detail please?  If you don't want to post confidential information on your scenarios, we could certainly take this conversation offline.  

-Bert

**Comment by junsaw** [comment]
Hey @BertKleewein,

Thanks for the reply, I do apologize for the delay in my response, I noticed I am using the Python V1 library let me first transition to V2 and see if the problem still exists.

Will post an update in the coming days.

Regards
Junior

**Comment by junsaw** [comment]
Hey @BertKleewein 

I updated my code to use the newer version of the Azure IoT Python module **(V2)** and I am now able to see messages sent from a device module to my IoT Hub.  This issue is now resolved.

Thanks for the follow up once again.

Junior

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @junsaw, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
