### ISSUE TITLE
Error in sample from Windows

### ISSUE THREAD

**Issue by Moncefmd** [Azure/azure-iot-sdk-python#41]
- **OS and version used:** Windows 10 

- **Python runtime used:** Python 3.4.3 

- **SDK version used:** azure-iothub-device-client 1.1.16.0 

# Description of the issue:

I installed successfully through pip the azure-iothub-device-client (1.1.16.0) but when I try to import iothub_client (as in the samples given in the project) I get the error below. 

# Code sample exhibiting the issue:

import iothub_client

# Console log of the issue:

C:\Python34\python.exe C:/[securePath]/main.py
Traceback (most recent call last):
  File "C:/[securePath]/main.py", line 11, in <module>
    import iothub_client
  File "C:\Python34\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

Process finished with exit code 1

**Comment by zolvarga** [comment]
@Moncefmd 
I could not repro the issue and for further investigation please provide the following information:
- the list of file of the folder where you want to run the sample from
- run the command "pip freeze: and paste the output here

Best Regards,
Zoltan

**Comment by Moncefmd** [comment]
My goal was originally to copy the mqtt sample into a file in Pycharm and run it. 
I installed the package through pip and but even just importing the package outputs the error message above. So there is no other file in the folder where I run the sample from (at this point, I am just trying to import the iothub_client module and to access items from it).

Here is the pip freeze command output : 
C:\Users\Moncefmd>pip freeze
appdirs==1.4.3
azure-iothub-device-client==1.1.16.0
certifi==2017.4.17
chardet==3.0.4
click==6.7
cycler==0.10.0
dask==0.14.3
decorator==4.0.11
Django==1.11.2
Flask==0.12.2
idna==2.5
itsdangerous==0.24
Jinja2==2.9.6
MarkupSafe==1.0
matplotlib==2.0.2
numpy==1.13.0
olefile==0.44
packaging==16.8
Pillow==4.1.1
pyparsing==2.2.0
python-dateutil==2.6.0
pytz==2017.2
requests==2.17.3
six==1.10.0
toolz==0.8.2
urllib3==1.21.1
Werkzeug==0.12.2

**Comment by Moncefmd** [comment]
(Accidently closed the issue, sorry about that)

**Comment by zolvarga** [comment]
@Moncefmd 

To narrow down the issue, please try the following:
Create a new folder somewhere
Copy the sample files into the new folder:
- iothub_client_args.py
- iothub_client_cert.py
- iothub_client_sample.py

Run this command from the folder: 
python iothub_client_sample.py -p mqtt -c <DEVICE_CONNECTION_STRING>

If it works, you have a configuration issue with PyCharm.

Please let me know,
Zoltan

**Comment by Moncefmd** [comment]
Here is the output that I have : 

Microsoft Windows [Version 10.0.15063]
(c) 2017 Microsoft Corporation. All rights reserved.

C:\dev>dir
 Directory of C:\dev

06/13/2017  01:59 PM    <DIR>          .
06/13/2017  01:59 PM    <DIR>          ..
06/13/2017  01:59 PM    <DIR>          .idea
06/13/2017  01:59 PM             2,920 iothub_client_args.py
06/13/2017  01:59 PM             7,518 iothub_client_cert.py
06/13/2017  01:57 PM             9,718 iothub_client_sample.py
               3 File(s)         20,156 bytes
               3 Dir(s)  143,395,368,960 bytes free

C:\dev>python iothub_client_sample.py -p mqtt -c "HostName=SECURED.azure-devices.net;DeviceId=myDeviceId;SharedAccessKey=Gkhke9GcdXHd878ERR1GqnlAM3jgXwU7bAj3knTGBN4="
Traceback (most recent call last):
  File "iothub_client_sample.py", line 10, in <module>
    import iothub_client
  File "C:\Python34\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

C:\dev>

**Comment by zolvarga** [comment]
@Moncefmd,

I figured out what is the issue on your machine. You need to have c++ runtime installed to load the DLL.
The easiest way to get it working to install Visual Studio (Community edition is enough).

Best Regards,
Zoltan

**Comment by Moncefmd** [comment]
@zolvarga it is a little bit weird because I do have Visual Studio 2017 installed. 
There are also in my programs installed : 
- Microsoft Visual C++ 2010 x86 Runtime - 10.0.4019
- Microsoft Visual C++ 2010 x64 Runtime - 10.0.4019

**Comment by zolvarga** [comment]
@Moncefmd 

I just did the following experiment.
- Installed Windows
- Installed Python
- Got the python repo and built it
- Tried the samples - it did not work, failed with the same error you got

- Installed VS 2017 Community
- Tried the samples - worked fine

I have the following C++ Redistributables installed:
C++ 2013 Redistributable (x64) - 12.0.30501
C++ 2013 Redistributable (x86) - 12.0.30501
C++ 2017 Redistributable (x64) - 14.10.25008
C++ 2017 Redistributable (x86) - 14.10.25008

Also, if you are on 64 bit machine please make sure you have 64 python installed.

Best Regards,
Zoltan

**Comment by sravangopu** [comment]
Hi zolvarga i'm building docker image for azure iot using python 2.7. I too got the same error as tameraw. I understood that I need visual c++ runtime. But how to fetch/install visual c++ runtime through pip.

**Comment by kiran007francis** [comment]
I AM ALSO GETTING THE SAME ERROR. CAN SOMEONE HELP ME

Operating System: Window 10
Language : Python
Version: Python 3.7

I was going through the tutorial given on Azure Portal's IoT Hub for sending telemetry. I am following the python tutorial https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-python .

![azure python tutorial](https://user-images.githubusercontent.com/43568831/46004833-7cd79080-c0d1-11e8-862c-26cbb7fe5017.PNG)

I followed the steps given exactly in the tutorial. The sample code to be executed was also given https://github.com/Azure-Samples/azure-iot-samples-python/archive/master.zip

When i run the **SimulatedDevice.py** in the folder **simulated-device** code i get the following error 

![error](https://user-images.githubusercontent.com/43568831/46004982-d93ab000-c0d1-11e8-8ba0-2db4b1351c5c.PNG)

I also tried the suggestions given on net. I created an anaconda environment in python 3.6 and python 2.7 . But the same error persists. Can someone help with the above issue?

**Comment by kartheekakkur** [comment]
from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

same error

**Comment by pierreca** [comment]
@attitude95 can you verify that you're installing the x64 version of python? it can also happen if you're running python x86 on an x64 machine.

**Comment by pierreca** [comment]
also may happen when the Visual C++ redistributable isn't installed - to cover all bases i'd suggest installing the 2015 and 2017 versions (x64 of course)

**Comment by attitude95** [comment]
@pierreca 
I've installed  Visual C++ redistributable  2017 version (x64) on my computer. I tried to install 2015 version and ended up with an error. Could you please tell me what may be the problem. I'm attaching the error file 
[dd_vcredist_amd64_20181115073634.log](https://github.com/Azure/azure-iot-sdk-python/files/2584158/dd_vcredist_amd64_20181115073634.log)

**Comment by pierreca** [comment]
@attitude95 the error is pretty clear: you've installed 2017 first so 2015 won't install. i'd suggest installing 2015 first, then 2017.

**Comment by attitude95** [comment]
@pierreca 
I uninstalled 2017 version and installed 2015 version. I tried running the code again. It resulted the same. I again installed 2017 version and tried it again. But the problem persists.

Traceback (most recent call last):
  File "SimulatedDevice.py", line 11, in <module>
    import iothub_client
  File "C:\Python35\lib\site-packages\iothub_client\__init__.py", line 1, in <module>
    from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

**Comment by joelcormack** [comment]
I'm getting the same error too.
Windows 10
Python 3.7.1

**Comment by pierreca** [comment]
@joelcormack you will get this error running python 3.7. On Windows, it has to be Python 3.6, the x64 version, and you have to have the VC++ redistributable installed. the reasons why are explained in the readme.

we're working on resolving these issues for good in the long term, but short term you have to play within these limits to use our SDK.

**Comment by aviatoredb** [comment]
Any update on fixing this library to run under python 3.7.x?

**Comment by pierreca** [comment]
@aviatoredb we've started the rewrite of the SDK, hope to have something (maybe not complete, but at least a preview) by January.

**Comment by JoelBennett** [comment]
@pierreca By chance is the rewrite available yet?  I'm on Python 3.7 (x64) and would rather not have to roll back to Python 3.6, if I can help it.

**Comment by pierreca** [comment]
@JoelBennett it's in progress at https://github.com/azure/azure-iot-sdk-python-preview
it's far from full-featured yet but the team is full-speed on it now so we should have a lot more within the next few weeks.
