### ISSUE TITLE
sending c2d impossible in Python?

### ISSUE THREAD

**Issue by radoye** [Azure/azure-iot-sdk-python#411]
What is the preferred/suggested way to send c2d from Python at the moment?

v2 does not support c2d sending?
v1-deprecated is broken; I get behavior similar to #291 
In our case `open_complete_callback` is never executed. I cannot send or close properly!

We're using

  * Python 3.7
  * Ubuntu 18.04 (libboost1.65)

fresh checkout & build of v1-deprecated branch

```
In [22]: import iothub_service_client as iothub

In [23]: cli = iothub.IoTHubMessaging(CONNECTION_STRING)

In [24]: cli.open(open_complete_callback, 1)

In [5]: cli.close()
Error: Time:Fri Dec  6 21:11:54 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:saslclientio_send_async Line:1181 send called while not open
Error: Time:Fri Dec  6 21:11:54 2019 File:/usr/sdk/src/c/uamqp/src/connection.c Func:on_bytes_encoded Line:268 Cannot send encoded bytes
Info: Closing tlsio from a state other than TLSIO_STATE_EXT_OPEN or TLSIO_STATE_EXT_ERROR
Error: Time:Fri Dec  6 21:11:54 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:on_underlying_io_open_complete Line:192 Open complete received in unexpected state
Error: Time:Fri Dec  6 21:11:54 2019 File:/usr/sdk/src/c/uamqp/src/saslclientio.c Func:saslclientio_close_async Line:1130 saslclientio_close called while not open
Error: Time:Fri Dec  6 21:11:54 2019 File:/usr/sdk/src/c/uamqp/src/connection.c Func:connection_close Line:1437 xio_close failed
```

Any pointers to docs/setup that we can use to get around this (before setting up a Java server or something silly like that)? Thanks!

**Comment by jebrando** [comment]
@radoye Your evaluation of the python SDK in sending C2D messages is correct.  

The v2 does not support c2d sending because of technical challenges that we're working to fix, but it will take time to get all the pieces together. 
V1 has some inherent difficulties with the underlying C-SDK which you're seeing.

The question I have is before you build the v1 did you pull try pulling the latest C-SDK, or did you just build what was there?

**Comment by radoye** [comment]
@jebrando Thanks for confirming.

This is what I have in my Dockerfile

```
RUN git clone --recurse-submodules \
      https://github.com/Azure/azure-iot-sdk-python.git ./src && \
      cd src && git checkout origin/v1-deprecated && \
      git submodule update --init --recursive

RUN source env3/bin/activate && \
    ./src/build_all/linux/setup.sh --python-version 3.6 && \
    source env3/bin/activate && \
    ./src/build_all/linux/release.sh --build-python 3.6
```

Current workaround:
  * Java SDK + service wrapper
  * [Py4J](https://www.py4j.org/) server to expose the service wrapper
  * Python client

A bit heavy to get c2d, no? :)

**Comment by jebrando** [comment]
@radoye, @BertKleewein gave me something that may be a sample to unblock you while we get the C2D messages in the v2 SDK:
 
https://github.com/Azure/iot-sdks-e2e-fx/blob/master/test-runner/adapters/direct_azure_rest/amqp_service_client.py

This code will send a C2D message to a device.  Let us know if this works for you.

**Comment by radoye** [comment]
@jebrando thanks, that works!

**Comment by az-iot-builder-01** [comment]
@radoye, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
