### ISSUE TITLE
some problems with the cross-compile  of  azure-iot-sdk-python

### ISSUE THREAD

**Issue by wushichuan** [Azure/azure-iot-sdk-python#42]
**#- OS and version used:**
host：Linux version 3.13.0-32-generic
taget：openwrt 10.03, mtk7621
gcc：toolchain-mipsel_gcc-4.6

**#- Python runtime used:**
python2.7: ELF 32-bit LSB  executable, MIPS, MIPS32 version 1

**- SDK version used:**
azure-iot-sdk-python

**#- Description of the issue:**
Hi, I encountered some problems with the cross compile  of  azure-iot-sdk-python. When I compile the sdk on host system and not cross-compile, everything goes well. But, it always throws me errs:

-- Could NOT find Boost
-- Found PythonLibs: /home/wusc/R200/package/azure-iot/output/Python-2.7.12/lib/libpython2.7.a (found suitable version "2.7.12", minimum required is "2.7") 
-- Could NOT find Boost
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES) (found suitable version "2.7.12", minimum required is "2.7")
CMake Warning at CMakeLists.txt:268 (message):
  This package may only be installed when 'use_installed_dependencies' is ON

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "iothub_service_client_python" in directory /home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src
    linked by target "iothub_service_client_mock" in directory /home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/tests

**# Code sample exhibiting the issue:**
wusc@ff-compiler:~/azure-iot-sdk-python/build_all/linux$  ./build.sh --toolchain-file toolchain-openwrt.cmake -cl -ldl    

**# Console log of the issue:**
-- The C compiler identification is GNU 4.6.3
-- The CXX compiler identification is GNU 4.6.3
-- Check for working C compiler: /home/wusc/R200/package/azure-iot/OpenWrt-Toolchain-mtk762x-for-mipsel-gcc-4.6-linaro_uClibc-0.9.33.2/toolchain-mipsel_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-gcc
-- Check for working C compiler: /home/wusc/R200/package/azure-iot/OpenWrt-Toolchain-mtk762x-for-mipsel-gcc-4.6-linaro_uClibc-0.9.33.2/toolchain-mipsel_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /home/wusc/R200/package/azure-iot/OpenWrt-Toolchain-mtk762x-for-mipsel-gcc-4.6-linaro_uClibc-0.9.33.2/toolchain-mipsel_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-c++
-- Check for working CXX compiler: /home/wusc/R200/package/azure-iot/OpenWrt-Toolchain-mtk762x-for-mipsel-gcc-4.6-linaro_uClibc-0.9.33.2/toolchain-mipsel_gcc-4.6-linaro_uClibc-0.9.33.2/bin/mipsel-openwrt-linux-c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Found OpenSSL: /home/wusc/R200/package/azure-iot/output/openssl-OpenSSL_1_0_2-stable/lib/libssl.a;/home/wusc/R200/package/azure-iot/output/openssl-OpenSSL_1_0_2-stable/lib/libcrypto.a  
-- Shared_Util architecture: GENERIC
-- Performing Test CXX_FLAG_CXX11
-- Performing Test CXX_FLAG_CXX11 - Failed
-- Found PkgConfig: /usr/bin/pkg-config (found version "0.26") 
-- Checking for module 'libcurl'
--   Found libcurl, version 7.35.0
-- Found CURL: curl  
CMake Warning at uamqp/deps/umock-c/CMakeLists.txt:147 (message):
  This package may only be installed when 'use_installed_dependencies' is ON

-- AMQP Target architecture: GENERIC
-- MQTT Target architecture: GENERIC
-- iothub architecture: GENERIC
-- Could NOT find Boost
-- Found PythonLibs: /home/wusc/R200/package/azure-iot/output/Python-2.7.12/lib/libpython2.7.a (found suitable version "2.7.12", minimum required is "2.7") 
-- Could NOT find Boost
-- Could NOT find PythonLibs (missing:  PYTHON_LIBRARIES) (found suitable version "2.7.12", minimum required is "2.7")
CMake Warning at CMakeLists.txt:268 (message):
  This package may only be installed when 'use_installed_dependencies' is ON

CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
PYTHON_LIBRARY (ADVANCED)
    linked by target "iothub_service_client_python" in directory /home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/src
    linked by target "iothub_service_client_mock" in directory /home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/service/tests

-- Configuring incomplete, errors occurred!
See also "/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/c/cmake/iotsdk_linux/CMakeFiles/CMakeOutput.log".
See also "/home/wusc/R200/package/azure-iot/py2.7.12_x86/azure-iot-sdk-python/c/cmake/iotsdk_linux/CMakeFiles/CMakeError.log".

**Comment by wushichuan** [comment]
I had sloved it

**Comment by anhtu91** [comment]
Hi, I also have problem with OpenWrt and python sdk rightnow. I would like to run the sdk on my router, which runs on OpenWrt and has 6MB storage. My question is, how did you bring the python sdk to a small OpenWrt router? Thanks
