### ISSUE TITLE
First 2.0.0 spin with Direct Message to Module on Edge - not working

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#421]
Took the brand new 2.0.0 for a spin (I was really looking forward to that) and it looks promising, but still no success:

```
MQTTTransportStage: _on_mqtt_disconnect called: Paho returned rc==1 caused by None
MQTTTransportStage: disconnection was unexpected
Exception caught in background thread.  Unable to handle.
['azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None caused by Paho returned rc==1 caused by None\n']
MethodInvokeOperation: completing with error HTTP operation returned: 504 GatewayTimeoutError(Error: Gateway Timeout) caused by None
Callback completed with error HTTP operation returned: 504 GatewayTimeoutError(Error: Gateway Timeout) caused by None
azure.iot.device.exceptions.ServiceError: HTTP operation returned: 504 GatewayTimeoutError(Error: Gateway Timeout) caused by None
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/iothub/aio/async_clients.py", line 29, in handle_result
    return await callback.completion()
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/async_adapter.py", line 93, in completion
    return await self.future
  File "/usr/lib/python3.5/asyncio/futures.py", line 380, in __iter__
    yield self  # This tells Task to wait for completion.
  File "/usr/lib/python3.5/asyncio/tasks.py", line 304, in _wakeup
    future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
azure.iot.device.exceptions.ServiceError: HTTP operation returned: 504 GatewayTimeoutError(Error: Gateway Timeout) caused by None

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "dm_2.py", line 42, in <module>
    loop.run_until_complete(main())
  File "/usr/lib/python3.5/asyncio/base_events.py", line 466, in run_until_complete
    return future.result()
  File "/usr/lib/python3.5/asyncio/futures.py", line 293, in result
    raise self._exception
  File "/usr/lib/python3.5/asyncio/tasks.py", line 241, in _step
    result = coro.throw(exc)
  File "dm_2.py", line 30, in main
    device_id="Haven2", module_id="motion-detection", method_params=fake_method_params
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/iothub/aio/async_clients.py", line 466, in invoke_method
    method_response = await handle_result(callback)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/iothub/aio/async_clients.py", line 39, in handle_result
    raise exceptions.ClientError(message="Unexpected failure", cause=e)
azure.iot.device.exceptions.ClientError: Unexpected failure caused by HTTP operation returned: 504 GatewayTimeoutError(Error: Gateway Timeout) caused by None
```

Is the output, when running [https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-edge-scenarios/invoke_method_on_module.py]( https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-edge-scenarios/invoke_method_on_module.py) inside a module on a device. Python 3.5.

**Comment by YoDaMa** [comment]
Hey @njbuch let’s figure out what’s wrong! When you are invoking the method on the target device or module, is the client set up to respond to your specific method invoke parameters? A 504 timeout to me might hint at that. If you could post some anonymized debug logs of the run here too that would be helpful in addition to the stack trace already provided.

**Comment by njbuch** [comment]
> Hey @njbuch let’s figure out what’s wrong! 
Thanks!

>When you are invoking the method on the target device or module, is the client set up to respond to your specific method invoke parameters? A 504 timeout to me might hint at that. 

I have other modules running on the device, and they are in C# and are receiving direct method calls nicely. There is also some C# code running in the same module that can receive direct method calls.

I am running the code linked in the OP out of the box to check that it works, except I have correct the device-name and module-name. So I am calling the "doSomethingInteresting" on the device and module I have specified. Is that what you mean by setup?

> If you could post some anonymized debug logs of the run here too that would be helpful in addition to the stack trace already provided.

Not sure what you mean, I run "python3 sample_code.py" and the output is above.

**Comment by YoDaMa** [comment]
For the logging, add the following lines to your sample code at the very top:

```python
import logging

logger = logging.getLogger('njbuch_app')
logger.setLevel(logging.DEBUG)
```

And, just for due diligence, when you're adjusting the code, you're adding in your respective device_id and module_id, and editing the fake_method_params object so that the methodName is a method that you have enabled on the C# module that is receiving method calls presently? I assume the answer is yes, but want to make sure.

**Comment by njbuch** [comment]
Argh. I misunderstood the purpose. I need code that listen to a method Call inside a module. Sorry. My mistake.

**Comment by az-iot-builder-01** [comment]
@YoDaMa, @njbuch, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
