### ISSUE TITLE
multicast c2d?

### ISSUE THREAD

**Issue by radoye** [Azure/azure-iot-sdk-python#429]
When I have multiple listeners waiting for c2d message only one of them receives. Is this by design or due to something I'm doing wrong? 

Is there a way to multicast, i.e. deliver to all listeners? Replaying last N messages for every listener would also be OK (the way service SDK works when reading messages from iothub). 

We use IoTHub c2d messages to coordinate cloud/edge FSMs. We run multiple services within each system. Single c2d message delivery means we must centralize receiving of c2d which complicates communication between teams.

**Comment by cartertinney** [comment]
This is by design, as each call to  `.receive_message()` will return the latest message, much like a FIFO queue. As such, once a message is returned, it is no longer available to be returned elsewhere.

In order to trigger multiple effects upon receiving a C2D message we recommend a pattern such as the following:

```python
async def on_message_task1(message):
     # do things

async def on_message_task2(message):
    # do other things

async def message_listener(device_client):
    while True:
        message = await device_client.receive_message()
        await asyncio.gather(
            on_message_task1(message),
            on_message_task2(message),
        )
```

If this is insufficient, please let us know more about your scenario, and we'll take your feedback into account for future iterations of the library.

**Comment by radoye** [comment]
@cartertinney Thank you for confirming.

**Comment by az-iot-builder-01** [comment]
@radoye, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by radoye** [comment]
It seems that the Service SDK can have only one reader process, as well. Can you confirm please? When I try to open multiple python instances using the same service connection string, the last one seems to win, and only that one receives the message stream. 

The pattern proposed above can still be used, but it's subject to a single python interpreter and forces coordination between multiple listener services.

**Comment by cartertinney** [comment]
Could you be specific about which API you're referring to in the service library?

**Comment by radoye** [comment]
@cartertinney I'm sorry for the late reply. This ended up on the second page.

At the time I was talking about the `iothub` API. It seems like it can have multiple listeners, but a limited number of those?

**Comment by cartertinney** [comment]
I'm still unclear as to the exact method and library you are referring to. Perhaps a sample would help?

**Comment by elhorton** [comment]
marking closed based on inactivity, if this is still an issue or point of confusion please open a new issue outlining your scenario so we can help accordingly!
