### ISSUE TITLE
No pypi packages for 2.0.1

### ISSUE THREAD

**Issue by LouanDuToitS3** [Azure/azure-iot-sdk-python#440]
Hi,

When will azure-iot-device V2.0.1 be available on Pypi?

[Check Pypi](https://pypi.org/search/?q=azure-iot-device)

**Comment by olivakar** [comment]
are you waiting for some specific feature ?

**Comment by LouanDuToitS3** [comment]
> are you waiting for some specific feature ?

No, not waiting for any specific feature, rather fixes (#401, #399). And obviously, to test for stability and compatibility.

**Comment by robbinvandamme** [comment]
@olivakar I'm waiting for a feature -> iot_device.is_connected().
That's in there right? In V2.0.1.

**Comment by olivakar** [comment]
v2.01 has been released with connected property

**Comment by az-iot-builder-01** [comment]
@LouanDuToitS3, @robbinvandamme, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
