### ISSUE TITLE
Version

### ISSUE THREAD

**Issue by mustafakasap** [Azure/azure-iot-sdk-python#449]
azure.iot.device.VERSION not working.

**Comment by olivakar** [comment]
How are you trying to access it ?

**Comment by mustafakasap** [comment]
like in the Azure Machine Learning Python SDK:

# Check AzureML SDK installation
import azureml.core

try:
    # display the core SDK version number
    print('Azure ML SDK Version: {0}'.format(**azureml.core.VERSION**))
except:
    print('Azure ML SDK not available.')

**Comment by olivakar** [comment]
Our package is `azure.iot.device`

The best way to import is `from azure.iot.device.constant import VERSION`
OR `from azure.iot.device import constant` and then use `constant.VERSION`

**Comment by mustafakasap** [comment]
That is the reason I wrote "like" the machine learning SDK and gave a sample.

I thought all Azure SDKs have the same experience. What ML SDK provides, something like very standard Python lib feature, i.e. cv.__version__  or np.__version__ (as in numpy and opencv libs...)

anyway , thanks
from azure.iot.device.constant import VERSION
works fine

**Comment by az-iot-builder-01** [comment]
@mustafakasap, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
