### ISSUE TITLE
./setup.sh: line 13: ./c/build_all/linux/setup.sh: No such file or directory

### ISSUE THREAD

**Issue by PREM1980** [Azure/azure-iot-sdk-python#45]
- **OS and version used:** Linux 6d8edc4b4e3f 4.9.13-moby #1 SMP Sat Mar 25 02:48:44 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux (Docker ubuntu image)

- **Python runtime used:** python2.7.2

- **SDK version used:** latest download

# Description of the issue:
Im trying to setup the env and inside the folder build_all/linux i tried to run the command ./setup.sh but get the following error.

python: can't open file 'version': [Errno 2] No such file or directory

# Code sample exhibiting the issue:

# Console log of the issue:
(bossa) docker@6d8edc4b4e3f:~/bossa/azure-iot-sdk-python/build_all/linux$ python version
python: can't open file 'version': [Errno 2] No such file or directory

**Comment by 0916174** [comment]
When cloning the repository, be sure to use `--recursive` like this:

`git clone https://github.com/Azure/azure-iot-sdk-python --recursive`

**Comment by bsafwen** [comment]
setup.sh: line 13:
13c13
< ./c/build_all/linux/setup.sh 
---
> ./build_all/linux/setup.sh

**Comment by bsafwen** [comment]
The problem is that when we clone the repo, the c directory is empty.

**Comment by zolvarga** [comment]
When you are cloning the repo use the "submodule update --init --recursive" options.
With that, all the submodules will be cloned and updated.

Best Regards,
Zoltan

**Comment by bsafwen** [comment]
@zolvarga I think this should be mentioned in the docs.

**Comment by tameraw** [comment]
@bsafwen - It is mentioned in the readme section below:
https://github.com/Azure/azure-iot-sdk-python#how-to-clone-the-repository
