### ISSUE TITLE
Remove Preview notice from pypi.org page

### ISSUE THREAD

**Issue by sebader** [Azure/azure-iot-sdk-python#452]
https://pypi.org/project/azure-iot-device/ still says "SDK is in preview". Should be removed now that it's GA.

![image](https://user-images.githubusercontent.com/11445087/73546690-f017b200-443d-11ea-88f7-3fe3bced17d3.png)

**Comment by jebrando** [comment]
@sebader Thanks for the heads up.  We will get this taken care of.

**Comment by olivakar** [comment]
The new release should have taken care of this.

**Comment by az-iot-builder-01** [comment]
@sebader, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
