### ISSUE TITLE
[Azure IoT Python SDK V2] Availability feature Cloud-to-device messaging

### ISSUE THREAD

**Issue by damienklotz77** [Azure/azure-iot-sdk-python#458]
Hi,

I plan to use version V2 of "Azure IoT Python SDK".

Following Git Hub page :
https://github.com/Azure/azure-iot-sdk-python
feature "Cloud-to-device messaging" is currently in status "feature planned but not yet supported".

When this feature will be supported ?

Regards,

Damien KLOTZ

**Comment by jebrando** [comment]
@damienklotz77 We are working on being a resolution to this issue.  There are a few technical hurdles that we need to solve for this.  I will keep this issue up to date on when this feature is available.

**Comment by HoLue** [comment]
@jebrando Is there any rough timeline when it will be available?

**Comment by jebrando** [comment]
@HoLue I have a PR to add this now.  This will have to go through our check in process, but I envision that by next week this will be in and then a release will happen shortly after that.  If any issues arise I will report back on this thread.

**Comment by damienklotz77** [comment]
Thank you for the information. I'm looking forward to it.

**Comment by jebrando** [comment]
Cloud-to-device messaging is now supported in the SDK.  You can view the sample [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/samples/iothub_registry_manager_c2d_sample.py).  If you have any question please open an issue.

**Comment by az-iot-builder-01** [comment]
@HoLue, @damienklotz77, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
