### ISSUE TITLE
Send Message Async Crashing

### ISSUE THREAD

**Issue by jackt-moran** [Azure/azure-iot-sdk-python#463]
Hi,
I am experiencing a crash with IoT Edge modules using the `receive_message_on_input` function. I initially thought it was in long running scenarios but I've experienced the issue in about 10 minutes too. Here is a pared down version of the code I'm using with a basic attempt at error catching:

```python
async def main():
    try:
        print("IoT Hub Client for Python")
        moduleClient = IoTHubModuleClient.create_from_edge_environment()
        await moduleClient.connect()
        async def telemetryListener(moduleClient)
            while True:
                try:
                    print("waiting for messages async")
                    msg = await moduleClient.receive_message_on_input("Test")
                except Exception:
                    print("Caught exception recieving message: ")
                    traceback.print_exc()
                    await moduleClient.disconnect()
                    await moduleClient.connect()
                    continue
                await moduleClient.send_message_to_output(msg, "Test")
        listeners = asyncio.gather(
            telemetryListener(moduleClient)
        )


if __name__ == "__main__":
    asyncio.run(main())
```

Empirically, after 10 minutes up to 24 hours of running smoothly the following stack trace is printed, but no error is thrown because it occurs in another thread:
```python
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 3428, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1782, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1177, in loop
    rc = self.loop_read(max_packets)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1568, in loop_read
    rc = self._packet_read()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 2271, in _packet_read
    byte = self._sock_recv(1)
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 660, in _sock_recv
    return self._sock.recv(bufsize)
AttributeError: 'NoneType' object has no attribute 'recv'
```
Because this issue occurs in another thread my error catching is in vain. After this issue occurs my code hangs forever on the await.

First off, it seems like the issue has to do with the Paho package, however it also seems like the thread this package spawns may not be handling this error properly.

Second, is there a good way to work around this, perhaps some async specific error handling, timing out, or using a protocol other than MQTT?

I am using `azure-iot-device==2.0.1` and here is my module's Dockerfile:

```Docker
FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

RUN useradd -ms /bin/bash moduleuser
USER moduleuser

CMD [ "python3", "-u", "./main.py" ]
```

**Comment by jackt-moran** [comment]
After further investigation the error is actually coming from

```python
await moduleClient.send_message_to_output(msg, "Test")
```

 I tried timing out on the `await moduleClient.receive_message_on_input("Test")` and `await moduleClient.send_message_to_output(msg, "Test")` calls as a workaround to recover from the failure with the following:

```python
try:
    print("waiting for messages async")
    message = await asyncio.wait_for(
        moduleClient.receive_message_on_input("Test"),
        timeout=60.0
    )
except asyncio.TimeoutError:
    print("Timed out recieving message: ")
    traceback.print_exc()
    await moduleClient.disconnect()
    await moduleClient.connect()
    continue
```

and

```python
try:
    await asyncio.wait_for(
        moduleClient.send_message_to_output(msg, "Test"),
        timeout=60.0
    )
except asyncio.TimeoutError:
    print("Caught exception sending message: ")
    traceback.print_exc()
    await moduleClient.disconnect()
    await moduleClient.connect()
```

Eventually the following is output:

```python
Caught exception sending message:
Traceback (most recent call last):
  File "./main.py", line 120, in telemetryListener
    timeout=60.0
  File "/usr/local/lib/python3.7/asyncio/tasks.py", line 449, in wait_for
    raise futures.TimeoutError()
concurrent.futures._base.TimeoutError
```

and execution then hangs forever on `await moduleClient.disconnect()`.

**Comment by BertKleewein** [comment]
This may be fixed in 2.1.1.  I made many improvements in this area, but I'm not 100% sure I fixed this particular issue.  I will review this your issue further to see if there is anything in here that I missed.  Please let me know if this is resolved.

**Comment by jackt-moran** [comment]
@BertKleewein thanks for the update. I pushed out the library upgrade yesterday and so far everything's looking good. I'll update this thread if I encounter the issue again but until then I'm closing the issue.

**Comment by az-iot-builder-01** [comment]
@jackt-moran, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
