### ISSUE TITLE
Documentation Link Issues

### ISSUE THREAD

**Issue by Rumpkie** [Azure/azure-iot-sdk-python#468]
Samples links in the Readme.md files are broken.

links to the samples library are broken
https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples

https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device
Samples repository link is broken
advanced-hub-scenarios 
advanced-edge-scenarios

To name a  few, please look at the links, I think the directories have been moved around or renamed.

**Comment by jebrando** [comment]
@Rumpkie I updated the ReadMe to include a new feature and removed some links.  I'm a little confused at which exact links are broken, but I removed a few that didn't belong.  If you see any more issues, please let me know.

**Comment by az-iot-builder-01** [comment]
@Rumpkie, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
