### ISSUE TITLE
Where is Upload to Blob?

### ISSUE THREAD

**Issue by sam-findler** [Azure/azure-iot-sdk-python#469]
File upload is one of the key features of iothub, and not only is it not implemented in this client (so far as I can tell), it is not even mentioned on the list of features.  Are there plans to support blob uploading in this client, and if so, when?

**Comment by jebrando** [comment]
@sam-findler Upload to Blob is indeed implemented in Python.  We have a sample showing how to do it [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/upload_to_blob.py).  Let us know if you have any questions or concerns with this.
