### ISSUE TITLE
How to send properties (key/value) with send_c2d_message

### ISSUE THREAD

**Issue by HoLue** [Azure/azure-iot-sdk-python#475]
According to
https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/samples/iothub_registry_manager_c2d_sample.py
```
send_message = "C2D message to be send to device"
...
    # Send Message To Device
    registry_manager.send_c2d_message(device_id, send_message)
```

I want to send additional properties (key-value pair) as it is possible in Azure Portal (send message to device). 

BTW, receiving is prepared e.g. in the example 
https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/receive_message.py
```
            message = await device_client.receive_message()  # blocking call
            print("the data in the message received was ")
            print(message.data)
            print("custom properties are")
            print(message.custom_properties)
```

**Comment by zolvarga** [comment]
@HoLue I will create a sample for updating the properties and update this thread with it.

**Comment by jebrando** [comment]
@HoLue We have added properties to the send_c2d_message to the master branch.  We are planning a pip release in a week so you can get it then.

**Comment by az-iot-builder-01** [comment]
@HoLue, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by HoLue** [comment]
Thanks!
