### ISSUE TITLE
How to get the IOT Edge device status by python sdk?

### ISSUE THREAD

**Issue by jackiecatchcatch** [Azure/azure-iot-sdk-python#477]
After connecting to IOT Edge , Runtime Response tag shows OK.
But when i use get_device in IoTHubRegistryManager,  'connection_state' shows 'Disconnected'

**Comment by jebrando** [comment]
@jackiecatchcatch The connection_state is a very slow moving status.  Can you describe your use case where you're not seeing this value change?

**Comment by jackiecatchcatch** [comment]
I create an IOT edge in my hub and connect my device with it.
After they have connected, IoT Edge Runtime Response in portal shows 200-OK.
I want to get this information from python.
So i use sample code in azure-iot-hub(iothub_registry_manager_sample.py) 
to get the information.
After running the code, the connection_state in that sample code get the wrong status.
or maybe i used the wrong function to get IoT Edge Runtime Response?

**Comment by darobs** [comment]
Hello @jackiecatchcatch, 

One of the issues you may be running into is that the IoT Edge runtime does not connect to the device itself, only to the modules on the device. One way to see if the IoT Edge runtine is connected is to look at the "$edgeAgent" module status.

**Comment by darobs** [comment]
I brought this up to the team, and even getting $edgeAgent status may not be 100% reliable.  The current recommendation is to use the [ping direct method](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-edgeagent-direct-method#ping).

**Comment by jackiecatchcatch** [comment]
OK I got it

**Comment by az-iot-builder-01** [comment]
@jackiecatchcatch, @darobs, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by esttenorio** [comment]
Are there any new ways of getting the IoT Edge Response using a direct method or some API?

On the portal I see this:

![image](https://user-images.githubusercontent.com/8483207/107297509-5efff180-6a28-11eb-94bc-72d0347863b2.png)

And when I sending the ping method to $edgeAgent I get this: `'{"status":200,"payload":null}'`

So clearly ping is not a perfect workaround for getting the actual state of the device.
