### ISSUE TITLE
[Question] How to connect to IoT Hub using SharedAccessSignature

### ISSUE THREAD

**Issue by jtfidje** [Azure/azure-iot-sdk-python#478]
I've been provided a SharedAccessSignature, but can't seem to figure out how to connect to their IoT Hub using it - could you please give an example of how to do it? 

The format of the SharedAccessSignature I've been given:
```
SharedAccessSignature sr=[xxx]&sig=[xxx]&se=[xxx]
```

AB#7366697

**Comment by jebrando** [comment]
@jtfidje We had to remove that functionality right before GA due to an inability to signal the user that they need to renew the SAS token.  We are working on figuring  a way to re-enable this and will alert you when we have the functionality enabled.  Sorry for the inconvenience.

**Comment by cartertinney** [comment]
This feature has been added in #692, which will be included in the next package release

**Comment by az-iot-builder-01** [comment]
@jtfidje, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
