### ISSUE TITLE
ModuleNotFoundError: No module named 'azure.iot' ?

### ISSUE THREAD

**Issue by MikeWilcoxMicrosoft** [Azure/azure-iot-sdk-python#483]
Env: Ubuntu with  python 3.8 
$ pip3 list  | grep -i azure
azure (4.0.0)

Symptom: 
++ python3 ./simple_send_message.py
Traceback (most recent call last):
  File "./simple_send_message.py", line 3, in <module>
    from azure.iot.device.aio import IoTHubDeviceClient
ModuleNotFoundError: No module named 'azure.iot'

**Comment by MikeWilcoxMicrosoft** [comment]
resolved user error :) 
My brain is completely scrambled with the plethora of pip and python version tried, but this seems to work 

$ pip3 --version
pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.6)
$ python -V
Python 3.8.0

$ pip3 install azure-iot-device                  
$ python  ./simple_send_message.py

**Comment by az-iot-builder-01** [comment]
@MikeWilcoxMicrosoft, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by MikeWilcoxMicrosoft** [comment]
whew

**Comment by AruruSreenu** [comment]
from azure.iot.device.aio import IoTHubDeviceClient

ModuleNotFoundError: No module named 'azure.iot'; 'azure' is not a package
