### ISSUE TITLE
deviceId is not found

### ISSUE THREAD

**Issue by 5nowx** [Azure/azure-iot-sdk-python#49]
- **OS and version used:** RASPBIAN JESSIE LITE

- **Python runtime used:** Python 2.7.9

- **SDK version used:** 	release_2017_06_16

# Description of the issue:
Running the sample i get the error deviceID not found, i checked it with the Device Explorer and also getting the connection string from the azure portal

# Code sample exhibiting the issue:
python iothub_client_sample.py -c CONNECTIONSTRING -p mqtt
python iothub_client_sample.py -c SECUNDARYCONNECTIONSTRING -p mqtt
python iothub_client_sample.py -c CONNECTIONSTRING -p https
python iothub_client_sample.py -c SECUNDARYCONNECTIONSTRING -p https

# Console log of the issue:
Info: IoT Hub SDK for C, version 1.1.17
Error: Time:Thu Jun 29 01:26:32 2017 File:/home/pi/azureIOT/azure-iot-sdk-python/c/iothub_client/src/iothub_client_ll.c Func:IoTHubClient_LL_CreateFromConnectionString Line:672 deviceId is not found
Error: Time:Thu Jun 29 01:26:32 2017 File:/home/pi/azureIOT/azure-iot-sdk-python/c/iothub_client/src/iothub_client.c Func:create_iothub_instance Line:763 Failure creating iothub handle
Unexpected error IoTHubClient.IoTHubClient, IoTHubClientResult.ERROR from IoTHub

**Comment by zolvarga** [comment]
@5nowx,

There are two problem I can think about:

- You are using a wrong connection string (IoTHub connection string instead of **device connection string**)
- You are not using double quotes around the device connection string

Best Regards,
Zoltan

**Comment by 5nowx** [comment]
Thanks zolvarga, it was exactly the double quotes on the connection string, i was using the the correct connection string, but not the quotes.

Thanks for the help!
