### ISSUE TITLE
Multiple module twin callbacks being called from cloud. 

### ISSUE THREAD

**Issue by viharigandrakota** [Azure/azure-iot-sdk-python#497]
Deployed [OpenVINO: Ready-to-Deploy AI Vision Module](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/intel-6134848.openvino-ai-vision-module?tab=Overview) from Azure Marketplace as an IoT Edge module.
Once deployed, updated the module twin properties with the URL of the model from customvision.ai
Ran the model for overnight and observed multiple module twin call backs happening from cloud.
Below is the log:

'''
Creating IoT Hub manager
Domain Type: ObjectDetection
Call: Constructor: ObjectDetection.__init__

 Triggering Inference...

Twin callback called with:
    updateStatus: COMPLETE
    payload: {"desired":{"inference_files_zip_url":"https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r","msg_per_minute":10,"object_of_interest":"ALL","$version":12},"reported":{"$version":1}}
Setting value to https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r from ::  data["desired"]["all_inference_files_zip"]
preparing: /app/./model
found directory cleaning it before copying new files...
Downloading File ::0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r

 Started Inference...
Got it ! File Download Complete !
Setting value to ALL from ::  data["object_of_interest"]
Setting value to 10 from ::  data["msg_per_minute"]
INFO:iot_hub_manager:Restarting inferencing
[ INFO ]  Restarting inferencing

 Reading cvexport.config file from model folder
Domain Type: ObjectDetection
Call: Constructor: ObjectDetection.__init__

 Triggering Inference...

 Started Inference...

Twin callback called with:
    updateStatus: COMPLETE
    payload: {"desired":{"inference_files_zip_url":"https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r","msg_per_minute":10,"object_of_interest":"ALL","$version":12},"reported":{"$version":1}}
Setting value to https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r from ::  data["desired"]["all_inference_files_zip"]
preparing: /app/./model
found directory cleaning it before copying new files...
Downloading File ::0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r
Got it ! File Download Complete !
Setting value to ALL from ::  data["object_of_interest"]
Setting value to 10 from ::  data["msg_per_minute"]
INFO:iot_hub_manager:Restarting inferencing
[ INFO ]  Restarting inferencing

 Reading cvexport.config file from model folder
Domain Type: ObjectDetection
Call: Constructor: ObjectDetection.__init__

 Triggering Inference...

 Started Inference...

Twin callback called with:
    updateStatus: COMPLETE
    payload: {"desired":{"inference_files_zip_url":"https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r","msg_per_minute":10,"object_of_interest":"ALL","$version":12},"reported":{"$version":1}}
Setting value to https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r from ::  data["desired"]["all_inference_files_zip"]
preparing: /app/./model
found directory cleaning it before copying new files...
Downloading File ::0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r
Got it ! File Download Complete !
Setting value to ALL from ::  data["object_of_interest"]
Setting value to 10 from ::  data["msg_per_minute"]
INFO:iot_hub_manager:Restarting inferencing
[ INFO ]  Restarting inferencing

 Reading cvexport.config file from model folder
Domain Type: ObjectDetection
Call: Constructor: ObjectDetection.__init__

 Triggering Inference...

 Started Inference...

Twin callback called with:
    updateStatus: COMPLETE
    payload: {"desired":{"inference_files_zip_url":"https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r","msg_per_minute":10,"object_of_interest":"ALL","$version":12},"reported":{"$version":1}}
Setting value to https://irisscuprodstore.blob.core.windows.net/m-b625970ad6d64ba18bfcb653ea50eeaf/0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r from ::  data["desired"]["all_inference_files_zip"]
preparing: /app/./model
found directory cleaning it before copying new files...
Downloading File ::0fd98177b5a744edba9fabd1ab1b1c2d.ONNX.zip?sv=2017-04-17&sr=b&sig=DqYkusSk4FU8AYAYTAJ%2FkjTGGg3qeN2RTR7jLODwTFE%3D&se=2020-03-17T12%3A43%3A24Z&sp=r
Got it ! File Download Complete !
Setting value to ALL from ::  data["object_of_interest"]
INFO:iot_hub_manager:Restarting inferencing
Setting value to 10 from ::  data["msg_per_minute"]
[ INFO ]  Restarting inferencing

 Reading cvexport.config file from model folder
Domain Type: ObjectDetection
Call: Constructor: ObjectDetection.__init__

 Triggering Inference...

 Started Inference...
''' 
This was repeated multiple times.
What is the reason for multiple module twin call backs from the cloud?

**Comment by elhorton** [comment]
Hi @viharigandrakota, thanks for reaching out. Think we need some more info to help out here. With this info it's hard to say if what you're seeing is a result of the Intel module, Edge service, or something in this Python SDK, so I don't know how to best route this issue yet. Also good to note that it looks like the module makes use of the v1 SDK. Could you please start by filling out this additional info template:

OS and version used: (Windows 10, Ubuntu 15.04, etc. )
Python version: (in a command prompt: python --version )
pip version: (in a command prompt: pip --version )
list of installed packages: ( in a command prompt, from the directory containing your code: pip list )
cloned repo: ( If you are using a cloned sdk repository, in a command prompt: git describe )

Description of the issue:
Has this been reproduced multiple times? Have you worked with this module before? It would also help if you could outline your overall scenario and solution at a high level-- what steps have you taken to get this going, what components are you using & where do they live (edge device, module, hub, etc.)?

Code sample exhibiting the issue:
Can you share the code you're using? 

Console log of the issue:
anything else in addition to what you've already provided? Logs from the module/device?

**Comment by viharigandrakota** [comment]
Hi @elhorton ,
Thanks for coming back. and apologies for my delayed response.
Here is the info:
**OS and version used** : Ubuntu 16.04 on Host machine & docker container
**Python version** : 3.7 
**pip version** : pip 19.3.1
**list of installed packages** : 
asn1crypto                           0.24.0             
azure-iot-provisioning-device-client 1.4.6              
azure-iothub-device-client           1.4.6              
azure-iothub-service-client          1.4.6              
certifi                              2019.9.11          
cffi                                 1.11.5             
chardet                              3.0.4              
Click                                7.0                
conda                                4.5.11             
cryptography                         2.3.1              
decorator                            4.4.1              
defusedxml                           0.6.0              
Flask                                1.1.1              
idna                                 2.7                
itsdangerous                         1.1.0              
Jinja2                               2.10.3             
MarkupSafe                           1.1.1              
mkl-fft                              1.0.14             
mkl-random                           1.1.0              
mkl-service                          2.3.0              
networkx                             2.3                
numpy                                1.17.2             
onnx                                 1.6.0              
onnxruntime-openvino                 1.0.0              
opencv-python                        4.1.1.26           
pip                                  19.3.1             
protobuf                             3.10.0             
pycosat                              0.6.3              
pycparser                            2.18               
pyOpenSSL                            18.0.0             
PySocks                              1.6.8              
requests                             2.19.1             
ruamel-yaml                          0.15.46            
setuptools                           41.6.0.post20191030
six                                  1.12.0             
test-generator                       0.1.1              
typing-extensions                    3.7.4.1            
urllib3                              1.23               
Werkzeug                             0.16.0             
wheel                                0.33.6 
**cloned repo** : This is an App from Azure marketplace. Please find it [here](https://azuremarketplace.microsoft.com/en-us/marketplace/apps/intel-6134848.openvino-ai-vision-module?tab=Overview)

Description:
This is an application from Azure Marketplace. You can get it as an Azure IoT Edge module on your edge machine. The module twin call back is expected to happen only when the module twin settings are updated in the Azure portal. But it is observed that this call back is happening repeatedly even without the module twin update. You can reproduce this issue by following the instructions in the link that I shared above. 
Yes, I observed this multiple times.
**High level outline** : This is a Ready-to-Deploy AI Vision Module that runs as a IoT Edge module on Edge machine. Once the module gets deployed on the Edge machine as an IoT edge module, the user has to update the module twin settings with the ONNX model url from customvision.ai ( find instructions [here](https://docs.google.com/document/d/13FTEJic2jOurk_j7E-qJRhEs0_UTwwpfN9fwK9TOZoQ/edit?usp=sharing)) which enforces the module twin callback. **But observed the module twin call back is happening multiple times even after updating the module twin settings only once **.

**Comment by elhorton** [comment]
Thanks @viharigandrakota , a couple pieces of info and some next steps for you. 

We cannot further investigate for two reasons:

1) This module does not appear to be open source, so I'm unable to see if the Intel module is properly implementing the callback. It could be an issue with connection (where the module never gets an ACK so it keeps trying to send). I would encourage you to raise this question on the module's forum: https://software.intel.com/en-us/forums/intel-distribution-of-openvino-toolkit

2) This module makes use of our deprecated v1 library, which we are no longer supporting. This means that, even if this was an SDK issue, we could not fix it in this scenario. Perhaps you could try programmatically catching the module twin callback after it's first send and suppressing further calls (assuming that the multiple callbacks are not a result of the twin not being initially updated).

Sorry that we can't help any further.

**Comment by psakamoori** [comment]
@elhorton Please help us understand more about "module makes use of our deprecated v1 library, which we are no longer supporting" which library are you mentioning. How to move/use latest version of library for this app? - We can test it with new version library and test multiple twin callbacks scenario

**Comment by elhorton** [comment]
Yes, absolutely. We released a v2 Python SDK last year that is built with native python. The [previous version of this SDK](https://github.com/Azure/azure-iot-sdk-python/tree/v1-deprecated) was a layer over the C SDK, leading it to be unnatural for Python developers and error prone. 

You should note that there are breaking changes between the API surfaces from v1 to v2, and this repo has a [migration guide](https://github.com/Azure/azure-iot-sdk-python/blob/master/migration_guide.md) to assist. You can also learn more about the v2 SDK from [this blog post](https://techcommunity.microsoft.com/t5/internet-of-things/new-version-of-the-python-sdk-released/ba-p/1201894).

**Comment by az-iot-builder-01** [comment]
@viharigandrakota, @psakamoori, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
