### ISSUE TITLE
Memory leak when sending telemetry every 10sec

### ISSUE THREAD

**Issue by patrickue** [Azure/azure-iot-sdk-python#498]
I'm using IoTHubModuleClient to send telemetry to an Azure IoTHub and noticed a constant increase of memory usage over time. 
I'm sending a bunch of telemetry every 10s (around 10-15 items).

in init:
`self.client = IoTHubModuleClient.create_from_connection_string(connection_string)`
in the regular reporting of telemetry:
`self.client.patch_twin_reported_properties(payload)`

I detected a memory usage which started typically around 10 hours after startup of about 10MB/hour. So that after around 3 days my raspberries (2 independent systems) with 1GB RAM stopped/crashed with "out of memory". After removing the second line (patch_twin_reported_properties) the memory issue went away.
Any ideas what this can be related to?

Regards, Patrick

AB#7366700

**Comment by olivakar** [comment]
Will it be possible to see your sample completely ? 
Please delete any connection strings or keys that you may have.

**Comment by patrickue** [comment]
Sure! 

In IIotHub.py, class IoTHubManager:
```
def sendReportedState(self, payload):
    """
    Sends reported state to IoT Hub.

    :param payload: Required Payload as JSON
    """
    #print("check: " + str(payload))
    payload = self.adjustKeys(payload, ['.', '$', '#', ' '], '_')
    try:
        print("IIoTHub Send to Azure: " + str(payload))
        # next line commented, because it causes our memory leak
        # self.client.patch_twin_reported_properties(payload)
    except Exception:
        print("Exception in send Reported state " + str(payload))
```

same class:
```
    def emit_status(self, reported_state):
        """
        Send state to devicetwin with log
        """
        try:
            # TODO: check user context value
            self.sendReportedState(reported_state)
            self.logger.handle_info("send_reported_state accepted message: %s" % reported_state)
        except Exception as e:
            self.logger.handle_exception(e, "emit_status ")
```

Class `Observer`
iothub is object of `IoTHubManager`
```
def sendBufferToTwin(self, seconds = 0):
        """
        Sens
        :param seconds:
        :return:
        """
        time.sleep(seconds)
        payload = {}
        # output queue length before sending
        print("MEMORY-LEAK-DEBUG: Queue length BEFORE sending: %s" % self.payloadQueue.qsize())
        self.payloadQueue.put(None)
        for data in iter(self.payloadQueue.get,None):
            payload = update_dict(payload,data)
        self.iothub.sendReportedState(payload)
        self.collectorTimerRuns.clear()
        print("MEMORY-LEAK-DEBUG: Queue length AFTER sending: %s" % self.payloadQueue.qsize())
```

same class, collecting data to be put in the payload Queue to IoTHub.
```
    def bufferAndSendToTwin(self, payload):
        """
        Buffer payload data for in self.updateTime specified time and then send it to Azure device twin
        :param payload: Dict wich should be sent to azure deviceTiwn
        :return:
        """
        #hold payload to send it at next sending period
        self.payloadQueue.put(payload)

        #if data comes in, buffer further data for 10s and then push it to Azure
        if not self.collectorTimerRuns.is_set():
            self.collectorTimerRuns.set()
            triggerThread = threading.Thread(target=self.sendBufferToTwin,
                                             name='TriggerBufferThread',
                                             args=(self.updateTime,),
                                             daemon=False)
            triggerThread.start()
```

**Comment by olivakar** [comment]
do u have the code portion where you are creating the client and connecting ?

**Comment by patrickue** [comment]
Here it is:

connection is: `"HostName=XYZ.azure-devices.net;DeviceId=RASPBERRY_XYZ_PILOT1;SharedAccessKey=XYZ"`

```
class IoTHubManager:
    """
    This class manages iothub control

    :ivar client : iothub client Object from Microsoft Azure library
    :ivar logger : logger object
    """

    methodList = ['shutdown', 'setTunnel', 'sendStatus', 'searchDevices']

    def __init__(self,
                 connection_string,
                 logger=None):
        """
        Connects to Azure IoT Hub
        :param connection_string: IoTHub connection string
        :param logger: logger
        """
        self.client = IoTHubModuleClient.create_from_connection_string(connection_string)
        self.logger = logger
```

**Comment by olivakar** [comment]
Can you send the portion where you are creating an instance of `IoTHubManager` or rather `iothub` ? 

And if you are creating the instance of `IoTHubManager` in the `init` of Observer class , then I would further like to see the portion where you are creating  the instance of `Observer`

**Comment by patrickue** [comment]
Here is the creation of the IoTHubManager:

in main.py:
```
if __name__ == '__main__':
    handler = IndustrialGateway()
    try:
        while handler.state == gatewayRunning:
            time.sleep(1)
            # pass
        sys.exit(0)
```

(also in main.py)
```
class IndustrialGateway:
    [...]
    def __init__(self):
        try:
            [...]
            self.identity = self.configurator.read_identity()
            [...]
            self.iotTwin = IIoTHub.IoTHubManager(self.iothub['connection'], self.logger)
            [...]
```
That's it. No loops around, just once in the constructor of our main class.

What are questions looking for? Possible "multi"-creation of the object?

**Comment by patrickue** [comment]
Sorry for the delay, by the way: :( Strange times we're living in. 🤣

**Comment by olivakar** [comment]
Could you send me the part part where you call this `bufferAndSendToTwin` ?

**Comment by patrickue** [comment]
The method `bufferAndSendToTwin` is called by every sensor, endpoint or thread which wants to report something. So these are the (parent) classes which call it in their update:

```
class ThreadObserver(Observer):
    """
    This class observes a running thread and pushes the new data to the Azure IoTHub
    """
    def __init__(self,name,iothub):
        super().__init__(name,iothub)

    def update(self, data):
        """
        Pushes lastLoop tmestamp to Azure IoTHub Twin
        :param data: observableThread Object
        """
        payload = {"Thread-last-loop":
                       {data.threadname: data.lastLoop}
                   }

        self.bufferAndSendToTwin(payload)
```

```
class SensorObserver(Observer):
    """
    Observes different sensors
    """
    def __init__(self,name,iothub):
        super().__init__(name,iothub)

    def update(self,data):
        """
        Pushes online state and last tmestamp to Azure IoTHub twin
        :param data: observableSensor Object
        """

        if data.online:
            onlineString = 'online'
        else:
            onlineString = 'offline'
        payload = {"Sensors":{ data.drivername:{data.name: onlineString}}}
        print( str(id(self)) +  "Send to Azure: " + data.name + " - " + onlineString + " Payload: " + str(payload))
        self.bufferAndSendToTwin(payload)
```
```
class EndpointObserver(Observer):
    """
    Observes an endpoint like a database system
    """
    def __init__(self,name,iothub):
        super().__init__(name, iothub)

    def update(self,data):
        if data.onlineState:
            onlineString = 'online'
        else:
            onlineString = 'offline'
        payload = {"Endpoints":{ data.dbname: onlineString}}

        self.bufferAndSendToTwin(payload)
```

**Comment by patrickue** [comment]
Partial solve, new question:
I found out that the call to `self.client.patch_twin_reported_properties(payload)`
is blocking around 6-10 hours after startup. And then the queue is running full, but no payload is delivered (never being removed from the queue). Sorry for the naming of `memory leak` when it's actually the function blocking – forever.

@olivakar Ideas why `patch_twin_reported_properties(...)` would block?

**Comment by olivakar** [comment]
Can you attach the full log for this ?

**Comment by BertKleewein** [comment]
Hi @patrickue , I suspect that PR 576 will fix this, though I do not know for sure.  if you want to test this, you can install from here.  This should be included in our next release after 2.1.2 (probably 2.1.3)

[azure_iot_device-2.1.2_test_pr576-py2.py3-none-any.zip](https://github.com/Azure/azure-iot-sdk-python/files/4746304/azure_iot_device-2.1.2_test_pr576-py2.py3-none-any.zip)

**Comment by BertKleewein** [comment]
@patrickue , [azure-iot-device 2.1.3])(https://pypi.org/project/azure-iot-device/2.1.3/) fixed an issue that sounds very similar to what you're seeing.  There was a bug which was basically a threading issue which would cause the MQTT library to get stuck in a failure state if you happen to be doing network IO while the SAS authentication token gets renewed.  I strongly suspect that your problem will be resolved with this build.

**Comment by patrickue** [comment]
@BertKleewein Thanks! Yes, it definitely solved this! Thanks also to @olivakar for supporting!

**Comment by az-iot-builder-01** [comment]
@patrickue, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
