### ISSUE TITLE
Mention somewhere in the doc the IoTHub Mgmt package

### ISSUE THREAD

**Issue by lmazuel** [Azure/azure-iot-sdk-python#5]
I generated and released the [IoTHub Mgmt package](https://pypi.python.org/pypi/azure-mgmt-iothub) from the Swagger file. I made a tiny quickstart [here](http://azure-sdk-for-python.readthedocs.io/en/latest/sample_azure-mgmt-iothub.html).

Should this doc/package mentioned somewhere in this repo? 

Opposite question, do you want more than a reference [here](http://azure-sdk-for-python.readthedocs.io/en/latest/index.html#azure-runtime) for your repo?

**Comment by zolvarga** [comment]
Hi Imazuel,

Good idea, we will mention and link to your management package in the next release.
It is also a good idea to link to us on your site. That should happen also after our next release, as we are thinking about the rename our PyPi packages.
We are planning to release on 13th of January.

Thanks,
Zoltan

**Comment by olivierbloch** [comment]
Links added to main readme.
@lmazuel, do you think you can replace the link you have now [here](http://azure-sdk-for-python.readthedocs.io/en/latest/index.html#azure-runtime) (and which is now dead) with the following:
[Azure IoT Hub service and device SDKs for Python](https://github.com/Azure/azure-iot-sdk-python)

**Comment by lmazuel** [comment]
@olivierbloch done!
https://github.com/Azure/azure-sdk-for-python/commit/2294cdb290f25e26abb7fe08f6eb8ac608c352dd

**Comment by olivierbloch** [comment]
Awesome. Thanks1
