### ISSUE TITLE
IoTHubClient.__init__ Boost.Python.ArgumentError: Python argument types did not match C++ signature:

### ISSUE THREAD

**Issue by karlbloedorn** [Azure/azure-iot-sdk-python#50]
Raspbian GNU/Linux 8,  kernel: 4.4.50+
Python 2.7.9 has issue.  Building for Python 3.4 and running with python3 works fine.
Compiled from git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git
Copied iothub_client.so from device samples folder to my own folder.
Tests all say OK when it built

Code:

self.iotClient = IoTHubClient(connString, IoTHubTransportProvider.AMQP_WS)
self.iotClient.set_option("messageTimeout", "5")

# Console log of the issue:
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    a.stuff()
  File "/root/stuff/stuff/__init__.py", line 65, in Stuff
    self.stuff= IoTHubClient(connString, IoTHubTransportProvider.AMQP_WS)
Boost.Python.ArgumentError: Python argument types in
    IoTHubClient.__init__(IoTHubClient, unicode, IoTHubTransportProvider)
did not match C++ signature:
    __init__(_object*, std::string, IOTHUB_TRANSPORT_PROVIDER)

It looks like maybe there could be something left over from compiling or setting up, I did try a fresh git clone into a different folder and the issue persists. 
I ran both setup.sh and build.sh.
Any step to clear this out?

**Comment by MeneerChen** [comment]
Please make sure connString has the string type if u get this from a json file. U can try str(connString) to make sure its string type.

**Comment by karlbloedorn** [comment]
Thanks. Calling str(connString) before passing in resolved the issue.  print(type(connString)) resulted in <type 'unicode'>. I had created the string via concatenation, and I just expected that to be a string type. So now it is working with that change. I assumed the issue was a mismatch between the python and C++ layers, rather than my calling code and the C++ layer. Thanks
