### ISSUE TITLE
Facing Socket timeout issue while sending data using module_client.send_message_to_output

### ISSUE THREAD

**Issue by kaleankush93** [Azure/azure-iot-sdk-python#507]
I am getting below socket timeout error while sending data  to IoT Edge Runtime--->IoT Hub using module_client.send_message_to_output.

transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 340, in connect
    host=self._hostname, port=8883, keepalive=DEFAULT_KEEPALIVE
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 937, in connect
    return self.reconnect()
  File "/usr/local/lib/python3.7/site-packages/paho/mqtt/client.py", line 1100, in reconnect
    sock.do_handshake()
  File "/usr/local/lib/python3.7/ssl.py", line 1139, in do_handshake
    self._sslobj.do_handshake()
socket.timeout: _ssl.c:1059: The handshake operation timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 115, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/mqtt_transport.py", line 345, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: None caused by _ssl.c:1059: The handshake operation timed out

ConnectOperation: completing with error None caused by _ssl.c:1059: The handshake operation timed out
RetryStage(ConnectOperation): Op needs retry with interval 20 because of None caused by _ssl.c:1059: The handshake operation timed out.  Setting timer**.**

Could anyone please help how to resolve this?

**Comment by kaleankush93** [comment]
++ @BertKleewein

**Comment by BertKleewein** [comment]
@kaleankush93, I am currently looking at several related failures.  Can I ask if this is causing the send_message_to_output call to raise an exception?  This particular failure should cause the Azure IoT library to retry the connection (assuming the library has successfully connected at least once in the past).

**Comment by kaleankush93** [comment]
@BertKleewein Thanks for replying!
Yes you are correct. This is causing send_message_to_output call to raise an exception. Till Friday it was working fine. I was getting the messages to IoTHub through this module deployed on the linux device. This issue has appeared today itself. I saw several threads going on. 

What could possibly be wrong here?

**Comment by BertKleewein** [comment]
This may be fixed in 2.1.1 which has several fixes for connection failure issues.  I'm going to investigate a few things in this specific report further to see if I can improve the fix.  Please let me know if this is resolved.

**Comment by kaleankush93** [comment]
Hi @BertKleewein , Thank you! My issue got resolved after restarting the edge device.

**Comment by az-iot-builder-01** [comment]
@kaleankush93, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
