### ISSUE TITLE
Specifying DeviceCapabilities (e.g., IoT Edge) with create_device_with_sas()

### ISSUE THREAD

**Issue by awshole** [Azure/azure-iot-sdk-python#509]
With the depricated SDK, it was possible to create an IoT Edge device by specifying DeviceCapabilities when invoking something like:
```
iothub_registry_manager.create_device(DEVICE_ID, primary_key, secondary_key, auth_method, deviceCapabilities)
```

How do we include DeviceProperties now that we create devices with SAS using something like:

```
create_device_with_sas(self, device_id, primary_key, secondary_key, status)
```

I'm aware of creating the device properties via:
```
from azure.iot.hub.protocol.models import DeviceCapabilities
deviceCapabilities = DeviceCapabilities()
deviceCapabilities.iot_edge = True
```

Thanks for the help! This is critical for our provisioning automation with Edge devices, and I'd prefer to not rely on the deprecated branch.

**Comment by zolvarga** [comment]
@awshole 

To create a module on IoTEdge please use the creation API's for modules:
create_module_with_sas
create_module_with_x509
create_module_with_certificate_authority

I hope this helps
Zoltan

**Comment by awshole** [comment]
> @awshole
> 
> To create a module on IoTEdge please use the creation API's for modules:
> create_module_with_sas
> create_module_with_x509
> create_module_with_certificate_authority
> 
> I hope this helps
> Zoltan

Thanks for the reply @zolvarga. However, I'm not wanting to create a module. I'm wanting to create an IoT device, specifically an Edge device. Does that make sense?

**Comment by zolvarga** [comment]
@awshole 

Yes, it does. I am looking at it and will get back to you.

Zoltan

**Comment by zolvarga** [comment]
@awshole 

I have checked in a fix to master branch. The fix will be in the next release.
Meanwhile please clone the repository and use it from there.

I created a sample for you here:
../azure-iot-hub/samples/iothub_registry_manager_edge_device_sample.py
Please take a look at it, there is a new optional boolean parameter in the create_device... APIs.
If it is True the created device  will be an IoTEdge device.

Zoltan

**Comment by awshole** [comment]
@zolvarga Thank you! I will clone and conduct testing. Looking forward to the next release!

**Comment by az-iot-builder-01** [comment]
@awshole, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
