### ISSUE TITLE
[Question] [Twin] Update reported properties after reconnection.

### ISSUE THREAD

**Issue by RickBadKan** [Azure/azure-iot-sdk-python#510]
# Context
- **OS and version used:** Windows 10
- **Python version:** Python 2.7.17
- **pip version:** pip 20.0.2
- **SDK version:** V2 with threads/synchronous applications.

# Description of the issue:
Hi, 

I have a question regarding the management of the versioning between the desired properties and the reported properties. Let's assume that while my device/module was disconnected, I made more than one change to the desired properties. When my device/module reconnects, the listener for the patches will not see any changes (as described [here](https://docs.microsoft.com/pt-br/azure/iot-hub/iot-hub-devguide-device-twins#device-reconnection-flow)). So, to change the reported properties I need to get all the document (using the `get_twin()` method, for example) and check the `$version` field. 

But the problem is that if I made more than one change I cannot change the `$version` directly to equal them (i.e. desired: `$version 6`, reported: `$version 2`). More than that, if it's about adding/removing fields there's no problem: I can check then individually; but if I made 6 changes to one field, I cannot see all the other 5 modifications to change incrementally on my reported properties.  So how can I manage properties with reconnection properly? Is there any code sample for this?

Thanks in advance.

AB#7366701

**Comment by BertKleewein** [comment]
I know this doesn't answer your question, but I just made a pull into master that will automatically fetch the twin after reconnecting, https://github.com/Azure/azure-iot-sdk-python/pull/522

**Comment by BertKleewein** [comment]
Regarding $version, the $version for reported properties and the $version for desired properties are not related.  It is perfectly valid for one to increment multiple times without the other one changing.  

Consider the example of a room thermostat,  The service might set a desired temperature of 72 degrees.  Since it can take several minutes to hours to heat a room, the thermostat might report the temperature several times as it slowly rises.

Regarding the question about seeing the 6 property changes that happened while the device was off-line, that is not a feature that twins support.  The twin only holds the most recent property values and all history is discarded.  If you need to see the incremental changes, you need to use a different feature such as cloud-to-device messages or direct methods.

**Comment by RickBadKan** [comment]
Hello @BertKleewein and thank you for the response. Sorry for coming back to you only after some time.

> I know this doesn't answer your question, but I just made a pull into master that will automatically fetch the twin after reconnecting, #522. This is not in any current releases but it should be in our next release.

About that, data consumption is very important for our application. So if the twin is fetched after every reconnection, our data usage is going to skyrocket if the device is placed somewhere with weak signal strength (i.e. so much reconnections). We bypassed this issue by fetching only the new desired properties from the twin automatically if the device is on by using the `receive_twin_desired_properties_patch()` client method. And if the device lost any update during this time off the grid, once a day we fetch the twin as a hole and compare the properties.


> Regarding $version, the $version for reported properties and the $version for desired properties are not related. It is perfectly valid for one to increment multiple times without the other one changing.
> 
> Consider the example of a room thermostat, The service might set a desired temperature of 72 degrees. Since it can take several minutes to hours to heat a room, the thermostat might report the temperature several times as it slowly rises.
> 
> Regarding the question about seeing the 6 property changes that happened while the device was off-line, that is not a feature that twins support. The twin only holds the most recent property values and all history is discarded. If you need to see the incremental changes, you need to use a different feature such as cloud-to-device messages or direct methods.

I perfectly understand the twin holding the most recent property values; my concern is about two major situations: (1) deleting a field when the device is not connected and (2) how to properly manage version if the device internet connection goes down and up again.

(1): this is about the way that need to be used to delete a field; passing the `null` value on the JSON is fine if the device is connected and listening for twin updates. But if this field is deleted when the equipment is offline, since the value is no more on the desired properties, I'd need to check field by field if it still exists. Is this the right method?

(2): regarding the versioning management process, what is the recommendation? Because if the device goes offline and then back up again, it can't know if there were any updates during this time off. The only way is fetching the twin completely and check it field by field (or use the `$version` property). I can't find any example that attends this situation. Could you provide one or guide us to how to implement this feature?

Best regards.

**Comment by njbuch** [comment]
The receive_twin_desired_properties_patch() method is not in the new SDK is that right?

**Comment by RickBadKan** [comment]
> The receive_twin_desired_properties_patch() method is not in the new SDK is that right?

You mean the v2.0? I don't know, I'm using the sync Python 2.X version for compatibility purposes. It's a blocking call that waits for a new patch of the desired properties from the cloud.

**Comment by njbuch** [comment]
Hmm, good question. I based my code on this sample: [link](https://github.com/Azure/azure-iot-sdk-python-preview/blob/master/azure-iot-device/samples/advanced-hub-scenarios/receive_twin_desired_properties_patch.py) which is now archived.

I guess its version 2 of the SDK. But I have problems with the blocking call as it is not active after a few hours. I think its the problem mentioned above.

**Comment by RickBadKan** [comment]
I didn't notice this blocking call not working even after long periods of time. I'm using some custom code and used the samples only to understand how it worked. Btw I'm using modules too and yet haven't gotten this problem.

The issue in this post isn't the blocking call not working after some time; it's more like a design question about how to properly manage the versioning process when the device reconnects.

**Comment by BertKleewein** [comment]
@RickBadKan - right now, the only way I know to detect if the twin version has changed is to re-fetch the full twin and compare the $version values.  If the version has changed, the only way to know what has changed is to look through it property-by-property.  Another alternative is to use a json patch library such as https://pypi.org/project/jsonpatch/ to calculate the diff.  I haven't looked at this library in detail, but I assume that it properly handles setting properties to None if they are deleted in the second object.  

Regarding the extra bandwidth consumed by automatically fetching the twin on reconnect, I've opened #599 to suggest a new feature that turns this off.

**Comment by elhorton** [comment]
Thanks @RickBadKan for raising this issue. Since we are tracking this as a feature request in issue #599 , we are going to close this issue. We appreciate you helping make our Python SDK better!

**Comment by az-iot-builder-01** [comment]
@BertKleewein, @RickBadKan, @njbuch, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
