### ISSUE TITLE
Is there a mean to write desired properties via iothub sdk ?

### ISSUE THREAD

**Issue by lmussier** [Azure/azure-iot-sdk-python#519]
# Context
- **OS and version used: Ubuntu 18.04
- **Python version: 3.6.9
- **cloned repo:**  SDK installed via pip3, a876b5cd8c9cbd919d3a6ae0a00b7771e6c63d58

```
robotframework
robotframework-databaselibrary
pyopenssl
-e git+https://github.com/Azure/azure-iot-sdk-python.git@a876b5cd8c9cbd919d3a6ae0a00b7771e6c63d58#egg=azure-iot-hub&subdirectory=azure-iot-hub
-e git+https://github.com/Azure/azure-iot-sdk-python.git@a876b5cd8c9cbd919d3a6ae0a00b7771e6c63d58#egg=azure-iot-device&subdirectory=azure-iot-device
```

# Description of the issue:
Hi,

I'm searching for a way to ** write desired properties in twins**.
I'm able to listen to them from device sdk, i'l able to send c2d messages from the iothub sdk.
But I can't find a way to write desired properties in iothub for them to be propagated to the device.

Is there anything available / planned to do so ?

Thanks you.

**Comment by lmussier** [comment]
... I need fresh air :'(

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/samples/iothub_registry_manager_sample.py here is the twin update sample I was looking for...

**Comment by az-iot-builder-01** [comment]
@lmussier, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
