### ISSUE TITLE
Clarify package name in pip

### ISSUE THREAD

**Issue by bearrito** [Azure/azure-iot-sdk-python#530]
I see this in pypi - https://pypi.org/project/azure-iothub-device-client/

Is that the same as this project? This projects document https://pypi.org/project/azure-iothub-device-client/

points to 

`pip install azure-iot-device`

**Comment by olivakar** [comment]
The correct pypi link for our Device Client Library is 
https://pypi.org/project/azure-iot-device/

And the correct command is `pip install azure-iot-device`

The correct link for IoTHub Service Library the pypi link is 
https://pypi.org/project/azure-iot-hub/

And the command is `pip install azure-iot-hub`

**Comment by az-iot-builder-01** [comment]
@bearrito, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
