### ISSUE TITLE
Samples repository link broken https://pypi.org/project/azure-iot-device/

### ISSUE THREAD

**Issue by prbans** [Azure/azure-iot-sdk-python#533]
Go here

https://pypi.org/project/azure-iot-device/

Look for this line:

Check out the samples repository for example code showing how the SDK can be used in a variety of scenarios, including:

Notice that the link https://pypi.org/project/azure-iot-device/azure-iot-device/samples is broken

**Comment by jebrando** [comment]
@prbans Thanks for the info.  We'll get this updated on the next release.

**Comment by az-iot-builder-01** [comment]
@prbans, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
