### ISSUE TITLE
TLS handshake failing from module to edgeHub

### ISSUE THREAD

**Issue by stevebus** [Azure/azure-iot-sdk-python#539]
# Context

- **OS and version used:** Ubuntu 16.04
- **Python version:** amd64/python:3.7-slim-buster
- **pip version:** n/a
- **list of installed packages:** azure-iot-device~=2.1.1

both edgeHub and edgeAgent are version:  Version - 1.0.9.29532150

## Description of the issue

Using the fairly standard "boilerplate" python module template from VS Code, my module doesn't successfully connect to edgeHub.  It seems like it does (no error in module), but in edgeHub I see the following TLS errors

TLS handshake failed., System.IO.IOException: Channel is closed, 298c0b15

this module is the 'boilerplate' module template generated by VS Code with two exceptions:
- I modified a couple of lines in input1_listener method to do my simple processing..  doesn't matter, as that method never gets invoked
- switched requirements.txt to install the 2.1.1 version of the python SDK instead of 2.0.0 (2.0.0 had the same problem, though)

in the logs for my module, it appears to successfully connect.  However, no messages ever get routed to it.   And even if I'm not actively generating messages, the edgeHub logs are full of this error:

TLS handshake failed., System.IO.IOException: Channel is closed, 298c0b15

this is the only module running other than edgeAgent and edgeHub.

## Code sample exhibiting the issue

the boilerplate python module generated by VS code

**Comment by stevebus** [comment]
nevermind - stand down..  boilerplate C# module doesn't work either, so not specific to python..   closing.

**Comment by az-iot-builder-01** [comment]
@stevebus, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
