### ISSUE TITLE
How to remove the delay from Invoking module with sending message to listener

### ISSUE THREAD

**Issue by nishad1092** [Azure/azure-iot-sdk-python#556]
Hi, 
I have this code where, I'm using 2 edge modules, 
1st module has Invoke_method_on_module and send_message_to_output where the module needs to get invoked and send a message, 
2nd module needs to receive it using receive_message_on_input.

here is the portion of the code:

```
async def method_listener(module_client):
        while True:
            print("Module listener")
            method_request = await module_client.receive_method_request("start")
            # Wait for unknown method calls
            # set response payload
            payload = {"result": True, "data": "Received"}
            status = 200  # set return status code
            print("executed method: " + method_request.name)
            print("Payload")
            method_response = MethodResponse.create_from_method_request(
                method_request, status, payload
            )
            # send response
            await module_client.send_method_response(method_response)
            await send_test_message(method_request)
  # send response
    listeners = await asyncio.gather(method_listener(module_client))
    # asyncio.run(await send_test_message(2))
    listeners.cancel()

    # finally, disconnect
    await module_client.disconnect()


async def send_test_message(method_request):
    global module_client
    print("Invoking message to next Module")
    msg = method_request.name
    await module_client.send_message_to_output(msg, "outputmsg")
    print("Done Invoke")
```

What I need:
I'm invoking the module with an API, and I want the entire process to be completed with 1 invoke (getting invoked and sending message and listening)

What Is happening:
When I send invoke from API once, It is taking 8 - 10 seconds to send msg or to listen in the next module, some where it is taking latency.
But, When I send invoke twice from API (**sending Twice simultaneously**) then it sends or listens immediately, and there is no latency in the entire process?
##scenario: Sending once API takes 8 seconds but sending twice does the job asap. How?

What I want to know:
1. How to resolve this?
2. Is this some logical error or Async programming  nature or is it how azure iot sdk is designed. 

Please help me resolve this.

AB#7366708

**Comment by nishad1092** [comment]
Hi, Anyone got any idea about this please?

**Comment by cartertinney** [comment]
Our apologies for not getting to this sooner. We are currently unaware of the cause of the issue, but we are looking into it and hope to have some information in the near future.

**Comment by BertKleewein** [comment]
Hi @nishad1092, I'm having trouble understanding your question.  What API is taking 8 seconds?  How are you "sending twice simultaneously".?  I don't see you invoking the method named "start" anywhere so I'm not sure how this is involved.

**Comment by nishad1092** [comment]
> Our apologies for not getting to this sooner. We are currently unaware of the cause of the issue, but we are looking into it and hope to have some information in the near future.

Hi @cartertinney Thnz for the response, Sure, I'll be happy to get this resolved soon.

**Comment by nishad1092** [comment]
> Hi @nishad1092, I'm having trouble understanding your question. What API is taking 8 seconds? How are you "sending twice simultaneously".? I don't see you invoking the method named "start" anywhere so I'm not sure how this is involved.

Hi @BertKleewein  Im using this api https://docs.microsoft.com/en-us/rest/api/iothub/digitaltwinmodel/service/invokedevicemodulemethod to invoke this module above mentioned, Since Im running this api through postman , I can send it "twice" right, So only when Im executing this api request twice or more, the response is given asap, otherwise for 1 request , response is delayed, I really im not getting why is that?

**Comment by az-iot-builder-01** [comment]
@nishad1092, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
