### ISSUE TITLE
Cannot remove Device Twin property / key

### ISSUE THREAD

**Issue by ralfr** [Azure/azure-iot-sdk-python#558]
I am trying to remove a property (key) from a Device Twin:

`
reported_properties_patch = {"name": null}
await device_client.patch_twin_reported_properties(reported_properties_patch)
`

and receive the following error:

**```NameError: name 'null' is not defined```**

Any idea? What's the correct way to removing a key?

**Comment by ralfr** [comment]
Found the solution myself. In Python I have to use `None` and not `null`.

**Comment by elhorton** [comment]
thanks for the update, glad you found the solution! Closing this issue.

**Comment by az-iot-builder-01** [comment]
@ralfr, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
