### ISSUE TITLE
[Technical Question] SSL certificate verify failed:  unable to get local issuer certificate

### ISSUE THREAD

**Issue by GlanThorian** [Azure/azure-iot-sdk-python#562]
Hello,

First I want to state that I have already searched the related issues here and on the internet, also I read the related documentations, but of course it can be that I have missed some. 

My goal is to communicate form a custom device, which has a SOM board on it running Linux (Debian Buster)
First I installed Azure IoT Device SDK on my computer (Windows10) and downloaded the iot-hib Quickstart samples. I created a test device on iot hub (using VS Code) and also generated SAS token for it. I run SimulatedDevice.py it works properly. 

Next I tried to run the same SimulatedDevice.py from my virtual machine (Ubuntu 16.04), of course first I installed the necessary toolchain. It also works properly. Note: I use the same connection string for the test.

After this I installed the Azure IoT Device SDK on my embedded device, copied the SimulatedDevice.py sample(with same connection string) and I got the following error message(I won't copy the full message but if it necessary I will)

```
transport.connect raised error

File "/usr/lib/python3.7/ssl.py", line 1117, in do_handshake
self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1056)
```

I tried to search whether others had similar issue to this, here is what I tried:

- check if certifi python package is installed - many suggested that this solved their similar issue, but I had it already installed

- check certificates: I checked in `/etct/ssl/certs` and I have `Baltimore_CyberTrust_Root.pem`, I don't know whether I should check for other certificates as well?

- check python version - I use `Python 3.7.3`

- check whether I can reach the my iot hub with requests - I tried with requests.get and I could reach the iot hub through port 8883

- I am using home network (but in case of the successful test from windows and ubuntu I used the same network)

Can someone please give me some pointers what other things should I try, how could I discover the root cause of this issue?

**Comment by olivakar** [comment]
I specifically used the Baltimore cert and the sample ran correctly for me. 
Can you try out your sample using another cert that you supply and see if it works ?

If you do so, please establish the connection using

```
certfile = open(filename_of_cert)
root_ca_cert = certfile.read()

device_client = IoTHubDeviceClient.create_from_connection_string(connection_string=conn_str,
                                                                     server_verification_cert=root_ca_cert)
```

**Comment by GlanThorian** [comment]
Hello!

So I tried to set the baltimore certificate directly and it helped, thanks! The certificate is valid by the way.
For me the interesting thing is that it works differently on different platforms... 
I am using a VAR-SOM-MX7. 
Thanks for the help again!

**Comment by olivakar** [comment]
I will close the issue.

**Comment by az-iot-builder-01** [comment]
@GlanThorian, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
