### ISSUE TITLE
What are the packages need to be installed before running this script?

### ISSUE THREAD

**Issue by Canalytix** [Azure/azure-iot-sdk-python#57]
Please help me,

What are the packages need to be installed before running this script?

Because, when run the script I get this error,

ModuleNotFoundError                       Traceback (most recent call last)
<ipython-input-7-215347aec7aa> in <module>()
     11 from iothub_client import IoTHubClient, IoTHubClientError, IoTHubTransportProvider, IoTHubClientResult
     12 from iothub_client import IoTHubMessage, IoTHubMessageDispositionResult, IoTHubError, DeviceMethodReturnValue
---> 13 from iothub_client_args import get_iothub_opt, OptionError
     14 
     15 # HTTP options

ModuleNotFoundError: No module named 'iothub_client_args'

I only have these packages at the moment
1. azure_iothub_device_client
2. azure_iothub_service_client

Thanks

**Comment by zolvarga** [comment]
@Canalytix 

Please take a look at our samples here:
https://github.com/Azure/azure-iot-sdk-python/tree/master/device/samples
https://github.com/Azure/azure-iot-sdk-python/tree/master/service/samples

When you run the sample you would need all the "py" files in the same directoy, including iothub_client_args.py.

Best Regards,
Zoltan

**Comment by tameraw** [comment]
Closing. Please let us know if still having any issues.
