### ISSUE TITLE
Missing module twin patch IoTEdge SDK

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#570]
I have used sample from here as primary inspiration: https://github.com/Azure/azure-iot-sdk-python-preview/blob/master/azure-iot-device/samples/advanced-hub-scenarios/receive_twin_desired_properties_patch.py

This is not implemented or included in the new SDK. Whats the recommended route forward for implementing use of module-twins from python in a module on IoTEdge?

AB#7366706

**Comment by az-iot-builder-01** [comment]
@njbuch, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by njbuch** [comment]
Mistake

**Comment by njbuch** [comment]
Still a problem

**Comment by njbuch** [comment]
Hmm, this is the error I am getting from the older SDK:
`ReauthorizeConnectionOperation: completing with error OperationCancelled('Transport timeout on connection operation',)
ConnectionLockStage(ReauthorizeConnectionOperation): op failed.  Unblocking queue with error: OperationCancelled('Transport timeout on connection operation',)
UpdateSasTokenOperation: completing with error OperationCancelled('Transport timeout on connection operation',)
UseAuthProviderStage(UpdateSasTokenOperation): token update operation failed.  Error=OperationCancelled('Transport timeout on connection operation',)
Exception caught in background thread.  Unable to handle.
["azure.iot.device.common.pipeline.pipeline_exceptions.OperationCancelled: OperationCancelled('Transport timeout on connection operation',)\n"]
`

**Comment by kgalic** [comment]
I have the same problem, that this is not getting triggered/called. It keeps awaiting. Can anyone from the product group  help on this one?

**Comment by cartertinney** [comment]
Which version of the package are you using? Is it the latest 2.1.2?

**Comment by njbuch** [comment]
Yes, it is the latest.

**Comment by olivakar** [comment]
Closing issue as another module receive twin has been logged

https://github.com/Azure/azure-iot-sdk-python/issues/573
