### ISSUE TITLE
receive_twin_desired_properties_patch on module - inconsistent behaviour

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#573]
# Context

- **OS and version used:** Linux an0206 4.19.97-v7l+ #1294 SMP Thu Jan 30 13:21:14 GMT 2020 armv7l GNU/Linux Raspian 10 Buster
- **Python version:** 3.5.3
- **pip version:** pip 9.0.1 from /usr/lib/python3/dist-packages (python 3.5)
- **list of installed packages:** 
aniso8601 (8.0.0)
azure-iot-device (2.1.1)
certifi (2020.4.5.1)
chardet (3.0.4)
click (7.1.2)
Flask (1.1.2)
Flask-RESTful (0.3.8)
idna (2.9)
itsdangerous (1.1.0)
janus (0.5.0)
Jinja2 (2.11.2)
MarkupSafe (1.1.1)
numpy (1.12.1)
paho-mqtt (1.5.0)
pip (9.0.1)
pygame (1.9.6)
PySocks (1.7.1)
pytz (2020.1)
requests (2.23.0)
requests-unixsocket (0.2.0)
setuptools (33.1.1)
six (1.14.0)
transitions (0.8.1)
urllib3 (1.25.9)
Werkzeug (1.0.1)

## Description of the issue
I am running the code below in a seperate thread in a IoT Edge module, and the blocking call to receive_twin_desired_properties_patch does not consistently unblock when there is a change to desired properties. The code works 1 of 5 times, but the changes are not always sent to the module to unblock this call.

## Code sample exhibiting the issue
I have a thread that runs this code:
```
    module_client = IoTHubModuleClient.create_from_edge_environment()
    module_client.connect()
    while True:
        try:
            while True:
                twin = module_client.receive_twin_desired_properties_patch(block=True, timeout=60) 
                if twin != None:
                    break
            app.logger.info(twin)
```

## Console log of the issue
None.

AB#7366707

**Comment by njbuch** [comment]
Further to this, after a longer burn-in period I have spotted some info that might be helpful in the logs:

```
CoordinateRequestAndResponseStage(ResponseEvent): request_id b3d632b8-e608-4c0d-af39-7c527945667c not found in pending list.  Nothing to do.  Dropping
CoordinateRequestAndResponseStage(ResponseEvent): request_id b4c89066-c566-4b05-a5d9-8c7221972593 not found in pending list.  Nothing to do.  Dropping
CoordinateRequestAndResponseStage(ResponseEvent): request_id b4c89066-c566-4b05-a5d9-8c7221972593 not found in pending list.  Nothing to do.  Dropping
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0xb2983ad0>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 226, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/mqtt_transport.py", line 574, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('The client is not currently connected.',)

MQTTPublishOperation: completing with error ConnectionDroppedError('The client is not currently connected.',)
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionDroppedError('Paho returned rc==1',)
CoordinateRequestAndResponseStage(ResponseEvent): request_id 858c2fea-f05e-4941-8e88-7589177692f5 not found in pending list.  Nothing to do.  Dropping
```

And

```
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0xb2983ad0>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 226, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/mqtt_transport.py", line 574, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('The client is not currently connected.',)

MQTTPublishOperation: completing with error ConnectionDroppedError('The client is not currently connected.',)
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0xb2983ad0>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 226, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/mqtt_transport.py", line 574, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('The client is not currently connected.',)

MQTTPublishOperation: completing with error ConnectionDroppedError('The client is not currently connected.',)
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): failing ConnectOperation op because of error
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
Response received for unknown MID: 2881
CoordinateRequestAndResponseStage(ResponseEvent): request_id 6ef952fc-5c62-4359-b23c-d58c2520b7d3 not found in pending list.  Nothing to do.  Dropping
Response received for unknown MID: 2882
```
And these messages repeat with regular intervals while the different threads are running.

**Comment by njbuch** [comment]
Please note that the samples on this are using the deviceClient features, and my code are using the module-client - and assuming they are fundamentally similar.

**Comment by njbuch** [comment]
Adding the this debugging, I am now seeing something more, the use of blocking calls for the direct_method features are also having inconsistent behavior, and are falling off after a while.

**Comment by kgalic** [comment]
@njbuch did you manage to resolve this? I found an alternative by using module_client.get_twin() but this is something that requires different implementation handling.

**Comment by njbuch** [comment]
> @njbuch did you manage to resolve this? I found an alternative by using module_client.get_twin() but this is something that requires different implementation handling.

Nope, and in my case the twin-manipulations are important to react to relatively quickly, and polling this api would not make sense. But thanks for caring ;)

**Comment by cartertinney** [comment]
Have you tried using the latest version 2.1.2? We have added several connection stability improvements in this latest release

**Comment by njbuch** [comment]
Yes, just double-checked:
```
root@d7c297540d0e:/app# pip3 freeze
aniso8601==8.0.0
azure-iot-device==2.1.2
certifi==2020.4.5.1
chardet==3.0.4
click==7.1.2
dnspython==1.16.0
Flask==1.1.2
Flask-RESTful==0.3.8
idna==2.9
itsdangerous==1.1.0
janus==0.4.0
Jinja2==2.11.2
MarkupSafe==1.1.1
numpy==1.12.1
paho-mqtt==1.5.0
pygame==1.9.6
pymongo==3.10.1
PySocks==1.7.1
pytz==2020.1
requests==2.23.0
requests-unixsocket==0.2.0
six==1.15.0
transitions==0.8.1
urllib3==1.25.9
Werkzeug==1.0.1
root@d7c297540d0e:/app#
```

**Comment by BertKleewein** [comment]
@njbuch - the fact that this is in a separate thread implies that you have at least two different module_client objects?  Is this true?  If so, that could explain your problem.  The two instances would be "fighting" to be connected to the hub such that one instance connects, the other one gets forcibly disconnected (because only one client can be connected at a time), then the other one re-connects and causes the first one to reconnect, and so on.

The fix is to only have a single module client objects.  It is OK to share this object between threads.  It should be completely thread safe.

If you only have a single client object, can you tell me how long the client is running when you see this behavior?  There's a timing bug that I'm working on, but its "window of opportunity" only hits after 58 minutes, and then every 58 minutes after that.

**Comment by njbuch** [comment]
> @njbuch - the fact that this is in a separate thread implies that you have at least two different module_client objects? Is this true? If so, that could explain your problem. The two instances would be "fighting" to be connected to the hub such that one instance connects, the other one gets forcibly disconnected (because only one client can be connected at a time), then the other one re-connects and causes the first one to reconnect, and so on.
> 
> The fix is to only have a single module client objects. It is OK to share this object between threads. It should be completely thread safe.

I only use one module_client instantiated in the beginning, and used from several threads. 


> If you only have a single client object, can you tell me how long the client is running when you see this behavior? There's a timing bug that I'm working on, but its "window of opportunity" only hits after 58 minutes, and then every 58 minutes after that.

I have created some extra logging and will revert when I see problems, with some timestamps if possible. How long is the window after 58 minutes?

Further to this I am still seing this error

```
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0xb292a3f0>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 226, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/mqtt_transport.py", line 574, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('The client is not currently connected.',)

MQTTPublishOperation: completing with error ConnectionDroppedError('The client is not currently connected.',)
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionDroppedError('Paho returned rc==1',)
CoordinateRequestAndResponseStage(ResponseEvent): request_id 20e98ef0-fdaf-4b2e-949f-b55fed223db1 not found in pending list.  Nothing to do.  Dropping


```

**Comment by njbuch** [comment]
I have been trying to stabilize the system, without luck.

Here is a new chunk of the log:
```
[2020-06-15 11:22:10,656] ERROR in main: LOGGER: Exception in the send keepalive function.
[2020-06-15 11:22:10,657] INFO in main: The Soundgroup starting point is:GROUP2
transport.connect raised error
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 168, in _run_op
    self.transport.connect(password=self.sas_token)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/mqtt_transport.py", line 425, in connect
    self._mqtt_client.loop_start()
  File "/usr/local/lib/python3.5/dist-packages/paho/mqtt/client.py", line 1825, in loop_start
    self._thread.start()
  File "/usr/lib/python3.5/threading.py", line 844, in start
    _start_new_thread(self._bootstrap, ())
RuntimeError: can't start new thread

ConnectOperation: completing with error can't start new thread
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: can't start new thread
```

I am trying send some info to Atlas MongoDB at the 11:22:10,656 timestamp. The code continues, but shortly after fails on the MQTT related stuff. Which fails, and seems to prevent a new thread starting, and the whole system ends up in a bad state.

**Comment by njbuch** [comment]
Terrible mistake on my side, sorry for wasting your time. Thanks for trying to assist. Multithreading gone wrong.

I see no problems now.

**Comment by az-iot-builder-01** [comment]
@njbuch, @kgalic, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
