### ISSUE TITLE
Unable to generate SAS Token using python Script.

### ISSUE THREAD

**Issue by nishad1092** [Azure/azure-iot-sdk-python#577]
Hello, I am trying to execute python script mentioned [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/azure/iot/hub/sastoken.py) to generate SAS Token.
I have added the parameters value according to my iothub. I have added the parameters in the section from line 49-54.
I am not getting any error but there is no output as well.
Can you please guide me what might be wrong. 
I have updated the following snippet from the script. Do I need to add any other details also, please let me know
 ```
def __init__(self, uri, key, key_name=None, ttl=3600):
        self._uri = urllib.parse.quote_plus(uri for my iothub)
        self._key = my_iothub_key
        self._key_name = my_iothub_key_name
        self.ttl = ttl
        self.refresh()
```

**Comment by olivakar** [comment]
The class that you are using is for internal usage only. 

But if you are using that as a helper script for your own specific scenario utilizing the same code it should not be a problem. That script will return error in case it is not able to build the token. Without completely knowing how you are using it will be difficult to understand the issue.

I tried the `SasToken` class as is with the following dummy code and it worked for me. May be you should try printing out the token or the string representation for it. 

```
token = SasToken("some_hostname.com", "FCKY")

print(token)
print(str(token))
```


OUTPUT

```
SharedAccessSignature sr=some_hostname.com&sig=KXSg9p1D0c8KThfNF6rN9MaeUd4u53WuRkvFVsunFbI%3D&se=1590710595
SharedAccessSignature sr=some_hostname.com&sig=KXSg9p1D0c8KThfNF6rN9MaeUd4u53WuRkvFVsunFbI%3D&se=1590710595
```

**Comment by nishad1092** [comment]
Hi @olivakar , thanks for the response, I still couldn't understand, Could you walk me through how to execute this code? or should we execute the entire set of codes in the auth folder? https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/azure/iot/device/common/auth

Where to print this sasToken, It would be great if you could walkthrough this script or how to generate sas token.

**Comment by olivakar** [comment]
@nishad1092 you have linked 2 different `sastoken` files both time.
I am not sure what you are using the class for. 

If you are using to create clients for either device or hub then you should **NOT** use this class externally. Any authentication will be handled appropriately as mentioned by Carter above.

But if you are using this for some other scenario **unrelated to our device or hub functionalities** as a helper code then you can always copy the code that builds the token and use it for ur own purpose. 
You will only need common python modules (like hmac, hashlib and base64) in that case.

**Comment by nishad1092** [comment]
@cartertinney @olivakar thanks for the response. I'll sum up what I really want to achieve. I'm using azure components and for its use case only. 

Tell me what I need to do to generate sas token for Azure IoT Hub. Becuase now I either use azure cli or through VS code to generate it. I just want to generate sas token for IoT hub programmatically.

**Comment by olivakar** [comment]
As said before , in the last comment, you can always copy the code in the `build token` portion to create your own SAS token. You don't need to use the class, you can selectively copy only the build token portion. You will need only base64, hmac, hashlib and urllib modules.

Please don't use the class for generating sas tokens for your own purpose.
As an example I have copied this code and created 2 sas tokens. Feel free to use this code snippet.

```
import base64
import hmac
import hashlib
import six.moves.urllib as urllib

_service_token_format = "SharedAccessSignature sr={}&sig={}&se={}&skn={}"
_device_token_format = "SharedAccessSignature sr={}&sig={}&se={}"

def build_token(uri, key, expiry_time, key_name=None, encoding_type="utf-8"):
    """Buid SasToken representation
    Returns:
    String representation of the token
    """
    try:
        message = (uri + "\n" + str(expiry_time)).encode(encoding_type)
        signing_key = base64.b64decode(key.encode(encoding_type))
        signed_hmac = hmac.HMAC(signing_key, message, hashlib.sha256)
        signature = urllib.parse.quote(base64.b64encode(signed_hmac.digest()))
    except (TypeError, base64.binascii.Error) as e:
        raise TypeError("Unable to build SasToken from given values", e)
    if key_name:
        token = _service_token_format.format(
            uri, signature, str(expiry_time), key_name
        )
    else:
        token = _device_token_format.format(uri, signature, str(expiry_time))
    return token


if __name__ == '__main__':
    token_without_key_name = build_token("hogwarts.com", "OUST", 3600)
    print(token_without_key_name)
    token_with_key_name = build_token("hogwarts.com", "OUST", 3600, "fake_key_name")
    print(token_with_key_name)
```


The output for sas without keyname

```
SharedAccessSignature sr=hogwarts.com&sig=O%2B5h31Bo/iGcriX84J%2B7lfRlyY%2BIS2KBh7iHSKi7N28%3D&se=3600
```
The output for sas with keyname
```
SharedAccessSignature sr=hogwarts.com&sig=O%2B5h31Bo/iGcriX84J%2B7lfRlyY%2BIS2KBh7iHSKi7N28%3D&se=3600&skn=fake_key_name
```

**Comment by nishad1092** [comment]
Hi @olivakar , Thannk you so much for walking throgh the code again, It worked and generated the SAS token, but somehow it isn't working. Im using the postman to check it using one basic API, but it always gives this error as in the response body and a 401 unauthorized, 
I then compared with the SAS token generated from the VS code, and it worked just fine,
Compared both SAS token and it looks fine to me. I'm checking what went wrong. since expiry time needs to be in UTC, I added this  to your code:
expiry_time = int(time.time() + 3600)
(Just added 1 hour expiry from the UTC, Looks good but Postman responded error) Please respond if you knw why this happened .. 

{
    "Message": "{\"errorCode\":401002,\"trackingId\":\"01d7d277a5e34c56a87-G:3-TimeStamp:06/03/2020 14:57:14\",\"message\":\"Unauthorized\",\"timestampUtc\":\"2020-06-03T14:57:14.1051442Z\"}",
    "ExceptionMessage": ""
}

**Comment by az-iot-builder-01** [comment]
@nishad1092, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
