### ISSUE TITLE
Is it possible to provide pip way to use this module for Ubuntu?

### ISSUE THREAD

**Issue by erich-wang** [Azure/azure-iot-sdk-python#58]

**Comment by tameraw** [comment]
Yes. This has been released as of two weeks ago.
https://github.com/Azure/azure-iot-sdk-python/releases
Pip packages:
https://pypi.python.org/pypi?:action=display&name=azure-iothub-device-client&version=1.1.20.0
https://pypi.python.org/pypi?:action=display&name=azure-iothub-service-client&version=1.1.0.12

**Comment by erich-wang** [comment]
Great! It would be great if adding section for pip way on Linux in [Prepare your development environment](
https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md)

**Comment by zolvarga** [comment]
I updated the document

Best Regards,
Zoltan
