### ISSUE TITLE
after pip installing azure.iot.device and azure version 4.0.0, i can still not get the module imported into my python program. The error i get is "from azure.iot.device import IoTHubDeviceClient, Message, MethodResponse ModuleNotFoundError: No module named 'azure'"

### ISSUE THREAD

**Issue by mishfish123** [Azure/azure-iot-sdk-python#580]

**Comment by az-iot-builder-01** [comment]
@mishfish123, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
