### ISSUE TITLE
Re-connecting causes repeated ConnectionDroppedError

### ISSUE THREAD

**Issue by maranov** [Azure/azure-iot-sdk-python#581]
Hi,

# Context

- **OS and version used:** Windows 10
- **Python version:** 3.8.2, AMD64
- **pip version:** 19.2.3
- **list of installed packages:**
```
Package             Version
------------------- ----------
astroid             2.4.1
azure-iot-device    2.1.2
certifi             2020.4.5.1
chardet             3.0.4
colorama            0.4.3
idna                2.9
isort               4.3.21
janus               0.4.0
lazy-object-proxy   1.4.3
mccabe              0.6.1
paho-mqtt           1.5.0
pip                 19.2.3
pylint              2.5.2
PySocks             1.7.1
requests            2.23.0
requests-unixsocket 0.2.0
setuptools          41.2.0
six                 1.15.0
toml                0.10.1
transitions         0.8.1
urllib3             1.25.9
wrapt               1.12.1
```
- **cloned repo:** N/A

## Description of the issue
Properly disconnecting an existing IoTHubDeviceClient, re-creating and re-connecting it logs ConnectionDroppedError and causes direct method invocations and C2D messages to fail in about a half of the cases. D2C messaging functionality remains unaffected.

## Code sample exhibiting the issue
Can be reproduced by running the following modified sample. Direct methods invoked via Azure portal work OK, until first "q" is issued, then about a half of them fail and errors get logged.

```python
import os
import asyncio
from logging import basicConfig
from six.moves import input
from azure.iot.device.aio import IoTHubDeviceClient
from azure.iot.device import MethodResponse


async def main():
    conn_str = os.getenv("IOTHUB_DEVICE_CONNECTION_STRING")
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
    await device_client.connect()

    async def generic_method_listener(device_client):
        while True:
            method_request = await device_client.receive_method_request()
            payload = {"result": True, "data": "some data"}
            status = 200
            print("executed method")
            method_response = MethodResponse.create_from_method_request(method_request, status, payload)
            await device_client.send_method_response(method_response)

    def stdin_listener():
        while True:
            selection = input("Press Q to quit\n")
            if selection == "Q" or selection == "q":
                print("Quitting...")
                break

    listeners = asyncio.gather(generic_method_listener(device_client))
    loop = asyncio.get_running_loop()
    user_finished = loop.run_in_executor(None, stdin_listener)
    await user_finished
    listeners.cancel()
    await device_client.disconnect()


if __name__ == "__main__":
    basicConfig(filename='log.txt', level=0)
    asyncio.run(main())
    asyncio.run(main())
```

## Console log of the issue
Output after invoking one method, "quitting", then four more methods.
```
python .\sample.py
Press Q to quit
executed method
q
Quitting...
Press Q to quit
executed method
executed method
q
Quitting...
```

Azure portal error:
```
{"message":"{\"Message\":\"{\\\"errorCode\\\":400027,\\\"trackingId\\\":\\\"31fc865c994e4833b83ef786a2b8606b-G:16-TimeStamp:05/29/2020 13:23:01\\\",\\\"message\\\":\\\"BadRequest\\\",\\\"info\\\":{},\\\"timestampUtc\\\":\\\"2020-05-29T13:23:01.8967782Z\\\"}\",\"ExceptionMessage\":\"\"}"}
```

Attached "logging" log. The moment new instance was created can be identified by the 2nd "DEBUG:asyncio:Using proactor: IocpProactor" line.

## Notes
Disposing of every resource and starting anew is an approach that we've used to handle unexpected/unrecoverable exceptions in our system. Another usecase is enabling and disabling the Hub component on demand.

Looking at the log and SDK code, it seems it leaves a number of resources behind, after "disconnecting" (e.g. token update timers). This seems to be the core of the problem. The fact that some messages go through, while others don't seems to indicate that the new and old connection are continuously fighting over the same endpoint.

AB#7344401

**Comment by maranov** [comment]
The log:
[log.txt](https://github.com/Azure/azure-iot-sdk-python/files/4702153/log.txt)

**Comment by olivakar** [comment]
I tried your sample ditto and almost ran it for more than 2 hours without any issues. I have not been able to replicate it so far. 


Could you try out this other local package to see if this resolves the situation ?
https://github.com/Azure/azure-iot-sdk-python/issues/531#issuecomment-634275019

**Comment by maranov** [comment]
Hi olivakar,
odd, when I run the sample, I can replicate the error every time. I made a docker image you could try:
```shell
# Have .env file ready with "IOTHUB_DEVICE_CONNECTION_STRING=..." contents.
docker run --env-file .env -it --name iot-hub-bug-test maranov/iot-hub-bug
# After invoking a method, quitting and invoking the method again several more times, quit and extract the log:
docker cp iot-hub-bug-test:/log.txt .
# Container can be removed afterwards:
docker container rm iot-hub-bug-test
```

I've also tried the alternative version. On reconnection it goes into a failure loop, unable to handle any direct methods at all. The errors also occur in a quicker succession. I noticed there's just one token update timer running, which is also IMHO wrong -- there should be two, each starting and then stopping on each connect/disconnect. An indication that disconnect() doesn't properly dispose of all resources in both versions.

Also tried on Ubuntu 20.04 with the same result.

**Comment by BertKleewein** [comment]
I know about this one.  I have a fix almost ready to go -- I'm just working on the unit tests now.

**Comment by maranov** [comment]
Hi Bert,
great. If you have some dev version available, I could do some testing.

**Comment by BertKleewein** [comment]
Hi @maranov, here is a test version for this.  The PR for this fix is #576.  This should work as long as you call device_client.disconnect, which I see you are doing, so you should be good. 
 
[azure_iot_device-2.1.2_test_pr576-py2.py3-none-any.zip](https://github.com/Azure/azure-iot-sdk-python/files/4746304/azure_iot_device-2.1.2_test_pr576-py2.py3-none-any.zip)

**Comment by maranov** [comment]
Thanks @BertKleewein, I've tested the wheel with the sample and our SW a few times, including over websockets and a different OS and the issue seems to be gone.

The logs of of the two sequential instantiations show very similar init & destruction. Nothing suspicious, everything seems to be OK. Good job. :-)

**Comment by az-iot-builder-01** [comment]
@maranov, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
