### ISSUE TITLE
module_client.receive_message_on_input does not return the message

### ISSUE THREAD

**Issue by kgalic** [Azure/azure-iot-sdk-python#587]
The code below does not get executed properly, and the application 'hangs' on 'receive_message_on_input' method. All the messages that I send to this specific route do no trigger the code below this method call. It seems like the method keeps 'awaiting' forever. 

       async def input_listener(module_client):
            while True:
                print("Listening for messages in input!")
                input_message = await module_client.receive_message_on_input("input")  # blocking call
                if not input_message is None:
                    print("*************************received message %s" % json.dumps(input_message))
                    value = input_message["state"]
                    if value == 1 or value == 0:
                        sensor_reader.update_state(value)
                        print("**************************updated sensor value")
                        timestamp = datetime.datetime.utcnow().strftime('%Y-%m-%d %H:%M:%S:%fZ')

                        message_to_output = sensor_reader.get_message_template(timestamp,
                                                                               sensor_reader.RELAY_MEASUREMENT_TYPE,
                                                                               sensor_reader.get_measurement_unit(),
                                                                               input_message["state"])

                        await module_client.send_message_to_output(message_to_output, TELEMETRY_MESSAGE)
                        print("Messages sent to outputs!")

I am using the latest device client library:
azure-iot-device~=2.1.2
and IoT Edge version 1.0.9.1 

I am running my IoT edge application on Raspbian Buster, on Raspberry PI. 

Expected behavior:
Every time my route passes the message to the specified input, the message gets displayed in the console per code above and executes the rest of the logic.

Below is the route: 
`"MessagePublisherModuleToRelay": "FROM /messages/modules/MessagePublisherModule/outputs/* INTO BrokeredEndpoint(\"/modules/RelayModule/inputs/input\")"`

Side note:
messages I send from the MessagePublisherModule, and message is not None, per my code above..  

The rest of the code is similar like in the MSFT examples, and code generated by VSCode template:
For example, I am calling 
`listeners = asyncio.gather(input_listener(module_client), twin_patch_listener(module_client))`
in order to listen for messages. 
In the console output, I can see 
"Listening for messages in input!"
But nothing more than that.

**Comment by kgalic** [comment]
Logs:


DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_pipeline_event in callback thread
DEBUG:azure.iot.device.iothub.inbox_manager:Input message sent to input inbox
DEBUG:paho:Received PUBLISH (d0, q1, r0, m1), 'devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule', ...  (15 bytes)
DEBUG:paho:Sending PUBACK (Mid: 1)
INFO:azure.iot.device.common.mqtt_transport:message received on devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_message_received in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: message received on topic devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_pipeline_event in callback thread
DEBUG:azure.iot.device.iothub.inbox_manager:Input message sent to input inbox
DEBUG:paho:Received PUBLISH (d0, q1, r0, m1), 'devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule', ...  (15 bytes)
DEBUG:paho:Sending PUBACK (Mid: 1)
INFO:azure.iot.device.common.mqtt_transport:message received on devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_message_received in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: message received on topic devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_pipeline_event in callback thread
DEBUG:azure.iot.device.iothub.inbox_manager:Input message sent to input inbox
DEBUG:paho:Received PUBLISH (d0, q1, r0, m1), 'devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule', ...  (15 bytes)
DEBUG:paho:Sending PUBACK (Mid: 1)
INFO:azure.iot.device.common.mqtt_transport:message received on devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_message_received in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: message received on topic devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_pipeline_event in callback thread
DEBUG:azure.iot.device.iothub.inbox_manager:Input message sent to input inbox
DEBUG:paho:Received PUBLISH (d0, q1, r0, m1), 'devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule', ...  (15 bytes)
DEBUG:paho:Sending PUBACK (Mid: 1)
INFO:azure.iot.device.common.mqtt_transport:message received on devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_message_received in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: message received on topic devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_pipeline_event in callback thread
DEBUG:azure.iot.device.iothub.inbox_manager:Input message sent to input inbox
Pin: 16
DEBUG:paho:Received PUBLISH (d0, q1, r0, m1), 'devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule', ...  (15 bytes)
DEBUG:paho:Sending PUBACK (Mid: 1)
INFO:azure.iot.device.common.mqtt_transport:message received on devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_mqtt_message_received in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_mqtt:MQTTTransportStage: message received on topic devices/kgDebugEdgeDevice/modules/RelayModule/inputs/input/%24.cdid=kgDebugEdgeDevice&%24.cmid=MessagePublisherModule
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting _on_pipeline_event in callback thread
DEBUG:azure.iot.device.iothub.inbox_manager:Input message sent to input inbox
getting the module twin
INFO:azure.iot.device.iothub.aio.async_clients:Getting twin
DEBUG:azure.iot.device.common.pipeline.pipeline_thread:Starting run_op in pipeline thread
DEBUG:azure.iot.device.common.pipeline.pipeline_stages_base:CoordinateRequestAndResponseStage(RequestAndResponseOperation): adding request 361338e7-aa30-401f-ad80-a89daf60acd7 to pending list


:Input message sent to input inbox

**Comment by BertKleewein** [comment]
The problem is that you call json.dumps() on the return from receive_message_on_input.  This raises an exception.  Because your mainline code never awaited the asyncio.gather call that included this coroutine, the exception never surfaced.  In short, the exception was swallowed and input_listener failed silently.  

In the future, I recommend wrapping all listeners with try/except blocks that output exception details before re-raising them.  i also recommend being smarter about handling the return from asyncio.gather.  Since this pattern came from our sample apps, we'll have to update the samples so others don't run into this same bug.

**Comment by kgalic** [comment]
By adding the following lines of code to enable detail logging:
```
import traceback
import logging
logging.basicConfig(level=logging.INFO)
logging.getLogger("paho").setLevel(level=logging.DEBUG)

logging.getLogger("azure.iot.device").setLevel(level=logging.DEBUG)

```

and by surrending my 'receive_message_on_input' method with try-except per example:

```
            except Exception as e:
                traceback.print_exc()
                print("******************* Exception")
                print(e)
```

This helped me to track the issue. Since I am sending the message from C# based module, the object that is retrieved from this method call is a type of Message, which requires to be treated differently than what I expected: 

```
input_message = await module_client.receive_message_on_input("input")  # blocking call
if not input_message is None and not input_message.data is None:
   encoding = 'utf-8'
   message_string = input_message.data.decode(encoding)
   data = json.loads(message_string)
```

**Comment by az-iot-builder-01** [comment]
@kgalic, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
