### ISSUE TITLE
Porting my code from V1 to V2[Technical Question]

### ISSUE THREAD

**Issue by Swiit1** [Azure/azure-iot-sdk-python#588]
Good morning.
A little back story: I'm a mechanic and a hobby programmer (mostly home automation) whos been tasked with setting up some sensors (mostly vibration) as a test project for my company using the Raspberry pi. im quite new to coding. So we hired a 3rd party to setup our IoT hub etc. So i never really read up on anything past preparing the data to be sent from the client to the IoTHub.

As this project expanded i picked up a few new Rpi4's and proceeded to install the SDK. but when running my script i wasnt able to find the Package, i quickly realized it was renamed and after some quick research i saw that youre working on a V2. unfortunately my Third party was unable to answer my questions:

The data im sending is formated as json strings and with multiple values per string (see example 2)
As for the code, im using exactly what i was provided by this thrid party. and i havent done all that much research of the SDK (see example 1)

How would i make this work in V2 of the SDK?

[Example 1.txt](https://github.com/Azure/azure-iot-sdk-python/files/4734468/Example.txt)

[Example 2.txt](https://github.com/Azure/azure-iot-sdk-python/files/4734421/Example.2.txt)

AB#7376392

**Comment by jebrando** [comment]
@Swiit1 A couple of questions before I recommend anything.  What version of python are you using (2.7 or 3.5+)?

If you're using python version 2.7 you should look at this example:
[Python sync sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/sync-samples/send_message.py)

If you're are using version 3.5 or above you should move to async for performance reasons:
[Python async sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/send_message.py)

Does this help at all?

**Comment by Swiit1** [comment]
My apologies for not listing something as obvious as that, I am indeed using python 2.7. 
I have done some research over the past few days, and it seems we were using the "client.set_option("auto_url_encode_decode", True)" and HTTP protocol to bypass a bug in the SDK  [Issue #331](https://github.com/Azure/azure-iot-sdk-c/issues/331) 

If this is not a issue anymore and i can simply go back to the default MQTT protocol without the encode/decode flag without issue then my issue is solved. I will try this tomorrow morning.

**Comment by jebrando** [comment]
The V2 Python SDK is written in pure python and is no longer a port over the c-sdk.  So there is a big paradigm shift so we no longer need to set_options for auto encoding.  If you follow the 2.7 sync samples it should be all you need.  Let us know if you have any issue with any of this.

**Comment by Swiit1** [comment]
The issue in regards to encode/decode has indeed been fixed and the SDK works flawlessly without any additional options. thank you for your help!

**Comment by az-iot-builder-01** [comment]
@Swiit1, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
