### ISSUE TITLE
Error when running the IoT Hub Client Sample

### ISSUE THREAD

**Issue by sebastianbk** [Azure/azure-iot-sdk-python#59]
I am trying to run one of the samples of this repo ([iothub_client_sample_class.py](https://github.com/Azure/azure-iot-sdk-python/blob/master/device/samples/iothub_client_sample_class.py)) but I am constantly running into these errors:

```
Error: Time:Mon Jul 24 15:40:00 2017 File:C:\Users\zolvarga\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\adapters\socketio_win32.c Func:socketio_open Line:306 Failure: connect failure 10060.
Error: Time:Mon Jul 24 15:40:00 2017 File:C:\Users\zolvarga\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\src\tlsio_schannel.c Func:send_chunk Line:413 invalid tls_io_instance->tlsio_state: TLSIO_STATE_NOT_OPEN
Error: Time:Mon Jul 24 15:40:00 2017 File:C:\Users\zolvarga\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\src\tlsio_schannel.c Func:internal_send Line:508 send_chunk failed
Error: Time:Mon Jul 24 15:40:00 2017 File:C:\Users\zolvarga\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\c-utility\src\tlsio_schannel.c Func:tlsio_schannel_send Line:1256 send failed
Error: Time:Mon Jul 24 15:40:00 2017 File:C:\Users\zolvarga\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:sendPacketItem Line:323 1257: Failure sending control packet data
Error: Time:Mon Jul 24 15:40:00 2017 File:C:\Users\zolvarga\Documents\WindowsPowerShell\Modules\aziotsdk_pytools\src\c\umqtt\src\mqtt_client.c Func:mqtt_client_disconnect Line:1097 Error: mqtt_client_disconnect send failed
```

I have tried a bunch of different things to make it work but I can't seem to get around this error. I am running Windows 10 (version 1703, build 15063.483) with Anaconda 4.3.14. I created an environment that contains the following packages:

```
> conda list
# packages in environment at C:\Users\sbran\Anaconda3\envs\azureiot:
#
azure-iothub-device-client 1.1.19.0                  <pip>
pip                       9.0.1                    py36_1
python                    3.6.2                         0
setuptools                27.2.0                   py36_1
vs2015_runtime            14.0.25420                    0
wheel                     0.29.0                   py36_0
```

Here's the command I ran:

```
python iothub_client_sample_class.py -c HostName=vrinno.azure-devices.net;DeviceId=device32e9473e376d4016a2e27fac9b81a6c8;SharedAccessKey=jmxJmbis7IXqLVUTPBmyVogNyvRnEff/Gb198Z08IMg= -p MQTT
```

Note: The connection string above was just for a test device that I have deleted before posting this issue.

I both tried cloning the entire repository and running the sample from within the `samples` directory as well as downloading the three necessary files individually. Neither approach seems to work.

I am quite confused about the reference to the `C:\Users\zolvarga\Documents` directory printed in the output. This directory does not exist on my computer but it seems like it might on one of your developers' PCs (@zolvarga). How can this sort of reference sneak into production code? I don't understand that.

I hope you can help me debug this issue. Please let me know if you need any other diagnostics output from me.

**Comment by zolvarga** [comment]
@sebastianbk 

Hi Sebastian,

The error shows a networking issue (connection timeout) on your box. Go here and search for "10060":
https://msdn.microsoft.com/en-us/library/windows/desktop/ms740668(v=vs.85).aspx

Please verify the connection to your IoTHub.
You can use this command (for MQTT): 
telnet IOTHUB-FQDN 8883

Also please try to run the iothub_client_sample.py (not the class) with the same parameters.

Another thing what I would ask you to do - could you please update to the latest client (version 1.1.20.0) and try it out with that?

Best Regards,
Zoltan

**Comment by tameraw** [comment]
Closing. Let us know if still having any issues.
Regards.
