### ISSUE TITLE
ImportError: libboost_python-py35.so.1.62.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by millena7** [Azure/azure-iot-sdk-python#591]
Hi!

When I try to import **iothub_client** I receive this error: 

**ImportError: libboost_python-py35.so.1.62.0: cannot open shared object file: No such file or directory**

I've seen this issue here, but not using:

Raspbian buster
Python 3.7.3

I already installed **libboost-python1.62.0** using **sudo apt-get install libboost-python1.62.0**

I can't use the Azure API for python! Could you help me please?

**Comment by jebrando** [comment]
@millena7 it looks as if you're using the v1 SDK, which has been deprecated for the new (and Improved) V2 SDK.  What is the pip install command that you're using? 

The correct command is as follows:

```Bash
pip install azure-iot-device
```
Let me know if this works for you.

**Comment by millena7** [comment]
I used this command to install SDK.

If I try again:
"Requirement already satisfied"

**Comment by millena7** [comment]
> @millena7 it looks as if you're using the v1 SDK, which has been deprecated for the new (and Improved) V2 SDK. What is the pip install command that you're using?
> 
> The correct command is as follows:
> 
> ```shell
> pip install azure-iot-device
> ```
> 
> Let me know if this works for you.


Do you have any idea what it might be?

**Comment by jebrando** [comment]
@millena7 Checkout the sample [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/sync-samples/send_message.py) that shows the importing of the library.

If you're trying to send telemetry you can add the import statement

```Python
from azure.iot.device import IoTHubDeviceClient, Message
```
Let me know if you have any issues with this.

**Comment by millena7** [comment]
> @millena7 Checkout the sample [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/sync-samples/send_message.py) that shows the importing of the library.
> 
> If you're trying to send telemetry you can add the import statement
> 
> ```python
> from azure.iot.device import IoTHubDeviceClient, Message
> ```
> 
> Let me know if you have any issues with this.

I already do this import and It works! I can send telemetry messages to azure.
But the issue I'm facing is when I try this import: **iothub_client** 

I need to import this library because without this I can't change the message properties like this:

prop_map = message.properties()
prop_message.add("temperatureAlert", "true" if temperature > TEMPERATURE_ALERT else "false")

**Comment by millena7** [comment]
> @millena7 Checkout the sample [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/sync-samples/send_message.py) that shows the importing of the library.
> 
> If you're trying to send telemetry you can add the import statement
> 
> ```python
> from azure.iot.device import IoTHubDeviceClient, Message
> ```
> 
> Let me know if you have any issues with this.

Hi,

Do you know anything else I can do to solve this problem?

**Comment by elhorton** [comment]
Hi @millena7 , sorry for the delay in getting back to you here. You shouldn't have to mix importing both the v1 and v2 SDK. You say that you are struggling to send message properties-- can you elaborate on your use case here? You should be able to send custom properties on your messages as follows. Please see [this sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/send_message.py) for more info.
``` python
    async def send_test_message(i):
        print("sending message #" + str(i))
        msg = Message("test wind speed " + str(i))
        msg.message_id = uuid.uuid4()
        msg.correlation_id = "correlation-1234"
        msg.custom_properties["tornado-warning"] = "yes"
        await device_client.send_message(msg)
        print("done sending message #" + str(i))
```

**Comment by az-iot-builder-01** [comment]
@millena7, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
