### ISSUE TITLE
[feature request] need way to disable twin fetch on network reconnect

### ISSUE THREAD

**Issue by BertKleewein** [Azure/azure-iot-sdk-python#599]
From #510 

> data consumption is very important for our application. So if the twin is fetched after every reconnection, our data usage is going to skyrocket if the device is placed somewhere with weak signal strength (i.e. so much reconnections). 

It would be nice to have a user-settable option that turns off the "automatically fetch the twin on reconnect" feature.

AB#7485724

**Comment by elhorton** [comment]
commenting to ack this internal issue for supportability reporting
