### ISSUE TITLE
Clone

### ISSUE THREAD

**Issue by abmachinthosh** [Azure/azure-iot-sdk-python#6]
Please do --recursive clone with the repo... Build and setup scripts will not work if you download zip file and run SDK

**Comment by zolvarga** [comment]
Hi abmachintosh,

Thank you for this observation. The zip file created by GitHub does not contain the code for submodules.
We are linking our submodules into language repos and not hard copying them, so the preferred way to work with our repo is to use "git clone ..." and "git submodule update --init --recursive".

I will update our documentation with the information above.

Best Regards,
Zoltan
