### ISSUE TITLE
Network errors - bad connection to IoTHub

### ISSUE THREAD

**Issue by njbuch** [Azure/azure-iot-sdk-python#601]
# Context

- **OS and version used:** Raspian Buster
- **Python version:** 3.5.3
- **pip version:** 9.0.1
- **list of installed packages:** 
aniso8601 (8.0.0)
azure-iot-device (2.1.3)
certifi (2020.4.5.2)
chardet (3.0.4)
click (7.1.2)
dnspython (1.16.0)
Flask (1.1.2)
Flask-RESTful (0.3.8)
idna (2.9)
itsdangerous (1.1.0)
janus (0.4.0)
Jinja2 (2.11.2)
MarkupSafe (1.1.1)
numpy (1.12.1)
paho-mqtt (1.5.0)
pip (9.0.1)
pygame (1.9.6)
pymongo (3.10.1)
PySocks (1.7.1)
pytz (2020.1)
requests (2.23.0)
requests-unixsocket (0.2.0)
setuptools (33.1.1)
six (1.15.0)
urllib3 (1.25.9)
Werkzeug (1.0.1)
- **cloned repo:** NA

## Description of the issue

When running this python IoTEdge module, the connection to the IoTHub fails, and fills the logs with errors.

## Code sample exhibiting the issue
Not sure which part of the code has the problem.

## Console log of the issue
```
MQTTPublishOperation: completing with error ConnectionDroppedError('The client is not currently connected.',)
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): failing ConnectOperation op because of error
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): failing ConnectOperation op because of error
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): failing ConnectOperation op because of error
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
failed to receive on socket: [Errno 32] Broken pipe
failed to receive on socket: [Errno 32] Broken pipe
failed to receive on socket: [Errno 32] Broken pipe
failed to receive on socket: [Errno 32] Broken pipe
failed to receive on socket: [Errno 32] Broken pipe
Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0xb1ff5b30>._run_op() call
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 102, in run_op
    self._run_op(op)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 218, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/usr/local/lib/python3.5/dist-packages/azure/iot/device/common/mqtt_transport.py", line 549, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('The client is not currently connected.',)

MQTTPublishOperation: completing with error ConnectionDroppedError('The client is not currently connected.',)
ConnectOperation: completing with error ConnectionDroppedError('Paho returned rc==1',)
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionDroppedError('Paho returned rc==1',)
failed to receive on socket: [Errno 32] Broken pipe
```

AB#7495927

**Comment by njbuch** [comment]
I forgot to say, this module is working fine on another device, which is running an older Raspian Stretch.

**Comment by njbuch** [comment]
In my investigation I have done an "sudo iotedge check":

```
Connectivity checks
-------------------
√ host can connect to and perform TLS handshake with IoT Hub AMQP port - OK
√ host can connect to and perform TLS handshake with IoT Hub HTTPS / WebSockets port - OK
√ host can connect to and perform TLS handshake with IoT Hub MQTT port - OK
√ container on the default network can connect to IoT Hub AMQP port - OK
√ container on the default network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the default network can connect to IoT Hub MQTT port - OK
√ container on the IoT Edge module network can connect to IoT Hub AMQP port - OK
√ container on the IoT Edge module network can connect to IoT Hub HTTPS / WebSockets port - OK
√ container on the IoT Edge module network can connect to IoT Hub MQTT port - OK
```

**Comment by njbuch** [comment]
I have isolated the problem to my routine that listens for twin-updates, which is running in a seperate thread. This code is resulting in lots of broken pipe and disconnect error messages - see above. The timeout is to make sure its still active.

```
def twin_update_listener():

    global SoundGroup
    global module_client
    app.logger.info("Logger: Twin update listener start.")
    
    while True:
        try:
            app.logger.info("Twin-update-listener waiting.")
            while True:
                twin = module_client.receive_twin_desired_properties_patch(block=True, timeout=600)
                app.logger.info("Twin-update-listener exit from blocked call")
                if twin != None:
                    break

            app.logger.info("Twin-update-listener received a patch.")
            app.logger.info(twin)
       
            try:
                app.logger.info("Reading keys")
                # Code removed for reading the keys removed for testing...
                    
            except KeyError:
                app.logger.info("KeyError Exception")
                exit()

        except Exception as e:
            app.logger.info("Exception %s", e)
            app.logger.info("Exception in twinlistener... reconnecting")
            print("Exception in twinlistener...")
            module_client.connect()
            pass
```

**Comment by SampleText2k77** [comment]
Same issue on Python 3.6.8, azure-iot-device SDK 2.0.1 version, app running in docker, image based on Ubuntu 18.04

Logs: 
`Unexpected error in <azure.iot.device.common.pipeline.pipeline_stages_mqtt.MQTTTransportStage object at 0x7fb9a413fa90>._run_op() call
Traceback (most recent call last):
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_base.py", line 101, in run_op
    self._run_op(op)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_thread.py", line 198, in wrapper
    return func(*args, **kwargs)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 157, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_published)
  File "/root/.local/share/virtualenvs/app-4PlAip0Q/lib/python3.6/site-packages/azure/iot/device/common/mqtt_transport.py", line 497, in publish
    raise _create_error_from_rc_code(rc)
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: The client is not currently connected. caused by None
MQTTPublishOperation: completing with error The client is not currently connected. caused by None
RetryStage(MQTTPublishOperation): Op needs retry with interval 20 because of The client is not currently connected. caused by None.  Setting timer.`

**Comment by olivakar** [comment]
Did you try the latest the `azure-iot-device` to see if this problem still persists ?

**Comment by njbuch** [comment]
I have upgraded to 2.1.4 and see no improvements. Code works fine for a while, looses connection with hub, and never recovers. I am considering other options using classic rest apis, and looking for feasible work-arounds. 

Any tips to re-connect to the hub or create stable direct-method setups will be appreciated.

**Comment by olivakar** [comment]
can you please provide your entire log by enabling logging set to DEBUG ?

**Comment by njbuch** [comment]
> can you please provide your entire log by enabling logging set to DEBUG ?
> it will be easier if you can save the log in a file as well
> 
> Also please also enable logging for this specific library
> `logging.getLogger("paho").setLevel(level=logging.DEBUG)`

Log-levels verified, and log-files sent to @olivakar ! Code can be sent on request.

It seems that the inconsistent twin-operations has very similar problems, code works on-off for some time. 

I have tried putting other processing intensive tasks in seperate process instead of using threading, as I am suspecting some blocking might happen. Most of the time I get the time-out reply from the call.

**Comment by olivakar** [comment]
I have looked at the logs.  I have not found a direct reference to `ConnectionDroppedError`. But these are the interesting lines from the edge hub log.
```
[EdgeHub] - Closing connection for device: an0003/motion-detection, Microsoft.Azure.Devices.Edge.Hub.Core.MultipleConnectionsException: Multiple connections detected for device an0003/motion-detection
```
AND 
```
[EdgeHub] - Closing connection for device: an0003/anicositemasterpy, Microsoft.Azure.Devices.Edge.Hub.Core.MultipleConnectionsException: Multiple connections detected for device an0003/anicositemasterpy
```

`ConnectionDroppedError` may occur if t you have multiple connections for your modules having same identity.

**Comment by njbuch** [comment]
Thanks for looking into this. I am considering the combination of Flask and these blocking threads to be an impossible combination. Searching around, it seems that threading becomes unstable, and the blocking call that waits for the method-call is never unblocked, and the call fails. 

I tried the asyncio sample for the direct method calls, and that one runs seamlessly. 

To me this is a very annoying case, and I am now forced to ugly workarounds, creating routing and hub-modules to have simple method calls work.

If anyone has experience with Flash and direct-method calls to a module on an azure edge device I would love to hear from them.

**Comment by njbuch** [comment]
> I have looked at the logs. I have not found a direct reference to `ConnectionDroppedError`. But these are the interesting lines from the edge hub log.
> 
> `ConnectionDroppedError` may occur if t you have multiple connections for your modules having same identity.

I only have one module_client.connect() call in the init of the module, and I am not sure I understand you point?

**Comment by olivakar** [comment]
Please zip your code at this point coz it will be difficult for me to say otherwise from where it is occurring. 

Direct methods mean this API `receive_method_request`? But the cause of the problem isolated and shown here in code snippet seems to be `receive_twin_desired_properties_patch` which is another API.

**Comment by njbuch** [comment]
> Please zip your code at this point coz it will be difficult for me to say otherwise from where it is occurring.

Its on its way to you. :)

> 
> Direct methods mean this API `receive_method_request`. But the cause of the problem isolated and shown here in code snippet seems to be `receive_twin_desired_properties_patch` which is another API.


Both calls behave in similar way, and are used in similar ways from the code.

**Comment by njbuch** [comment]
I have refactored the whole module to use aiohttp instead of Flask, and are using the asyncio calls for the direct methods and twin-updates instead of the blocking calls that are too fragile. 

This works like a charm and this issue does not matter to me anymore. Thanks for trying to help me.

I will not close this issue myself, as it might be important to others. 

@olivakar You can stop investigating my code.

**Comment by az-iot-builder-01** [comment]
@njbuch, @SampleText2k77, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
