### ISSUE TITLE
[Technical Question] Help On Sample - provision_symmetric_key.py

### ISSUE THREAD

**Issue by jorgevinagre** [Azure/azure-iot-sdk-python#602]
Hi there
I´m asking for help because pyhton isn´t my "native language" but I need a sample on how to properly send an infinite number of messages(with intervals) to IoTHub(using async) that can be properly "canceled".
I explain:If we take the sample on https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/provision_symmetric_key.py as an example.
How to send "n" messages over time with 20 seconds interval. Should the async def send_test_message(i) method have a While True loop with a time.sleep or a await asyncio.sleep?
How to properly stop this from running?

I would appreciate a simple sample on this.

Thanks everyone

AB#7526323

**Comment by olivakar** [comment]
It seems you are tying to just send message to IoTHub , not sure why you are using provisioning sample.
Here is a [sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/send_message.py) that sends multiple messages to IoTHub.

Is there a reason why you would like to have an interval between sending each message ?
With async it is possible to actually send them at the same time. 
If you are looking for a pattern where you would like to have an interval between messages , then this [sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/sync-samples/send_message.py) should help you.

**Comment by az-iot-builder-01** [comment]
@jorgevinagre, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
