### ISSUE TITLE
[client.py] : Failed to receive on socket: [Errno 104] Connection reset by peer

### ISSUE THREAD

**Issue by mebster2** [Azure/azure-iot-sdk-python#603]
Hi there,

<h2>Context</h2>

* OS and version used: Ubuntu 18.04 / Windows 10 Build 18363
* Python version: 3.6, 3.7 / 3.8.3
* pip version: 20.0.2 / 20.1.1
* list of installed packages:
 adal==1.2.2
aiohttp==3.6.2
async-timeout==3.0.1
attrs==19.3.0
azure-common==1.1.23
azure-iot-device==2.1.3
azure-keyvault==1.1.0
azure-nspkg==3.0.2
azure-storage-blob==12.2.0
certifi==2019.9.11
cffi==1.13.2
chardet==3.0.4
cryptography==2.8
docker==4.1.0
future==0.18.2
idna==2.8
isodate==0.6.0
json-compare==0.2.11
msrest==0.6.10
msrestazure==0.6.2
multidict==4.6.1
oauthlib==3.1.0
pycparser==2.19
pyjwt==1.7.1
pylint==2.4.4
pyopenssl==19.1.0
python-dateutil==2.8.1
python-rapidjson==0.9.1
requests-oauthlib==1.3.0
requests==2.22.0
six==1.13.0
splunk-sdk==1.6.12
terminaltables==3.1.0
urllib3==1.25.7
websocket-client==0.56.0
yarl==1.3.0
pymsteams==0.1.12
robotframework==3.1.2 
xmlrunner==1.7.7
xmltodict==0.12.0

<h2>Description</h2>
Test connects to IoTHub, requests/writes information from/into the device twin.
It seems that the remote peer (Azure/IoTHub) resets the connection. This results in a lot of (automatic) reconnects during the tests. Many exceptions happen. But sooner or later the connection recovers and the test finishes. 

For more details see attached logs.

<h2>Questions</h2>
Is this a known issue?
Do you have any ideas how to solve it?

<h2>Logs</h2>

![Log](https://user-images.githubusercontent.com/33530371/85543747-a1e89280-b61a-11ea-9b4f-2a922df40952.PNG)
![Log2](https://user-images.githubusercontent.com/33530371/85544563-6c907480-b61b-11ea-96a3-a4931a09e028.PNG)

Thanks to everyone

AB#7526489

**Comment by jebrando** [comment]
@mebster2 Do you have a sample of the code that is causing the issue.  There are many issues that can cause a disconnect, what does your data that you're adding to the twin look like.

**Comment by mebster2** [comment]
### Connect / Disconnect

    async def iot_connect(self) -> bool:
        """Connect device on Azure IoT Hub"""

        if not self._device_client:
            # Delay any activity in case the device was killed recently
            # We should wait 10 seconds before starting any IoT activity
            if self._kill_time:
                _secs = 10.0 - (time.time() - self._kill_time)
                if _secs > 0:
                    logging.info("Device was just killed before. Wait for 10 secs total before any IoT activity: serial=%s", self._serial)
                    await asyncio.sleep(_secs)

            x509 = self.get_cert_files()
            if not x509:
                return False
            hostname = self._imsapi.get_iot_url()
            cn_serial = self.get_registration_id()

            # The client object is used to interact with your Azure IoT hub.
            logging.info("IoT: Connect to IoT: url=%s serial=%s", hostname, cn_serial)
            self._device_client = IoTHubDeviceClient.create_from_x509_certificate(
                hostname=hostname,
                device_id=cn_serial,
                x509=x509,
                websockets=True
            )

            for _idx in range(20):
                try:
                    await self._device_client.connect()
                except ConnectionFailedError as e:
                    logging.error("Exception on connect: " + str(e))
                    await asyncio.sleep(1)

        return True

    async def _iot_disconnect(self):
        """Disconnect device from Azure IoT Hub"""

        if self._device_client:
            await self._device_client.disconnect()
            self._device_client = None

### Update

    async def update(self) -> dict:
        """Retrieve latest twin properties"""

        _status = await self._x509_device.iot_connect()
        if not _status:
            return None

        # Added debug output to investigate:
        # https://commend.atlassian.net/browse/IMS-4622
        # https://github.com/Azure/azure-iot-sdk-python/issues/399
        try:
            # Workaround: Twin request may hang if connection dropped!
            t0 = datetime.now()
            logging.debug("IoT: Request twin properties: serial=%s", self._x509_device.serial)
            self._twin = await asyncio.wait_for(self._x509_device.device_client.get_twin(), timeout=120.)
            _msecs = round((datetime.now() - t0).total_seconds()*1000)
            logging.debug("IoT: Request twin properties done: serial=%s msecs=%s", self._x509_device.serial, _msecs)
            return self._twin

        except asyncio.TimeoutError:
            logging.error("IoT: Twin not provided in time! serial=%s", self._x509_device.serial)

### Setter

    def set_reported_property(self, rep_props: dict):
        """Set given property in reported properties

        :param rep_props: property you want to set
        :type rep_props: dict
        """    
                
        if self._serial is None:
            logging.error("Device certificate does not exist!")
            return
    
        loop = asyncio.get_event_loop()
        loop.run_until_complete(self._iot_set_reported_property(rep_props=rep_props))          
         
    async def _iot_set_reported_property(self, rep_props: dict):
        """Set given property in reported properties

        :param rep_props: property you want to set
        :type rep_props: dict
        """          
        
        await self.iot_connect()
        await self._twin.update()
                
        logging.debug("IoT: Set twin reported properties: %s serial=%s", rep_props, self._serial)
        await self._device_client.patch_twin_reported_properties(rep_props)

### Getter

    def get_twin_section(self, twin_area: TwinProps, section: str) -> dict:
        """Get config of given twin area and section

        :param twin_area: reported or desired
        :type twin_area: TwinProps
        :param section: section in given twin area, e.g Config
        :type section: str
        :return: requested section of twin
        :rtype: dict
        """      
        
        if self._serial is None:
            logging.error("Device certificate does not exist!")
            return
    
        loop = asyncio.get_event_loop()
        config = loop.run_until_complete(self._iot_get_twin_section(twin_area=twin_area, section=section))          
        return config

    async def _iot_get_twin_section(self, twin_area: TwinProps, section: str) -> dict:
        """Get config of given twin area and section

        :param twin_area: reported or desired
        :type twin_area: TwinProps
        :param section: section in given twin area, e.g Config
        :type section: str
        :return: requested section of twin
        :rtype: dict
        """        
        
        await self.iot_connect()
        await self._twin.update()
        
        if twin_area.name == "desired":
            resp = self._twin.desired(section)
        elif twin_area.name == "reported":
            resp = self._twin.reported(section)
            
        if resp:
            return resp
        else:
            logging.error("IoT: Given section could not be found in twin props")

**Comment by mebster2** [comment]
Above you can see the major task my application does. With custom getter and setter functions I modify and request twin properties. I also added connect, disconnect and twin update implementation in the code example above. This should help you to understand my workflow. Thx for help.

**Comment by mebster2** [comment]
Do you have any ideas concerning the disconnect, perhaps it helps me to find the problem.

**Comment by olivakar** [comment]
From your disconnect logs it feels like , your device client object has already been garbage collected and a connection is still going on.

One of the 2 things may have happened.

1. You are setting device client explicitly to None that could have caused something weird.
2. You have already disconnected. You are somewhere trying to call connect without instantiating the device client again.

**Comment by jebrando** [comment]
@mebster2 The IotHub is disconnecting the device, this may be for a few reasons.  I was able to recreate this by have an invalid device id name (created a device Id with a $ character as the leading character).  

From your code it looks like you are creating multiple connections from the same device.  This will cause the IotHub to drop the connection from any existing connection once the new connection begins.  You should only create a new connection if one does not exist previously.  

Changing this should give you better results.

Let us know if you have any issues after changing this.

**Comment by mebster2** [comment]
Thank you for helping. jebrando you were right. I am running multiple test steps inside of a test case class, using unittest framework. I connected to IoTHub via the setUp method of the test case class. It turned out, that at the begin of every test step a new connection was created. That is clear to me, because the method setUp, executes stuff before every test step. I am connecting to IoT Hub via setUpClass and disconnect via tearDownClass now. That works fine for me. Only if i let multiple test cases running inside of a test suite, sharing one device, i still get some connection resets. Despite that I only have one connection and one disconnect to IoTHub per test case. Using one test device per test case solved the problem for me.

**Comment by elhorton** [comment]
Hi @mebster2 , great to hear that this was resolved for you. let us know if you have any other issues using the Python SDK! We will close this issue now.

**Comment by az-iot-builder-01** [comment]
@mebster2, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
