### ISSUE TITLE
[feature request] Configurable connection keep-alive setting in python.

### ISSUE THREAD

**Issue by mcisoc** [Azure/azure-iot-sdk-python#604]
I'm developing an IoT device with a global reach in a constrained network environment. This means we have strict requirements on network usage. Previously we were using python v1 SDK, but after moving to v2 we see a spike in our network traffic due to increased keep-alive activity on the MQTT connection.

As the v1 SDK was based on the C SDK, we had a 4 minute keepalive (which is configurable, see https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support) now we have a 1 minute keepalive which is not configurable. This will lead to a 25-50% network usage increase. For comparison with a 4 minute keepalive over a 15 minute timespan you will use ~500 bytes of traffic. With 60 seconds keepalive the usage is ~2000 bytes of data (depending on IP/TCP implementation overhead). 

Ideally we would want to be able to configured a keepalive of 16 minutes. We close our connection after 15 minutes to conserve network traffic. With a configurable keep alive we can reduce our network traffic significantly. 

If we don't have this option, we will not meet our data usage requirements, actually we will use our total usage just for keepalive.  We would then have use the C SDK with a python wrapper, stop using a MS sdk and use our own MQTT broker, or stop using IoT Hub and use another MQTT broker which supports are data requirements.

AB#7526607

**Comment by jebrando** [comment]
We have added this feature on the backlog and we will be keep you updated on the progress.

**Comment by olivakar** [comment]
Released at 2.2.0

**Comment by az-iot-builder-01** [comment]
@mcisoc, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by olivakar** [comment]
https://github.com/Azure/azure-iot-sdk-python/pull/635
