### ISSUE TITLE
_GatheringFuture exception

### ISSUE THREAD

**Issue by SirLancelotDuLac** [Azure/azure-iot-sdk-python#605]
Hi there

Almost all samples that halt the application allowing the user to press Q to quit throws an exception : _GatheringFuture exception was never retrieved

I cant seem to catch this expcetion. Is this a python issue or a sdk issue?

Thanks

AB#7526772

**Comment by olivakar** [comment]
Other than `receive_direct_method.py` what other samples have you encountered this error ?

**Comment by SirLancelotDuLac** [comment]
Hi

Let me explain better. receive_direct_method and receive_twin_desired_properties_patch samples was what I was working with.
receive_direct_method throws this exception when quiting the app and receive_twin_desired_properties_patch does not.
From what I can see they both halt the application and wait to receive messages from IoT hub. 
The diference(for me) is that one sample uses asyncio.gather(this sample throws exception) and the other uses asyncio.create_task(does not throw exception).
Thats why I asked if this could a python issue and not a SDK issue.

I am confused by this behavior because I cant catch the exception anywhere.

Thanks

**Comment by olivakar** [comment]
It is a gather usage issue. I asked as I wanted to verify that you only receive it only 1 sample.

**Comment by SirLancelotDuLac** [comment]
It´s working now.

Thanks

**Comment by olivakar** [comment]
Will be closing this

**Comment by az-iot-builder-01** [comment]
@SirLancelotDuLac, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
