### ISSUE TITLE
Connection refused when we try to connect after connection failed the first time.

### ISSUE THREAD

**Issue by robbinvandamme** [Azure/azure-iot-sdk-python#606]
# Context

- **OS and version used:** embedded linux | armv7l 
- **Python version:** <python3.7> 
- **list of installed packages:** see requirements.txt
[requirements.txt](https://github.com/Azure/azure-iot-sdk-python/files/4836381/requirements.txt)

- **cloned repo:** Azure IoT Device Library for Python v2.1.3

## Description of the issue

DOES NOT WORK:
- Device boots without internet.
- Application calls connect() on de iot-device-client.
- Connect fails
- Internet gets plugged in after 5min.
- Application calls connect() again (**on the some iot-device-client object**)
- We get "azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by ConnectionRefusedError(111, 'Connection refused')" instead of a successful connection.

DOES WORK:
It could have something to do with never being connected before because the following DOES work:
- Boot device with internet
- Connect() gets called and succeeds
- Internet drops for some time
- iot-device-client connection drops
- internet comes back
- iot-device-client connection succeeds towards iot-hub

## Console log of the issue

[log.txt](https://github.com/Azure/azure-iot-sdk-python/files/4836404/log.txt)

AB#7547883

**Comment by robbinvandamme** [comment]
@cartertinney 
Seems to be related with DNS, the host doesn't get resolved again on a new connect()?
So the 'wrong' ip is still used on the second connect() even if network came back up.

Explains why it works when I boot with internet connection and doesn't when I boot without internet.

Was able to work around it, but maybe something you still want to fix.

Kind regards,

Robbin

**Comment by cartertinney** [comment]
@robbinvandamme Thank you for the update - that's extremely helpful information. I'm taking a look into this now.

**Comment by robbinvandamme** [comment]
@cartertinney 
I think this is related to a previous bug I filed #548

**Comment by cartertinney** [comment]
I have unfortunately been unable to replicate this. I will speak with Bert, who was the point of contact on 548

**Comment by BertKleewein** [comment]
@robbinvandamme - how did you work around it?

**Comment by robbinvandamme** [comment]
Think we can close this one and focus #548 since it will be fixed if 548 will be fixed?
Provided some extra info on that ticket.

**Comment by az-iot-builder-01** [comment]
@robbinvandamme, @BertKleewein, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
