### ISSUE TITLE
ImportError: DLL load failed: The specified module could not be found

### ISSUE THREAD

**Issue by Pugalr** [Azure/azure-iot-sdk-python#61]
- **OS and version used:** < Windows 7 >

>>> print (sys.version)
3.5.4rc1 (v3.5.4rc1:385b368, Jul 24 2017, 14:37:10) [MSC v.1900 64 bit (AMD64)]

-# Description of the issue:
 import iothub_client
  File "C:\Users\pugal\AppData\Local\Programs\Python\Python35\lib
\site-packages\iothub_client\__init__.py", line 1, in <module>
 from .iothub_client import *
ImportError: DLL load failed: The specified module could not be found.

# Code sample exhibiting the issue:

import iothub_client

**Comment by tameraw** [comment]
@Pugalr - Can you please confirm that you cloned the repo recursively. Or use PIP to install the package.
Thanks.

**Comment by tameraw** [comment]
Closing. Let us know if you still have any issues.
Regards.

**Comment by kiran007francis** [comment]
I AM ALSO FACING THE SAME ISSUE. CAN YOU HELP ME @tameraw 

Operating System: Window 10
Language : Python
Version: Python 3.7

I was going through the tutorial given on Azure Portal's IoT Hub for sending telemetry. I am following the python tutorial https://docs.microsoft.com/en-us/azure/iot-hub/quickstart-send-telemetry-python .

![azure python tutorial](https://user-images.githubusercontent.com/43568831/46004833-7cd79080-c0d1-11e8-862c-26cbb7fe5017.PNG)

I followed the steps given exactly in the tutorial. The sample code to be executed was also given https://github.com/Azure-Samples/azure-iot-samples-python/archive/master.zip

When i run the **SimulatedDevice.py** in the folder **simulated-device** code i get the following error 

![error](https://user-images.githubusercontent.com/43568831/46004982-d93ab000-c0d1-11e8-8ba0-2db4b1351c5c.PNG)

I also tried the suggestions given on net. I created an anaconda environment in python 3.6 and python 2.7 . But the same error persists. Can someone help with the above issue?

**Comment by elenaterenzi** [comment]
Had the same issue with Python 3.5.2, I created an environment with Python 3.6 and it works

**Comment by JoelBennett** [comment]
I've run into the same issue on Python 3.7.3 with azure-iothub-device-client 1.4.6. :(
