### ISSUE TITLE
Unable to update device registered with X509 using method update_device_with_x509 defined in IoTHubRegistryManager

### ISSUE THREAD

**Issue by astha-kohli11** [Azure/azure-iot-sdk-python#613]
OS : Windows 10
Python version : Python 3.7.4
pip version :  19.0.3 
azure-iot-hub==2.2.1

ISSUE OCCURRED IN 
  Python module : "azure.iot.hub.IoTHubRegistryManager"
  Method Name : update_device_with_x509

## HEADING OF ISSUE
Unable to update device registered with X509 using method update_device_with_x509 defined in IoTHubRegistryManager

## Description of the issue
Using Method update_device_with_x509(self, device_id, etag, primary_thumbprint, secondary_thumbprint, status) to update already registered device (device is registered with X509 certificate).

The method is returning 'Conflict' Exception always.

## Root Cause of Issue
'Conflict' Exception is thrown because the above method was always creating device instead of updating the device.
It found device already created so throwing 'Conflict' Exception always

## Updated following in the method to solve the issue
the return statement in this method was:
return self.protocol.registry_manager.create_or_update_device(device_id, device,)

Changed it to 
return self.protocol.registry_manager.create_or_update_device(device_id, device, "*")

And its start updating the device.

AB#7613969

**Comment by jebrando** [comment]
@astha-kohli11 thanks for the bug, we will update this and get it checked in

**Comment by jebrando** [comment]
The fix is checked in and will be in pip on the next release.  Thank you.

**Comment by az-iot-builder-01** [comment]
@astha-kohli11, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by astha-kohli11** [comment]
This is still an issue.
I am using version 2.23

**Comment by vishnureddy17** [comment]
@astha-kohli11 Thanks for reporting this. Looks like #657 undid the fix that was applied. Reopening.
