### ISSUE TITLE
MQTT is not delivering the system properties: correlation_id and message_id

### ISSUE THREAD

**Issue by neutronzz** [Azure/azure-iot-sdk-python#62]
- **OS and version used:** Debian 8.9

- **Python runtime used:** Python 2.7.9

- **SDK version used:** 1.0.37

# Description of the issue:
MQTT is not delivering the system properties: correlation_id and message_id
After correlation_id and message_id were set in IoTHubMessage, the reply message delivered to IoTHub does not contain correlation_id and message_id properties.  Please, see the example below,

# Code sample exhibiting the issue:

info_json = "{ 'channel' : 'httpResp', 'status' : 'HTTP/1.1 200 OK', 'headers' : { "'Server' : 'nginx/1.11.4', 'Content-type' : 'application/json', 'Transfer-Encoding' : 'chunked' , 'Connection' : 'keep-alive' }, 'body' :  { 'data' } "

msg = IoTHubMessage(bytearray(info_json, 'utf8'))

# Method 1
msg.correlation_id = 'value1'
msg.message_id = 'value2'

# Method 2
msg_prop = msg.properties()
msg.pop.add('correlationId','value1')
msg.pop.add('messageId','value2')

client.send_event_async(msg, send_confirmation_callback, message_counter)

None of these methods work, the message sent does not contains the properties: correlation_id and message_id.

NOTE: For method 2, I used other possibilities of keys like: correlation_id, correlationId, CorrelationId, CorrelationIds

For our application is required and mandatory reply the correlation_id and message_id

Please, what can be done in order to fix this issue?

# Console log of the issue:

No errors, the message is sent correctly, but, correlation_id and message_id are not delivered in the message

**Comment by tameraw** [comment]
@neutronzz - This should have been fixed as of release 1.1.16. Can you please update your version to the latest and try again and let us know if still having any issues. Thanks.

**Comment by neutronzz** [comment]
Hi @tameraw 

Thanks for your prompt reply. I updated my IoTHub client and now it is working fine. 
The correlation_id and message_id are sent correctly.
I'm using IoT Hub SDK for C, version 1.1.20
