### ISSUE TITLE
Unable to send file larger than 15 MB to Azure IoTHub

### ISSUE THREAD

**Issue by Milan991** [Azure/azure-iot-sdk-python#624]
- **OS and version used:** Ubuntu 18.04.4
- **Python version:** 3.6.9
- **pip version:** 9.0.1
- **list of installed packages:** azure-iot-device 2.1.4, azure-storage-blob 12.3.2

## Description of the issue

Device is unable to send files larger than 15 MB. With smaller files everything works fine without any issues.

## Code sample exhibiting the issue

I'm using the code from the official example without any change (https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-file-upload). Files that I'm sending are .mp4 video files recorded with the camera.

## Console log of the issue

> 2020-07-16 13:31:39,852 Sending CONNECT (u1, p1, wr0, wq0, wf0, c0, k60) client_id=b'poultryVideoV1-00:00:00:00:00:01'
> 2020-07-16 13:31:39,906 Received CONNACK (0, 0)
> 2020-07-16 13:31:40,177 
> Uploading file: videos/video-2020_07_16_13_23_57.mp4 to Azure Storage as blob: poultryVideoV1-00:00:00:00:00:01/video-2020_07_16_13_23_57.mp4 in container iothub
> 
> 2020-07-16 13:31:40,786 Request URL: 'https://sasagronet.blob.core.windows.net/iothub/poultryVideoV1-00%3A00%3A00%3A00%3A00%3A01/video-2020_07_16_13_23_57.mp4?sv=REDACTED&sr=REDACTED&sig=REDACTED&se=REDACTED&sp=REDACTED'
> 2020-07-16 13:31:40,787 Request method: 'PUT'
> 2020-07-16 13:31:40,787 Request headers:
> 2020-07-16 13:31:40,787     'Content-Type': 'application/octet-stream'
> 2020-07-16 13:31:40,787     'Content-Length': '25287600'
> 2020-07-16 13:31:40,788     'x-ms-version': 'REDACTED'
> 2020-07-16 13:31:40,788     'x-ms-blob-type': 'REDACTED'
> 2020-07-16 13:31:40,788     'x-ms-date': 'REDACTED'
> 2020-07-16 13:31:40,788     'x-ms-client-request-id': 'ae96bd40-c768-11ea-8eb7-000000000001'
> 2020-07-16 13:31:40,788     'User-Agent': 'azsdk-python-storage-blob/12.3.2 Python/3.6.9 (Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic)'
> 2020-07-16 13:31:40,792 Starting new HTTPS connection (1): sasagronet.blob.core.windows.net
> 2020-07-16 13:32:17,471 Request URL: 'https://sasagronet.blob.core.windows.net/iothub/poultryVideoV1-00%3A00%3A00%3A00%3A00%3A01/video-2020_07_16_13_23_57.mp4?sv=REDACTED&sr=REDACTED&sig=REDACTED&se=REDACTED&sp=REDACTED'
> 2020-07-16 13:32:17,471 Request method: 'PUT'
> 2020-07-16 13:32:17,471 Request headers:
> 2020-07-16 13:32:17,471     'Content-Type': 'application/octet-stream'
> 2020-07-16 13:32:17,472     'Content-Length': '25287600'
> 2020-07-16 13:32:17,472     'x-ms-version': 'REDACTED'
> 2020-07-16 13:32:17,472     'x-ms-blob-type': 'REDACTED'
> 2020-07-16 13:32:17,472     'x-ms-date': 'REDACTED'
> 2020-07-16 13:32:17,472     'x-ms-client-request-id': 'ae96bd40-c768-11ea-8eb7-000000000001'
> 2020-07-16 13:32:17,472     'User-Agent': 'azsdk-python-storage-blob/12.3.2 Python/3.6.9 (Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic)'
> 2020-07-16 13:32:17,476 Starting new HTTPS connection (2): sasagronet.blob.core.windows.net
> 2020-07-16 13:32:39,976 Sending PINGREQ
> 2020-07-16 13:32:40,020 Received PINGRESP
> 2020-07-16 13:32:59,127 Request URL: 'https://sasagronet.blob.core.windows.net/iothub/poultryVideoV1-00%3A00%3A00%3A00%3A00%3A01/video-2020_07_16_13_23_57.mp4?sv=REDACTED&sr=REDACTED&sig=REDACTED&se=REDACTED&sp=REDACTED'
> 2020-07-16 13:32:59,127 Request method: 'PUT'
> 2020-07-16 13:32:59,127 Request headers:
> 2020-07-16 13:32:59,128     'Content-Type': 'application/octet-stream'
> 2020-07-16 13:32:59,128     'Content-Length': '25287600'
> 2020-07-16 13:32:59,128     'x-ms-version': 'REDACTED'
> 2020-07-16 13:32:59,128     'x-ms-blob-type': 'REDACTED'
> 2020-07-16 13:32:59,128     'x-ms-date': 'REDACTED'
> 2020-07-16 13:32:59,128     'x-ms-client-request-id': 'ae96bd40-c768-11ea-8eb7-000000000001'
> 2020-07-16 13:32:59,129     'User-Agent': 'azsdk-python-storage-blob/12.3.2 Python/3.6.9 (Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic)'
> 2020-07-16 13:32:59,132 Starting new HTTPS connection (3): sasagronet.blob.core.windows.net
> 2020-07-16 13:33:40,090 Sending PINGREQ
> 2020-07-16 13:33:40,137 Received PINGRESP
> 2020-07-16 13:34:01,223 Request URL: 'https://sasagronet.blob.core.windows.net/iothub/poultryVideoV1-00%3A00%3A00%3A00%3A00%3A01/video-2020_07_16_13_23_57.mp4?sv=REDACTED&sr=REDACTED&sig=REDACTED&se=REDACTED&sp=REDACTED'
> 2020-07-16 13:34:01,223 Request method: 'PUT'
> 2020-07-16 13:34:01,223 Request headers:
> 2020-07-16 13:34:01,224     'Content-Type': 'application/octet-stream'
> 2020-07-16 13:34:01,224     'Content-Length': '25287600'
> 2020-07-16 13:34:01,224     'x-ms-version': 'REDACTED'
> 2020-07-16 13:34:01,224     'x-ms-blob-type': 'REDACTED'
> 2020-07-16 13:34:01,224     'x-ms-date': 'REDACTED'
> 2020-07-16 13:34:01,224     'x-ms-client-request-id': 'ae96bd40-c768-11ea-8eb7-000000000001'
> 2020-07-16 13:34:01,225     'User-Agent': 'azsdk-python-storage-blob/12.3.2 Python/3.6.9 (Linux-4.9.140-tegra-aarch64-with-Ubuntu-18.04-bionic)'
> 2020-07-16 13:34:01,228 Starting new HTTPS connection (4): sasagronet.blob.core.windows.net
> 2020-07-16 13:34:21,501 Upload failed. Exception is: 
> 
> 2020-07-16 13:34:21,502 ('Connection aborted.', timeout('The write operation timed out',))
> 2020-07-16 13:34:21,502 
> Exception:
> 2020-07-16 13:34:21,502 'ServiceResponseError' object has no attribute 'status_code'
> 2020-07-16 13:34:21,503 Sending DISCONNECT

AB#7718469

**Comment by Milan991** [comment]
@jebrando @cartertinney Any updates on this issue?

**Comment by cartertinney** [comment]
I am unable to replicate this issue. However your issue is coming from the Azure Storage client, not the Azure IoT Device client. Please open this issue with Azure Storage (https://github.com/Azure/azure-storage-python)

**Comment by az-iot-builder-01** [comment]
@Milan991, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
