### ISSUE TITLE
Yandex problem.

### ISSUE THREAD

**Issue by nickolaymykhalych** [Azure/azure-iot-sdk-python#63]
- **OS and version used:** <VERSION> 

- **Python runtime used:** <VERSION> 

- **SDK version used:** <VERSION> 

# Description of the issue:

I'm living in Ukraine, and when i'm doing installation on Linux, it's trying to download headers hosted at yandex servers. But Yandex domain is blocked in Ukraine.
# Code sample exhibiting the issue:

# Console log of the issue:

**Comment by zolvarga** [comment]
@nickolaymykhalych 

What headers are you trying to download?

Best Regards,
Zoltan

**Comment by nickolaymykhalych** [comment]
When i'm trying to install your sdk. I see 98% waiting for headers. and link to the yandex servers.

**Comment by zolvarga** [comment]
@nickolaymykhalych 

Unfortunately I don't have a control on the server access, but a possible work around would be to download our package from PyPi site:
https://pypi.python.org/pypi/azure-iothub-device-client/1.1.20.0
https://pypi.python.org/pypi/azure-iothub-service-client/1.1.0.12

and manually install it on your box.

I hope this helps.

Best Regards,
Zoltan
