### ISSUE TITLE
IoTHubModuleClient.invoke_method incorrect function parameter documentation

### ISSUE THREAD

**Issue by dapisani** [Azure/azure-iot-sdk-python#633]
The method_params parameter for invoke_method is stated as
        :param dict method_params: Should contain a method_name, payload, connect_timeout_in_seconds, response_timeout_in_seconds.

When invoking a method in which the method_params dictionary has the aforementioned keys you will receive a 402 error.

By changing to camel case such that
        :param dict method_params: Should contain a methodName, payload, connectTimeoutInSeconds, responseTimeoutInSeconds.

the invocation works as expected.

Also the description should state what the value types should be in the method_parms dictionary. It was unclear if the payload value should be an object, a json string or some other type.

AB#7788584

**Comment by cartertinney** [comment]
Fixed in #655

**Comment by az-iot-builder-01** [comment]
@dapisani, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
