### ISSUE TITLE
macOS Sierra build error

### ISSUE THREAD

**Issue by GapiSla** [Azure/azure-iot-sdk-python#64]
- **OS and version used:** <VERSION>  macOS Sierra 10.12.6

- **Python runtime used:** <VERSION>  2.7.10

- **SDK version used:** <VERSION>  latest

# Description of the issue:
 when I want to build as instructions says I get some errors.

# Code sample exhibiting the issue:

# Console log of the issue:
 -- The C compiler identification is AppleClang 8.1.0.8020042
-- The CXX compiler identification is AppleClang 8.1.0.8020042
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc
-- Check for working C compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++
-- Check for working CXX compiler: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:9 (add_subdirectory):
  add_subdirectory given source "c" which is not an existing directory.

-- Configuring incomplete, errors occurred!
See also "/Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/CMakeFiles/CMakeOutput.log".
make: *** No targets specified and no makefile found.  Stop.
Test project /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac
No tests were found!!!
~/Documents/azure-iot/azure-iot-sdk-python
copy iothub_client library to samples folder
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
copy iothub_client_mock library to tests folder
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/test/iothub_client_mock.dylib: No such file or directory
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client library to samples folder
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
copy iothub_service_client_mock library to tests folder
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/tests/iothub_service_client_mock.dylib: No such file or directory
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python_service_client/src/iothub_service_client.dylib: No such file or directory
cp: /Users/gaspersladic/Documents/azure-iot/azure-iot-sdk-python/c/cmake/iotsdk_mac/python/src/iothub_client.dylib: No such file or directory
python2.7 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: No module named iothub_client_mock

**Comment by GapiSla** [comment]
forgot to clone repo with --recursive option. Now it builds.

**Comment by axper** [comment]
Install Mac OS X Command Line Tools first: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/ and make sure you have cloned this repo recursively. Spent 5 hours trying to figure this out, hope this helps someone.
