### ISSUE TITLE
[Technical Question] Unable to import module 'app': No module named 'azure'

### ISSUE THREAD

**Issue by donniekerr** [Azure/azure-iot-sdk-python#642]
I import this into a Lambda Function running Python 3.8
`from azure.iot.hub import IoTHubRegistryManager`
And I get the error in the lambda logs 
Unable to import module 'app': No module named 'azure'

My requirements.txt includes azure-iot-hub and uamqp .  Yet, for some reason it is trying to load the azure module.  Why?

I even tried to add azure to requirements.txt and force install azure 2.0.0, even though your instructions say it is no longer compatible/required. It still got the same error.   I even tried reverting to Python 2.7 and that didn't help either.  For some reason it keeps wanted to install azure, which isn't supposed to be required. 

How can I make azure.iot.hub work in the 3.8 Lamda Function? 

Background: Amazon Lex forces me to use a Lamba function for fulfillment.  I'm trying to send a C2D message to fulfill it. 

I'd appreciate some help because I spent a couple days trying to get this to work.  Thanks!

AB#7874497

**Comment by zolvarga** [comment]
@donniekerr Could you please provide a code snippet including the imports what you are using to repro this issue?
Thanks,
-Zoltan

**Comment by donniekerr** [comment]
Thank you @zolvarga .  I'm basically trying to run the python code snippets in this example here, inside a Lambda function 
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-c2d#send-a-cloud-to-device-message 
That should be enough to repro the import error.  But, if not, let me know. 
imports at top 
`import sys
from azure.iot.hub import IoTHubRegistryManager`

function that uses it ...
`def send_message_to_device(intent_request):
    """
    Performs fulfillment for sending command to iot device.
    """

    sensor = get_slots(intent_request)["sensor"]
    greenhouseNumber = get_slots(intent_request)["greenhouseNumber"]
    CONNECTION_STRING = ""
    DEVICE_ID = "SimulatedTemperatureSensor"
    try:
        # Create IoTHubRegistryManager
        registry_manager = IoTHubRegistryManager(CONNECTION_STRING)
        data = '{"command":"reset"}'

        props={}
        # optional: assign system properties
        props.update(messageId = "message_1")
        props.update(correlationId = "correlation_1")
        props.update(contentType = "application/json")

        # optional: assign application properties
        #prop_text = "PropMsg_%d" % i
        #props.update(testProperty = prop_text)

        registry_manager.send_c2d_message(DEVICE_ID, data, properties=props)
    except Exception as ex:
        print ( "Unexpected error {0}" % ex )
        return close(intent_request['sessionAttributes'],
                 'Failed',
                 {'contentType': 'PlainText',
                  'content': 'An error occurred when sending your command to {}  in {}'.format(sensor, greenhouseNumber)})
    else:
        return close(intent_request['sessionAttributes'],
                 'Fulfilled',
                 {'contentType': 'PlainText',
                  'content': 'Your command to {} has been sent to device in {}'.format(sensor, greenhouseNumber)})

`

**Comment by donniekerr** [comment]
requirements.txt just contains this ...

`azure-iot-hub`
`uamqp`

and not 'azure'.

**Comment by donniekerr** [comment]
Here is the whole AWS SAM Cli project in a zip.  (if you 
[lex-cloud-to-device.zip](https://github.com/Azure/azure-iot-sdk-python/files/5024730/lex-cloud-to-device.zip)

**Comment by zolvarga** [comment]
@donniekerr - thanks!

**Comment by donniekerr** [comment]
Here are the lambda settings showing Python 3.8  and log I see in cloud watch .
<img width="685" alt="Screen Shot 2020-08-04 at 4 49 06 PM" src="https://user-images.githubusercontent.com/41065378/89348721-aae56e80-d672-11ea-8cf8-2698c682b980.png">
<img width="1208" alt="Screen Shot 2020-08-04 at 4 50 23 PM" src="https://user-images.githubusercontent.com/41065378/89348724-ac169b80-d672-11ea-81e3-b1fb106c050c.png">

**Comment by donniekerr** [comment]
@zolvarga  I was just experimenting with putting the azure folder manually into the package (not using pip) and the error goes away.  Then I got same error for the other dependencies. I did the same for them and the error went way.  But, now it is erroring on msrest.authentication , even though that file exists in the msrest folder. 
Obviously this isn't a good solution.  It should work by simply doing pip3 install azure-iot-hub .  But, it does tell me that AWS is not finding the dependencies from the pip3 install of azure-iot-hub. Don't know why.
<img width="185" alt="Screen Shot 2020-08-05 at 9 00 28 AM" src="https://user-images.githubusercontent.com/41065378/89422005-60a7d000-d6fa-11ea-8f27-3edec772ca5c.png">

**Comment by donniekerr** [comment]
I tried re-installing Python3.8 and clearing out the site packages folder in it on my MacBook.  Then I re-installed azure-iot-hub which created these dependencies in site-packages.  I explicitly added all of these to my requirements.txt .  Note there is no reference to 'azure' at all.  I re-built and re-deployed the SAM function.  Yet, still got same error No module names 'azure' error.  ugh! very frustrating. :( 
azure-iot-hub==2.2.1
certifi==2020.6.20
chardet==3.0.4
idna==2.10
isodate==0.6.0
msrest==0.6.18
oauthlib==3.1.0
requests==2.24.0
requests-oauthlib==1.3.0
six==1.15.0
uamqp==1.2.9
urllib3==1.25.10

**Comment by donniekerr** [comment]
I did learn that when you do pip3 install azure-iot-hub it does in fact create an 'azure' folder in /site-packages. Since only things in this folder were installed by azure-iot-hub, I copied the entire dependency folders into my SAM project deployment package.  They got rid of the azure error, but left me with this one now 
[ERROR] Runtime.ImportModuleError: Unable to import module 'app': cannot import name 'c_uamqp' from partially initialized module 'uamqp' (most likely due to a circular import) (/var/task/uamqp/__init__.py)

So, again, the pip install of azure-iot-hub is not working even with this hack attempt.  Just passing on what I've tried in case it helps you @zolvarga 
<img width="996" alt="Screen Shot 2020-08-05 at 1 11 33 PM" src="https://user-images.githubusercontent.com/41065378/89448537-64991980-d71d-11ea-8f97-86e85253e975.png">
<img width="650" alt="Screen Shot 2020-08-05 at 1 12 34 PM" src="https://user-images.githubusercontent.com/41065378/89448544-6662dd00-d71d-11ea-82e2-dbb79c6d86d8.png">

**Comment by donniekerr** [comment]
@zolvarga good news ... resolved the issue.  It was not with the azure-iot-hub sdk, it was a problem with AWS SAM Cli/docker.  This command does not work 'sam build --use-container' with the --use-container added like their instructions say.  I removed this flag and it fixed the no module error.   Got lucky! I guess it wasn't able to find the packages with the use-container turned on, but it does without it.  I don't care, as long it works!   My Lex bot now sends the C2D message! Thanks!

BTW, my tweet went out to @azuresupport and @awssupport with a link to this issue.  Only @zolvarga responded, so thank you very much for that!

**Comment by jebrando** [comment]
@donniekerr I'm really glad this worked out  I'm unfamiliar with the Amazon Lex Functions before this and it sounds really cutting edge some of the stuff you're doing.  Let us know if you have any other issues of finding with this

Cheers.

**Comment by donniekerr** [comment]
@jebrando Yes, doing some very fun "edgy edge" stuff! Azure IoT Hub is making it possible for my greenhouse sensors to talk directly to Lex and Alexa and for them both to send out commands to devices!  Alexa for when the hemp growers hands are busy farming! Lex for when they are on their phone or in the control center!  I want the human to have a conversation before authorizing the machines to automate something.  At NASA I called this human-in-the-loop automation. Now I'm doing it for Hemp farms! :)   Appreciate the amazing work you all are doing on Azure IoT! My Virtual Grow Assistant will be out soon!  Just trying now to forward the IoT Hub anomalies (ASA ML) to Alexa now!

**Comment by jebrando** [comment]
This is wonderful work @donniekerr let us know if you have any issues or if there are any features that you'd like to see going forward.

**Comment by az-iot-builder-01** [comment]
@donniekerr, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by elhorton** [comment]
hi @donniekerr , thanks for engaging with this open source project! You seem to have an interesting scenario here, would you be interested in a call with our product team so we can better understand this scenario?

**Comment by donniekerr** [comment]
I would love to.  I'm very passionate about building our Cedar Valley Farms (hemp farms) Virtual Grow Assistant product on top of Azure IoT.  send me a Team's invite to dkerr at cvfarms.co  (no m at end)

**Comment by donniekerr** [comment]
Good news ... I now have Alexa talking to azure-iot-hub too! Now, when the user confirms using either Lex or Alexa they send the C2D message.  Super easy. Debugging was less than 5 min with no major errors ... using same azure-iot-hub python code in both. With Alexa, you don't have to use SAM Cli to deploy it so it installed azure-iot-hub no problem!
<img width="831" alt="Screen Shot 2020-08-07 at 11 28 06 AM" src="https://user-images.githubusercontent.com/41065378/89667155-46f4bd00-d8a1-11ea-9eda-b646b4ca2bb6.png">

**Comment by elhorton** [comment]
awesome, glad to hear this was an easy implementation for you with the Python SDK!
