### ISSUE TITLE
[Technical Question] Error handling on on async websockets connection

### ISSUE THREAD

**Issue by Frostlock** [Azure/azure-iot-sdk-python#643]
Hi,
I'm working with python 3.7 azure-iot-device v2.1.4 and using the async implementation with websockets.
Starting from the example code found [here](https://docs.microsoft.com/en-us/azure/iot-central/core/tutorial-connect-device-python) I have a working setup. Normal operation is OK but I'm getting in trouble when trying to deal with bad network conditions. I simulate this in a very high tech way by unplugging my network cable ;-)

A bit more context:
``` python
self.client = IoTHubDeviceClient.create_from_symmetric_key(
                    symmetric_key=self.central_device_key,
                    hostname=registration_result.registration_state.assigned_hub,
                    device_id=registration_result.registration_state.device_id,
                    websockets=True
                )
await self.client.connect()
```
This is how I create my client. It works on a good network and the `await self.client.connect()`raises a `ClientError` when my network is disconnected. I can catch that error and react to it.

A bit further on in the program I have my property and telemetry sending setup using:
``` python
await self.client.patch_twin_reported_properties(self.properties)
```
and
``` python
await self.client.send_message(msg)
```
Starting with a good network connection this works but if I unplug the network both of these await operations get stuck. I see errors appear in the error output but these are not being raised to my await calls. I have included the errors for reference below. 

**Workaround**
As a workaround I'm currently using an asyncio `wait_for()` with timeout instead of the simple await, like this:
```python
task = asyncio.create_task(self.client.send_message(msg))
await asyncio.wait_for(task, timeout=4)
```
With an unplugged network cable this throws an asyncio `TimeoutError` which I can react to. Unfortunately this doesn't stop the background message sending. I see it keeps trying every 10 seconds or so and doesn't look to ever give up. 
Since the `cancel()` feature is not implemented (according to [known pitfalls)](https://github.com/Azure/azure-iot-sdk-python/wiki/pitfalls) this doesn't enable me to stop those background routines.

I realize that when replugging my network cable the operations successfully complete but I don't want them stampeding in the background for a long time I prefer to back off on the connection and retry an hour later. Our device has other stuff to do and our customers often have unreliable network connections.

**Questions**
- Why are these errors not being raised to my code?
- How long will the underlying pipeline keep trying to send on a broken network connection (I see it retry about every 10 seconds but I haven't seen it give up yet)
- What is the best way to properly kill and clean up those awaited coroutines on which I now have the TimeoutError setup?

Better solutions are of course very welcome :-) 
Thanks!

For reference these are the errors I see in the error output (but which are not being raised):
``` txt
failed to receive on socket: [WinError 10054] An existing connection was forcibly closed by the remote host
transport.connect raised error
Traceback (most recent call last):
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 384, in connect
    host=self._hostname, port=443, keepalive=DEFAULT_KEEPALIVE
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\paho\mqtt\client.py", line 937, in connect
    return self.reconnect()
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\paho\mqtt\client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\paho\mqtt\client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\azure\iot\device\common\pipeline\pipeline_stages_mqtt.py", line 182, in _run_op
    self.transport.connect(password=password)
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 411, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by gaierror(11001, 'getaddrinfo failed')

ConnectOperation: completing with error ConnectionFailedError(None) caused by gaierror(11001, 'getaddrinfo failed')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionFailedError(None) caused by gaierror(11001, 'getaddrinfo failed')
transport.connect raised error
Traceback (most recent call last):
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 384, in connect
    host=self._hostname, port=443, keepalive=DEFAULT_KEEPALIVE
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\paho\mqtt\client.py", line 937, in connect
    return self.reconnect()
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\paho\mqtt\client.py", line 1071, in reconnect
    sock = self._create_socket_connection()
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\paho\mqtt\client.py", line 3522, in _create_socket_connection
    return socket.create_connection(addr, source_address=source, timeout=self._keepalive)
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\socket.py", line 707, in create_connection
    for res in getaddrinfo(host, port, 0, SOCK_STREAM):
  File "C:\Program Files (x86)\Microsoft Visual Studio\Shared\Python37_64\lib\socket.py", line 748, in getaddrinfo
    for res in _socket.getaddrinfo(host, port, family, type, proto, flags):
socket.gaierror: [Errno 11001] getaddrinfo failed

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\azure\iot\device\common\pipeline\pipeline_stages_mqtt.py", line 182, in _run_op
    self.transport.connect(password=password)
  File "C:\Users\pboog\source\repos\IOT\IOT\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 411, in connect
    raise exceptions.ConnectionFailedError(cause=e)
azure.iot.device.common.transport_exceptions.ConnectionFailedError: ConnectionFailedError(None) caused by gaierror(11001, 'getaddrinfo failed')

ConnectOperation: completing with error ConnectionFailedError(None) caused by gaierror(11001, 'getaddrinfo failed')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: ConnectionFailedError(None) caused by gaierror(11001, 'getaddrinfo failed')
```

AB#7987081

**Comment by olivakar** [comment]
- Why are these errors not being raised to my code?  
   - The error of `socket.gaierror: getaddrinfo failed` gets translated to a transient error for us upon receiving which we keep on retrying. This is our expected behavior.
- How long will the underlying pipeline keep trying to send on a broken network connection (I see it retry about every 10 seconds but I haven't seen it give up yet)
  - Right now the SDK does it at every 10 secs and it is not yet configurable from the user end. 
  - In the easy short term approach we can disable the retry completely so that it can be managed at user's end.
  - Right now we don't have this capability but these are features we will consider.
- What is the best way to properly kill and clean up those awaited coroutines on which I now have the TimeoutError setup?
   - The best way right now is would be to catch the `Timeout Error` and do the following
      - Cancel any tasks that you may have scheduled
      - Call `await device_client.disconnect()`

**Comment by Frostlock** [comment]
Thanks for the clarification @olivakar !
This might need to be labelled as a feature request :-)

I have set up the workaround with the `Timeout Error` and the `await device_client.disconnect()` and that looks to be working out. Good to have a recommended workaround, thanks!

The network setups for our customers are all different and from our point of view unreliable :-) So it would be great to have a bit more control on retry behaviour. For example configuring the nbr of retries would already be very helpful.

Also being able to catch the actual underlying error message would be helpful. We see TCP timeouts (dear customer your network is too slow), gaierrors (dear customer please open port 443) and authorization errors (dear internal service team you messed up the credentials). It would make troubleshooting for our service team a lot easier if we can get these insights in our code.

Finally an extra point. We have some customers that have very slow networks. From an IOT point of view slow networks should also work. The default TCP timeouts look to be a bit strict though so it would be great to be able to configure those as well. For example we see DNS lookups take more than 6 seconds in the field. So it all works but its just terribly slow. However with the current SDK all network  operations timeout on those 6 seconds.

Here is a short block of text that hopefully helps in getting this on the roadmap :)

**Feature requests**

- Add a max nbr of retries for communication operations
- Provide a way to get some insight in underlying error messages (specifically for the network), this can be a call back or preferably an error being raised back to the async coroutine.
- Add a max TCP timeout (some customers have a workable but slow network) current default timeout values cause the operation to fail. Or just increase the max timeout value


thanks

**Comment by olivakar** [comment]
Thank you  for your suggestions.
We will consider these and keep you updated.
For now I am closing the issue.

**Comment by az-iot-builder-01** [comment]
@Frostlock, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
