### ISSUE TITLE
[Technical Question] Why are message_properties being cast to a string

### ISSUE THREAD

**Issue by edmkdrp** [Azure/azure-iot-sdk-python#646]
I have the following block of code:

```
msg = Message(json.dumps(data))
msg.message_id = 0
msg.correlation_id = 0
msg.content_type = "application/json"
msg.content_encoding = "utf-8"
msg.custom_properties['type'] = "LOG"
msg.custom_properties['timestamp'] = 1597780692    # Replaced function that returns Epoch time as int
msg.custom_properties['seq_num'] = 11                         # Replaced function that returns Sequence Number as int
```

When this shows up "on-the-wire", I see:

$ az iot central app monitor-events --app-id XXXXXXX. -d YYYYYYY --props ALL

```
{
    "event": {
.....
"application": {
                "seq_num": "11",
                "timestamp": "1597780692",
                "type": "LOG",
                "iotc-app-id": "4c6606d3-05a0-4c9c-8df2-7b977a047829",
                "iotc-hub-name": "iotc-1f997072-a1e1-41a5-bfd8-2a7157702560"
            }
.....
    }
}
```

**Why are seq_num and timestamp showing up as a string?  Is there some way to prevent that?**

AB#8029201

**Comment by olivakar** [comment]
we will check this and get back to you

**Comment by olivakar** [comment]
The custom properties of a message goes into the topic which can never be anything else other than string.
Since python allows any type of value , this confusion arises only for python case. 
We will improve the docs to say that only string values are allowed.

**Comment by elhorton** [comment]
closing this issue

**Comment by az-iot-builder-01** [comment]
@edmkdrp, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
