### ISSUE TITLE
Issue in building project for macOs

### ISSUE THREAD

**Issue by maryheng** [Azure/azure-iot-sdk-python#65]
- **OS and version used:** macOS Sierra 10.12.4

- **Python runtime used:** Python 2.7.10

- **SDK version used:** current latest

# Description of the issue:

I was able to follow the instructiosn to clone recursively ,` git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git `

Then, I went on to follow this set of instructions: https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#mac . 

**Tried to run `./setup.sh` but had this problem [image below]:**

<img width="729" alt="screen shot 2017-08-18 at 2 14 12 am" src="https://user-images.githubusercontent.com/13627091/29427261-d9de7db0-83bb-11e7-8264-b8b05de92c5b.png">

Which, i tried removing the file mentioned, 'boost--patch.....' and tried running it again, but gave me the same error of **'SHA256 mismatch'**

**Then afterwards, tried to run `./build.sh` but encountered another problem [image below]:**

<img width="737" alt="screen shot 2017-08-18 at 2 14 53 am" src="https://user-images.githubusercontent.com/13627091/29427297-efee5ecc-83bb-11e7-88dc-a61765c8053a.png">

Error: 
```
No such file or directory
python2.7 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: No module named iothub_client_mock
```

May I know where did i go wrong in setting up the sample project? Appreciate your help! Thanks!

**Comment by zolvarga** [comment]
@maryheng 

We are looking at this and will get back to you.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@maryheng 

I could not repro the issue you reported. but the setup.sh script should run without error before you build, so the SHA256 error needs to be fixed. 
The build.sh log shows you don't have valgrind installed because the setup.sh script could not finish.

The log says you have a boost library already downloaded and there is a SHA mismatch. 
Could you please make sure you remove the boost before you run the script?

Best Regards,
Zoltan

**Comment by tameraw** [comment]
Please let us know if still having issues.
Thanks.

**Comment by axper** [comment]
Install Mac OS X Command Line Tools first: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/ and make sure you have cloned this repo recursively. Spent 5 hours trying to figure this out, hope this helps someone.
