### ISSUE TITLE
How to get response from module_client.receive_message_on_input

### ISSUE THREAD

**Issue by nishad1092** [Azure/azure-iot-sdk-python#652]
Hi, 
I would like to know how to get response after I recieve input to the module. 
 
I have first module to get invoked request from the cloud and here I get reponse for the method_response from await module_client.receive_method_request using
 method_response = MethodResponse.create_from_method_request(
                method_request, status, payload
            )

Similarly, I want to get the invoked message to the second module which is the receiver and get response frm there, please tell me how to do it?

AB#8133736

**Comment by jebrando** [comment]
@nishad1092 Thanks for the issue, we'll look into it let you know.

**Comment by elhorton** [comment]
hi @nishad1092 , we recommend checking out [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-iot-sdk.html) (tag is azure-iot-sdk) as the best forum for these types of questions--you'll get the fastest response for your questions there. It also helps if you can provide more context on your scenario, including full code examples and a description of your solution architecture.

**Comment by az-iot-builder-01** [comment]
@nishad1092, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
