### ISSUE TITLE
pnp device sample,  pnp_thermostat.py & pnp_temp_controller_with_thermostats.py ,DPS success but no "modeId"

### ISSUE THREAD

**Issue by BerryTsai** [Azure/azure-iot-sdk-python#653]
Pnp device sample,  pnp_thermostat.py & pnp_temp_controller_with_thermostats.py ,DPS success but no "modelId"

![image](https://user-images.githubusercontent.com/34261469/91712371-31ca3000-ebba-11ea-8a61-f7f2d27ab2b2.png)

AB#8137005

**Comment by daisukeiot** [comment]
It seems the sample codes are missing to pass model ID to create_from_symmetric_key()

        if registration_result.status == "assigned":
            device_client = IoTHubDeviceClient.create_from_symmetric_key(
                symmetric_key=symmetric_key,
                hostname=registration_result.registration_state.assigned_hub,
                device_id=registration_result.registration_state.device_id,
                product_info=model_id <<=====
            )

**Comment by jebrando** [comment]
@daisukeiot Thanks for the issue, we'll add this to the create function

**Comment by olivakar** [comment]
This bug was discovered during certification and I am in the process of fixing it.

**Comment by olivakar** [comment]
samples have been fixed

**Comment by az-iot-builder-01** [comment]
@BerryTsai, @daisukeiot, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
