### ISSUE TITLE
Documentation in docs.microsoft.com is incorrect - possible indentation issue in code docstrings

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-iot-sdk-python#667]
## Description of the issue

In the [autogenerated docs for the ProvisioningDeviceClient class](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.provisioningdeviceclient?view=azure-python), the descriptions of the functions are incorrectly constructed from the docstrings in the code. It looks like a possible indentation issue with the docstrings in the [Python code](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/azure/iot/device/provisioning/abstract_provisioning_device_client.py).

![2020-09-14_15-03-24](https://user-images.githubusercontent.com/1710385/93142818-9ea1f780-f69b-11ea-9aa0-766a81f67335.png)

AB#8271514

**Comment by olivakar** [comment]
Ok we will try and fix this in our code.

**Comment by askpatrickw** [comment]
While you're in there.. double check the returns for create_from_x509_certificate. It says:
    `:returns: A ProvisioningDeviceClient which can register via Symmetric Key.`
in `help(ProvisioningDeviceClient.create_from_x509_certificate)`

**Comment by olivakar** [comment]
@elhorton to check with doc team for the fix

**Comment by az-iot-builder-01** [comment]
@jimbobbennett, @askpatrickw, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
