### ISSUE TITLE
[Technical Question] Additional logging/stack traces from uamqp when switching from azure-iot-hub 2.0.2 to 2.2.2

### ISSUE THREAD

**Issue by JoelBennett** [Azure/azure-iot-sdk-python#669]
Hopefully this makes a bit of sense...

I'm currently dealing with a fairly large Django based project which used the IoT Hub Python libraries to communicate with devices located on an Azure IoT Hub.  Last week (specifically on 2020-09-11) we found that our calls to the IoT hub were not working.  We eventually discovered that the specific version of the `azure-iot-hub` library wouldn't work properly.  If we updated the version from 2.02 to 2.2.2, things started working again.  But in addition to working, any time we close the local development environment, we get several stack traces, like so:
```
[repeated ~10 times, with the final two stack traces looking like the following]

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1365, in debug
  File "c:\program files\python37\lib\logging\__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: 'uamqp.c_uamqp.XIO.__dealloc__'
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1365, in debug
  File "c:\program files\python37\lib\logging\__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1619, in isEnabledFor
KeyError: None

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1365, in debug
  File "c:\program files\python37\lib\logging\__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
Exception ignored in: 'uamqp.c_uamqp.XIO.__dealloc__'
Traceback (most recent call last):
  File "c:\program files\python37\lib\logging\__init__.py", line 1365, in debug
  File "c:\program files\python37\lib\logging\__init__.py", line 1621, in isEnabledFor
TypeError: 'NoneType' object is not callable
```
It may just be the structure of the application I'm working on, but it seems that something is being de-allocated several times when it has already been de-allocated.  The version of `uamqp` is 1.2.10, which is what was installed when we updated the `azure-iot-hub` library.  Prior to updating to 2.2.2, we didn't see any such error messages.

Has anyone seen something like this before?  If so, any ideas what we can do to resolve this?

AB#8312330

**Comment by elhorton** [comment]
Hi @JoelBennett , thanks for reaching out! We haven't seen this before-- we'll take a look and update you soon. Is any of your scenario's functionality noticeably broken? Or just noticing the appearance of these error messages when closing the local dev environment?

**Comment by JoelBennett** [comment]
It's more so just the appearance of the error messages after things are terminated.  Everything functionality wise seems to still be working.

I suspect it's something specific to the project and environment, but it's proving to be quite tricky to track down.

**Comment by JoelBennett** [comment]
I'm just taking another quick look at this.  I've noticed that when running the local Django development server (e.g.: `python mangae.py runserver`), by default, it spins up two different threads.  It would appear that one of these is for the StatReloader, which triggers the Django project to reload when it detects changed files within the project.  If I run it with the `--noreload` option, it only spins up a single thread, but even then, I'm still seeing the same errors being logged to the console when killing the development server with Ctrl+C.

I was originally thinking that having multiple instances of the `IoTHubRegistryManager` (each on a different thread) was causing the issue, but now I'm not so sure.  Given I still get the errors logged to the console when it runs under a single thread, that makes me think it still might be something else.

**Comment by JoelBennett** [comment]
I think we were able to figure out a workaround for our purposes.  Not sure if this will help anyone else, but I guess it doesn't hurt to have it documented anywhere.

The original developers who integrated the Azure IoT Hub with our existing Django application created the `IoTHubRegistryManager` as a fairly long lasting global object.  Switching it out to a position where it is more transient, and gets created only when needed (and only when used) seems to have fixed the issue.  I'm not sure if there is anything in the current documentation that makes a recommendation either way (e.g.: how long should an instance of the `IoTHubRegistryManager` be used before being discarded?).

**Comment by az-iot-builder-01** [comment]
@JoelBennett, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)

**Comment by elhorton** [comment]
Hi @JoelBennett , thanks for all the info! This is helpful, we're taking a look to see if it's something that could be an issue with the recent release. Agreed that this should be documented as a best practice/guidelines-- noted. We'll look at adding this to our [Common pitfalls/FAQ](https://github.com/Azure/azure-iot-sdk-python/wiki/pitfalls) page.
