### ISSUE TITLE
broker unavailable error when ID_SCOPE is incorrect

### ISSUE THREAD

**Issue by askpatrickw** [Azure/azure-iot-sdk-python#670]
This _might_ only be IOT Central related.

If your ID_SCOPE is wrong, the error you will get is "broker unavailable" instead of something more helpful like "ID_SCOPE Unknown".

AB#8338612

**Comment by olivakar** [comment]
If you are using our Device SDK , we do not translate any `IDSCOPE` error specially for the provisioning workflow.
When id_scope is wrong the result code for such a connection is 3 and that for MQTT is a `Connection Refused: broker unavailable` error.
We are simply giving  back that as a `ConnectionFailedError` with the inner cause being the same above error.

We will consider this but prior to that we need to make sure that this error is unique to only id_scope and does not happen in any other situation.

**Comment by az-iot-builder-01** [comment]
@askpatrickw, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
