### ISSUE TITLE
IoT Plug and Play sample code and readme.md not aligned

### ISSUE THREAD

**Issue by BerryTsai** [Azure/azure-iot-sdk-python#672]
The "switch" connection string, value in code and readme.md not aligned. 

![bug2](https://user-images.githubusercontent.com/34261469/93871074-ab0ffb00-fd00-11ea-8ce8-350183b10356.jpg)
![bug1](https://user-images.githubusercontent.com/34261469/93871079-ac412800-fd00-11ea-9dca-2c411effbc09.jpg)

AB#8359970

**Comment by jebrando** [comment]
Thanks for this issue, we will update it and get it pushed out.

**Comment by elhorton** [comment]
Hey @BerryTsai  and @jebrando , thanks for pointing this out, I noticed this as well and fixed it in our PnP release staging branch yesterday, this will be live when we merge to master. Marking this as fix-checked-in for now.

**Comment by olivakar** [comment]
https://github.com/Azure/azure-iot-sdk-python/pull/673

**Comment by az-iot-builder-01** [comment]
@BerryTsai, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
