### ISSUE TITLE
Unable to receive C2D invoke request 

### ISSUE THREAD

**Issue by nishad1092** [Azure/azure-iot-sdk-python#679]
Hi, 

I recently read about a similiar issue regarding iot hub, but here Im using Invoke method for IoT device using this api version :
https://docs.microsoft.com/en-us/rest/api/iothub/service/devices/invokemethod

And I'm using azure-iot-device version 2.2.0, and also have installed iot-hub 2.2.2 considering that issue, but this requesting isn't getting completed. Im getting badrequest and iothub-errorcode as ArgumentInvalid, Please tell me why?
My IoT Hub is in the East US region, 
API payload is :: 
{
    "methodName": "startservice",
    "connectTimeoutInSeconds" : 60,
    "responseTimeoutInSeconds": 60,
    "payload": 0
} 

API version : 2020-05-31-preview

Do I need to downgrade the iot-device version? or use a different api-version ? 

AB#8407548

**Comment by az-iot-builder-01** [comment]
@nishad1092, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
