### ISSUE TITLE
libboost_python-py27.so.1.58.0: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by waytai** [Azure/azure-iot-sdk-python#68]
python CreateDeviceIdentity.py 

- **OS and version used:** <VERSION> 
ubuntu14.04  
- **Python runtime used:** <VERSION> 
 python2.7.6
- **SDK version used:** <VERSION> 
 python CreateDeviceIdentity.py 

# Description of the issue:

python CreateDeviceIdentity.py
# Code sample exhibiting the issue:

# Console log of the issue:

Traceback (most recent call last):
  File "CreateDeviceIdentity.py", line 8, in <module>
    from iothub_service_client import IoTHubRegistryManager, IoTHubRegistryManagerAuthMethod
  File "/usr/local/lib/python2.7/dist-packages/iothub_service_client/__init__.py", line 1, in <module>
    from .iothub_service_client import *
ImportError: libboost_python-py27.so.1.58.0: cannot open shared object file: No such file or directory

**Comment by waytai** [comment]
azure-iothub-service-client (1.1.0.14)

**Comment by waytai** [comment]
ubuntu14.04 64bit

**Comment by waytai** [comment]
pip 9.0.1 from /usr/local/lib/python2.7/dist-packages (python 2.7)

**Comment by digimaun** [comment]
@waytai are you able to install/update at least boost 1.58 on your system?

**Comment by waytai** [comment]
@digimaun I have update my boost to 1.58 , but also have errors.

**Comment by waytai** [comment]
I have compile the resource and replace the iothub_client.so and iothub_service_client.so.
and is alright

**Comment by Jazmine9** [comment]
First build according to the following instructions. [Build IoT Hub SDKs for Python](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#build-the-azure-iot-hub-sdks-for-python-on-linux)

After building according to the above instructions. 
`pip install azure-iothub-device-client`

**Comment by buhongw7583c** [comment]
@GauravGaikwad94 , I encountered the same issue. Follow the advice of @Jazmine9, after the successful build, the iothub_client.so  file is created under the device/samples folder and should be copied to the folder iothub_service_client. Then it works. I would suggest the compile should create the iothub_client.so file directly under iothub_service_client folder.

**Comment by Jazmine9** [comment]
@buhongw7583c , I tried to install it on other devices also. Once I build the the SDK, I only need 3 files to import the IoTHub functions in my Python code(For sending data to IoT Hub). 
*   iothub_client.so generated by building
*  iothubclient_args.py and iothub_client_cert.py from the repository.
