### ISSUE TITLE
Mismatch between kwarg name for keepalive in docstring

### ISSUE THREAD

**Issue by michael0liver** [Azure/azure-iot-sdk-python#688]
Occurs in a few places:

https://github.com/Azure/azure-iot-sdk-python/blob/7fdbe8a622f8695c97cc9a3f30a4f83b674de501/azure-iot-device/azure/iot/device/iothub/abstract_clients.py#L290

https://github.com/Azure/azure-iot-sdk-python/blob/7fdbe8a622f8695c97cc9a3f30a4f83b674de501/azure-iot-device/azure/iot/device/iothub/abstract_clients.py#L159

https://github.com/Azure/azure-iot-sdk-python/blob/7fdbe8a622f8695c97cc9a3f30a4f83b674de501/azure-iot-device/azure/iot/device/iothub/abstract_clients.py#L35

https://github.com/Azure/azure-iot-sdk-python/blob/7fdbe8a622f8695c97cc9a3f30a4f83b674de501/azure-iot-device/azure/iot/device/iothub/abstract_clients.py#L51

AB#8472225

**Comment by bradleydamato** [comment]
@michael0liver I have a PR for this. Do you know of any good tests I can run? There doesn't seem to be a CONTRIBUTING.MD file or anything similar.

**Comment by bradleydamato** [comment]
@michael0liver I have a PR I can submit for this, but first, is there any standardized testing that I should do? I don't seem to see a CONTRIBUTING.MD file or anything similar. I do see some tests files but I figure there is something else more robust here?

**Comment by michael0liver** [comment]
> @michael0liver I have a PR I can submit for this, but first, is there any standardized testing that I should do? I don't seem to see a CONTRIBUTING.MD file or anything similar. I do see some tests files but I figure there is something else more robust here? 

Hi!
Sorry I am new to this repository and don't know the recommended procedures yet. Nice work on the PR!

**Comment by elhorton** [comment]
Hi @bradleydamato and @michael0liver -- thanks for raising this issue and contributing the PR. It's been merged. Since this was a docs fix and no new code, you're not required to write any new tests. If you'd like to contribute code, we'd request tests and help to ensure your PR is robust. Closing this issue now with the merged PR-- let us know if you have any other feedback or questions. Thanks!

**Comment by az-iot-builder-01** [comment]
@michael0liver, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
