### ISSUE TITLE
./build.sh

### ISSUE THREAD

**Issue by waytai** [Azure/azure-iot-sdk-python#69]
- **OS and version used:** <VERSION> 
ubuntu14.04
- **Python runtime used:** <VERSION> 
python2.7.6
- **SDK version used:** <VERSION> 

# Description of the issue:

I have run ./setup.sh and then run ./build.sh
# Code sample exhibiting the issue:

# Console log of the issue:

copy iothub_client library to samples folder
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python/src/iothub_client.so’: No such file or directory
copy iothub_client_mock library to tests folder
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python/test/iothub_client_mock.so’: No such file or directory
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python/src/iothub_client.so’: No such file or directory
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python_service_client/src/iothub_service_client.so’: No such file or directory
copy iothub_service_client library to samples folder
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python_service_client/src/iothub_service_client.so’: No such file or directory
copy iothub_service_client_mock library to tests folder
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python_service_client/tests/iothub_service_client_mock.so’: No such file or directory
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python_service_client/src/iothub_service_client.so’: No such file or directory
cp: cannot stat ‘/home/wayne/test/azure-iot-sdk-python/c/cmake/iotsdk_linux/python/src/iothub_client.so’: No such file or directory
python2.7 iothub_client_ut.py
Traceback (most recent call last):
  File "iothub_client_ut.py", line 9, in <module>
    import iothub_client_mock
ImportError: No module named iothub_client_mock

**Comment by zolvarga** [comment]
Probably you forgot to clone the c submodule. Use this on the python repo::
git submodule update --init --recursive

Best Regards,
Zoltan

**Comment by waytai** [comment]
thank you,  It's alright now

**Comment by axper** [comment]
Install Mac OS X Command Line Tools first: http://osxdaily.com/2014/02/12/install-command-line-tools-mac-os-x/ . Spent 5 hours trying to figure this out, hope this helps someone.
