### ISSUE TITLE
Calling ProvisioningDeviceClient.create_from_symmetric_key with an empty registration_id leads to PyErr_WriteUnraisable logging an error.

### ISSUE THREAD

**Issue by chris-hibberd** [Azure/azure-iot-sdk-python#691]
# Context

-  OS: Windows 10, WSL2
- Python version: 3.8.2
- pip version: 19.2.3
- azure-iot-device: 2.3.0
- paho-mqtt: 1.5.1

## Description of the issue

If an invalid registration_id is provided to ProvisioningDeviceClient.create_from_symmetric_key then a value error is raised in the paho.mqtt.client.Client constructor before the Client's _sock attribute is created. During application shutdown, __del__ is called on the client object and leads to an AttributeError being raised.

## Code sample exhibiting the issue

``` python
from azure.iot.device.aio import ProvisioningDeviceClient
import asyncio
import logging
async def main():
    try:
        ProvisioningDeviceClient.create_from_symmetric_key(
            registration_id="",
            symmetric_key="",
            provisioning_host="",
            id_scope="",
        )
    except ValueError as e:
        print(f"This is handled: {e}")
logger = logging.getLogger('azure')
logger.setLevel('ERROR')
asyncio.run(main())
```

## Console log of the issue

```
This is handled: A client id must be provided if clean session is False.
Exception ignored in: <function Client.__del__ at 0x7f0ff6831ee0>
Traceback (most recent call last):
  File "/c/Users/hibbe/Code/bg-hub-applications/.venv/lib/python3.8/site-packages/paho/mqtt/client.py", line 660, in __del__
    self._reset_sockets()
  File "/c/Users/hibbe/Code/bg-hub-applications/.venv/lib/python3.8/site-packages/paho/mqtt/client.py", line 704, in _reset_sockets
    self._sock_close()
  File "/c/Users/hibbe/Code/bg-hub-applications/.venv/lib/python3.8/site-packages/paho/mqtt/client.py", line 691, in _sock_close
    if not self._sock:
AttributeError: 'Client' object has no attribute '_sock'
```

The AttributeError is raised in .venv/lib/python3.8/site-packages/paho/mqtt/client.py and I have opened https://github.com/eclipse/paho.mqtt.python/issues/520 to track it. It would be useful if the code that creates the client from this SDK could check that the registration_id is not None or an empty string and raise an exception in order to prevent attempting Client creation when it has no chance of succeeding.

AB#8585692

**Comment by chris-hibberd** [comment]
Looks great, thanks!

**Comment by elhorton** [comment]
Thanks for your engagement @chris_hibberd , now that this has been released, we'll close this issue. Please let us know if you have any more feedback!

**Comment by az-iot-builder-01** [comment]
@chris-hibberd, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
