### ISSUE TITLE
Calling IOTHUB_REGISTRY_MANAGER.get_module_twin on custom module returns 404 'Not Found'

### ISSUE THREAD

**Issue by mstiehm-NF** [Azure/azure-iot-sdk-python#694]
# Context
- **OS and version used:** Ubuntu 18.03
- **Python version:** Python 2.7.17
- **pip version:** pip 20.2.3
- **list of installed packages:** azure-iot-hub 2.2.3

## Description of the issue

I can no longer retrieve the module twin of a custom module using the IOTHUB_REGISTRY_MANAGER.get_module_twin() method.

This worked as of Thursday.

AB#8613945

**Comment by mstiehm-NF** [comment]
Closed. Working as expected.

**Comment by az-iot-builder-01** [comment]
@mstiehm-NF, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
