### ISSUE TITLE
Example for Pubsub [Technical Question]

### ISSUE THREAD

**Issue by ishang3** [Azure/azure-iot-sdk-python#699]
I am trying to follow a simple tutorial to pubsub example using azure iot sdk python, but cannot find any examples. 

Any information is greatly appreciated. 

AB#8663967

**Comment by olivakar** [comment]
Are you looking for a sample that does both together because individually the samples exist.

**Comment by ishang3** [comment]
Thanks for responding - Individual ones works fine with me too. Could you point me in the right locations?

**Comment by olivakar** [comment]
You can find all async samples here
https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples/async-hub-scenarios

**Comment by elhorton** [comment]
hi @ishang3 , did this help? if not, can you elaborate on your scenario for "pubsub"? The samples show how to create a device client, authenticate, send messages, etc. but please let us know if something is missing for your scenario.

**Comment by elhorton** [comment]
Hi @ishang3 , we'll close this issue for now, but please let us know if you have any other questions! Thanks.

**Comment by az-iot-builder-01** [comment]
@ishang3, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
