### ISSUE TITLE
Python HTTP Protocol Not Working for receiving messages.

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-python#7]
_From @asebak on December 3, 2016 22:45_

When using AMQP the python library works fine for both sending and receiving messages.  When using HTTP and configuring with a timeout and minimum polling period, messages are not received.  I didn't set any certificates so not sure if that could be an issue from my side.

_Copied from original issue: Azure/azure-iot-sdks#1011_

**Comment by zolvarga** [comment]
Hi asebak,

Thanks for reporting this. We are going to investigate the issue and will get back with the result.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Hi asebak,

We released a new version of our SDK recently:
https://github.com/Azure/azure-iot-sdk-python/releases

I have tried to repro the issue with the new release but It works fine with HTTP.
Please try with the new release and if you still have a repro then open a new issue here in the Python repo.

Best Regards,
Zoltan
