### ISSUE TITLE
cmake CMakeLists.txt

### ISSUE THREAD

**Issue by waytai** [Azure/azure-iot-sdk-python#70]
- **OS and version used:** <VERSION> 
ubuntu14.04      gcc 4.8.4     cmake version 2.8.12.2
- **Python runtime used:** <VERSION> 
python2.7.6
- **SDK version used:** <VERSION> 

# Description of the issue:

# Code sample exhibiting the issue:

# Console log of the issue:

-- The C compiler identification is GNU 4.8.4
-- The CXX compiler identification is GNU 4.8.4
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
CMake Error at CMakeLists.txt:9 (add_subdirectory):
  The source directory

    /home/wayne/test/azure-iot-sdk-python/c

  does not contain a CMakeLists.txt file.

-- Configuring incomplete, errors occurred!
See also "/home/wayne/test/azure-iot-sdk-python/CMakeFiles/CMakeOutput.log".

**Comment by zolvarga** [comment]
Please make sure you checked out our repo correctly.
This folder indeed has the CMakeLists.txt file:
https://github.com/Azure/azure-iot-sdk-c

Probably you forgot to clone the c submodule. Use this on the python repo::
git submodule update --init --recursive

Best Regards,
Zoltan

**Comment by waytai** [comment]
It's alright now , thank you
