### ISSUE TITLE
SDK doesn't reconnect after host device long sleep

### ISSUE THREAD

**Issue by electrozen** [Azure/azure-iot-sdk-python#700]
As discussed in #548 , when the host device awake from a long sleep, reconnection doesn't occur due to expired SAS token ("Connection Refused: not authorised"). SAS token renewal occur later but fail to restart the connection.

What would be the best workaround ? Any way to check on the state of the SDK and restart it ? So far I'm attempting to detect sleeps outside of the process and restart the process instantiating the SDK. Thanks for your help.

Log in debug mode showing the issue below.
 [perfdaemon-issue.log](https://github.com/Azure/azure-iot-sdk-python/files/5452390/perfdaemon-issue.log)

AB#8680651

**Comment by cartertinney** [comment]
This is a known issue - we're working on implementing a solution

**Comment by cartertinney** [comment]
Issue is being tracked in #706

**Comment by cartertinney** [comment]
This issue has been resolved and included in the latest release, 2.5.0

**Comment by az-iot-builder-01** [comment]
@electrozen, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
