### ISSUE TITLE
Azure IoT Hub DPS support

### ISSUE THREAD

**Issue by rploeg** [Azure/azure-iot-sdk-python#703]
Hi,

I see that DPS is coming soon in v2 of the Python SDK. Do you have any timelines when we can use this? We have some potential projects that need support of Python

thanks for the great work!

thanks,

Remco

AB#8722324

**Comment by elhorton** [comment]
Hi @rploeg , thanks for reaching out! We don't have a concrete timeline for DPS support, but right now it's looking like this will be in the first half of 2021. I'll also take this as great feedback to post a roadmap-- we're finalizing our first half of 2021 planning over the next month or so, and following that we'd like to share a roadmap. If you have the time, it would also be great to hear more about your IoT projects & scenarios using Python. Feel free to connect with me via email at elhorton@microsoft.com. Thanks!

**Comment by anthonyvercolano** [comment]
Second half of 2021
