### ISSUE TITLE
Not able to access blob uri in callback after a succesfull file upload.

### ISSUE THREAD

**Issue by tanwarsatya** [Azure/azure-iot-sdk-python#71]
- **OS and version used:** Windows 10 
- **Python runtime used:** 3.6
- **SDK version used:** 1.1.22.0 

# Description of the issue:
Callback for the File Upload is not able to return the bloburi or filename. The calback only returns result either OK or ERROR.

**Comment by zolvarga** [comment]
@tanwarsatya 

That is by design. 
Our Python SDK is a wrapper on top of the C SDK and the C SDK implementatation is returning only the upload status to the user.

Best Regards,
Zoltan
