### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by prbans** [Azure/azure-iot-sdk-python#715]
The readme here - https://github.com/Azure/azure-iot-sdk-python/tree/master/azure-iot-device/samples/pnp

references a few files

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/pnp/simple_thermostat
https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/pnp/temp_controller_with_thermostats

These links are both broken

**Comment by elhorton** [comment]
Hi @prbans , thank you for reporting this! We really appreciate it--sometimes the links just can't keep up with the changes :/-- and will get these fixed asap.

**Comment by az-iot-builder-01** [comment]
@prbans, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
