### ISSUE TITLE
Etag ignored when updating module twin.

### ISSUE THREAD

**Issue by dapisani** [Azure/azure-iot-sdk-python#716]
# Context

- **OS and version used:**  Ubuntu 18.04 )
- **Python version:** 3.6.12
- **pip version:**  20.3
- **list of installed packages:** 

| Name                |    Version          |         Build   |    Channel |
| --------- | ------------------- | --------- | ---|
| _libgcc_mutex       |      0.1            |            main ||
| astroid             |      2.4.2          |          pypi_0 |    pypi|
| attrs               |      20.3.0         |          pypi_0 |    pypi|
| ca-certificates     |      2020.10.14     |               0 ||
| certifi             |      2020.11.8      |  py36h06a4308_0 ||
| dataclasses         |      0.7            |          pypi_0 |    pypi|
| importlib-metadata  |      3.1.1          |          pypi_0 |    pypi|
| iniconfig           |      1.1.1          |          pypi_0 |    pypi|
| isort               |      5.6.4          |          pypi_0 |    pypi|
| jedi                |      0.17.2         |          pypi_0 |    pypi|
| lazy-object-proxy   |      1.4.3          |          pypi_0 |    pypi|
| ld_impl_linux-64    |      2.33.1         |      h53a641e_7 ||
| libedit             |      3.1.20191231   |      h14c3975_1 ||
| libffi              |      3.3            |      he6710b0_2 ||
| libgcc-ng           |      9.1.0          |      hdf63c60_0 ||
| libstdcxx-ng        |      9.1.0          |      hdf63c60_0 ||
| mccabe              |      0.6.1          |          pypi_0 |    pypi|
| ncurses             |      6.2            |      he6710b0_1 ||
| openssl             |      1.1.1h         |      h7b6447c_0 ||
| packaging           |      20.7           |          pypi_0 |    pypi|
| parso               |      0.7.1          |          pypi_0 |    pypi|
| pip                 |      20.3           |  py36h06a4308_0 ||
| pluggy              |      0.13.1         |          pypi_0 |    pypi|
| py                  |      1.9.0          |          pypi_0 |    pypi|
| pylint              |      2.6.0          |          pypi_0 |    pypi|
| pyparsing           |      2.4.7          |          pypi_0 |    pypi|
| pytest              |      6.1.2          |          pypi_0 |    pypi|
| pytest-mock         |      3.3.1          |          pypi_0 |    pypi|
| python              |      3.6.12         |      hcff3b4d_2 ||
| readline            |      8.0            |      h7b6447c_0 ||
| setuptools          |      50.3.2         |  py36h06a4308_2 ||
| six                 |      1.15.0         |          pypi_0 |    pypi|
| sqlite              |      3.33.0         |      h62c20be_0 ||
| tk                  |      8.6.10         |      hbc83047_0 ||
| toml                |      0.10.2         |          pypi_0 |    pypi|
| typed-ast           |      1.4.1          |          pypi_0 |    pypi|
| wheel               |      0.36.0         |    pyhd3eb1b0_0 ||
| wrapt               |      1.12.1         |          pypi_0 |    pypi|
| xz                  |      5.2.5          |      h7b6447c_0 ||
| zipp                |      3.4.0          |          pypi_0 |    pypi|
| zlib                |      1.2.11         |      h7b6447c_3 ||     

## Description of the issue
It is to my understanding that the etag is a readonly element which can be used for caching and data consistency. I am seeing that the etag property does nothing at all.

Steps:
1. Grab the same twin from two separate registry managers.
2. Have the two registry managers update the same key/value pair in the twin with different values using the etag from the retrieved twins.

Outcome:
No error. Last registry manager to write is the final value.

Expected:
Second registry manager throws an error when updating the twin.

## Code sample exhibiting the issue

rm_1 = IoTHubRegistryManager("conn_string")
rm_2 = IoTHubRegistryManager("conn_string")
one = rm_1.get_module_twin("device", "module")
two = rm_2.get_module_twin("device", "module")
one.properties.desired["test"] = "one"
two.properties.desired["test"] = "two"
rm_1.update_module_twin("device", "module", one, one.etag)
rm_2.update_module_twin("device", "module", two, two.etag)

**Comment by elhorton** [comment]
Hi @dapisani , thanks for reporting this! We've added this to our list and will get back to you soon.
