### ISSUE TITLE
Proposed changes in Python services samples

### ISSUE THREAD

**Issue by FabianKLS** [Azure/azure-iot-sdk-python#72]
Windows 10
Python 3.6.1
Latest SDK
    \service\samples\iothub_devicemethod_sample.py
    \service\samples\iothub_devicetwin_sample.py
    \service\samples\iothub_messaging_sample.py
    \service\samples\iothub_registrymanager_sample.py

# Description of the issue:
The services samples don't provide you with the full usage parameters. **-d Device ID** is missing and are not consistent over the files mentioned above.

`def usage():
    print ( "Usage: iothub_devicemethod_sample.py -c <connectionstring> " )
    ....
`
and isn't consistent in iothub_registrymanager_sample.py

`print ( "Usage: iothub_registrymanager_sample.py -c <connection_string> -d <device_id>" )`

Propose to change this to

`def usage():
    print ( "Usage: iothub_devicemethod_sample.py -c <connectionstring> -d <deviceid>" )
...
`

**Comment by zolvarga** [comment]
@FabianKLS 

Thanks for the correction, we will update the samples in the next release.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
The samples have been update in the release:
https://github.com/Azure/azure-iot-sdk-python/releases/tag/release_2017_09_26

Best Regards,
Zoltan
