### ISSUE TITLE
Python Service SDK don't have useragent

### ISSUE THREAD

**Issue by ericmitt** [Azure/azure-iot-sdk-python#723]
The ClientVersion from Python Service SDK is blank. It should have **azure-iot-service-iothub-py**

**Comment by olivakar** [comment]
For node the user agent that is reported from Node service seems to be `azure-iothub/1.9.9`
Does python need to be the exactly like that of Node or does python needs to be `azure-iot-service-iothub-py/<some_version>` ?

**Comment by olivakar** [comment]
From the service side code of python it seems that there is an user agent `iothubgatewayserviceapis/<some_versison>` but this seems to be never reported.

**Comment by olivakar** [comment]
![Screen Shot 2021-01-19 at 11 26 58 AM](https://user-images.githubusercontent.com/5783914/105083536-e241af00-5a49-11eb-8c4a-4abe641fa635.png)

This is the user agent that gets sent in one of the headers

**Comment by elhorton** [comment]
Closing this as it appears to be an issue on the data ingestion side-- will reopen if needed
