### ISSUE TITLE
certificate verify failed with edgeHub Mqtt Broker 

### ISSUE THREAD

**Issue by lakshmisivareddy** [Azure/azure-iot-sdk-python#724]
i am experimenting with Azure IoT Edge MQTT broker to publish and subscribe
from below link : https://docs.microsoft.com/en-us/azure/iot-edge/how-to-publish-subscribe?view=iotedge-2020-11#pre-requisites

i was able to test successfully  with SAS Token 
but when i tried with x509 i am getting below Error 

#Error
Traceback (most recent call last):
  File "cert_pub.py", line 41, in <module>
    client.connect("localhost", 8883,60)
  File "/home/challal/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 941, in connect
    return self.reconnect()
  File "/home/challal/.local/lib/python2.7/site-packages/paho/mqtt/client.py", line 1104, in reconnect
    sock.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 828, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:727)

#Edge runtime version :
iotedge 1.2.0~rc1

#System containers version: 
challal@challal:~/Downloads$ docker ps 
CONTAINER ID        IMAGE                                            COMMAND                   CREATED             STATUS              PORTS                                                                                          NAMES
b8487c368cf5        mcr.microsoft.com/azureiotedge-hub:1.2.0-rc2     "/bin/sh -c 'echo \"$…"   4 hours ago         Up 2 hours          0.0.0.0:443->443/tcp, 0.0.0.0:1883->1883/tcp, 0.0.0.0:5671->5671/tcp, 0.0.0.0:8883->8883/tcp   edgeHub
305ff643a56a        mcr.microsoft.com/azureiotedge-agent:1.2.0-rc2   "/bin/sh -c 'exec /a…"    4 hours ago         Up 2 hours                                                                                                         edgeAgent

#Code i tried :
from paho.mqtt import client as mqtt
import ssl

path_to_root_cert = "/home/challal/Downloads/cacert.pem"
#path_to_root_cert = "/home/challal/Downloads/certs/azure-iot-test-only.root.ca.cert.pem"
device_id = "pub_cert"

def on_connect(client, userdata, flags, rc):
    print("Device connected with result code: " + str(rc))

def on_disconnect(client, userdata, rc):
    print("Device disconnected with result code: " + str(rc))

def on_publish(client, userdata, mid):
    print("Device sent message")

client = mqtt.Client(client_id=device_id,clean_session=True,userdata=None,protocol=mqtt.MQTTv311,transport="tcp")

client.on_connect = on_connect
client.on_disconnect = on_disconnect
client.on_publish = on_publish

client.username_pw_set(username="WE-SB-DEV-SC-iothub02.azure-devices.net/pub_cert/?api-version=2018-06-30", password=None)

cert_file = "/home/challal/Downloads/pub_cert/new-device.cert.pem"
key_file = "/home/challal/Downloads/pub_cert/new-device.key.pem"
client.tls_set(ca_certs=path_to_root_cert, certfile=cert_file, keyfile=key_file,
               cert_reqs=ssl.CERT_REQUIRED, tls_version=ssl.PROTOCOL_TLSv1_2, ciphers=None)

#client.connect("WE-SB-DEV-SC-iothub02.azure-devices.net", 8883,60)
#client.publish("devices/pub_cert/messages/events/", "{id=123}", qos=1)

client.connect("localhost", 8883,60)
client.publish("test_topic", "{id=123}", qos=1)
client.loop_forever()

#Deployment json:
{
  "$schema-template": "2.0.0",
  "modulesContent": {
    "$edgeAgent": {
      "properties.desired": {
        "schemaVersion": "1.0",
        "runtime": {
          "type": "docker",
          "settings": {
            "minDockerVersion": "v1.25",
            "loggingOptions": "",
            "registryCredentials": {}
          }
        },
        "systemModules": {
          "edgeAgent": {
            "type": "docker",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-agent:1.2.0-rc2",
              "createOptions": {}
            }
          },
          "edgeHub": {
            "type": "docker",
            "status": "running",
            "env": {
              "experimentalFeatures__enabled": {
                  "value": "true"
              },
              "experimentalFeatures__mqttBrokerEnabled": {
                  "value": "true"
              }
           },
            "restartPolicy": "always",
            "settings": {
              "image": "mcr.microsoft.com/azureiotedge-hub:1.2.0-rc2",
              "createOptions": {
                "HostConfig": {
                  "PortBindings": {
                    "5671/tcp": [
                      {
                        "HostPort": "5671"
                      }
                    ],
                    "8883/tcp": [
                      {
                        "HostPort": "8883"
                      }
                    ],
                    "443/tcp": [
                      {
                        "HostPort": "443"
                      }
                    ],
                    "1883/tcp": [
                      {
                        "HostPort": "1883"
                      }
                    ]
                  }
                }
              }
            }
          }
        },
        "modules": {
          "TemperatureSensorModule": {
            "version": "1.0",
            "type": "docker",
            "status": "running",
            "restartPolicy": "always",
            "settings": {
              "image": "${MODULES.TemperatureSensorModule}",
              "createOptions": {}
            }
          }
        }
      }
    }, 
      "$edgeHub":{
         "properties.desired":{
            "schemaVersion":"1.2",
            "routes":{
              "Route1":"FROM /messages/* INTO $upstream"
           },
           "storeAndForwardConfiguration":{
              "timeToLiveSecs":7200
           },
            "mqttBroker":{
              "authorizations":[
                {
                   "identities": [
                      "{{iot:identity}}"
                   ],
                   "allow":[
                      {
                         "operations":[
                            "mqtt:connect"
                         ]
                      }
                   ]
                },
                {
                   "identities": [
                    "{{iot:identity}}"
                   ],
                   "allow":[
                      {
                         "operations":[
                            "mqtt:subscribe",
                            "mqtt:publish"
                         ],
                         "resources":[
                            "test_topic",
                            "$iothub/methods/POST/#",
                            "$iothub/twin/res/#"
                         ]
                      }
                   ]
                },
                {
                   "identities": [
                    "{{iot:identity}}"
                   ],
                   "allow":[
                      {
                         "operations":[
                            "mqtt:publish"
                         ],
                         "resources":[
                            "test_topic"
                         ]
                      }
                   ]
                }
             ]
            }
         }
      }
  }
}

**Comment by az-iot-builder-01** [comment]
@lakshmisivareddy, thank you for your contribution to our open-sourced project! Please help us improve by filling out this 2-minute [customer satisfaction survey](https://forms.office.com/Pages/ResponsePage.aspx?id=v4j5cvGGr0GRqy180BHbRx8jpG79OudPqY-BojcKjkJUMFFBQjgxNkw5ODJIRjBWTzI0Nk85R0pUQiQlQCN0PWcu)
