### ISSUE TITLE
raw_input is used, which is replaced by input in latest py version.

### ISSUE THREAD

**Issue by FabianKLS** [Azure/azure-iot-sdk-python#73]
Windows 10
Python 3.6.1
Latest SDK
\service\samples\iothub_devicemethod_sample.py

`def iothub_devicemethod_sample_run():

    try:
        ...
        print ( "Response payload         : {0}".format(response.payload) )

        raw_input("Press Enter to continue...\n")`

After changing this to `input` the sample worked for me

**Comment by zolvarga** [comment]
@FabianKLS 

Thanks for the correction, we will update the samples in the next release.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
The samples have been update in the release:
https://github.com/Azure/azure-iot-sdk-python/releases/tag/release_2017_09_26

Best Regards,
Zoltan
