### ISSUE TITLE
Device SDK connection drop after throttling error

### ISSUE THREAD

**Issue by thurnbauermatthi** [Azure/azure-iot-sdk-python#735]
# Context

- **OS and version used:** Windows 10
- **Python version:** 3.7.4
- **pip version:** 19.0.3
- **list of installed packages:** 
Package             Version
------------------- ---------
azure-iot-device    2.5.0
azure-iot-hub       2.2.3
certifi             2020.6.20
chardet             3.0.4
deprecation         2.1.0
idna                2.10
isodate             0.6.0
janus               0.4.0
jsonmodels          2.4
msrest              0.6.19
oauthlib            3.1.0
packaging           20.4
paho-mqtt           1.5.1
pip                 19.0.3
pyparsing           2.4.7
PySocks             1.7.1
python-dateutil     2.8.1
requests            2.24.0
requests-oauthlib   1.3.0
requests-unixsocket 0.2.0
setuptools          40.8.0
six                 1.15.0
uamqp               1.2.12
urllib3             1.25.10

- **cloned repo:** -

## Description of the issue

I am using the IoTHubDeviceClient to connect to an IoT Hub and publish telemetry data. For testing purposes I am using the free tier of the IoT Hub. After hitting the quota limit of 8000 messages per day, the service drops the connection without informing the python SDK about a throttling error. I have already contacted the Microsoft Support who told me to open the issue here after discussing my problem.

## Code sample exhibiting the issue

from azure.iot.device import IoTHubDeviceClient
device_client = IoTHubDeviceClient.create_from_connection_string(connection_string="connection_string", websockets=True,
                                                                     keep_alive=10)

for x in range(9000):
    message = Message("test {0}".format(x))
    device_client.send_message(message)

## Console log of the issue

Starting run_op in pipeline thread
Creating pipeline executor
Gateway Hostname not present. Setting Hostname to: HOSTNAME
HTTPTransportStage(InitializePipelineOperation): got connection args
creating a SSL context
InitializePipelineOperation: completing without error
Starting <azure.iot.device.common.evented_callback.EventedCallback object at 0x00000269D0BCD408> in callback thread
Creating callback executor
Callback completed with result None
Starting run_op in pipeline thread
Scheduling SAS Token renewal at epoch time: 1611059149
Gateway Hostname not present. Setting Hostname to: HOSTNAME
MQTTTransportStage(InitializePipelineOperation): got connection args
creating mqtt client
Creating client for connecting using MQTT over websockets
Setting custom proxy options on mqtt client
creating a SSL context
configuring SSL context with default certs
Created MQTT protocol client, assigned callbacks
InitializePipelineOperation: completing without error
Starting <azure.iot.device.common.evented_callback.EventedCallback object at 0x00000269D0BCDF08> in callback thread
Callback completed with result None
Connecting to Hub...
Starting ConnectOperation on the pipeline
Starting run_op in pipeline thread
ReconnectStage(ConnectOperation): State changes LOGICALLY_DISCONNECTED->LOGICALLY_CONNECTED.  Adding to wait list and sending new connect op down
ReconnectStage: sending new connect op down
ConnectionLockStage(ConnectOperation): blocking
MQTTTransportStage(ConnectOperation): connecting
MQTTTransportStage(ConnectOperation): Starting watchdog
connecting to mqtt broker
Connect using port 443 (websockets)
_mqtt_client.connect returned rc=0
connected with result code: 0
Starting _on_mqtt_connected in pipeline thread
_on_mqtt_connected called
PipelineRootStage: ConnectedEvent received. Calling on_connected_handler
Starting _on_connected in callback thread
completing connect op
Connection State - Connected
MQTTTransportStage(ConnectOperation): cancelling watchdog
ConnectOperation: completing without error
ConnectionLockStage(ConnectOperation): op succeeded.  Unblocking queue
ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
ConnectionLockStage(ConnectOperation): processing 0 items in queue for error=None
ReconnectStage(ConnectOperation): on_connect_complete error=None state=LOGICALLY_CONNECTED never_connected=True connected=True 
ReconnectStage: completing waiting ops with error=None
ConnectOperation: completing without error
Starting on_complete in callback thread
Callback completed with result None
Successfully connected to Hub
Connecting to broker
Sending message to Hub...
Starting SendD2CMessageOperation on the pipeline
Starting run_op in pipeline thread
SendD2CMessageOperation: creating worker op of type MQTTPublishOperation
AutoConnectStage(MQTTPublishOperation): Connected.  Sending down and adding callback to check result
MQTTTransportStage(MQTTPublishOperation): publishing on devices/.../messages/events/
publishing on devices/.../messages/events/
_mqtt_client.publish returned rc=0
Waiting for response on MID: 1
failed to receive on socket: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen, 2021-01-19 12:27:55.243008
disconnected with result code: 1
  File "C:\Program Files\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 3453, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 1780, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 1182, in loop
    rc = self.loop_read(max_packets)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 1575, in loop_read
    return self._loop_rc_handle(rc)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 2228, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 3361, in _do_on_disconnect
    self.on_disconnect(self, self._userdata, rc)
  File "C:\Users\...\...\...\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 210, in on_disconnect
    logger.debug("".join(traceback.format_stack()))

Forcing paho disconnect to prevent it from automatically reconnecting
in paho thread.  nulling _thread
Done forcing paho disconnect
Starting _on_mqtt_disconnected in pipeline thread
MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('Paho returned rc==1')
ReconnectStage(DisconnectedEvent): State is LOGICALLY_CONNECTED Connected is True.
ReconnectStage: State is WAITING_TO_RECONNECT. Connected=True Starting reconnect timer
PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
Starting _on_disconnected in callback thread
MQTTTransportStage: disconnection was unexpected
Unexpected disconnection.  Safe to ignore since other stages will reconnect.
Connection State - Disconnected
Cleared all pending method requests due to disconnect
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Paho returned rc==1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\...\...\venv\lib\site-packages\azure\iot\device\common\handle_exceptions.py", line 43, in swallow_unraised_exception
    raise e
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('Paho returned rc==1')

Starting on_reconnect_timer_expired in pipeline thread
ReconnectStage: Reconnect timer expired. State is WAITING_TO_RECONNECT Connected is False.
ReconnectStage: sending new connect op down
ConnectionLockStage(ConnectOperation): blocking
MQTTTransportStage(ConnectOperation): connecting
MQTTTransportStage(ConnectOperation): Starting watchdog
connecting to mqtt broker
Connect using port 443 (websockets)
_mqtt_client.connect returned rc=0
connected with result code: 0
Starting _on_mqtt_connected in pipeline thread
_on_mqtt_connected called
PipelineRootStage: ConnectedEvent received. Calling on_connected_handler
Starting _on_connected in callback thread
completing connect op
MQTTTransportStage(ConnectOperation): cancelling watchdog
ConnectOperation: completing without error
ConnectionLockStage(ConnectOperation): op succeeded.  Unblocking queue
ConnectionLockStage(ConnectOperation): unblocking and releasing queued ops.
ConnectionLockStage(ConnectOperation): processing 0 items in queue for error=None
ReconnectStage(ConnectOperation): on_connect_complete error=None state=LOGICALLY_CONNECTED never_connected=False connected=True 
ReconnectStage: completing waiting ops with error=None
Connection State - Connected
failed to receive on socket: [WinError 10054] Eine vorhandene Verbindung wurde vom Remotehost geschlossen, 2021-01-19 12:28:00.614058
disconnected with result code: 1
  File "C:\Program Files\Python37\lib\threading.py", line 890, in _bootstrap
    self._bootstrap_inner()
  File "C:\Program Files\Python37\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "C:\Program Files\Python37\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 3453, in _thread_main
    self.loop_forever(retry_first_connection=True)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 1780, in loop_forever
    rc = self.loop(timeout, max_packets)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 1182, in loop
    rc = self.loop_read(max_packets)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 1575, in loop_read
    return self._loop_rc_handle(rc)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 2228, in _loop_rc_handle
    self._do_on_disconnect(rc, properties)
  File "C:\Users\...\...\...\venv\lib\site-packages\paho\mqtt\client.py", line 3361, in _do_on_disconnect
    self.on_disconnect(self, self._userdata, rc)
  File "C:\Users\...\...\...\venv\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 210, in on_disconnect
    logger.debug("".join(traceback.format_stack()))

Forcing paho disconnect to prevent it from automatically reconnecting
in paho thread.  nulling _thread
Done forcing paho disconnect
Starting _on_mqtt_disconnected in pipeline thread
MQTTTransportStage: _on_mqtt_disconnect called: ConnectionDroppedError('Paho returned rc==1')
ReconnectStage(DisconnectedEvent): State is LOGICALLY_CONNECTED Connected is True.
ReconnectStage: State is WAITING_TO_RECONNECT. Connected=True Starting reconnect timer
PipelineRootStage: DisconnectedEvent received. Calling on_disconnected_handler
Starting _on_disconnected in callback thread
MQTTTransportStage: disconnection was unexpected
Unexpected disconnection.  Safe to ignore since other stages will reconnect.
Connection State - Disconnected
Cleared all pending method requests due to disconnect
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError('Paho returned rc==1')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\Users\...\...\...\venv\lib\site-packages\azure\iot\device\common\handle_exceptions.py", line 43, in swallow_unraised_exception
    raise e
azure.iot.device.common.transport_exceptions.ConnectionDroppedError: ConnectionDroppedError(None) caused by ConnectionDroppedError('Paho returned rc==1')

**Comment by cartertinney** [comment]
This is a known issue. We are working on a fix, but it will take some time yet before it becomes available. This is related to issue #727

**Comment by thurnbauermatthi** [comment]
Hello again, could you give some feedback about the current status of this bug?

**Comment by cartertinney** [comment]
@thurnbauermatthi

Unfortunately, the IoTHub service doesn't indicate that throttling occurs, it simply drops the connection with the client, which means we aren't able to directly report what happened to you.

However, there are potential mitigations we are looking at, which depend on some new infrastructure being built. I'm currently working on this infrastructure. The idea would be that we can provide the option to disable automatic connection retry so it doesn't get stuck infinitely attempting to re-establish a connection (this presently exists in the latest release, however has some bugs that need to be addressed). We also would like to more gracefully report the errors to the end user via a handler function, allowing for some kind of heuristic implementation to infer the error's cause (this is partially implemented as of now).

I apologize for the delay in addressing this, but we are actively working on the pre-requisite work required to present the most workable solution we can

**Comment by cartertinney** [comment]
Unfortunately this feature is not able to be supported. We are looking at attempting to enhance our error story in the near future, however it won't bring any specificity to this exact issue as the IoTHub does not specify why it closes a connection.

However, we have mitigated this with several features in releases over the past few months - automatic reconnection can now be disabled via the `auto_connect` keyword argument at client creation, so the client will not keep attempting to reconnect after throttling occurs, and we have also have introduced more fail-fast responses so that the client won't lock up if it does get stuck in such a loop.
