### ISSUE TITLE
Not able to get Twin Patch Handler to work

### ISSUE THREAD

**Issue by XavierGeerinck** [Azure/azure-iot-sdk-python#737]
# Context

- **OS and version used:** Windows 10
- **Python version:** 3.8.6
- **pip version:** 21.0.1
- **list of installed packages:** N/A (will post if required anyways)
- **cloned repo:** N/A

## Description of the issue

When trying to work with the `module_client.on_twin_desired_properties_patch_received` I am expecting my method to be executed when the Twin for my module gets updated and my `print` call being executed.

> ⚠ I am utilizing the Simulator to test this! I am not 100% sure this is supported but could not find documentation stating that this is not supported.

**The way I test Twin updates:**

1. Go to Portal
2. Open Device + Module
3. Edit the `Module Identity Twin` + Save

OR

1. Go to VSCode IoTHub
2. Right Click module -> Edit Module Twin
3. Edit Twin + Click `Update Module Twin` in the left top

## Code sample exhibiting the issue

```python
import time
import os
import sys
import asyncio
from six.moves import input
import threading
from azure.iot.device.aio import IoTHubModuleClient
from azure.iot.device import Message
import random

async def main():
  try:
    print("IoT Hub Client for Python")

    # The client object is used to interact with your Azure IoT hub.
    module_client = IoTHubModuleClient.create_from_edge_environment()

    # connect the client.
    await module_client.connect()

    async def main_loop(module_client):
      while True:
        print("Waiting for commands")
        await asyncio.sleep(1)

    def twin_patch_handler(patch):
      print("the data in the desired properties patch was: {}".format(patch))
    
    module_client.on_twin_desired_properties_patch_received = twin_patch_handler

    print("The sample is now waiting for messages. ")
    await main_loop(module_client)

    # Finally, disconnect
    await module_client.disconnect()

  except Exception as e:
    print("Unexpected error %s " % e)
    raise

if __name__ == "__main__":
  asyncio.run(main())
```

Thanks for helping in advance! Let me know if anything else is required from my side.

**Comment by XavierGeerinck** [comment]
Any update on this? :) @cartertinney

**Comment by XavierGeerinck** [comment]
Update on my side, I was working with this and tried with the deprecated method. When utilizing the following, I am receiving Twin updates!

```python
async def twin_patch_listener(device_client):
    while True:
        patch = await device_client.receive_twin_desired_properties_patch()  # blocking call
        print("the data in the desired properties patch was: {}".format(patch))

# Create task for twin patch
asyncio.create_task(twin_patch_listener(module_client))
```

**Comment by XavierGeerinck** [comment]
Anything?... Would love to start utilizing the Twins @cartertinney

**Comment by cartertinney** [comment]
Apologize for the delay, we're looking into this now.

**Comment by XavierGeerinck** [comment]
Any updates @cartertinney?

**Comment by cartertinney** [comment]
@XavierGeerinck We are still working on this, once again, our apologizes for the delay

**Comment by XavierGeerinck** [comment]
We are now 2 months further without a solution for Twin patching on an edge device. We are blocked by this for production purposes, so I would love to follow up again to see what the status is on this. Are other users seeing this as well?

**Comment by cartertinney** [comment]
Our apologies for the delay. This is now a top priority item. I have not yet been able to reproduce the issue, but am looking into it actively. So far you are the only user to have experienced this particular issue.

**Comment by cartertinney** [comment]
We have been able to reproduce the issue and are now looking for solutions.

**Comment by cartertinney** [comment]
@XavierGeerinck Which version of Python are you using? By default the Edge Solution generated by VS Code while using the simulator uses a `requirements.txt` file with the text "azure-iot-device~=2.0.0", which installs the highest available version of 2.0.x.

However, handler support wasn't added until 2.3.0, which being part of a minor version increase, won't be installed via the requirements.txt in the default solution configuration.

Can you verify that you are using at least version 2.3.0 of azure-iot-device?

**Comment by XavierGeerinck** [comment]
`azure-iot-device==2.5.1` is what I have written

**Comment by cartertinney** [comment]
@XavierGeerinck can you try adding the following lines to the beginning of your module `main,py`?

```python
import logging
logging.basicConfig(level=logging.DEBUG)
print("Python Version: - {}".format(sys.version))
```

This will result in the output including debug statements that will help us diagnose the issue. If you could post the resulting logs, that would be of great help.

Also, is it just the twin patch handler, or are other handlers (e.g. on_message_received) not working as well?

**Comment by cartertinney** [comment]
@XavierGeerinck any updates on this?

**Comment by XavierGeerinck** [comment]
Apologies for the delay, I am currently swamped and removed the entire IoT Hub Twin handling due to this issue from my codebase. Will work on trying this again by the beginning of next week

**Comment by cartertinney** [comment]
No worries, completely understandable.

**Comment by cartertinney** [comment]
@XavierGeerinck 

Following up once more, is this still an issue?

**Comment by cartertinney** [comment]
I'm going to close this issue now due to inactivity. If the issue persists, please open a new GitHub issue and we will be happy to assist.
