### ISSUE TITLE
X509 connection between device and edge 

### ISSUE THREAD

**Issue by TheRealSvc** [Azure/azure-iot-sdk-python#743]
In the Lab 14 of of Az220 (which can be found here: https://microsoftlearning.github.io/AZ-220-Microsoft-Azure-IoT-Developer/Instructions/Labs/LAB_AK_14-iot-edge-device-in-restricted-network.html#exercise-5-open-iot-edge-gateway-device-inbound-ports-using-azure-cli), a transparent gateway was created to connect a temp-sensor device via the edge with the iot hub.  In that example C# code was used on the device side.   There, in the Program.cs file, a certificate was added to the  local cert store for use by downstream device to authenticate to the edge device.  I've tried to do the same thing for python but failed so far. Is there an example to use for python that is equivalent to the Lab Program C# code ?  Thanks !

**Comment by elhorton** [comment]
Hi @TheRealSvc , we don't have a Python equivalent for the Lab Program C# code, but we do have a [sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-edge-scenarios/send_message_downstream.py) showing how to use a downstream Python device. [This article](https://docs.microsoft.com/en-us/azure/iot-edge/how-to-connect-downstream-device?view=iotedge-2018-06#python) also explains the overall downstream device connection process. 

Do these help? Are you stuck on something in particular?

**Comment by TheRealSvc** [comment]
Thanks , yeah. I didnt look into your sample because i understood its for sending messages downstream (the name is 'send_message_downstream.py'). So it means send message from! (not to) downstream device. I will check.

**Comment by elhorton** [comment]
good point-- that is confusing! Let me see about renaming that sample. Glad it works for you now!
