### ISSUE TITLE
[Technical Question] Get Azure IotHub DeviceId after routing from IotHub to service bus queue

### ISSUE THREAD

**Issue by NhanNgocThien** [Azure/azure-iot-sdk-python#745]
Hello everyone,

I have a question when I am routing the device message from Azure IotHub to the service bus queue,  Is there any way that I can get the IoTHub deviceId from service bus message properties.
If no then is there a good way to set the DeviceId in the message.

Thank you very much

**Comment by elhorton** [comment]
Hi @NhanNgocThien , this question is not related to this Python SDK specifically, could you please ask on [Microsoft Q&A](https://docs.microsoft.com/en-us/answers/topics/azure-iot.html) with the Azure-IoT tag? Thank you!

**Comment by anthonyvercolano** [comment]
Closing as we haven't heard from you.
