### ISSUE TITLE
Support Micropython for constraint device

### ISSUE THREAD

**Issue by xiongyu0523** [Azure/azure-iot-sdk-python#749]
**Is your feature request related to a problem? Please describe.**
Now connecting constraint devices running micropython runtime can only via MQTT. The trend is this number will increase in the next few years. 

**Describe the solution you'd like**
a single repo support both python and micropython

**Describe alternatives you've considered**
independent azure-iot-sdk-micropython repo, api compatible as much as possible

**Additional context**
e.g. https://github.com/blynkkk/lib-python

**Comment by cartertinney** [comment]
This is an ask we have been considering for a while, but at this time we do not yet have concrete plans to support this.

**Comment by xiongyu0523** [comment]
ok if it is not in scope I'm fine to close this discussion.
