### ISSUE TITLE
No matching distribution found for Azure-iothub-device-client 

### ISSUE THREAD

**Issue by vaishnavils97** [Azure/azure-iot-sdk-python#752]
Hi,
I am using Dockerfile for building a module for architecture arm64. But getting error with azure-iothub-device-client. I have tried changing the pip version to 19.3.1 and  21.0.1. 

This is the dockerfile
RUN apt-get update && \
    apt-get install -y --no-install-recommends \
        build-essential \
        python3 \
        git \
        g++ \
        libx11-xcb1 \
        python3-pip \   
        python3-dev \
        libcurl4-openssl-dev \
        libboost-python-dev \
        libgl1-mesa-glx \
        libgtk2.0-dev
RUN apt-get install -y cmake
#RUN pip3 install --upgrade pip
RUN pip3 install --upgrade pip==21.0.1
RUN pip3 install --upgrade setuptools
RUN cd ~ && \
    mkdir -p dlib && \
    git clone --depth=1 -b 'v19.9' --single-branch https://github.com/davisking/dlib.git dlib/ && \
    cd  dlib/ && \
    python3 setup.py install --yes USE_AVX_INSTRUCTIONS  
RUN pip3 install azure-iothub-device-client  
COPY requirements.txt ./
RUN pip3 install -r requirements.txt

COPY . .

ENTRYPOINT [ "python3", "-u", "./main.py" ]

"Requirement.txt " have numpy and azure-iot-device~=2.0.0

while building I am getting the below error. Please give a solution 

RUN pip3 install azure-iothub-device-client                                                     13.9s 
------
 > [ 9/12] RUN pip3 install azure-iothub-device-client:
#12 13.45 ERROR: Could not find a version that satisfies the requirement azure-iothub-device-client
#12 13.45 ERROR: No matching distribution found for azure-iothub-device-client
------
executor failed running [/bin/sh -c pip3 install azure-iothub-device-client

**Comment by BertKleewein** [comment]
azure-iothub-device-client is a deprecated library and is not being maintained.  You should be using azure-iot-device instead.
