### ISSUE TITLE
The SDK raises an exception if a direct method is requests without a payload

### ISSUE THREAD

**Issue by jimbobbennett** [Azure/azure-iot-sdk-python#761]
# Context

- **OS and version used:** Raspberry Pi OS
- **Python version:** 3.7.3

## Description of the issue

* Create a Python app that listens to direct methods
* Send a direct method request to the device without a payload from the Azure portal
* Instead of handling the request and invoking the `on_method_request_received` function, an error is logged to the terminal:

    ```output
    Unexpected error in <azure.iot.device.iothub.pipeline.pipeline_stages_iothub_mqtt.IoTHubMQTTTranslationStage object at 0xb5c6b9b0>._handle_pipeline_event() call
    Exception caught in background thread.  Unable to handle.
    ['json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n']
    ```

## Code sample exhibiting the issue

```python
def handle_method_request(request):
    method_response = MethodResponse.create_from_method_request(request, 200)
    device_client.send_method_response(method_response)

device_client.on_method_request_received = handle_method_request
```

## Console log of the issue

```output
Unexpected error in <azure.iot.device.iothub.pipeline.pipeline_stages_iothub_mqtt.IoTHubMQTTTranslationStage object at 0xb5c6b9b0>._handle_pipeline_event() call
Exception caught in background thread.  Unable to handle.
['json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)\n']
```

**Comment by cartertinney** [comment]
I have been able to reproduce the problem and we are investigating possible solutions

**Comment by cartertinney** [comment]
@jimbobbennett We have identified the problem as a bug with the Azure Portal rather than this device client. The team responsible for maintaining it has scheduled a fix, and it should be available within a couple weeks. In the meantime, your issue could be mitigated by using a different means of sending direct method requests, such as an IoT Hub service client, the CLI, or the IoT Explorer.

**Comment by cartertinney** [comment]
@jimbobbennett I believe the fix has now been addressed on the portal side. Let me know if this has been sufficient for you.

**Comment by jimbobbennett** [comment]
Confirmed - this is now working. Thanks @cartertinney!
