### ISSUE TITLE
can't init submodule recursive since friday 6.10.

### ISSUE THREAD

**Issue by rolandho** [Azure/azure-iot-sdk-python#77]
here is the log-output for [git submodule update --init --recursive]:
(i used the latest release-branch release_2017_09_26)

| Cloning into 'testtools/ctest'...
| fatal: reference is not a tree: b3f3ab7fa3824009c4aab8b493dbc221193f5dd2
| 
| fatal: reference is not a tree: b3f3ab7fa3824009c4aab8b493dbc221193f5dd2
| Cloning into 'testtools/testrunner'...
| 
| Cloning into 'testtools/testrunner'...
| fatal: reference is not a tree: 286394050620ee284d54dfa908cef44f193664e4
| 
| fatal: reference is not a tree: 286394050620ee284d54dfa908cef44f193664e4
| Cloning into 'testtools/umock-c'...
| 
| Cloning into 'testtools/umock-c'...
| fatal: reference is not a tree: 52a652266f14a2452fc9e1f0fdc20bd591e85fcf
| 
| fatal: reference is not a tree: 52a652266f14a2452fc9e1f0fdc20bd591e85fcf
| Unable to checkout 'b3f3ab7fa3824009c4aab8b493dbc221193f5dd2' in submodule path 'c/umqtt/c-utility/testtools/ctest'
| 
| Unable to checkout 'b3f3ab7fa3824009c4aab8b493dbc221193f5dd2' in submodule path 'c/umqtt/c-utility/testtools/ctest'
| Unable to checkout '286394050620ee284d54dfa908cef44f193664e4' in submodule path 'c/umqtt/c-utility/testtools/testrunner'
| Unable to checkout '52a652266f14a2452fc9e1f0fdc20bd591e85fcf' in submodule path 'c/umqtt/c-utility/testtools/umock-c'
| 
| Unable to checkout '286394050620ee284d54dfa908cef44f193664e4' in submodule path 'c/umqtt/c-utility/testtools/testrunner'
| Unable to checkout '52a652266f14a2452fc9e1f0fdc20bd591e85fcf' in submodule path 'c/umqtt/c-utility/testtools/umock-c'
| Failed to recurse into submodule path 'c/umqtt/c-utility'
| 
| Failed to recurse into submodule path 'c/umqtt/c-utility'
| Failed to recurse into submodule path 'c/c-utility'
| Failed to recurse into submodule path 'c/deps/uhttp'
| Failed to recurse into submodule path 'c/dps_client/deps/utpm'
| Failed to recurse into submodule path 'c/uamqp'
| 
| Failed to recurse into submodule path 'c/c-utility'
| Failed to recurse into submodule path 'c/deps/uhttp'
| Failed to recurse into submodule path 'c/dps_client/deps/utpm'
| Failed to recurse into submodule path 'c/uamqp'
| Failed to recurse into submodule path 'c/umqtt'
| 
| Failed to recurse into submodule path 'c/umqtt'
| Failed to recurse into submodule path 'c'

**Comment by skotzko** [comment]
Same thing here.

**Comment by angelobt** [comment]
Same for me

**Comment by andrewwylie** [comment]
This is impacting the use of the python tool-kit. Can anyone give a workaround or expected date for resolution?

**Comment by zolvarga** [comment]
IT has been fixed in the latest release
