### ISSUE TITLE
could you share Azure python paho-mqtt example, please?

### ISSUE THREAD

**Issue by AndreV84** [Azure/azure-iot-sdk-python#772]
we are trying to send from linux to azure iot.
with python-azure sdk we can send the message but it is not obvious how to adjust the example to send GPS.
So could you provide paho-mqtt exxample for python to send a test message from ilnux device to azure Iot Please? Maye with paho-mqtt it will be easier to incorporate GPS

**Comment by cartertinney** [comment]
Closing - both this and your previous issue #771 can be tracked together

**Comment by AndreV84** [comment]
@cartertinney 
Thank you for following up
Indeed they can be tracked, but they are separate issues.
This one is concerned in procurement of paho-mqtt sample to send a test message to IoT hub initially
so that this particular transparent example could be developed further e.g. by ingesting GPS data into it
The other issue is concerned in using os/async python modules with the python-iot-sdk sample that uses azure-iot python module
