### ISSUE TITLE
[Technical Question] How to add a new certificate authority using this SDK ?

### ISSUE THREAD

**Issue by MrVhek** [Azure/azure-iot-sdk-python#776]
Hello,
I've been searching on how to provision a new certificate authority using the SDK.
I don't see any mentions of this point in the documentation here or in Azure, is this a planned feature or impossible to do ?
I'm using the certificate authority to authenticate all the device I run on my IoTHubs and I need to update it at some point.
I'm searching for an automated way of doing it.

Thanks for you help !

**Comment by cartertinney** [comment]
We do not yet support this feature. Right now, you would have to shut down the client, and make a new client with the new certificate authority.

We do plan to support this in the future however, and have scheduled implementation for this feature in the next few months.

**Comment by anthonyvercolano** [comment]
[Management Plane](https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/iothub/azure-mgmt-iothub) Carter mis-spoke above.  To accomplish adding a CA you want to use the linked management plane SDK.
