### ISSUE TITLE
[Technical Question] Is SASToken authentication not currently supported?

### ISSUE THREAD

**Issue by matsujirushi** [Azure/azure-iot-sdk-python#777]
Hi,

IoTHubDevliceClient class has [create_from_sastoken](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.iothubdeviceclient?view=azure-python#create-from-sastoken-sastoken----kwargs-) method.
And ...
There is "SASToken authentication is not currently supported." in [Authentication feature](https://github.com/Azure/azure-iot-sdk-python#iothub-device-client).

Which is correct?

**Comment by cartertinney** [comment]
It is supported. That documentation is outdated. I will fix that. Thank you for pointing it out.

[Here is a sample showing use of user-provided SAS Tokens](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/use_custom_sastoken.py)

**Comment by cartertinney** [comment]
Documentation has been fixed. Closing issue.
