### ISSUE TITLE
Unable to clone the lts_07_2017 release (and current version)

### ISSUE THREAD

**Issue by andrewwylie** [Azure/azure-iot-sdk-python#78]
- **OS and version used:** <VERSION> Ubuntu 16.04

- **Python runtime used:** <VERSION> 3.6.2

- **SDK version used:** <VERSION> lts_07_2017

# Description of the issue:

The clone fails with the --recursive option, thereby rendering this unusable.

# Code sample exhibiting the issue:

# Console log of the issue:

fatal: reference is not a tree: 1f591f650b5314faf5199ec580789047d34f0f57
Unable to checkout '92c82a95fb19255c378cfb56a5ca2b68f2f4b7e7' in submodule path 'c/umqtt/c-utility/testtools/umock-c/deps/ctest'
Unable to checkout '1f591f650b5314faf5199ec580789047d34f0f57' in submodule path 'c/umqtt/c-utility/testtools/umock-c/deps/testrunner'
Unable to checkout '92c82a95fb19255c378cfb56a5ca2b68f2f4b7e7' in submodule path 'c/umqtt/c-utility/testtools/ctest'
Unable to checkout '1f591f650b5314faf5199ec580789047d34f0f57' in submodule path 'c/umqtt/c-utility/testtools/testrunner'
Failed to recurse into submodule path 'c/umqtt/c-utility/testtools/umock-c'
Failed to recurse into submodule path 'c/umqtt/c-utility'
Failed to recurse into submodule path 'c/c-utility'
Failed to recurse into submodule path 'c/uamqp'
Failed to recurse into submodule path 'c/umqtt'
Failed to recurse into submodule path 'c'

**Comment by zolvarga** [comment]
It has been fixed in the latest release of C SDK and Python SDK
