### ISSUE TITLE
[Technical Question] How to change used HTTPS port for IoTHubModuleClient?

### ISSUE THREAD

**Issue by licensedslacker** [Azure/azure-iot-sdk-python#784]
How do I change the used HTTPS port of remote method calls for IoTHubModuleClient?
Our IoT edge hub deployment uses a different port for SSL connections rather than 443.

Related question: Is there any way to change the used MQTT port for IoTHubModuleClient?

**Comment by cartertinney** [comment]
Currently we only support using port 8883 via TCP and 443 via websockets.

Which protocol do you want to use a custom port for?

**Comment by licensedslacker** [comment]
Well the use case for us that we have configured edge hub to utilize different port for HTTPS connections beyond port 1024. Module client makes remote method calls by using the port and thus all clients shall be configured with the abnormal port.

**Comment by cartertinney** [comment]
@licensedslacker 

Is there a particular reason you've elected to do that? The more information you can provide about why, the more helpful it will be for us to try and get official support for this scenario

**Comment by licensedslacker** [comment]
The reason behind the problem is that we are running container engine rootless mode and that cause some issue with user permissions after the hub and the agent images switch the container's user to regular user from the root. One problem is binding service ports and thus we have decided to move to utilize some other port for HTTPS.

**Comment by RemiCardona** [comment]
I'd like to chime in: mocks.

We mock iothub in unit tests with a very simple mqtt broker. To avoid any issues, we request a random unused port from the system and configure the broker with it. IOW, our automated tests *never* use port 8883, only the production code does.

So right now, we have to monkeypatch paho underneath azure-iot-sdk to ignore the hard-coded port and use instead the one we want. It works but it's a kludge.

Thanks for considering adding this option. Cheers.
