### ISSUE TITLE
Python API Documentation

### ISSUE THREAD

**Issue by tameraw** [Azure/azure-iot-sdk-python#8]
_From @sanket-kulkarni-vmware on August 11, 2016 9:41_

I didn't find complete documentation of the python API's, can you please provide me the same?

_Copied from original issue: Azure/azure-iot-sdks#763_

**Comment by tameraw** [comment]
_From @sanket-kulkarni-vmware on August 12, 2016 15:29_

Hello, I got stuck because of incomplete documentation, Can you please provide the link for the same.

Thanks

**Comment by tameraw** [comment]
@sanket-kulkarni-vmware - Currently we provide a document on how to start running the sample in Python. [https://github.com/Azure/azure-iot-sdks/blob/master/python/device/readme.md](url)
We'll work on generating API docs for the Python libraries.

**Comment by 5nowx** [comment]
Any news on the documentation by now?

**Comment by lulzmachine** [comment]
@tameraw your link leads to a 404

**Comment by 5nowx** [comment]
@lulzmachine https://github.com/Azure/azure-iot-sdk-python/tree/master/device/samples thats the link he is referring to

**Comment by zolvarga** [comment]
Documentation in place - closing as resolved
