### ISSUE TITLE
azure-iot-device async edge receive message on input  example in repo gives the following error

### ISSUE THREAD

**Issue by kaushikCanada** [Azure/azure-iot-sdk-python#806]
Press Q to quit
Traceback (most recent call last):
  File "./main.py", line 56, in <module>
    asyncio.run(main())
  File "/usr/local/lib/python3.7/asyncio/runners.py", line 43, in run
    return loop.run_until_complete(main)
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "./main.py", line 49, in main
    await user_finished
  File "/usr/local/lib/python3.7/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "./main.py", line 39, in stdin_listener
    selection = input("Press Q to quit\n")
EOFError: EOF when reading a line
Task was destroyed but it is pending!
task: <Task pending coro=<AsyncHandlerManager._receiver_handler_runner() running at /usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/aio/async_handler_manager.py:43> wait_for=<Future pending cb=[_chain_future.<locals>._call_check_cancel() at /usr/local/lib/python3.7/asyncio/futures.py:351, <TaskWakeupMethWrapper object at 0x7f07245cf050>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>
Task was destroyed but it is pending!
task: <Task pending coro=<_AsyncQueueProxy.get() running at /usr/local/lib/python3.7/site-packages/janus/__init__.py:451> wait_for=<Future pending cb=[<TaskWakeupMethWrapper object at 0x7f07245cf390>()]> cb=[_chain_future.<locals>._call_set_state() at /usr/local/lib/python3.7/asyncio/futures.py:358]>

**Comment by anthonyvercolano** [comment]
Which particular version of the Python SDK are you using?
Which edge release version are you using?
What underlying OS are you using?

This just happened when you hit "Q" to terminate the sample?

**Comment by kaushikCanada** [comment]
python sdk - 2.7.0
edge release - 1.2
underlying os - ubuntu 20.04
its not going upto the 'q'  i a running it through the deployment manifest.
I am not able to receive messages on any inputs.

**Comment by cartertinney** [comment]
@kaushikCanada 

This is a problem with our samples. I will work on fixing them in the coming days. Apologies for the inconvenience, and thank you for bringing this to our attention.

**Comment by kaushikCanada** [comment]
Thank you for your response. I have not been able to get thw routing to
modules working. Let me k ow if u have new samples.

**Comment by cartertinney** [comment]
@kaushikCanada 

I've [updated the sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-edge-scenarios/receive_data.py) to no longer require standard input in order to exit gracefully. Using this sample, you can now exit by issuing a direct method to your edge device using the method name "shutdown"

You can see documentation for how to issue a direct method [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-direct-methods)

Let me know if this solves your problem

**Comment by kaushikCanada** [comment]
WoW this is awesome!.
One more thing. Inspite of a LOT of attempts i have not been able to make
module to module routing work for me using these programs. I am definitely
doing something wrong. But cannot find what it is. let mek now if there is
a way i can do that.

Thanks,
Roy

**Comment by cartertinney** [comment]
@kaushikCanada
Unfortunately, the best I can do there is to point you towards our devguides on the topic:

https://docs.microsoft.com/en-us/azure/iot-edge/module-composition
https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-devguide-messages-d2c

If this updated sample works for you, may I close this GitHub issue and mark it as resolved?
