### ISSUE TITLE
[Technical Question] Follow up to "How do I handle azure.iot.device send_message hanging when message quota is exhausted #775"

### ISSUE THREAD

**Issue by terryholland** [Azure/azure-iot-sdk-python#812]
Hi @cartertinney 
You provided a fix to Issue #775 .   I am still having problems with this code.  Should the initial issue be reopened or should a new one be created?  I will briefly explain what I have been trying to do here and perhaps you can advise.

I'll give a bit more of an overview of my project.  It is a python 3 project running on a raspberry pi 4. I have a number of environmental sensors connected (temperature, humidity, light etc) and based on the readings from these sensors I control devices such as heaters, coolers, lighting etc via relays connected to output pins on the raspberry pi,

I have a pairing class that will pair a sensor with a device or two and based on the sensor reading I will control the devices paired with it.  I have a number of instances of these pairings and I run each of them on a separate thread.  It is within each pairing that I am trying to send telemetry data to the azure cloud using the send_message method in IoTHubDeviceClient.  The send_message call is in a singleton class that gets initialised at startup

Issue #775 was raised because when I reached my message quota (8000 as Im developing on the free tier), my code froze on the send_message line of code.  The solution you provided seemed to address the issue if I created my client using the connection_retry=False param ie

`self.client = IoTHubDeviceClient.create_from_connection_string(self.connectionString,connection_retry=False)`

What I found in my initial tests was that once the quota had been exceeded, the send_message method call would raise an exception which I was able to trap.  Since reporting that all looked fine, I have been trying to run continuous tests but I am finding that I get problems after 24 around hours of continuous running (I did message on #775 but I guess you do not monitor closed threads so I will post comments below here).  Sometimes Im getting errors like the one below and other time my code hangs.  The hanging is a particular worry to me as if the code hangs while one of my heaters in on, then I run into a situation were my real world environment overheats causing safety concerns

I will happily provide more logging after Ive completed my current round of testing.  

What I do know is that 

- If I disable my send_message code, then my rig runs continuously without issue.  It has currently been running for 24 hours for 4 days without issue.  
- The issue does not only happen when I exceed message quota.  Sometimes it occurs after only 2000 messages (all messages are small)

Could you share with me a small sample of how you would execute send_message from multiple threads (around 5 different threads) including initialising the client and checking for exceptions and reconnecting if the connection is dropped for some reason.  Id really appreciate this as I am looking to do full field testing within the next 6 weeks and I need to be able have confidence that I can use the library to collect my data without safety fears of this method killing my code.

I am sure the problem will be with the way I am using the IoTHubDeviceClient.  My class that actually does the sending is...

![image](https://user-images.githubusercontent.com/10390177/124679587-9cc05380-debc-11eb-91b1-71a2f71392a3.png)

Let me know if you need more info 

**Example error**
```
I left code running for 24 hours. I seems I spoke too soon as I woke this am to see logs full of these errors:

2021-06-29 04:00:58,927 MAIN_GR INFO: T_Avg (Thread-2) Reading 20.62466620889601
ReconnectStage: DisconnectEvent received while in unexpected state - LOGICALLY_DISCONNECTED, Connected: False
Exception in thread Thread-6:
Traceback (most recent call last):
File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 34, in handle_result
return callback.wait_for_completion()
File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
raise self.exception
azure.iot.device.common.pipeline.pipeline_exceptions.OperationCancelled: OperationCancelled('Operation cancelled before PUBACK received')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
File "/usr/lib/python3.7/threading.py", line 917, in _bootstrap_inner
self.run()
File "/usr/lib/python3.7/threading.py", line 865, in run
self._target(*self._args, **self._kwargs)
File "/home/pi/CabinetFarming/WIP/Pairings.py", line 80, in Start
self._doWork(settings)
File "/home/pi/CabinetFarming/WIP/Pairings.py", line 125, in _doWork
pairingSetpoint=setPoint
File "/home/pi/CabinetFarming/WIP/AZTelemetryService.py", line 66, in SendMessage
self.client.send_message(message)
File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/patch_documentation.py", line 66, in send_message
return super(IoTHubDeviceClient, self).send_message(message)
File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 322, in send_message
handle_result(callback)
File "/home/pi/.local/lib/python3.7/site-packages/azure/iot/device/iothub/sync_clients.py", line 56, in handle_result
raise exceptions.OperationCancelled(message="Could not complete operation", cause=e)
azure.iot.device.exceptions.OperationCancelled: OperationCancelled('Could not complete operation') caused by OperationCancelled('Operation cancelled before PUBACK received')
```

**Comment by cartertinney** [comment]
@terryholland

I'm going to begin looking into this, and will reach out if I need more information. This is not something we have seen before, so I will need to try and reproduce. You said this is hanging / unexpected error is coming from the `.send_message()` call, right?

I understand you are using five threads with a singleton device - how long is the period between messages you send?

Is your code doing anything else other than sending that I should be aware of?

**Comment by terryholland** [comment]
Thanks for response @cartertinney 

Answers to your questions in order asked...

- Its seems to be. 
- About 2 mins
- This varies.  I have had it occur after 12 hours.  The longest my code ran without error is 35 hours
- No.  I will provide a scaled down version of my code this coming weekend, providing you with the essential bits of what Im doing

**Comment by cartertinney** [comment]
@terryholland I would appreciate that scaled down version for repro purposes, will make fixing this a lot faster.

**Comment by terryholland** [comment]
I will get something to you over the weekend

**Comment by terryholland** [comment]
@cartertinney I have condensed my code into the snippet below.  I set very short periods so that I could exceed my message quota quickly.  Normally these values would be 120.

I've not experienced the freezing or unexpected errors yet so I am going set period to 120 and leave this version running on pi over the weekend so see if the problem happens

```
import threading
import random

from azure.iot.device import IoTHubDeviceClient
from azure.iot.device import Message

from datetime import datetime,time,timedelta
import time

class AZTelemetryService:
    __instance = None
    
    def __init__(self,connectionString,iotDeviceId,logger):
        self.Busy=False
        
        if AZTelemetryService.__instance!=None:
            raise Exception("Can use contructor to create a new instance of class.  Use getInstance method instead")
        else:
            AZTelemetryService.__instance=self
        
    
        self.connectionString=connectionString
        self.iotDeviceId=iotDeviceId
        self.client = IoTHubDeviceClient.create_from_connection_string(self.connectionString,connection_retry=False)
        self.client.connected
        self.logger=logger
        self.lock=threading.Lock()
        
        
    @staticmethod 
    def getInstance(connectionString,iotDeviceId,logger):
        
        """ Static access method. """
        if AZTelemetryService.__instance == None:
            AZTelemetryService(connectionString,iotDeviceId,logger)
            
        service=AZTelemetryService.__instance
        
        return AZTelemetryService.__instance
        
    def SendMessage(self,clientPairingId,clientDeviceId,type,subType,deviceState,pairingSetpoint=None):
        
        
        self.lock.acquire()
        
        messageTemplate = """{{"iotDeviceId":"{iotDeviceId}","timeStampUTC":"{timeStampUTC}","clientPairingId":"{clientPairingId}","clientDeviceId":"{clientDeviceId}","type":"{type}","subType":"{subType}","state": "{deviceState}","setPoint": "{pairingSetpoint}"}}"""
        
        message = Message(messageTemplate.format(iotDeviceId=self.iotDeviceId,
                                                clientPairingId=clientPairingId,
                                                clientDeviceId=clientDeviceId,
                                                type=type,
                                                subType=subType,
                                                deviceState=deviceState,
                                                pairingSetpoint=pairingSetpoint,
                                                timeStampUTC=datetime.utcnow()))
        
        
        
        maxConnectionAttempt=10
        connectionAttempt=0
        while self.client.connected==False and connectionAttempt<maxConnectionAttempt:
            
            connectionAttempt=connectionAttempt+1
            print("IoTHubDeviceClient connection attempt #{}".format(connectionAttempt))
            
            try:
                self.client.connect()
            except Exception as e:
                self.logger.error(e)
            
            
                    
        if self.client.connected:
            try:
                self.client.send_message(message)

            except Exception as e:
                print("Could not send telemetry: {}".format(e))
                self.client.shutdown()
                self.client = IoTHubDeviceClient.create_from_connection_string(self.connectionString,connection_retry=False)
                
        self.lock.release()
    

class Pairing:
    
    def __init__(self,id,telemetryService,period=120):
        self.Id=id
        self.TelemetryService=telemetryService
        self.Period=period
        
        
    def Start(self):
        #when a pairing starts it is run as an endless loop
        while True:
            self._doWork()
            time.sleep(self.Period)
        
    def _doWork(self):
        
        try:
            
            reading=random.randint(1,100)
            
            print("id:{}, reading:{}".format(self.Id,reading))
            print()
            
            self.TelemetryService.SendMessage(clientDeviceId="D",
                                              type="S",
                                              subType="ST",
                                              deviceState=reading,
                                              clientPairingId=self.Id,
                                              pairingSetpoint=""
                                              )
            
        
        except Exception as e:
            print (e)
        finally:
            pass

def main():
    
    iotDeviceId="???"
    iotHubConnectionString="????"

    
    #initialise telemetry service
    aZTelemetryService=AZTelemetryService.getInstance(iotHubConnectionString,iotDeviceId,None)

    pairings=[]
    
    pairings.append(Pairing(id="S1",telemetryService=aZTelemetryService,period=.1)) # usually period = 120
    pairings.append(Pairing(id="S2",telemetryService=aZTelemetryService,period=.2))
    pairings.append(Pairing(id="S3",telemetryService=aZTelemetryService,period=.3))
    pairings.append(Pairing(id="S4",telemetryService=aZTelemetryService,period=.4))
    pairings.append(Pairing(id="S5",telemetryService=aZTelemetryService,period=.5))
    pairings.append(Pairing(id="S6",telemetryService=aZTelemetryService,period=.6))
    
    
    threads=[]
    for pairing in pairings:
        
        thread= threading.Thread(target=pairing.Start,args=())
        thread.start()
        threads.append(thread)
    try:
        while 1:
            pass
    except KeyboardInterrupt:
        pass
    finally:
        for thread in threads:
            thread.join();
        
       
main()


```

**Comment by terryholland** [comment]
FYI I ren this code for the last 3 days without issue.  I need to start adding back my real code to see at which point it fails

**Comment by cartertinney** [comment]
Thanks for the update. When you have a case that reproduces, I will immediately get to work on fixing it.

**Comment by cartertinney** [comment]
@terryholland

Any updates on this?

**Comment by terryholland** [comment]
I will be working on this over the weekend. I will send update

**Comment by cartertinney** [comment]
@terryholland

Any updates?

**Comment by terryholland** [comment]
Apologies for not updating at weekend. I have not managed to work on recreating this issue as I have been ill.  I have scheduled time to look at is on Thu/Fri this week.

**Comment by cartertinney** [comment]
@terryholland

I'm going to go ahead and close the issue now since I haven't heard back, but do please open a new GitHub issue when you have reproduced the issue.
