### ISSUE TITLE
create_from_edge_environment()'s get_twin() is not returning the module twin values

### ISSUE THREAD

**Issue by ismaan1998** [Azure/azure-iot-sdk-python#821]
**Issue**- 

I'm reading module twin properties in my edge module. 

When i'm using - 

````
client = IoTHubModuleClient.create_from_connection_string("HostName=example.azure-devices.net;DeviceId=example;ModuleId=ExampleModuleId;SharedAccessKey=somekey")
client.get_twin()
````

I'm able to get the module twin values from ExampleModuleId but when we're using - 
````
client = IoTHubModuleClient.create_from_edge_environment()
client.get_twin()
````

It's returning  - . 
````
{'desired':{}, 'reported':{}}
````

**Note** - I'm running this code in edge environment. 

Let me know if anything other details needed to debug the issue.

**Comment by cartertinney** [comment]
@ismaan1998 

Thanks for bringing this to our attention. I'm going to look into this

**Comment by ismaan1998** [comment]
@cartertinney any update on this?

**Comment by cartertinney** [comment]
@ismaan1998 So far, I have been completely unable to replicate it. I'm reaching out to our Edge team to see if they have any additional insights, but any additional information or logs you can provide will be helpful.

**Comment by cartertinney** [comment]
@ismaan1998 

It appears the issue may be with your configuration of the Edge. Could you provide us the Edge logs using the command
`iotedge support-bundle`

https://docs.microsoft.com/en-us/azure/iot-edge/troubleshoot?view=iotedge-2020-11#gather-debug-information-with-support-bundle-command

**Comment by ismaan1998** [comment]
[support_bundle.zip](https://github.com/Azure/azure-iot-sdk-python/files/6898860/support_bundle.zip)


@cartertinney Let me know if anything else needed

**Comment by cartertinney** [comment]
Apologies for the delay, we're still trying to get this looked into.

**Comment by cartertinney** [comment]
@ismaan1998 any updates on this?

**Comment by ismaan1998** [comment]
@cartertinney 
By modifying the config.toml as shown below in the image has solved this issue. Thanks  
![image](https://user-images.githubusercontent.com/30122168/130409133-5e9c4d9c-c829-4b84-b52b-6070d8b9437a.png)
 
we can close this now. Thanks for all the help
