### ISSUE TITLE
Trying to disable an IoT Edge device using iothub_registry_manager.update_device_with_sas shows an error

### ISSUE THREAD

**Issue by marcus-tapias** [Azure/azure-iot-sdk-python#825]
# Context

- **OS and version used:** Windows 10
- **Python version:** 3.9.0
- **pip version:** pip 20.1.1
- **list of installed packages:
```
azure-common                1.1.27
azure-core                  1.16.0
azure-identity              1.6.0
azure-iot-hub               2.4.0
azure-keyvault              4.1.0
azure-keyvault-certificates 4.3.0
azure-keyvault-keys         4.4.0
azure-keyvault-secrets      4.3.0
certifi                     2021.5.30
cffi                        1.14.6
charset-normalizer          2.0.3
cryptography                3.4.7
idna                        3.2
isodate                     0.6.0
msal                        1.12.0
msal-extensions             0.3.0
msrest                      0.6.21
oauthlib                    3.1.1
pip                         21.1.3
portalocker                 1.7.1
pycparser                   2.20
PyJWT                       2.1.0
pywin32                     301
requests                    2.26.0
requests-oauthlib           1.3.0
setuptools                  57.4.0
six                         1.16.0
uamqp                       1.4.1
urllib3                     1.26.6
```

## Description of the issue

Hello guys. I'm trying to update the state of an IoT Edge device using the example described on [azure-iot-hub](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/samples/iothub_registry_manager_sample.py), but I'm getting an error.
I've noted that if i use this function without the keyword *"iotedge"* the device stays disabled but then i can't see it on the IoT Edge devices (as it assumes the default value, wich is *False*).

## Code sample exhibiting the issue
```
from azure.iot.hub import IoTHubRegistryManager
import vars

iothub_registry_manager = IoTHubRegistryManager(vars.iothub_connection_str)

def updateDeviceState(device_id, state):
    device = iothub_registry_manager.get_device(device_id)
    primary_key = device.authentication.symmetric_key.primary_key
    secondary_key = device.authentication.symmetric_key.secondary_key
    device_updated = iothub_registry_manager.update_device_with_sas(
        device_id, device.etag, primary_key, secondary_key, state, iot_edge=True
    )
    return device_updated

print(updateDeviceState(vars.deviceId, "disabled"))
```
## Console log of the issue
```
Traceback (most recent call last):
  File "C:/.../Documents/updateDevice/updateDevice.py", line 15, in <module>
    print(updateDeviceState(vars.deviceId, "disabled"))
  File "C:/.../Documents/updateDevice/updateDevice.py", line 11, in updateDeviceState
    device_id, device.etag, primary_key, secondary_key, state, iot_edge=True
  File "C:\...\Documents\updateDevice\venv\lib\site-packages\azure\iot\hub\iothub_registry_manager.py", line 329, in update_device_with_sas
    device_id, device, _ensure_quoted(etag)
  File "C:\...\Documents\updateDevice\venv\lib\site-packages\azure\iot\hub\protocol\operations\devices_operations.py", line 199, in create_or_update_identity
    raise HttpOperationError(self._deserialize, response)
msrest.exceptions.HttpOperationError: Operation returned an invalid status code 'Bad Request'
```

Is it something I'm doing wrong here? Hope you guys can help me!

**Comment by vishnureddy17** [comment]
Hi @marcus-tapias , if you take the `device_scope` from the device returned by `get_device` and pass it to the update function, it should work. 

The reason why this happens is because the for edge devices, the device scope is immutable. With the way the service is designed it is interpreting what you are doing in your example as changing the device scope to null which would be invalid for a edge device. 

Please let me know if this resolves your issue.

**Comment by marcus-tapias** [comment]
> Hi @marcus-tapias , if you take the `device_scope` from the device returned by `get_device` and pass it to the update function, it should work.
> 
> The reason why this happens is because for edge devices, the device scope is immutable. With the way the service is designed it is interpreting what you are doing in your example as changing the device scope to null which would be invalid for a edge device.
> 
> Please let me know if this resolves your issue.

vishnureddy17, this worked perfectly, thank you so much for your answer!

**Comment by MrVhek** [comment]
Hello !
Reopening this issue,
I just had the same problem, spending 3h debugging it and finally founding this issue.
Just please add some documentation in the SDK in comments or return an explicit message from the response. 

Thanks
