### ISSUE TITLE
Tests not passing on Ubuntu 20.04

### ISSUE THREAD

**Issue by charelstoncrabb** [Azure/azure-iot-sdk-python#828]
Side note: `pytest`, `pytest-testdox` and `pytest-timeout` have to be installed manually (not listed in `setup.py` requirements)

Started with a fresh test virtual environment, have the `master` branch checked out locally to run the tests, and almost all are throwing errors.

```
(test-venv2) $ hostnamectl
   Static hostname: ---
         Icon name: computer-desktop
           Chassis: desktop
        Machine ID: ---
           Boot ID: ---
  Operating System: Ubuntu 20.04.2 LTS
            Kernel: Linux 5.8.0-59-generic
      Architecture: x86-64
(test-venv2) $ python --version
Python 3.8.10
(test-venv2) $ pip freeze
attrs==21.2.0
azure-iot-device==2.7.1
certifi==2021.5.30
charset-normalizer==2.0.3
deprecation==2.1.0
geminus==0.0.4
idna==3.2
iniconfig==1.1.1
janus==0.4.0
packaging==21.0
paho-mqtt==1.5.1
pluggy==0.13.1
py==1.10.0
pyparsing==2.4.7
PySocks==1.7.1
pytest==6.2.4
pytest-testdox==2.0.1
pytest-timeout==1.4.2
requests==2.26.0
requests-unixsocket==0.2.0
six==1.16.0
toml==0.10.2
urllib3==1.26.6

(test-venv2) $ pytest tests/

...

==== 422 passed, 75 skipped, 77 warnings, 4937 errors in 13.04s ====
```

**Comment by cartertinney** [comment]
@charelstoncrabb

The only dependencies listed in setup.py are the ones required to actually use the package itself. We maintain other dependencies in two separate requirements files, `requirements_dev.txt` and `requirements_test.txt`. For running tests you should only need to install the items in `requriements_test.txt`.

From the repository root, please try
```
pip install -U -r requirements_test.txt
```

If this still does not solve your problem, please post the error output of the tests.

**Comment by charelstoncrabb** [comment]
Ah, thank you. Apologies for overlooking the `requirements_test.txt` file at the repo root

```
========= 5428 passed, 6 skipped, 1 warning in 54.31s =========
```
