### ISSUE TITLE
Authenticating `IoTHubRegistryManager` using the `from_token_credential` constructor

### ISSUE THREAD

**Issue by sgoyal1012** [Azure/azure-iot-sdk-python#831]
### Problem

* Hi azure team; we have a need to manage several IoT hubs; sending cloud to device messages for eg. So far, we have been using the `from_connection_string` constructor to do this. However this is a bit clunky as it requires us to have the connection string encoded as a secret for each of the IoT hubs.

* We are instead hoping to use `from_token_credential` to achieve authentication to all the IoT hubs within a subscription.

### Attempt and error faced

We are following the instructions as given [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-c2d#send-a-cloud-to-device-message) to try out C2D messaging for a simulated device; the only difference being

```
# This line is removed
registry_manager = IoTHubRegistryManager(CONNECTION_STRING)

# This is added
from azure.identity import EnvironmentCredential
credential = EnvironmentCredential()
registry_manager = IoTHubRegistryManager.from_token_credential(
            url="azure-simlab1.azure-devices.net",
            token_credential=credential.get_token(os.environ.get("scopes")),
        ) 
```

Upon running the command; it either

* Throws when an invalid _scope_ is passed;
* Or just hangs; the simulated device does not receive a message.
* It works perfectly fine if we switch back to the connection string method.

### Question
* What is the correct _scope_ for such a request?
* Is the `EnvironmentCredential` the correct approach?

Thanks!
Sahil

**Comment by vishnureddy17** [comment]
Hi @sgoyal1012, you directly pass the `EnvironmentCredential` to `from_token_credential()` for the `token_credential` parameter. No need to call any methods on the `EnvironmentCredential` or worry about the scope. 

Please let me know if this resolves your issue. 

Just out of curiosity, was there a sample or documentation that led you to do it your way?

**Comment by sgoyal1012** [comment]
@vishnureddy17 thanks a lot for your response; I tried what you mentioned and the code sort of *hangs* -- this is how I am initializing it now

```
registry_manager = IoTHubRegistryManager.from_token_credential(
            url="azure-simlab1.azure-devices.net",
            token_credential=EnvironmentCredential(),
        ) 
```
Is this what you had in mind?

> Just out of curiosity, was there a sample or documentation that led you to do it your way?
Not really.. me and my teammate looked at the method definition for `from_token_credential`; and the `token_credential` variable type is mentioned to be `str`. We sort of guessed that one needs to call the `get_token` on `EnvironmentCredential` ,

Source of `from_token_credential` -- https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-hub/azure/iot/hub/iothub_registry_manager.py#L113

```
:param str url: The Azure service url (host name).
:param str token_credential: The Azure token credential object.
 ```
Thanks for your help!

**Comment by vishnureddy17** [comment]
@sgoyal1012 Your example is correct. When you say it "sort of hangs", do you mean that it eventually succeeds but takes a long time, or do you mean that it doesn't succeed even after waiting for a while? The authentication could take some time.

`EnvironmentCredential` expects you to have certain environment variables set. Can you make sure that the variables are set correctly? [Here's some documentation on the environment variables that `EnvironmentCredential` uses](https://github.com/Azure/azure-sdk-for-python/tree/main/sdk/identity/azure-identity#environment-variables).

The type `str` in the docstring is a mistake and needs to be fixed. Thanks for pointing that out.

**Comment by sgoyal1012** [comment]
@vishnureddy17 thanks a lot for your response

> The type str in the docstring is a mistake and needs to be fixed. Thanks for pointing that out.

Ack, thank you!

------------------------------------
>  When you say it "sort of hangs", do you mean that it eventually succeeds but takes a long time, or do you mean that it doesn't succeed even after waiting for a while?

The latter; let me explain what we are running -- we are following the documentation [here](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-python-python-c2d) 

* The `SimulatedDevice.py` is copied verbatim (using connection string)
* For sending a cloud to device message we try three approaches
    a. `SendCloudToDeviceMessage` with connection string as the example (as in the example)
    b. `SendCloudToDeviceMessage` with token credentials
    c. az cli -- `az iot device c2d-message send -d myDevice -n azure-simlab1 --ack full --wait`

### Success cases -- (a) and (c)
For (a) and (c); the simulated device logs show the following

```
Message received:
    ('data', b'Ping from Az CLI IoT Extension')
    ('custom_properties', {})
    ('message_id', 'f9e20d56-d907-4f24-b8d5-ecf836aae099')
    ('expiry_time_utc', None)
    ('correlation_id', None)
    ('user_id', None)
    ('content_encoding', 'utf-8')
    ('content_type', None)
    ('output_name', None)
    ('input_name', None)
    ('ack', 'full')
    ('_iothub_interface_id', None)
Total calls received: 1
```
In the case of (a); I see the following confirmation 
```
Starting C2D feedback monitor, filtering on device: myDevice, use ctrl-c to stop...
feedback:
  description: Success
  deviceGenerationId: 'Some device ID'
  deviceId: myDevice
  enqueuedTimeUtc: '2021-07-28T16:15:29.741147Z'
  originalMessageId: SOme Message ID
  statusCode: Succes
```

### Failure Case - (b)

The program just waits, with no feedback neither on the receiver (`SimulatedDevice.py`) side; or the sender side. This is how it is invoked

```
AZURE_SUBSCRIPTION_ID="some sub" AZURE_CLIENT_ID="some client ID" \        
AZURE_CLIENT_SECRET="some secret" \
AZURE_TENANT_ID="some tenant ID" \
python3 SendCloudToDeviceMessage.py
Starting the Python IoT Hub C2D Messaging service sample...
Sending message: 0
Sending message: 1
Press Enter to continue...
```
Note that it seems to pass the credential init successfully; does not fail out.

I will add the code for your reference; thanks!

`SimulatedDevice.py`
```
import threading
import time
from azure.iot.device import IoTHubDeviceClient

RECEIVED_MESSAGES = 0

CONNECTION_STRING = "CONN_STRING_HERE"


def message_listener(client) -> None:
    global RECEIVED_MESSAGES
    while True:
        message = client.receive_message()
        RECEIVED_MESSAGES += 1
        print("\nMessage received:")

        # print data and both system and application (custom) properties
        for property in vars(message).items():
            print("    {0}".format(property))

        print("Total calls received: {}".format(RECEIVED_MESSAGES))
        print()


def iothub_client_sample_run() -> None:
    try:
        client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)

        message_listener_thread = threading.Thread(
            target=message_listener, args=(client,)
        )
        message_listener_thread.daemon = True
        message_listener_thread.start()

        while True:
            time.sleep(1000)

    except KeyboardInterrupt:
        print("IoT Hub C2D Messaging device sample stopped")


if __name__ == "__main__":
    print("Starting the Python IoT Hub C2D Messaging device sample...")
    print("Waiting for C2D messages, press Ctrl-C to exit")

    iothub_client_sample_run()

```

`SendCloudToDeviceMessage.py`

```
import random
import sys
from azure.iot.hub import IoTHubRegistryManager
from azure.identity import EnvironmentCredential

# from azure.common.credentials import ServicePrincipalCredentials
import os

MESSAGE_COUNT = 2
AVG_WIND_SPEED = 10.0
MSG_TXT = '{"service client sent a message": %.2f}'

CONNECTION_STRING = "CONN_STRING_HERE"
DEVICE_ID = "myDevice"


credential = EnvironmentCredential()


def iothub_messaging_sample_run():
    try:
        # Create IoTHubRegistryManager

       # This works.
        """registry_manager = IoTHubRegistryManager.from_connection_string(
            connection_string=CONNECTION_STRING
        )"""

       # This does not
        registry_manager = IoTHubRegistryManager.from_token_credential(
            url="azure-simlab1.azure-devices.net",
            token_credential=EnvironmentCredential(),
        )

        for i in range(0, MESSAGE_COUNT):
            print("Sending message: {0}".format(i))
            data = MSG_TXT % (AVG_WIND_SPEED + (random.random() * 4 + 2))

            props = {}
            # optional: assign system properties
            props.update(messageId="message_%d" % i)
            props.update(correlationId="correlation_%d" % i)
            props.update(contentType="application/json")

            # optional: assign application properties
            prop_text = "PropMsg_%d" % i
            props.update(testProperty=prop_text)

            registry_manager.send_c2d_message(DEVICE_ID, data, properties=props)

        try:
            # Try Python 2.xx first
            raw_input("Press Enter to continue...\n")
        except:
            pass
            # Use Python 3.xx in the case of exception
            input("Press Enter to continue...\n")

    except Exception as ex:
        print("Unexpected error {0}" % ex)
        return
    except KeyboardInterrupt:
        print("IoT Hub C2D Messaging service sample stopped")


if __name__ == "__main__":
    print("Starting the Python IoT Hub C2D Messaging service sample...")

    iothub_messaging_sample_run()

```

**Comment by vishnureddy17** [comment]
> In the case of (a); I see the following confirmation
> 
> ```
> Starting C2D feedback monitor, filtering on device: myDevice, use ctrl-c to stop...
> feedback:
>   description: Success
>   deviceGenerationId: 'Some device ID'
>   deviceId: myDevice
>   enqueuedTimeUtc: '2021-07-28T16:15:29.741147Z'
>   originalMessageId: SOme Message ID
>   statusCode: Succes
> ```
Where did this confirmation come from? I don't see where it could have come from in `SimulatedDevice.py` or `SendCloudToDeviceMessage.py`. Or did you mean "in the case of (c)"?

I went ahead and tried the specific files you sent me, and in case (b), I am able to see the messages on `SimulatedDevice.py`

Here are some things you can try:
- [ ] Check that the service principal associated with your `AZURE_SUBSCRIPTION_ID`, `AZURE_CLIENT_SECRET`, and `AZURE_TENANT_ID` values have the correct role on your IoT Hub to send C2D messages
- [ ] Check that the environment variables are actually set when running the program, and that there are no typos in the variables
- [ ] Check that your IoT Hub hostname corresponds to the hub that actually has a role assignment for your service principal

**Comment by sgoyal1012** [comment]
> Or did you mean "in the case of (c)"?

Yes, I meant (c) -- the command line option.
Thanks for the checklist; I will try it out.

[] Check that the service principal associated with your AZURE_SUBSCRIPTION_ID, AZURE_CLIENT_SECRET, and AZURE_TENANT_ID values have the correct role on your IoT Hub to send C2D messages
We have the following roles -- `IoT Hub Data Contributor` and `IoT Hub Registry Contributor` -- *are these correct* ?

[x] Check that the environment variables are actually set when running the program, and that there are no typos in the variables

yes, this I re-checked. If I miss any of the variables; I get this warning

```
Incomplete environment configuration. These variables are set: AZURE_CLIENT_ID, AZURE_CLIENT_SECRET
```
[] Check that your IoT Hub hostname corresponds to the hub that actually has a role assignment for your service principal
We have given the service principal this role assignment across the whole subscription (since we plan to have multiple IoT hubs); is that alright?

Thanks!

**Comment by sgoyal1012** [comment]
Also, could you confirm if what I have highlighted is the correct parameter to pass for the `url` option?

![Azure](https://user-images.githubusercontent.com/7093391/127536262-b2fb59a2-7ff3-476a-b09c-2716c15b4c97.jpg)

**Comment by vishnureddy17** [comment]
> We have the following roles -- `IoT Hub Data Contributor` and `IoT Hub Registry Contributor` -- _are these correct_ ?

Yes, IoT Hub Data Contributor should be sufficient.

> We have given the service principal this role assignment across the whole subscription (since we plan to have multiple IoT hubs); is that alright?

Yes, that should not be a problem. As long you go to your IoT Hub in the portal and see the role assignment for your service principal in the role assignments list (see image), then you should be good there.
![image](https://user-images.githubusercontent.com/30186564/127540846-bea3fb1d-27fd-4d9b-935a-b61e44a403b9.png)

> Also, could you confirm if what I have highlighted is the correct parameter to pass for the `url` option?

Looks good there.

Based on the logs you sent, it seems like the service is accepting the C2D messages without giving an error in case (b). This makes me think that the messages are getting sent _somewhere_. As a sanity check, can you check that the device id and hub you are using in `SimulatedDevice.py` and `SendCloudToDeviceMessage.py` match? (on the device side, you can see the the device id and hub hostname in the connection string)

**Comment by sgoyal1012** [comment]
> Based on the logs you sent, it seems like the service is accepting the C2D messages without giving an error in case (b)

I agree with your hunch.

I checked the role assignments as you mentioned; and they look good. (good tip there! I was not aware of this)
![Screenshot from 2021-07-29 18-25-37](https://user-images.githubusercontent.com/7093391/127585970-a11a7e7f-97c2-441d-ab9f-bb5ab5e4fbdb.png)

>  As a sanity check, can you check that the device id and hub you are using in SimulatedDevice.py and SendCloudToDeviceMessage.py match?

Checked; and I validate with the connection string authentication method that this is okay.

### Next steps to try

I do not have the privileges in my org to do so; I am going to work with someone who has to bounce the client secret and see if that helps.

**Comment by vishnureddy17** [comment]
Please do let me know if that solves your issue! @sgoyal1012

**Comment by vishnureddy17** [comment]
Would it be possible for you to give yourself the IoT Hub Data Contributor role, logging into Azure CLI, and then trying `AzureCliCredential` instead of `EnvironmentCredential`? That's another thing that could help narrow the issue down. 

Apologies for not being able to figure this out yet—this issue is strange.

**Comment by sgoyal1012** [comment]
Thanks for your help @vishnureddy17 ! really appreciate you taking out the time and helping us this; you are right, this issue is strange :) -- we did something similar for our EventHubs and it seems to work fine there (with the same `EnvironmentCredentials`)

-------------
> Would it be possible for you to give yourself the IoT Hub Data Contributor role, log into Azure CLI, and then try AzureCliCredential instead of EnvironmentCredential? 

Will do that; I believe I should already have this role; as I am able to send a C2D message using the CLI as I mentioned earlier.

**Comment by sgoyal1012** [comment]
@vishnureddy17 we got a chance to try out what I mentioned, **but the problem still persists unfortunately**

Here is what we tried

* Using `EnvironmentCredentials` with a new SP, scoped as an `IoT Hub Data Contributor` on the entire subscription;
* Then the same SP to be scoped on the particular IoT hub.
* The `AzureCliCredentials` method

In all three cases; it is the same behavior; the application does not seem to send any messages. In the CLI case, its weird because the `az iot device c2d-message send` works well.

Here is the screenshot from the IAM tab
![Screenshot from 2021-07-30 13-24-05](https://user-images.githubusercontent.com/7093391/127711294-dbac1e91-f243-421f-a7d7-cf557977d220.png)

I also made sure the device ID etc is correct; by using CLI and connection string; I see the following metric being updated

![Screenshot from 2021-07-30 13-52-36](https://user-images.githubusercontent.com/7093391/127711370-f4a4a63b-2da7-4b82-ba77-7e1a43a74933.png)

----

I will go ahead and let you know the specific library versions I am using; maybe this could help us diagnose.

```
python3.8 --version
Python 3.8.9

pip3 freeze | grep -i 'azure'                           
azure-common==1.1.27
azure-core==1.16.0
azure-identity==1.6.0
azure-iot-device==2.7.1
azure-iot-hub==2.4.0
```

*Is there any other information I can provide you that may be useful?*

Thanks again! Really appreciate you looking into this.

**Comment by sgoyal1012** [comment]
I see the latest version at the pip registry is dating May 5 -- https://pypi.org/project/azure-iot-hub/#history

and the latest here is from Jun 18 -- https://github.com/Azure/azure-iot-sdk-python/tags

Do you think this could be a potential issue; that you and I are using different versions?

**Comment by vishnureddy17** [comment]
That is because the latest version of `azure-iot-hub` (service client) is May 5th, but the latest version of `azure-iot-device` (device client) is June 18th. 

I will try to match your version numbers exactly and run the sample again tomorrow,

**Comment by vishnureddy17** [comment]
@sgoyal1012, what version of uamqp are you using?

**Comment by vishnureddy17** [comment]
Ah, I'm able to reproduce this now. Need some time to investigate

**Comment by vishnureddy17** [comment]
> Do you think this could be a potential issue; that you and I are using different versions?

You're right. We just never made a release since we added support for AMQP operations with TokenCredential authentication 🤦‍♂️

We will probably make a release soon, I'll keep you posted.

**Comment by sgoyal1012** [comment]
Hi @vishnureddy17 thanks a lot for your analysis, glad we were able to figure this out!
--------
> We will probably make a release soon, I'll keep you posted.

Thanks! Do you want me to keep the ticket open?

**Comment by vishnureddy17** [comment]
> Thanks! Do you want me to keep the ticket open?
Yeah, let's leave it open until we make the release and you can confirm that that the issue is resolved.

**Comment by vishnureddy17** [comment]
@sgoyal1012 , please update your azure-iot-hub to version 2.5.0. Then you should be able to send the messages. Please let me know if this resolves it, thanks!

**Comment by sgoyal1012** [comment]
@vishnureddy17 that worked! Thanks for the quick turnaround, really appreciate it :)

Here is the code that worked

```
credential = EnvironmentCredential()
registry_manager = IoTHubRegistryManager.from_token_credential(
    url="azure-simlab1.azure-devices.net",
    token_credential=credential,
)
```
