### ISSUE TITLE
Using custom topics and listeners for MQTT on IoT Hub.

### ISSUE THREAD

**Issue by gitnwana** [Azure/azure-iot-sdk-python#832]
Hi ,

We are trying to use Azure IoT Hub as an MQTT Broker for a project. Following this [link](https://docs.microsoft.com/en-us/azure/iot-hub/iot-hub-mqtt-support).
We understand that Azure IOT Hub  is not a full replacement for a MQTT Broker,  however, we noticed that we can only send messages to topic - ""devices/" + device_id + "/messages/events/". Also , when we try to connect multiple listeners to same MQTT Endpoint, they keep connecting and disconnecting until we keep the max listeners to "1". 

Is there any configuration that we need to change so the IOT Hub is able to publish to a custom topic  and have more than a single listener?

Thanks

**Comment by BertKleewein** [comment]
Hi @gitnwana, your observations describe exactly how the IoTHub broker is designed to work.  There is currently no way to work around these limitations..  The IoTHub service may be enabling features like you describe in the future.

**Comment by anthonyvercolano** [comment]
Question answered and inactivity.
