### ISSUE TITLE
Invalid azure.core in install_requires for azure-iot-hub

### ISSUE THREAD

**Issue by fvdnabee** [Azure/azure-iot-sdk-python#841]
Line 75 of azure-iot-hub's setup.py lists 'azure.core' as an install requires, but this isn't a valid package identifier: 
https://github.com/Azure/azure-iot-sdk-python/blob/ed78f86a8d2dfbfbba8c9af59125a00c11851d95/azure-iot-hub/setup.py#L75

poetry show lists azure.core as a missing package for my project which uses azure-iot-hub 2.5.0 as a dependency.

This change was introduced [here](https://github.com/Azure/azure-iot-sdk-python/pull/757/commits/7444bf6cae53a0fa699b7df6b8ad8c64f6d5af14) and has been released since v2.4.0. While replacing `azure.core` with `azure-core` would fix this issue, azure-iot-hub should also specify a version constraint for azure-core.

Please update the install_requires in setup.py to fix this issue.

**Comment by cartertinney** [comment]
Thanks for pointing this out. We'll get this fixed shortly.

**Comment by cartertinney** [comment]
Tracked in #842

**Comment by cartertinney** [comment]
Fix is checked in, will be part of the next release

**Comment by cartertinney** [comment]
Fix has been released as part of the 2.6.0 release, available now.

Please let us know if this has addressed your issue.
