### ISSUE TITLE
Command and links are not correct in readme.md

### ISSUE THREAD

**Issue by MadhavPK** [Azure/azure-iot-sdk-python#842]
# Context

- **OS and version used:** <VERSION>Windows 10
- **Python version:** <VERSION>3.9.6
- **pip version:** <VERSION> 21.2.4 
- **list of installed packages:** <VERSION>
Package | Version
--- | ---
azure-core | 1.17.0
azure-iot-device |  2.7.1
azure-iot-hub |2.5.0
certifi |2021.5.30
charset-normalizer | 2.0.4
deprecation | 2.1.0
idna |3.2
isodate | 0.6.0
janus |0.4.0
msrest | 0.6.21
oauthlib | 3.1.1
packaging |   21.0
paho-mqtt |   1.5.1
pip |21.2.4
pyparsing |    2.4.7
PySocks |  1.7.1
requests | 2.26.0
requests-oauthlib | 1.3.0
requests-unixsocket | 0.2.0
setuptools | 56.0.0
six |1.16.0
uamqp |    1.4.1
urllib3 | 1.26.6

## Description of the issue

@file: Readme.md
1. Under Quick Start - Simple Telemetry Sample (send message) Step 3
Link in the hyper linked text gives 404 - Page not found
This gives error
  `az iot hub device-identity show-connection-string --device-id <your device id> --hub-name <your IoT Hub name>`
Correct Command is
  `az iot hub device-identity connection-string show --device-id <your device id> --hub-name <your IoT Hub name>`

2.  Step 4
  Link in the hyper linked text gives 404 - Page not found

**Comment by anthonyvercolano** [comment]
Thank you.

**Comment by cartertinney** [comment]
Addressed in #845
