### ISSUE TITLE
Ability for the app to read the connection status from the SDK while in WAITING_TO_RECONNECT state. 

### ISSUE THREAD

**Issue by pchevallier** [Azure/azure-iot-sdk-python#846]
During normal condition, the  client device is connected to the iotHub and we transmit data as needed. We also receive Device Twin patch update whenever required. 

From time to time, we lose the connection (ex WiFi out of range). An error message from the SDK is displyed on the output device. 
The message reads:
_ReconnectStage: DisconnectEvent received while in unexpected state - WAITING_TO_RECONNECT, Connected: False_

Once the network is again available, the client eventually re-establishes the connection. All is well but we face a problem, especially when the disconnection last a very long period of time.
In order to take some disposition on the client side, it would be nice to know when the connection is "False". 

ideally, we should be able to check the connection state from the IoTHubDeviceClient

### Exemple: 
`IoTHubDeviceClient.isConnected()`
which would return a boolean value `True` or `False` based on the "Connected" state. 

Having this information would allow the application to buffer the MQTT messages until the connection is restored. 

### Alternative:
One alternative is connect and disconnect each time I need to send a message. That works, but not a full feature solution since it prevents from receiving ioTHub Device Twin Patch  events.

**Comment by cartertinney** [comment]
@pchevallier

Good news - the feature you ask for already exists. It is not a method, but an attribute you can check: `.connected`

e.g.

```python
client = IotHubDeviceClient.create_from_connection_string("<your conn string>")
client.connect()

assert client.connected
```

Another option you may be interested in is using the `.on_connection_state_change` handler. You can define a function or coroutine yourself, and set it to the above attribute on the client. Your function will be called each time that the client connects or disconnects.

e.g.

```python
client = IotHubDeviceClient.create_from_connection_string("<your conn string>")

def on_connection_state_change():
    if client.connected:
        print("Connected!")
    else:
        print("Disconnected!")

client.on_connection_state_change = on_connection_state_change
```

Do note however that no matter which way you go about it, if a connection drops it will take the client a short while to detect that this is the case (by default 60 seconds). You can modify this by providing a value (in seconds) to the optional `keep_alive` parameter at client instantiation

**Comment by pchevallier** [comment]
Thanks @cartertinney, that definitely fits the purpose. 

Perhaps that could be documented accordingly in here: 
https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.iothubdeviceclient?view=azure-python

**Comment by cartertinney** [comment]
It is documented there, under the "attributes" section.
