### ISSUE TITLE
Are there some ways to retrieve options?

### ISSUE THREAD

**Issue by SLdragon** [Azure/azure-iot-sdk-python#86]
Hi, team,
I found that in the python SDK, there are SetOption method in the iothub_client_python, however, there are no GetOption method. 

Are there some ways to retrieve options, because I need to retrieve the original  "product_info" string.

Thanks a lot.

**Comment by zolvarga** [comment]
Hi @SLdragon,

Currently we don't have GetOption API exposed in the underlying C SDK, therefore Python SDK does not have it.

Best Regards,
Zoltan

**Comment by SLdragon** [comment]
Thanks @zolvarga :
In the c sdk, there is the IoTHubClient_LL_GetOption function in the iothub_client_ll.c. Do you mean the Python sdk will not expose API in this file, it only expose API in the iothub_client.c?

**Comment by zolvarga** [comment]
@SLdragon 

Yes, you are right. I created a work item to create a convenience API.

Zoltan
