### ISSUE TITLE
How read All the IOT HUB devices C2D messages in python

### ISSUE THREAD

**Issue by asayeedi** [Azure/azure-iot-sdk-python#860]
In azure IOT Hub, I have multiple IoT Edge devices and I want to read all the cloud to device messages in python. I am unable to find the way how to read all the devices messages from cloud to device. I have tried paho.mqtt and azure.iot.device.aio, it works perfect for the one device.

Please suggest how to achieve this in Azure using Python.

**Comment by anthonyvercolano** [comment]
@asayeedi, I'm a bit unclear about your question.  A device client can ONLY read messages sent to that device id.

**Comment by asayeedi** [comment]
> @asayeedi, I'm a bit unclear about your question. A device client can ONLY read messages sent to that device id.

Hi Anthony,

I have an API, from where I get the list of all IoT Edge devices with their connection strings and I want to use these details for reading their C2D messages for all the devices using python IoTHubDeviceClient.

Please suggest how to achieve this.

**Comment by cartertinney** [comment]
@asayeedi 

The client is intended to represent a single device - you cannot simply use all your connection strings from all devices on a single device. The idea is that on each device you run an instance of the client, and run device-specific application code there.

If you are using Edge (which it sounds like you are), perhaps you could dedicate a module to processing messages received from all devices, and create a route whereby all devices will send their received messages to the message processing module?

**Comment by asayeedi** [comment]
Hi Carter,

Basically I want to get the data from the devices, which is received from the cloud every time for every devices.
Using all the devices connection string in client is not the correct way.
So, could you please explain or share some examples for implementing this what you explained **_If you are using Edge (which it sounds like you are), perhaps you could dedicate a module to processing messages received from all devices, and create a route whereby all devices will send their received messages to the message processing module?_**

**Comment by cartertinney** [comment]
@danhellem should be able to provide some assistance in this regard

**Comment by asayeedi** [comment]
> @danhellem should be able to provide some assistance in this regard

Hi @danhellem,
My requirement is as I receive the connection string of each devices and the IoT hub name from the API and I want to get all the cloud to device messages in python. I am unable to find any way for doing this.

**Comment by asayeedi** [comment]
> @danhellem should be able to provide some assistance in this regard

Hi @danhellem,
My requirement is as I receive the connection string of each devices and the IoT hub name from the API and I want to get all the cloud to device messages in python. I am unable to find any way for doing this.

**Comment by danhellem** [comment]
@asayeedi just to make sure I understand what you are trying to do. Is this picture accurate?

![image](https://user-images.githubusercontent.com/10525048/135868690-93802bbd-7c6a-49c9-a648-3f58af2f05d1.png)

1. you have many devices
2. C2D message is sent from Azure to a device
3. you want to track every message that is sent to the each device?

**Comment by asayeedi** [comment]
@danhellem
Yes, I want to read every messages sent to each device

**Comment by asayeedi** [comment]
> @asayeedi just to make sure I understand what you are trying to do. Is this picture accurate?
> 
> ![image](https://user-images.githubusercontent.com/10525048/135868690-93802bbd-7c6a-49c9-a648-3f58af2f05d1.png)
> 
> 1. you have many devices
> 2. C2D message is sent from Azure to a device
> 3. you want to track every message that is sent to each device?

@danhellem
Yes, I want to read every messages sent to each device

**Comment by asayeedi** [comment]
@danhellem Yes I want read messages that is sent to many devices from Azure

**Comment by danhellem** [comment]
The easiest path, if you control the C2D message, you could just wait for the device response and then log it.

if you don't control who is sending the device a message, you could then add extra code on device to log the message to a external service. This may or may not work for you. 

Finally, you could use an IoT Edge module and have that be used as a pass thru between Azure and the device. That IoT Edge module could then look at the messages, send them to the right devices, and also log the message.

![image](https://user-images.githubusercontent.com/10525048/135873683-3c3043e7-aeb5-4c19-8870-75e925cfa5d1.png)

**Comment by asayeedi** [comment]
@danhellem 
I am unable to find any example/blogs to implement the way you suggested **_Finally, you could use an IoT Edge module and have that be used as a pass thru between Azure and a set of devices. That IoT Edge module could then look at the messages, send them to the right devices, and also log the message._**

Could you please explain or share some examples/links for implementing this. This is what I asked to **cartertinney** after that he assign this to you.

**Comment by danhellem** [comment]
@asayeedi yeah it looks like I misspoke. I just checked with the owners of IoT Edge and C2D is not supported yet in edge modules. So it looks like the first 2 are the only feasible options right now. Sorry for the ooops

**Comment by danhellem** [comment]
@asayeedi I did some more digging. It looks like you can do a DM from Edge Module to a leaf device. There is an example here.

https://github.com/AzureIoTGBB/azure-iot-edge-hol-linux

But I don't think a C2D message works

**Comment by asayeedi** [comment]
@danhellem  If I call below function with devices connection string on loop and If I send data from Device Explorer Twin sometime it receives the message but most of the time it didn't, even after the loop restart for each devices it didn't receive the message. Is it the correct way or it need some changes, Please suggest

`async def main(con_str):
    try:
        conn_str = con_str
        device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)
        await device_client.connect()

        def message_received_handler(message):
            print("the data in the message received was ")
            print(message.data)
            print("custom properties are")
            print(message.custom_properties)
            print("content Type: {0}".format(message.content_type))
            print("")

        device_client.on_message_received = message_received_handler
        await device_client.shutdown()`

**Comment by danhellem** [comment]
if you are looking for samples to receive a message, these should help. I have not seen any instances of the devices not receiving messages. If you still run into the issue let me know and I can go investigate.

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/receive_direct_method.py

https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/receive_message.py

**Comment by asayeedi** [comment]
@danhellem 
I wanted to confirm one thing that if I send a message from the Device Explorer Twin and after that I execute below code `python receive_message.py`. Then in this case it will print the message in console or not?

In my case if I send the message from Device Explorer Twin and after sending the message, I execute below code but I didn't receive the message in console but after executing the code,  Device Explorer Twin shows Output: _Message Feedback status: "Success", Description: "Success", Original Message Id: b0e69bfc-1e84-4a31-9d18-ddasdb7b6d432_

`import os
import asyncio
from six.moves import input
import threading
from azure.iot.device.aio import IoTHubDeviceClient


async def main():
    # The connection string for a device should never be stored in code. For the sake of simplicity we're using an environment variable here.
    conn_str = os.getenv("IOTHUB_DEVICE_CONNECTION_STRING")
    # The client object is used to interact with your Azure IoT hub.
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)

    # connect the client.
    await device_client.connect()

    # define behavior for receiving a message
    # NOTE: this could be a function or a coroutine
    def message_received_handler(message):
        print("the data in the message received was ")
        print(message.data)
        print("custom properties are")
        print(message.custom_properties)
        print("content Type: {0}".format(message.content_type))
        print("")

    # set the mesage received handler on the client
    device_client.on_message_received = message_received_handler

    # define behavior for halting the application
    def stdin_listener():
        while True:
            selection = input("Press Q to quit\n")
            if selection == "Q" or selection == "q":
                print("Quitting...")
                break

    # Run the stdin listener in the event loop
    loop = asyncio.get_running_loop()
    user_finished = loop.run_in_executor(None, stdin_listener)

    # Wait for user to indicate they are done listening for messages
    await user_finished

    # Finally, shut down the client
    await device_client.shutdown()


if __name__ == "__main__":
    asyncio.run(main())`
