### ISSUE TITLE
Problem defining a proxy option

### ISSUE THREAD

**Issue by xiangyan99** [Azure/azure-iot-sdk-python#873]
This is reported by a customer @eng-khaled1 in azure-sdk-for-python repo:

---

Hello,

I am trying to configure a proxy option for the IOThubDeviceclient as suggested in the documentation:
client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING, proxy_options=( 'SOCKS5' , 'http://**.***.***.***', '8883', None, None))

but I keep getting the error message

AttributeError: 'tuple' object has no attribute 'proxy_type'

i would be very thankfull if you could help me on it

im using azure-iothub-device-client 1.4.6 library

**Comment by eng-khaled1** [comment]
Hi there, 
thanks a lot for your support 
i installed azure-iot-device    2.8.0 but am  still getting the same error

**Comment by eng-khaled1** [comment]
@cartertinney, 

yes, many many thanks.
