### ISSUE TITLE
[Technical Question] Is there any way to know from device side after authentication if a device is already connected ?

### ISSUE THREAD

**Issue by MrVhek** [Azure/azure-iot-sdk-python#878]
Hello,

With my company we're trying to use IoT Hub to develop a solution where basically there will be gateways that will connects to bluetooth peripherals from times to time (if on range and there is something to do with). 

For that purpose, we've designed a solution where we will have a IoT Hub device per gateway and one per bluetooth peripheral. The problem is that sometimes, two gateways will see the same bluetooth peripheral and attempt to connect to the same device at the same time.

What I've seen is that the two devices are constantly reconnecting to the hub. What I would like to have is an indicator that will, after authentication tell me if there is already another connection to this device. Is there such an option available ?

Thanks for your help

**Comment by cartertinney** [comment]
There is an attribute on the client called `.connected` that can tell you the connection status.

e.g.

```python
client = IoTHubDeviceClient.create_from_connection_string("<your string>")
client.connect()
if client.connected:
    # do things
```

**Comment by MrVhek** [comment]
This indicator is not the best because the device keep disconnecting and reconnecting and so it changes over time but I can use it like this:

```
    # Connect the device to the flux
    async def connect_device(self):
        connection = await self.device_client.connect()
        tries: int = 30
        nb_disconnected: int = 0
        for i in range(tries):
            sleep(0.1)
            if not self.device_client.connected:
                nb_disconnected += 1
        self.__logger.info(f"Authenticating {self.device_id}: disconnected {nb_disconnected} times")
        if nb_disconnected > 0:
            self.__logger.info(f"Authenticating {self.device_id}: raising DeviceAlreadyConnected")
            await self.device_client.shutdown()
            raise DeviceAlreadyConnected()
        return connection
```
I don't know if this is the best way but it seems to work. Do there is a retry policy that we can associate with the connect ?

Thanks for your help

**Comment by cartertinney** [comment]
Currently we don't support automatic retry of the `.connect()` operation. However, when a device becomes successfully connected, and then later the connection is dropped for some reason (intermittent network failure, for example), it will automatically try and reconnect by default. This is likely what you are seeing.

You can turn this behavior off if you want to control connection completely manually by adding `connection_retry=False` as a keyword argument to whichever factory method you are using to create the client (e.g. `create_from_connection_string`).
