### ISSUE TITLE
error with iothub_client_python.cpp python/converter/registered.hpp

### ISSUE THREAD

**Issue by dvescovi1** [Azure/azure-iot-sdk-python#88]
- **OS and version used:** <windows 10 32bit> 

- **Python runtime used:** <3.4> 

- **SDK version used:** <10-30-2017> 

# Description of the issue:

I am getting this error when compiling iothub_client_python.cpp.
I am not sure how to clear it.
# Code sample exhibiting the issue:

# Console log of the issue:

------ Rebuild All started: Project: iothub_client_python, Configuration: Debug Win32 ------
  Building Custom Rule C:/IoT/azure-iot-sdk-python/device/iothub_client_python/src/CMakeLists.txt
  CMake does not need to re-run because C:/Users/dvesc/cmake_Win32/python/src/CMakeFiles/generate.stamp is up-to-date.
  iothub_client_python.cpp
  NOTE: Use of this header (ice_or.hpp) is deprecated
  NOTE: Use of this header (ice_and.hpp) is deprecated
  NOTE: Use of this header (ice_not.hpp) is deprecated
  NOTE: Use of this header (ice_eq.hpp) is deprecated
C:\boost_1_60_0\boost/python/converter/registered.hpp(93): error C2672: 'boost::python::converter::detail::registry_lookup2': no matching overloaded function found
  C:\boost_1_60_0\boost/python/converter/registered.hpp(104): note: see reference to function template instantiation 'const boost::python::converter::registration &boost::python::converter::detail::registry_lookup1<void>(boost::type<void>)' being compiled
  C:\boost_1_60_0\boost/python/converter/registered.hpp(104): note: while compiling class template static data member 'const boost::python::converter::registration &boost::python::converter::detail::registered_base<boost::add_reference<volatile const void>::type>::converters'
  C:\boost_1_60_0\boost/python/converter/registered.hpp(44): note: see reference to class template instantiation 'boost::python::converter::detail::registered_base<boost::add_reference<volatile const void>::type>' being compiled
  C:\boost_1_60_0\boost/python/converter/registered_pointee.hpp(26): note: see reference to class template instantiation 'boost::python::converter::registered<void>' being compiled
  C:\boost_1_60_0\boost/python/converter/arg_to_python.hpp(215): note: see reference to class template instantiation 'boost::python::converter::registered_pointee<Ptr>' being compiled
          with
          [
              Ptr=METHOD_HANDLE
          ]
  C:\boost_1_60_0\boost/python/converter/arg_to_python.hpp(215): note: while compiling class template member function 'boost::python::converter::detail::pointer_deep_arg_to_python<T>::pointer_deep_arg_to_python(Ptr)'
          with
          [
              T=METHOD_HANDLE,
              Ptr=METHOD_HANDLE
          ]
  C:\boost_1_60_0\boost/python/converter/arg_to_python.hpp(256): note: see reference to function template instantiation 'boost::python::converter::detail::pointer_deep_arg_to_python<T>::pointer_deep_arg_to_python(Ptr)' being compiled
          with
          [
              T=METHOD_HANDLE,
              Ptr=METHOD_HANDLE
          ]
  C:\boost_1_60_0\boost/python/converter/arg_to_python.hpp(256): note: while compiling class template member function 'boost::python::converter::arg_to_python<A2>::arg_to_python(const T &)'
          with
          [
              A2=METHOD_HANDLE,
              T=METHOD_HANDLE
          ]
  C:\boost_1_60_0\boost/python/call.hpp(62): note: see reference to function template instantiation 'boost::python::converter::arg_to_python<A2>::arg_to_python(const T &)' being compiled
          with
          [
              A2=METHOD_HANDLE,
              T=METHOD_HANDLE
          ]
  C:\boost_1_60_0\boost/python/call.hpp(65): note: see reference to class template instantiation 'boost::python::converter::arg_to_python<A2>' being compiled
          with
          [
              A2=METHOD_HANDLE
          ]
  C:\boost_1_60_0\boost/python/object_call.hpp(19): note: see reference to function template instantiation 'boost::python::api::object boost::python::call<obj,A0,A1,A2,A3>(PyObject *,const A0 &,const A1 &,const A2 &,const A3 &,boost::type<obj> *)' being compiled
          with
          [
              A0=std::string,
              A1=std::string,
              A2=METHOD_HANDLE,
              A3=boost::python::api::object
          ]
  C:\IoT\azure-iot-sdk-python\device\iothub_client_python\src\iothub_client_python.cpp(1099): note: see reference to function template instantiation 'boost::python::api::object boost::python::api::object_operators<boost::python::api::object>::operator ()<std::string,std::string,METHOD_HANDLE,boost::python::api::object>(const A0 &,const A1 &,const A2 &,const A3 &) const' being compiled
          with
          [
              A0=std::string,
              A1=std::string,
              A2=METHOD_HANDLE,
              A3=boost::python::api::object
          ]
  C:\IoT\azure-iot-sdk-python\device\iothub_client_python\src\iothub_client_python.cpp(1099): note: see reference to function template instantiation 'boost::python::api::object boost::python::api::object_operators<boost::python::api::object>::operator ()<std::string,std::string,METHOD_HANDLE,boost::python::api::object>(const A0 &,const A1 &,const A2 &,const A3 &) const' being compiled
          with
          [
              A0=std::string,
              A1=std::string,
              A2=METHOD_HANDLE,
              A3=boost::python::api::object
          ]
C:\boost_1_60_0\boost/python/converter/registered.hpp(93): error C2784: 'const boost::python::converter::registration &boost::python::converter::detail::registry_lookup2(T &(__cdecl *)(void))': could not deduce template argument for 'T &(__cdecl *)(void)' from 'void (__cdecl *)(void)'
  C:\boost_1_60_0\boost/python/converter/registered.hpp(83): note: see declaration of 'boost::python::converter::detail::registry_lookup2'
========== Rebuild All: 10 succeeded, 1 failed, 0 skipped ==========

**Comment by zolvarga** [comment]
@dvescovi1,

Thanks for using our SDKs and reporting this issue.
We are going to take a look at it.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
Closing as no repro and no activuty.

**Comment by dvescovi1** [comment]
pretty easy to reproduce when trying to build against python 3.4 as stated

**Comment by leandrorr2017** [comment]
I'm having exactly the same issue trying to compile the sdk. Using VS 2017 with VS 2015 building tools (Install option), Python 3.6.3, Windows 7 x64. I would suggest to re-open this issue.
