### ISSUE TITLE
Device feedback not working in service sample

### ISSUE THREAD

**Issue by msebolt** [Azure/azure-iot-sdk-python#89]
Hello,

I am able to successfully run the sample, send the messages, invoke both the open and send confirmation callback functions, but the feedback callback is never called.  The sample I'm referring to is 'iothub_messaging_sample.py'.  

Am I missing something?  I am running the service sample as-is out-of-box and have tried both Python 2.7 and 3.6 versions.

**Comment by zolvarga** [comment]
The feedback messages are sent by the server not immediately. The server does some processing and batching for the feedback messages. 
Please make sure you wait enough and you should get the feedback.

Best Regards,
Zoltan
