### ISSUE TITLE
[Technical Question] How to securely save DPS host and scope in device

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-python#896]
I see at this line https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-hub-scenarios/provision_x509.py#L15 the dps host is accesses from the env variables. Is it the secure way to save the credentials in env on a device or there is some other way to save credentials on a device?

**Comment by anthonyvercolano** [comment]
Actually, the value(s) referenced in the OP link are not particularly important secure information.  What should be treated as something to be protected are: https://github.com/Azure/azure-iot-sdk-python/blob/f91870e1ec666df4b850e175ecb3734eed149392/azure-iot-device/samples/async-hub-scenarios/provision_x509.py#L24 and the following line.

 Securing these secrets is a pretty big topic.  What is the OS support?  Is there hardware support on the device?  Here is one link: https://docs.microsoft.com/en-us/azure/iot-dps/concepts-device-oem-security-practices and another https://docs.microsoft.com/en-us/azure/iot-fundamentals/security-recommendations

I would say that the links I just provided should be the beginning of the research on how to secure your device.  There is a lot more material available.
 
  What is in the sample is simply a quick way to get started with the the device and dps provisioning.  It is NOT a production solution.

**Comment by amit12cool** [comment]
Thanks for the response. I understand that cert keys are something that we need to make sure are secured.
On the other hand, I see in the case of iot edge or say I'm using docker on my device where should the registry credentials be saved to fetch the docker images from say ACR.

**Comment by anthonyvercolano** [comment]
We as the SDK don't provide any mechanisms for secure storage of keys.  It SO much depends upon your particular hardware and OS.  Again I would suggest you explore some of the security publications that we've published and look at your OS documentation and whether you have some kind of secure element on your hardware.

**Comment by danhellem** [comment]
Closing this issue.
