### ISSUE TITLE
 Unable to find remote helper for 'https'

### ISSUE THREAD

**Issue by caenfuro** [Azure/azure-iot-sdk-python#9]
Hi I've been following the instructions to run the python samples that connect with Azure IoT Hub using an Arduino YUN. When I execute this line:

git clone --recursive https://github.com/Azure/azure-iot-sdk-python.git 

I always get this answer: "fatal: Unable to find remote helper for 'https' "

If I use "git" instead "https" it runs, but fails while it is cloning, this is the output taken from Putty:

root@FCP:~# git clone --recursive git://github.com/Azure/azure-iot-sdk-python.git
Cloning into 'azure-iot-sdk-python'...
remote: Counting objects: 36082, done.
remote: Compressing objects: 100% (49/49), done.
remote: Total 36082 (delta 15), reused 0 (delta 0), pack-reused 36031
Receiving objects: 100% (36082/36082), 39.13 MiB | 263 KiB/s, done.
Resolving deltas: 100% (21810/21810), done.
Checking out files: 100% (87/87), done.
git: 'sh-i18n--envsubst' is not a git command. See 'git --help'.
git: 'sh-i18n--envsubst' is not a git command. See 'git --help'.

Cloning into 'c'...
fatal: Unable to find remote helper for 'https'
git: 'sh-i18n--envsubst' is not a git command. See 'git --help'.
git: 'sh-i18n--envsubst' is not a git command. See 'git --help'.

Do I need to install some package in order to to find remote helper for 'https'???

**Comment by anporumb** [comment]
Helo @caenfuro,

We believe you should cross-compile for Arduino YUN and not run natively on YUN. We don't have examples for YUN, but we have for digi. This is the link for digi xbee gateway that we can point you to:

https://github.com/Azure/azure-iot-device-ecosystem/blob/ae2c29c41a1e207855a9b2de16bb919e74eb0c50/get_started/digi-xbee-gateway-python.md

While not tied to your Linux distro, there should be some useable information in there for you.

Best Regards,
Andrei Porumb

**Comment by caenfuro** [comment]
Thanks for your answer, I appreciate it.

Looking today at the Microsoft website [https://catalog.azureiotsuite.com/details?title=Arduino_Yun](url), I can see how they recommend cross-compile as you did in your last post. That's a recent change in the documentation, as many others that I've found while researching about this. What is the best way to get support if the new instructions fail in some point?
