### ISSUE TITLE
Issue changing from deprecated receive_message_on_input to on_message_received

### ISSUE THREAD

**Issue by mbrierley01** [Azure/azure-iot-sdk-python#900]
# Context

- **OS and version used:** Raspbian GNU/Linux 10
- **Python version:** 3.7.3
- **pip version:** pip 18.1

## Description of the issue

When changing away from deprecated receive_message_on_input to on_message_received module no longer receives incoming messages from another module giving reason "Error while receiving data: 'NoneType' object is not callable"

## Code sample exhibiting the issue

 while True:
                try:
                    LogInfo('Receiving input message...')
                    input_message = await module_client.on_message_received("input1")  # blocking call
                except Exception as ex:
                    LogInfo("Error while receiving data: %s" % ex)

## Console log of the issue

<6> 2021-11-08 17:54:28.000 -00:00 [INF] - IoT Hub Client for Python
<6> 2021-11-08 17:54:28.000 -00:00 [INF] - Version 0.1.7
<6> 2021-11-08 17:54:31.000 -00:00 [INF] - Getting Twin Properties
<6> 2021-11-08 17:54:33.000 -00:00 [INF] - The sample is now waiting for messages. 
<6> 2021-11-08 17:54:33.000 -00:00 [INF] - Checking for user input to quit
Press Q to quit
<6> 2021-11-08 17:54:33.000 -00:00 [INF] - Receiving input message...
<6> 2021-11-08 17:54:33.000 -00:00 [INF] - Error while receiving data: 'NoneType' object is not callable
<6> 2021-11-08 17:54:33.000 -00:00 [INF] - Decoding Message
<6> 2021-11-08 17:54:33.000 -00:00 [INF] - Failed To Decode: local variable 'input_message' referenced before assignment
No input message inbox for input1 - dropping message
No input message inbox for input1 - dropping message
<6> 2021-11-08 17:54:43.000 -00:00 [INF] - Checking for user input to quit
Press Q to quit
No input message inbox for input1 - dropping message
<6> 2021-11-08 17:54:53.000 -00:00 [INF] - Checking for user input to quit
Press Q to quit
No input message inbox for input1 - dropping message
<6> 2021-11-08 17:55:03.000 -00:00 [INF] - Checking for user input to quit
Press Q to quit
No input message inbox for input1 - dropping message
<6> 2021-11-08 17:55:13.000 -00:00 [INF] - Checking for user input to quit
Press Q to quit
No input message inbox for input1 - dropping message
<6> 2021-11-08 17:55:23.000 -00:00 [INF] - Checking for user input to quit
Press Q to quit
No input message inbox for input1 - dropping message

**Comment by cartertinney** [comment]
@mbrierley01

This is happening because you are trying to use the new client construct like the old API, but they function differently. The new handlers are like callbacks, rather than the poll-style API from before.

Please refer to [this sample](https://github.com/Azure/azure-iot-sdk-python/blob/master/azure-iot-device/samples/async-edge-scenarios/receive_data.py) to see an example of how to do it.

**Comment by mbrierley01** [comment]
@cartertinney Hi thank you for the response. I'm working through the samples sent currently, but wanted to ask does this mean the tutorial here: [https://docs.microsoft.com/en-us/azure/iot-edge/tutorial-python-module?view=iotedge-2020-11](url) is no longer valid? Is there a more up to date tutorial to be referenced in the future?

**Comment by cartertinney** [comment]
Yeah, that's correct. That sample is out of date - I thought I had updated them all, but clearly this one slipped through the gaps. I will get to work on fixing this sample now, but for the meantime look at the Edge samples in our repository (like the one I linked above) for how to implement the code itself.

**Comment by cartertinney** [comment]
@mbrierley01 

You should find that the tutorial from MS Docs has now been updated.
