### ISSUE TITLE
IoT Hub client reconnect

### ISSUE THREAD

**Issue by THULiusj** [Azure/azure-iot-sdk-python#91]
Hi, will the device client reconnect to IoT Hub after it is reconnected the Internet? and where to set this reconnect parameter in Python SDK?

**Comment by zolvarga** [comment]
@THULiusj 

The retry policy can be set using the "set_retry_policy / get_retry_policy" APIs.
See the documentation here:
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client.h#L181
https://github.com/Azure/azure-iot-sdk-c/blob/master/iothub_client/inc/iothub_client_ll.h#L41

Best Regards,
Zoltan
