### ISSUE TITLE
Overflow error 

### ISSUE THREAD

**Issue by jhanit-bh** [Azure/azure-iot-sdk-python#911]
When running azure-iot-sdk-python 2.9 i get the following error 
i am running Python 3.9 on Windows x64. the code still executes and the messages are sent but this error occurs every time.

IoTHub Device Client Recurring Telemetry Sample
Press Ctrl+C to exit
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Program Files\Python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large
Exception in thread Thread-6:
Traceback (most recent call last):
  File "C:\Program Files\Python39\lib\threading.py", line 954, in _bootstrap_inner
    self.run()
  File "C:\Users\jhanit\cleanbot\venv2\lib\site-packages\azure\iot\device\common\alarm.py", line 31, in run
    self.finished.wait(interval)
  File "C:\Program Files\Python39\lib\threading.py", line 574, in wait
    signaled = self._cond.wait(timeout)
  File "C:\Program Files\Python39\lib\threading.py", line 316, in wait
    gotit = waiter.acquire(True, timeout)
OverflowError: timeout value is too large

**Comment by danhellem** [comment]
@jhanit-bh I just got the latest on the repo and I am running the `async-hub-scenarios\send_message.py` and it is not producing any errors.

I am running python38.

can you confirm this is the same sample?

@cartertinney any reason why python39 would be an issue?

**Comment by jhanit-bh** [comment]
@danhellem  its the azure-iot-device/samples/sync-samples/recurring_telemetry.py example that I am running. Python 3.9.5 is the exact version. Also happens in python3.6

**Comment by danhellem** [comment]
@jhanit-bh hmmm, I just tested that out that as well and it seems to be working fine.

@cartertinney any thoughts?

**Comment by danhellem** [comment]
@jhanit-bh do you get the exceptions right away or does it take some time?

**Comment by jhanit-bh** [comment]
the exception is right away. 
setting a breakpoint before this line the value is site-packages\azure\iot\device\common\alarm.py the value of interval is 5458506.257889032

**Comment by cartertinney** [comment]
@jhanit-bh

Based on what you're saying, it seems that your SAS Tokens last about.... 63 days? Is this correct?

**Comment by jhanit-bh** [comment]
@cartertinney i am using the function IoTHubDeviceClient.create_from_sastoken(sas_token_str,  websockets=True) this function doesn't accept the sastoken_ttl keyword.

**Comment by cartertinney** [comment]
@jahnit-bh

I see. What is the TTL on the SAS Token you are passing in? Is it 63 days?

**Comment by jhanit-bh** [comment]
@cartertinney yes the token is valid for 63 days. expiry is set to 01.02.2022 00:27:45 GMT+01:00. the tokens were generated by a customer which has the iot hub instance setup.

**Comment by cartertinney** [comment]
@jhanit-bh 

It seems we don't properly support token TTLs of this length, whether customer provided or generated by the client itself from a connection string.

I'm going to investigate further and see if we can fix this.

**Comment by cartertinney** [comment]
@jhanit-bh

Would the customer be okay with the tokens being refreshed more than every 63 days? Their tokens are valid for 63 days, but is it okay for the client to replace one every 49 days?

**Comment by jhanit-bh** [comment]
@cartertinney In our case the device won't be online all the time but 49 days would also work.

**Comment by cartertinney** [comment]
This issue is tracked in #912

**Comment by cartertinney** [comment]
@jhanit-bh 

This fix for this issue in #912 has been merged to main branch and will be included in our next release
