### ISSUE TITLE
SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by gorleabhinav** [Azure/azure-iot-sdk-python#914]
hello, 
i am facing one weird issue, i am running python sdk on arm board. and trying to create device using azure provisioning services, device is being created in first 2-3 trails( once device created i am deleting it and again trying  to create it), after that when i tried to create again, getting below error:
```
transport.connect raised error
Traceback (most recent call last):
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 388, in connect
  File "usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 839, in connect
  File "usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 994, in reconnect
  File "usr/lib/python3.8/ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 182, in _run_op
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 401, in connect
azure.iot.device.common.transport_exceptions.TlsExchangeAuthError: TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')

ConnectOperation: completing with error TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')
ConnectionLockStage(ConnectOperation): op failed.  Unblocking queue with error: TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')
ConnectOperation: completing with error TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')
MQTTSubscribeOperation: completing with error TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')
EnableFeatureOperation: completing with error TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')
Callback completed with error TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')
NoneType: None

Traceback (most recent call last):
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 388, in connect
  File "usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 839, in connect
  File "usr/lib/python3.8/site-packages/paho/mqtt/client.py", line 994, in reconnect
  File "usr/lib/python3.8/ssl.py", line 1309, in do_handshake
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "usr/lib/python3.8/site-packages/azure/iot/device/provisioning/provisioning_device_client.py", line 25, in handle_result
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/evented_callback.py", line 70, in wait_for_completion
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/pipeline/pipeline_stages_mqtt.py", line 182, in _run_op
  File "usr/lib/python3.8/site-packages/azure/iot/device/common/mqtt_transport.py", line 401, in connect
azure.iot.device.common.transport_exceptions.TlsExchangeAuthError: TlsExchangeAuthError(None) caused by SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "device_register.py", line 107, in <module>
    azure_.register_device()
  File "device_register.py", line 64, in register_device
    registration_result = provisioning_device_client.register()
  File "usr/lib/python3.8/site-packages/azure/iot/device/provisioning/provisioning_device_client.py", line 69, in register
  File "usr/lib/python3.8/site-packages/azure/iot/device/provisioning/provisioning_device_client.py", line 92, in _enable_responses
  File "usr/lib/python3.8/site-packages/azure/iot/device/provisioning/provisioning_device_client.py", line 35, in handle_result
azure.iot.device.exceptions.ClientError: ClientError('Unexpected failure') caused by TlsExchangeAuthError(None)
```

i tried with updating certifi module ```pip install --upgrade certifi``` but still getting same error.

library:
using python 3.8.2
azure-common==1.1.27
azure-core==1.19.0
azure-iot-device==2.1.4
azure-servicebus==7.3.4
azure-storage-blob==12.3.1
pyOpenSSL==19.1.0

i am getting kind of stuck, any help would appreciated.

**Comment by cartertinney** [comment]
@gorleabhinav

A couple things:

1) Can you try updating to a more recent version of `azure-iot-device`? 2.1.4 is quite old, and we have made numerous improvements to stability since.

2) If the problem persists after updating, can you please post a sample of your code so we have some idea how your application is running?

3) Can you also try adding the following lines to the beginning of your application so we can see a log of the incident?

```python
import logging

logging.basicConfig(level=logging.DEBUG)
```

**Comment by gorleabhinav** [comment]
@cartertinney ,
i have updated modules on the board, still i am getting same error. i am attaching log file log.txt and code file(python file) azure_iot_device_register.txt

library version:
azure-common==1.1.27
azure-core==1.21.1
azure-iot-device==2.9.0
azure-servicebus==7.4.0
azure-storage-blob==12.9.0
[log.txt](https://github.com/Azure/azure-iot-sdk-python/files/7683263/log.txt)
[azure_iot_device_register.txt](https://github.com/Azure/azure-iot-sdk-python/files/7683273/azure_iot_device_register.txt)

**Comment by cartertinney** [comment]
@gorleabhinav 

I want to clarify a couple more things about your exact process here. This is my understanding, and correct me if I'm wrong

1) You run your application (`azure_iot_device_register.py`) and successfully register the device
2) You manually delete the device registration (via the Portal or some other tool)
3) You repeat steps 1 and 2 several times
4) On the fourth attempt, you begin generating the log that you provided in `log.txt`

Is this correct? Anything I'm missing?

**Comment by cartertinney** [comment]
@gorleabhinav

Having some trouble reproducing this issue still. Some follow up questions:

1) Are you using group or individual enrollments?
2) Are you using the same device certificate the entire time?
3) Are you only deleting the enrollment record or also the device from the IoTHub?

**Comment by gorleabhinav** [comment]
@cartertinney 
1. group enrollment.
2. I am using same certificate.
3. deleting from both.

**Comment by cartertinney** [comment]
@gorleabhinav 

I am still unable to reproduce. I have followed the steps you have provided exactly (including using your `azure_iot_device_register.py` code you provided) and am able to provision 10+ times in a row. I have tried variations as well, including individual enrollments rather than group, and modifying the device client logic.

I do not think the issue you are experiencing is related to the Python device SDK. I suspect whatever is going wrong has something to do with your instance of the Device Provisioning Service or the way in which it is configured. I suggest you raise the issue with them.

**Comment by olivakar** [comment]
@gorleabhinav some questions if they have not been clarified before : 

1. What kind of group enrollment record have you created ? ca certificate or intermediate certificate ?
2. Have you previously done a proof of possession of the ca certificate in your chain ?
