### ISSUE TITLE
Connection reset by peer but never recovers until restart.

### ISSUE THREAD

**Issue by robbinvandamme** [Azure/azure-iot-sdk-python#931]
# Context

- **OS and version used:** embedded linux
- **Python version:** python3.7
- **list of installed packages:** azure-iot-device==2.5.1

## Description of the issue

* application/iot-hub-device-client is working fine.
* iot-hub-connection gets dropped ([Errno 104] Connection reset by peer)
* iot-hub-connect never recovers
* rest calls to other servers in the same application still work
* iot-hub-connect recovered after we restarted the application

I have no way of reproducing this.
Could this be solved in the latest version?
Any idea what could be going on here?

## Console log of the issue

[github_log.txt](https://github.com/Azure/azure-iot-sdk-python/files/7943165/github_log.txt)

**Comment by cartertinney** [comment]
@robbinvandamme There have been significant improvements to connection stability since 2.5.1, so the first thing I would do is try updating it and seeing if the problem persists.

**Comment by robbinvandamme** [comment]
@cartertinney ok an updated was planned in the upcoming weeks. Lets hope it doesn't come back. 
thx!
