### ISSUE TITLE
on_message_received property not documented

### ISSUE THREAD

**Issue by nabeelmsft** [Azure/azure-iot-sdk-python#936]
## Description of the issue

When reading the documentation for receive_method_request method at https://docs.microsoft.com/python/api/azure-iot-device/azure.iot.device.aio.iothubmoduleclient?view=azure-python#azure-iot-device-aio-iothubmoduleclient-receive-method-request 
the following comment appears:
Deprecated since version 2.3.0: We recommend that you use the "on_method_request_received" property to set a handler instead

Looking at the same page, I did not see any documentation for "on_method_request_received" property. 

If "on_method_request_received" property is valid to option to code hen we should add documentation on the same page or if this not supported, then we should update the documentation accordingly.

![image](https://user-images.githubusercontent.com/54415789/151635486-5f8ab6a8-bb0f-4365-9807-157100eed425.png)

Content: [azure.iot.device.aio.IoTHubModuleClient](https://docs.microsoft.com/en-us/python/api/azure-iot-device/azure.iot.device.aio.iothubmoduleclient?view=azure-python) class
Content Source: docs-ref-autogen/azure-iot-device/azure.iot.device.aio.IoTHubModuleClient.yml
Product: azure-iot
GitHub Login: @nabeelmsft
Microsoft Alias: munabeel

**Comment by cartertinney** [comment]
This seems to be an issue with the doc generation - the source code does have the documentation available, but it seems to have not populated to the web documentation.

Thanks for bringing this to our attention, we'll look into getting the documentation fixed as soon as possible.

**Comment by nabeelmsft** [comment]
Thanks @cartertinney for the response. I went ahead and added code for the missing documentation. This is done as part of PR: https://github.com/Azure/azure-iot-sdk-python/pull/940 . This is just a humble contribution. Please let me know if there is anything that I can contribute to.

**Comment by cartertinney** [comment]
Addressed the broader issue of missing docs in #945
