### ISSUE TITLE
[Technical Question] Any reason to copy all files in docker container

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-python#939]
I have created a module using VSCode python example. I see the `Dockerfile.amd64` contents as below:-
```
FROM amd64/python:3.7-slim-buster

WORKDIR /app

COPY requirements.txt ./
RUN pip install -r requirements.txt

COPY . .

CMD [ "python3", "-u", "./main.py" ]
```

Question:- Why there is a need to COPY over all the contents using `COPY . .`  in container. The contents like `Dockerfile.amd64.debug .gitignore etc.`. I think they are not required in the container. Event the `module.json` is copied over.

**Comment by cartertinney** [comment]
There is no reason you need to copy everything over. The `requirements.txt` and whatever python files you need for your application should be sufficient. I believe this example was written to copy everything so that it would easily scale for larger projects.

**Comment by amit12cool** [comment]
Ok Thanks.
