### ISSUE TITLE
Device creation issue on Mac OS

### ISSUE THREAD

**Issue by suleymanov** [Azure/azure-iot-sdk-python#94]
First of all, thank you for providing the possibility to work with simulated devices under Mac OS with Python. Installation went well, all tests were passed and I could run all imports suggested by IoT Hub overview on Azure website.

- **OS and version used: Mac OS High Sierra 10.13.1** <VERSION> 

- **Python runtime used: Python 2.7.13 |Anaconda custom (x86_64)** <VERSION> 

- **SDK version used: 2017-11-03** <VERSION> 

# Description of the issue:

Cannot create new device for my test IoT Hub.

# Code sample exhibiting the issue:

    iothub_registry_manager = IoTHubRegistryManager(CONNECTION_STRING)
    auth_method = IoTHubRegistryManagerAuthMethod.SHARED_PRIVATE_KEY
    new_device = iothub_registry_manager.create_device(DEVICE_ID, "", "", auth_method)

# Console log of the issue:

    Python 2.7.13 |Anaconda custom (x86_64)| (default, Dec 20 2016, 23:05:08)
    [GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)]
    Creating device using the Azure IoT Hub Service SDK for Python

        Connection string = [My connection string here]
        Device ID         = MyFirstPythonDevice
    Error: Time:Wed Nov 15 00:21:10 2017 
    File:/Users/railsuleymanov/Documents/azure_projects/repos/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:556 curl_easy_perform() failed: Out of memory

    Error: Time:Wed Nov 15 00:21:10 2017 File:/Users/railsuleymanov/Documents/azure_projects/repos/azure-iot-sdk-python/c/c-utility/adapters/httpapi_curl.c Func:HTTPAPI_ExecuteRequest Line:558 (result = HTTPAPI_OPEN_REQUEST_FAILED)
    Error: Time:Wed Nov 15 00:21:10 2017 File:/Users/railsuleymanov/Documents/azure_projects/repos/azure-iot-sdk-python/c/c-utility/src/httpapiex.c Func:HTTPAPIEX_ExecuteRequest Line:475 unable to recover sending to a working state
    Error: Time:Wed Nov 15 00:21:10 2017 File:/Users/railsuleymanov/Documents/azure_projects/repos/azure-iot-sdk-python/c/iothub_service_client/src/iothub_registrymanager.c Func:sendHttpRequestCRUD Line:982 HTTPAPIEX_SAS_ExecuteRequest failed
    Unexpected error IoTHubRegistryManager.create_device, IoTHubRegistryManagerResult.HTTPAPI_ERROR

**Comment by zolvarga** [comment]
@suleymanov 

We are looking at the curl issue and will get back to you with a conclusion.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@suleymanov 

We are still working on the optimization of memory usage in curl. We will let you know if it is done.

Best Regards,
Zoltan

**Comment by ewertons** [comment]
Hi @suleymanov ,
this issue seems related to https://github.com/Azure/azure-iot-sdk-python/issues/80.

Could you please try the solution proposed on that issue and confirm it addresses the failure you are experiencing?

**Comment by zolvarga** [comment]
Closed as duplicate and answered
