### ISSUE TITLE
ValueError: Publish topic cannot contain wildcards.

### ISSUE THREAD

**Issue by TravisKarp** [Azure/azure-iot-sdk-python#953]
**OS and version used:** Windows 10, Raspberry Raspbian GNU/Linux 10
**Python version:** 3.19
**pip version:** 21.2.4
**list of installed packages:**
anyio               3.5.0
asgiref             3.5.0
azure-core          1.22.1
azure-iot-device    2.10.0
certifi             2021.10.8
charset-normalizer  2.0.12
click               8.0.3
colorama            0.4.4
deprecation         2.1.0
fastapi             0.73.0
h11                 0.13.0
idna                3.3
isodate             0.6.1
janus               1.0.0
msrest              0.6.21
oauthlib            3.2.0
packaging           21.3
paho-mqtt           1.6.1
pip                 21.2.4
pydantic            1.9.0
pyparsing           3.0.7
PySocks             1.7.1
requests            2.27.1
requests-oauthlib   1.3.1
requests-unixsocket 0.3.0
setuptools          58.1.0
six                 1.16.0
sniffio             1.2.0
starlette           0.17.1
typing_extensions   4.0.1
uamqp               1.5.1
urllib3             1.26.8
uvicorn             0.17.4

**Description of the issue**
I just installed the library on two devices(Windows/RasberryPi). Using either the sample code from this repo (provided below) or an outside guide, the error "ValueError: Publish topic cannot contain wildcards."  is thrown on run. 

**Code sample exhibiting the issue**
**Code Sample 1:**
import os
import asyncio
from azure.iot.device.aio import IoTHubDeviceClient

async def main():
    conn_str = "conn_str"

    # Create instance of the device client using the authentication provider
    device_client = IoTHubDeviceClient.create_from_connection_string(conn_str)

    # Connect the device client.
    await device_client.connect()

    # Send a single message
    print("Sending message...")
    await device_client.send_message("This is a message that is being sent")
    print("Message successfully sent!")

    # finally, shut down the client
    await device_client.shutdown()

if __name__ == "__main__":
    asyncio.run(main())

**Code Sample 2:**
import random  
import time  
  
from azure.iot.device import IoTHubDeviceClient, Message  
  
CONNECTION_STRING = "Connection_String Here"  
  
TEMPERATURE = 20.0  
HUMIDITY = 60  
MSG_TXT = '{{"temperature": {temperature},"humidity": {humidity}}}'  
  
def iothub_client_init():  
    client = IoTHubDeviceClient.create_from_connection_string(CONNECTION_STRING)  
    return client  
  
def iothub_client_telemetry_sample_run():  
  
    try:  
        client = iothub_client_init()  
        print ( "IoT Hub device sending periodic messages, press Ctrl-C to exit" )  
        while True:  
            
            temperature = TEMPERATURE + (random.random() * 15)  
            humidity = HUMIDITY + (random.random() * 20)  
            msg_txt_formatted = MSG_TXT.format(temperature=temperature, humidity=humidity)  
            message = Message(msg_txt_formatted)  
  
            if temperature > 30:  
              message.custom_properties["temperatureAlert"] = "true"  
            else:  
              message.custom_properties["temperatureAlert"] = "false"  
  
            print( "Sending message: {}".format(message) )  
            client.send_message(message)  
            print ( "Message successfully sent" )  
            time.sleep(3)  
  
    except KeyboardInterrupt:  
        print ( "IoTHubClient sample stopped" )  
  
if __name__ == '__main__':  
    print ( "IoT Hub Quickstart #1 - Simulated device" )  
    print ( "Press Ctrl-C to exit" )  
    iothub_client_telemetry_sample_run()  

**Console log of the issue**

Traceback (most recent call last):
  File "C:\Python\lib\site-packages\azure\iot\device\iothub\aio\async_clients.py", line 33, in handle_result
    return await callback.completion()
  File "C:\Python\lib\site-packages\azure\iot\device\common\async_adapter.py", line 91, in completion
    return await self.future
  File "C:\Python\lib\site-packages\azure\iot\device\common\pipeline\pipeline_stages_mqtt.py", line 271, in _run_op
    self.transport.publish(topic=op.topic, payload=op.payload, callback=on_complete)
  File "C:\Python\lib\site-packages\azure\iot\device\common\mqtt_transport.py", line 548, in publish
    (rc, mid) = self._mqtt_client.publish(topic=topic, payload=payload, qos=qos)
  File "C:\Python\lib\site-packages\paho\mqtt\client.py", line 1233, in publish
    raise ValueError('Publish topic cannot contain wildcards.')
ValueError: Publish topic cannot contain wildcards.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "c:\Users\tkarp\IoTTest.py", line 26, in <module>
    asyncio.run(main())
  File "C:\Python\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "C:\Python\lib\asyncio\base_events.py", line 641, in run_until_complete
    return future.result()
  File "c:\Users\tkarp\IoTTest.py", line 18, in main
    await device_client.send_message("This is a message that is being sent")
  File "C:\Python\lib\site-packages\azure\iot\device\aio\patch_documentation.py", line 60, in send_message
    return await super(IoTHubDeviceClient, self).send_message(message)
  File "C:\Python\lib\site-packages\azure\iot\device\iothub\aio\async_clients.py", line 360, in send_message
    await handle_result(callback)
  File "C:\Python\lib\site-packages\azure\iot\device\iothub\aio\async_clients.py", line 63, in handle_result
    raise exceptions.ClientError(message="Unexpected failure", cause=e)
azure.iot.device.exceptions.ClientError: ClientError('Unexpected failure') caused by ValueError('Publish topic cannot contain wildcards.')

Older issue with same error:
[https://github.com/Azure/azure-iot-sdk-python/issues/503](503)

**Comment by cartertinney** [comment]
@TravisKarp does you device id contain any special characters by chance?

**Comment by TravisKarp** [comment]
Hey @cartertinney, I did have a special char in the id. I just recreated with out it and was able to successfully send a message. It looks like that fixed it. I appreciate the follow up!

**Comment by cartertinney** [comment]
Out of curiosity, which special character was it, and which way did you create the device? Through the azure portal or some other means?

**Comment by TravisKarp** [comment]
@cartertinney
I was using "#" to denote separate IoT device numbers ie "LightSensor#1". Interestingly I have a "-" in my IoT hub name which doesn't seem to cause any issues so it appears to just be the device id registration.

**Comment by cartertinney** [comment]
@TravisKarp

Thanks. I'm going to look into what caused this underlying issue.
