### ISSUE TITLE
[Technical Question] Azure IOT Token

### ISSUE THREAD

**Issue by PeteDouma** [Azure/azure-iot-sdk-python#962]
We have 1000's of device and a bunch are not sending messages. When I look in the logs keep seeing this. 
Feb 26 06:21:32 gardyn GRD-SVC-IOT[24984]: 2022-02-26 06:21:32,867-azure.iot.device.iothub.auth.base_renewable_token_authentication_provider-INFO-Generating new SAS token for (7293a28e-xxxx,None) that expires 3600 seconds in the future
Feb 26 06:21:32 gardyn GRD-SVC-IOT[24984]: 2022-02-26 06:21:32,885-azure.iot.device.iothub.pipeline.pipeline_stages_iothub-INFO-UseAuthProviderStage: New sas token received.  Passing down UpdateSasTokenOperation.

We did not get any messages. What happened and what should we do about it.

**Comment by PeteDouma** [comment]
Its running on a Raspberry Pi Zero W

**Comment by cartertinney** [comment]
@PeteDouma

Can you update `azure-iot-device` to the latest version of `2.10.0`? The version you are currently on, `2.0.0` is the initial release of this package, and there have been numerous improvements to stability since then

**Comment by PeteDouma** [comment]
No I can't these devices are in the field

**Comment by cartertinney** [comment]
@PeteDouma Do you have more detailed logs I can take a look at? The log message about the token is expected as it's the result of an operation that runs every ~3600 seconds, so it is likely not the issue.

**Comment by PeteDouma** [comment]
Its difficult because I have wait for a user to come back on line. Here is one I got today
`Mar  4 00:12:26 gardyn python3[800]: MQTTTransportStage: _on_mqtt_connection_failure called: Connection Refused: not authorised.
Mar  4 00:12:26 gardyn python3[800]: MQTTTransportStage: Connection failure was unexpected
Mar  4 00:12:26 gardyn python3[800]: Exception caught in background thread.  Unable to handle.
Mar  4 00:12:26 gardyn python3[800]: azure.iot.device.common.transport_exceptions.UnauthorizedError: Connection Refused: not authorised.
Mar  4 00:12:26 gardyn python3[800]: MQTTTransportStage: _on_mqtt_disconnect called: The connection was refused.
Mar  4 00:12:26 gardyn python3[800]: MQTTTransportStage: disconnection was unexpected
Mar  4 00:12:26 gardyn python3[800]: Exception caught in background thread.  Unable to handle.
Mar  4 00:12:26 gardyn python3[800]: azure.iot.device.common.transport_exceptions.ConnectionFailedError: The connection was refused.
Mar  4 00:12:26 gardyn python3[800]: The above exception was the direct cause of the following exception:
Mar  4 00:12:26 gardyn python3[800]: azure.iot.device.common.transport_exceptions.ConnectionDroppedError: None
M`

**Comment by PeteDouma** [comment]
This user just rebooted and everything was fine
