### ISSUE TITLE
[Technical Question] How often does the python SDK check the X509 certificate validity ?

### ISSUE THREAD

**Issue by gabrielSoudry** [Azure/azure-iot-sdk-python#968]
I use DPS and Enrollment Group to provision my devices and I noticed that my devices continued to work for 27 hours after their certificate expired. After these 27 hours the Azure SDK raise an "SSL" exception ([SSL: TLSV1_ALERT_UNKNOWN_CA] tlsv1 alert unknown ca (_ssl.c:2488))

How often does the python SDK check the X509 certificate validity? And why did it take 27 hours?

**Comment by BertKleewein** [comment]
Checking the validity of the cert is done by the TLS stack, definitely at connect time, and I've always seen it disconnect within a few hours of expiration. I'm running a wireshark trace right now to see if I can figure out what triggers the check.

**Comment by gabrielSoudry** [comment]
Thank you for the research! No specific concern, I was just wondering how it works, and if the behavior was normal (I didn't find any specifications in the doc for my case)
