### ISSUE TITLE
[Edge Transparent Gateway scenario]Send message using x509=true in connection string

### ISSUE THREAD

**Issue by amit12cool** [Azure/azure-iot-sdk-python#969]
I have set up transparent gateway with downstream device being authenticated to gateway using x509 auth mechanism.
My connection string in the downstream device code is as below:-
`HostName={hostname};DeviceId={downstreamDeviceId};x509=true`

The error is I get while instantiating the deviceclient is as below:-
```
Unexpected error Invalid Connection String - Invalid Key 
Shutting down IoT Hub Client...
Traceback (most recent call last):
  File "./iotagent.py", line 84, in <module>
    main()
  File "./iotagent.py", line 73, in main
    loop.run_until_complete(dowork())
  File "/usr/local/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "./iotagent.py", line 53, in dowork
    device_client = DeviceClient(registration_result, x509)
  File "/app/iotagent/device_client.py", line 21, in __init__
    server_verification_cert=root_ca_cert
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/aio/patch_documentation.py", line 85, in create_from_connection_string
    connection_string, **kwargs
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/iothub/abstract_clients.py", line 257, in create_from_connection_string
    connection_string = cs.ConnectionString(connection_string)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/auth/connection_string.py", line 83, in __init__
    self._dict = _parse_connection_string(connection_string)
  File "/usr/local/lib/python3.7/site-packages/azure/iot/device/common/auth/connection_string.py", line 50, in _parse_connection_string
    raise ValueError("Invalid Connection String - Invalid Key")
ValueError: Invalid Connection String - Invalid Key
```

It seems as per this [code](https://github.com/Azure/azure-iot-sdk-python/blob/5d6946fa3f34e307c8e37d16b6899e448a58a27a/azure-iot-device/azure/iot/device/common/auth/connection_string.py#L21), the key x509 is not supported in python sdk. Or am I missing something?

**Comment by cartertinney** [comment]
@amit12cool

Please use the `.create_from_x509_certificate()` factory method for the clients instead of `.create_from_connection_string()` when using X509 certificates. You can see an example of how to do so [in this sample code](https://github.com/Azure/azure-iot-sdk-python/blob/5d6946fa3f34e307c8e37d16b6899e448a58a27a/azure-iot-device/samples/sync-samples/send_message_x509.py)

**Comment by amit12cool** [comment]
@cartertinney ok. Will I need to use the root_ca.key on downstream device ? As far as I know for transparent gateway scenario the downstream device only requires root_ca.pem file to connect to the gateway device

**Comment by cartertinney** [comment]
@amit12cool 

I think what you're looking for is perhaps the `server_verification_cert` keyword argument, and provide the contents of the root_ca.pem.

As far as the GatewayHostName, that might be an issue - try without it, and if it it doesn't work, let me know.

**Comment by amit12cool** [comment]
I have used this 
```
 self.device_client = IoTHubDeviceClient.create_from_x509_certificate(
                x509=x509, 
                hostname=hostname,
                device_id=registration_result.registration_state.device_id,
                server_verification_cert=root_ca_cert
            )
```
And the error I get is below:-
`ConnectionFailedError('Could not connect to IoTHub') caused by ConnectionFailedError(None)`

Also, I have tested the connection of leaf device with gateway device using openssl command. Below is the output:-

```
CONNECTED(00000003)
Can't use SSL_get_servername
depth=2 CN = Veli Gateway Devices Root CA
verify return:1
depth=1 CN = Veli Gateway Devices Intermediate CA
verify return:1
depth=0 CN = amit-virtualbox
verify return:1
---
Certificate chain
 0 s:CN = amit-virtualbox
   i:CN = Veli Gateway Devices Intermediate CA
-----BEGIN CERTIFICATE-----
MIICPzCCAeWgAwIBAgIBADAKBggqhkjOPQQDAjAvMS0wKwYDVQQDEyRWZWxpIEdh
dGV3YXkgRGV2aWNlcyBJbnRlcm1lZGlhdGUgQ0EwHhcNMjIwMzE3MDQ1ODIxWhcN
MjIwNDE2MDQ1ODIxWjAaMRgwFgYDVQQDDA9hbWl0LXZpcnR1YWxib3gwggEiMA0G
CSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQC6rtyLrbVqcFeyyQBNNpcWl/LkbcOa
E7A1E2fjIQohESC9lirNkCf0ue8dbr6QojmL0UF1528PRzJMK3KwT2SnnhvZea/d
neQ4zTBfGDGs/feDEHtx4teO7RzU25hcYeDz6TUPUqGheWwPtXvC2SADW+0rRr4r
xPdaIrjLbmbF4Qtmg0vv7S8/SeAY3Y/VZoenWM1K4qXccPaOTK0vvwX7WvxU35P7
jbPMyNBB7F871CSjvMA0QGd8hdd2nZX+NYxIHzjmaPgvdh+9mtD6GiAJtEXhW06g
7joA8rMdz62Qcei+aWkGjz9TtF5NhWUuhxd2jOBaPS0xj+tkV9n1KGcVAgMBAAGj
PDA6MBMGA1UdJQQMMAoGCCsGAQUFBwMBMCMGA1UdEQQcMBqCB2VkZ2VodWKCD2Ft
aXQtdmlydHVhbGJveDAKBggqhkjOPQQDAgNIADBFAiEAzsDDrYFW5TE2byrYe+FU
aLNe8EJRBWhkHrfvn/Cwx3MCIC/5HlFVwOO4Q09k1HpmYFknhFCGiY2uvrwxUQQ3
O9EC
-----END CERTIFICATE-----
 1 s:CN = Veli Gateway Devices Intermediate CA
   i:CN = Veli Gateway Devices Root CA
-----BEGIN CERTIFICATE-----
MIIBvjCCAWOgAwIBAgIRAMuoMwh4s7LQROik0crmL9owCgYIKoZIzj0EAwIwJzEl
MCMGA1UEAxMcVmVsaSBHYXRld2F5IERldmljZXMgUm9vdCBDQTAgFw0yMjAzMTQw
ODEyMTRaGA8yMTIyMDIxODA4MTIxNFowLzEtMCsGA1UEAxMkVmVsaSBHYXRld2F5
IERldmljZXMgSW50ZXJtZWRpYXRlIENBMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcD
QgAEeqpUZEzOKA4ylSyG2WaeHQcNxGkVZkC9vvFJKgKNW2WnDAsGsGzSiSWHq3tg
mt4SUU/uj4Boq5SxhfiauPWUS6NmMGQwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB
/wQIMAYBAf8CAQAwHQYDVR0OBBYEFPCwQo7chhpc0oUBwsOkjgPtviYSMB8GA1Ud
IwQYMBaAFCqD8u3kUR5DJ84J5Q24R6hIxO/XMAoGCCqGSM49BAMCA0kAMEYCIQD0
XIya7XbLTYJNeyiimGnIL9Dld+1+OYMPreYX0UMF5wIhAOqCIMZfo3Wz+gKAC73b
ZeQlUbF+4qYMhYg7R83hdFKG
-----END CERTIFICATE-----
---
Server certificate
subject=CN = amit-virtualbox

issuer=CN = Veli Gateway Devices Intermediate CA

---
No client certificate CA names sent
Client Certificate Types: RSA sign, DSA sign, ECDSA sign
Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:ECDSA+SHA1:RSA+SHA224:RSA+SHA1:DSA+SHA224:DSA+SHA1:DSA+SHA256:DSA+SHA384:DSA+SHA512
Shared Requested Signature Algorithms: ECDSA+SHA256:ECDSA+SHA384:ECDSA+SHA512:Ed25519:Ed448:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA-PSS+SHA256:RSA-PSS+SHA384:RSA-PSS+SHA512:RSA+SHA256:RSA+SHA384:RSA+SHA512:ECDSA+SHA224:RSA+SHA224:DSA+SHA224:DSA+SHA256:DSA+SHA384:DSA+SHA512
Peer signing digest: SHA256
Peer signature type: RSA-PSS
Server Temp Key: X25519, 253 bits
---
SSL handshake has read 1720 bytes and written 388 bytes
Verification: OK
---
New, TLSv1.2, Cipher is ECDHE-RSA-AES256-GCM-SHA384
Server public key is 2048 bit
Secure Renegotiation IS supported
Compression: NONE
Expansion: NONE
No ALPN negotiated
SSL-Session:
    Protocol  : TLSv1.2
    Cipher    : ECDHE-RSA-AES256-GCM-SHA384
    Session-ID: 44BF78DA9455AB6C1C4C9F45E57506D3EE3E9DF6B7342D11F4A2A544875D5F4E
    Session-ID-ctx: 
    Master-Key: 656BFF346448759485F03EE7477B9C842ED69EEE2AE97A906E0F8F2E930A59B7E3ADB9D00EFF81DA11DBDC154B09A9C6
    PSK identity: None
    PSK identity hint: None
    SRP username: None
    TLS session ticket lifetime hint: 7200 (seconds)
    TLS session ticket:
    0000 - 99 57 cb 12 de f5 dd b7-b0 37 93 ab 02 59 94 aa   .W.......7...Y..
    0010 - 56 9e 0b f5 e6 bd 76 46-16 31 21 54 e8 54 49 ef   V.....vF.1!T.TI.
    0020 - ba 1d 01 c3 d5 0b 81 db-0c 96 73 b8 c9 0d f1 5e   ..........s....^
    0030 - 11 14 12 ed cb 94 aa 2e-a6 a7 93 1b 49 88 3f 80   ............I.?.
    0040 - 35 01 4e 44 07 9f 7e 1d-eb 42 85 65 0b 21 4d 66   5.ND..~..B.e.!Mf
    0050 - 20 5f d7 6e 8e e3 64 72-d2 50 7d 2f 15 b4 92 ea    _.n..dr.P}/....
    0060 - 50 8f 23 16 8b cf e3 86-fd cc fe 07 b6 69 bc f4   P.#..........i..
    0070 - b4 34 18 dc 85 21 54 af-21 13 21 6d a1 e6 53 35   .4...!T.!.!m..S5
    0080 - 9f aa 88 4b 25 45 d4 39-6b e2 12 ee 9a 72 24 c3   ...K%E.9k....r$.
    0090 - a1 42 43 b3 c3 80 35 38-2f bb 2a 1b c4 0e cd 96   .BC...58/.*.....

    Start Time: 1647519999
    Timeout   : 7200 (sec)
    Verify return code: 0 (ok)
    Extended master secret: yes
---

```

**Comment by cartertinney** [comment]
@amit12cool 

A fix to provide support for gateway_hostname is implemented in PR #973. This will be part of our next release.

**Comment by cartertinney** [comment]
Fix has been checked in

**Comment by amit12cool** [comment]
@cartertinney  Thanks for the fix. Since I will be using the  method below and as per your PR review changes I see we can pass `gateway_hostname` param too. But can we not use the `hostname` param only to pass the gateway_hostname value? If not, then what needs to be passed in the hostname param? Please prvode an example.

And when is the release expected with this fix?

```
self.device_client = IoTHubDeviceClient.create_from_x509_certificate(
                x509=x509, 
                hostname=hostname,
                device_id=registration_result.registration_state.device_id,
                server_verification_cert=root_ca_cert
            )
```

**Comment by cartertinney** [comment]
@amit12cool The hostname is the hostname of your IoTHub. Usually something like `<your-hub-name>.azure-devices.net`. You can find it on the Overview of your IoTHub on the Azure Portal

**Comment by amit12cool** [comment]
@cartertinney thanks mate. Any idea on next release as currently I'm blocked due to this issue.

**Comment by cartertinney** [comment]
@amit12cool

I'm gonna try to get `2.11.0` released as soon as possible. We've got a technical problem getting in the way of pushing out the release, otherwise it already would be out - working on fixing that now. Will update you as soon as it is available.

**Comment by cartertinney** [comment]
@amit12cool 

Version `2.11.0` has been released. You may now use the `gateway_hostname` keyword in the `.create_from_x509_certificate()` method.

**Comment by amit12cool** [comment]
@cartertinney Thanks for the speedy release. I did the changes as below:-

`requirements.txt`  has below line
`azure-iot-device==2.11.0`
self.device_client = IoTHubDeviceClient.create_from_x509_certificate(
                x509=x509, 
                hostname=<IoT hub hostname>,
                device_id=registration_result.registration_state.device_id,
                server_verification_cert=root_ca_cert,
                gateway_hostname=<My gateway hostanme>
 )

Unfortunately, Im still not able to connect and the error I get is below:-
`Could not connect to IoTHub` 

Is it still trying to connect to IoT Hub?

**Comment by amit12cool** [comment]
@cartertinney I was able to resolve the issue by providing below container create options:

```
{
  "HostConfig": {
    "NetworkMode": "host"
  },
  "NetworkingConfig": {
    "EndpointsConfig": {
      "host": {}
    }
  }
}
```
PS:- I'm running my downstream device in docker container
Please let me know if above is the correct way to do this.

Now, I just want to check if the messages are going to the gateway only. Can you suggest a way by which I can verify this?

**Comment by cartertinney** [comment]
@amit12cool

Unfortunately, I have little insight beyond the scope of the Device SDK. This is a question better suited for someone on the team of the relevant service (IoTHub or Edge). I can try to reach out to them myself if you don't have a contact in that area.

**Comment by veyalla** [comment]
> Now, I just want to check if the messages are going to the gateway only. Can you suggest a way by which I can verify this?

Couple ways: 
* Tail the logs of edgeHub module and see output showing the downstream device connecting.
* Setup Azure Monitor metrics monitoring for the IoT Edge device and check the built-in visualizations. See https://aka.ms/edgemon-docs

**Comment by cartertinney** [comment]
@amit12cool Please let us know if the above information helps you resolve the issue

**Comment by amit12cool** [comment]
Yes that helps. Thanks

**Comment by amit12cool** [comment]
@cartertinney  is it possible to send the IP address in gatewayhostname param instead of the hostname? I see connection error while sending the IP address.

**Comment by amit12cool** [comment]
@cartertinney any help on above?

**Comment by amit12cool** [comment]
@cartertinney any inputs?
