### ISSUE TITLE
which folders of the repo can i delete after installation using build method?

### ISSUE THREAD

**Issue by llealgt** [Azure/azure-iot-sdk-python#97]
I'm using a raspberry pi and an 8GB card and raspbian,after succesfully installing azure iot SDK by building from the repo, the file system is full and cannot create directories nor empty files, which folders of the repo can i safely delete without breaking the SDK installation?

**Comment by tameraw** [comment]
@llealgt - You could avoid cloning the repo and build altogether and resort to using the PIP packages as instructed [here](https://github.com/Azure/azure-iot-sdk-python/blob/master/doc/python-devbox-setup.md#install-the-python-modules-using-pypi-wheels-from-pypi).

**Comment by zolvarga** [comment]
@llealgt 

There are two ways how to run our SDKS on Raspberry Pi:
1. Use PIP packages to download the necessary binaries. In this case you don't need to clone the whole repo just get the sample applications (*.py files) from the "sample" folders.
2. You want or need to build the repo. In that case you would need all the folders cloned, plus boost library, plus OpenSSL. Then build it, which will produce the binaries. After a successful build you can delete the repo and the boost folders. Just keep the "*.so" files in the folder where you run the Python application from.

Best Regards,
Zoltan

**Comment by zolvarga** [comment]
@llealgt 

Closing as the question has been answered.

Best Regards,
Zoltan
