### ISSUE TITLE
Can't export devices from my IOTHub

### ISSUE THREAD

**Issue by alexandreg19** [Azure/azure-iot-sdk-python#98]
- **OS and version used:** <VERSION>  Ubuntu 16.04 (Bash For Windows)

- **Python runtime used:** <VERSION>  Python 3.5.2 (default, Sep 14 2017, 22:51:06)

- **SDK version used:** <VERSION>  
azure-iothub-service-client==1.1.0.19
azure-mgmt-iothub==0.2.2
azure==2.0.0

# Description of the issue:

When I try to use the iot_hub_resource.export_devices() method, I got an Error : `too many 500 error responses`
I don't know if it's caused by an argument, an other error in my code, or anything..
I just followed this document : http://azure-sdk-for-python.readthedocs.io/en/latest/ref/azure.mgmt.iothub.operations.html

I don't have any issue when I try to use other methods, like : 
```
- iot_hub_resource.get()
- iot_hub_resource.get_quota_metrics()
- iot_hub_resource.get_stats()
```

# Code sample exhibiting the issue:

```
authentication_endpoint = 'https://login.microsoftonline.com/'
resource = 'https://management.core.windows.net/'

context = adal.AuthenticationContext(authentication_endpoint + tenant_id)
token_response = context.acquire_token_with_client_credentials(resource, application_id, application_secret)

credential = AADTokenCredentials(token_response)

container_name = 'backupfiles-' + datetime.now().strftime("%Y-%m-%d")

blob_service = BlockBlobService(account_name=storage_account_name, account_key=storage_account_key)
containers = blob_service.list_containers()

if container_name in [c.name for c in containers]:
    print("Container %s already exist" % container_name)
else:
    blob_service.create_container(container_name, public_access=PublicAccess.Container)
    print("Container %s created" % container_name)

client = IotHubClient(credential,subscription_id)
client.iot_hub_resource.export_devices(resourcegroup,resourcename,'https://mystorage.blob.core.windows.net/' + container_name, False)
```

# Console log of the issue:

```
Traceback (most recent call last):
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/adapters.py", line 440, in send
    timeout=timeout
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 732, in urlopen
    body_pos=body_pos, **response_kw)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/connectionpool.py", line 712, in urlopen
    retries = retries.increment(method, url, response=response, _pool=self)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/urllib3/util/retry.py", line 388, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx/exportDevices?api-version=2016-02-03 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/service_client.py", line 194, in send
    **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
requests.exceptions.RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx/exportDevices?api-version=2016-02-03 (Caused by ResponseError('too many 500 error responses',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "export_devices.py", line 55, in <module>
    client.iot_hub_resource.export_devices(resourcegroup,resourcename,'https://mystorage.blob.core.windows.net/' + container_name + '/' + blob_filename, False)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/azure/mgmt/iothub/operations/iot_hub_resource_operations.py", line 1327, in export_devices
    request, header_parameters, body_content, **operation_config)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/service_client.py", line 220, in send
    raise_with_traceback(ClientRequestError, msg, err)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/exceptions.py", line 45, in raise_with_traceback
    raise error.with_traceback(exc_traceback)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/msrest/service_client.py", line 194, in send
    **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests_oauthlib/oauth2_session.py", line 360, in request
    headers=headers, data=data, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 508, in request
    resp = self.send(prep, **send_kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/sessions.py", line 618, in send
    r = adapter.send(request, **kwargs)
  File "/mnt/c/Apply/test-python-iot/venv/lib/python3.5/site-packages/requests/adapters.py", line 499, in send
    raise RetryError(e, request=request)
msrest.exceptions.ClientRequestError: Error occurred in request., RetryError: HTTPSConnectionPool(host='management.azure.com', port=443): Max retries exceeded with url: /subscriptions/xxx/resourceGroups/xxx/providers/Microsoft.Devices/IotHubs/xxx/exportDevices?api-version=2016-02-03 (Caused by ResponseError('too many 500 error responses',))
```

Hope you could help me.
Thanks,

Regards,
Alexandre

**Comment by alexandreg19** [comment]
Hi @tameraw  @zolvarga 
Do you have any news about that ?
I tried some other methods to get credentials, I add the path URL to the blob too, but I ended with the same error.

Regards,
Alexandre

**Comment by zolvarga** [comment]
@alexandreg19 

This issue belongs to the IoTHub management repo, probably you need to file it there:
https://github.com/Azure/azure-sdk-for-python

Best Regards,
Zoltan

**Comment by alexandreg19** [comment]
Thank you @zolvarga , I will post there.

Regards, 
Alexandre

**Comment by hello-azure** [comment]
The export_blob_container_uri should be a SAS uri on container, you can use Azure Storage Explore or code to get it.  I have test it successful in China Azure, share for you as bellow:


from azure import *

from azure.mgmt.iothub import IotHubClient
from azure.storage.blob import BlockBlobService

from azure.common.credentials import UserPassCredentials
from azure.mgmt.compute.models import *
from msrest.serialization import *
from msrestazure.azure_active_directory import AADTokenCredentials, ServicePrincipalCredentials

# auth var
client_id = '7915f005-202f-42da-86e8-bfd422aae15f'
client_secret = '1QAZxsw2'
tenant_id = 'b388b808-0ec9-4a09-a414-a7cbbd8b7e9b'
subscription_id = 'e0fbea86-6cf2-4b2d-81e2-9c59f4f96bcb '


# device var
resourcegroup = 'myresourcegroup'
resourcename = 'myiothub'
export_blob_container_uri = 'https://devstorage.blob.core.chinacloudapi.cn/iotbackupfiles?st=2018-01-08T14%3A57%3A00Z&se=2018-01-11T14%3A57%3A00Z&sp=rwdl&sv=2016-05-31&sr=c&sig=dHdJqQcNDmKDHMfVjIdKF7B4h7neFCuQbXxijFIG3ZY%3D'
exclude_keys = True


# export device operation
credentials = ServicePrincipalCredentials(client_id,client_secret,tenant=tenant_id,china='true')
client = IotHubClient(
  credentials,
  'e0fbea86-6cf2-4b2d-81e2-9c59f4f96bcb',
  base_url = 'https://management.chinacloudapi.cn'
)
client.iot_hub_resource.export_devices(resourcegroup,resourcename, export_blob_container_uri, exclude_keys)

print 'export device ok!'


===============================================================

credentials  can got from 2 ways:

1.	Subscription：
	credentials = UserPassCredentials(
		"<Subscription Account>",
		"<Subscription Account Password>",
		china=True
	)

2.	Application：
	# Connect China Azure: You can get <TeanantID>
	$cred = New-Object System.Management.Automation.PSCredential("<Subscription Account>",(ConvertTo-SecureString "<Subscription Account Password>" -AsPlainText -Force))
	Add-AzureRmAccount -EnvironmentName AzureChinaCloud -Credential $cred
	Get-AzureRmSubscription | select SubscriptionName,SubscriptionID | sort SubscriptionName,SubscriptionID
	Select-AzureRmSubscription -SubscriptionId “<Subscription ID>”  

	# Create Application: You can get <ClientID>、<ClientSecret>, ClientID = ApplicationId, ClientSecret=Password
	Get-AzureRmADApplication
	$azureAdApplication = New-AzureRmADApplication -DisplayName "geoapp01" -HomePage "https://www.geoapp01.org" -IdentifierUris "https://www.geoapp01.org/example" -Password "1QAZxsw2"
	$azureAdApplication

	# Assignment
	New-AzureRmADServicePrincipal -ApplicationId $azureAdApplication.ApplicationId
	New-AzureRmRoleAssignment -RoleDefinitionName Owner -ServicePrincipalName $azureAdApplication.ApplicationId

•	认证
	client_id = '7915f005-202f-42da-86e8-bfd422aae15f'
	client_secret = '******'
	tenant_id = 'b388b808-0ec9-4a09-a414-a7cbbd8b7e9b'
	subscription_id = 'e0fbea86-6cf2-4b2d-81e2-9c59f4f96bcb'

	credentials = ServicePrincipalCredentials(client_id,client_secret,tenant=tenant_id,china='true')

**Comment by alexandreg19** [comment]
Hi @hello-azure ,

I fixed my issue yesterday, it was the SAS token indeed.
Here the code that I added : 

```
container_permissions = ContainerPermissions.WRITE
blob_permissions = BlobPermissions.CREATE + BlobPermissions.WRITE + BlobPermissions.READ + BlobPermissions.DELETE

container_token = sas.generate_container(
            container_name,
            container_permissions + blob_permissions,
            datetime.now() + timedelta(hours=1)
        )

blob_filename = "backup-{}".format(datetime.now().strftime("%Y%m%d"))
url = blob_service.make_blob_url(container_name, blob_filename, sas_token=container_token)

client.iot_hub_resource.export_devices(rg, iothub.name, url, True)
```

Thanks for the help,
Regards,
Alexandre
