### ISSUE TITLE
IoTHub Provisioning Service Library - Feature is Coming Soon

### ISSUE THREAD

**Issue by mcfreis** [Azure/azure-iot-sdk-python#984]
According to the documentation:

'''
IoTHub Provisioning Service Library
Feature is Coming Soon
'''

When is "soon" or what could be done to support this feature?

Thank you

**Comment by cartertinney** [comment]
We don't have any news at this time. I apologize for not being able to say any more than that.

**Comment by cartertinney** [comment]
We have removed this from the README
